.TH "ActionAddAlias" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionAddAlias
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($args)"
.br
.ti -1c
.RI "\fBprocessWindow\fP ($window, $id, $ctrl, $param1, $param2)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBGAUGE_SAVE\fP = 2"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$wbBtnCancel\fP"
.br
.ti -1c
.RI "\fB$wbBtnDest\fP"
.br
.ti -1c
.RI "\fB$wbBtnSave\fP"
.br
.ti -1c
.RI "\fB$wbInputDest\fP"
.br
.ti -1c
.RI "\fB$wbInputName\fP"
.br
.ti -1c
.RI "\fB$wbLabelDest\fP"
.br
.ti -1c
.RI "\fB$wbLabelExp\fP"
.br
.ti -1c
.RI "\fB$wbLabelName\fP"
.br
.ti -1c
.RI "\fB$wbProgressBar\fP"
.br
.ti -1c
.RI "\fB$wbWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBActionAddAlias\fP Handles the creation of a new alias in the \fBBearsampp\fP application\&. 
.PP
Definition at line \fB14\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $args)"
\fBActionAddAlias\fP constructor\&. Initializes the window and its controls for adding a new alias\&.

.PP
\fBParameters\fP
.RS 4
\fI$args\fP Arguments passed to the constructor\&. 
.RE
.PP

.PP
Definition at line \fB35\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.nf
36     {
37         global $bearsamppLang, $bearsamppBins, $bearsamppWinbinder;
38 
39         $initName = 'test';
40         $initDest = 'C:\\\\';
41         $apachePortUri = $bearsamppBins\->getApache()\->getPort() != 80 ? ':' \&. $bearsamppBins\->getApache()\->getPort() : '';
42 
43         $bearsamppWinbinder\->reset();
44         $this\->wbWindow = $bearsamppWinbinder\->createAppWindow($bearsamppLang\->getValue(Lang::ADD_ALIAS_TITLE), 490, 200, WBC_NOTIFY, WBC_KEYDOWN | WBC_KEYUP);
45 
46         $this\->wbLabelName = $bearsamppWinbinder\->createLabel($this\->wbWindow, $bearsamppLang\->getValue(Lang::ALIAS_NAME_LABEL) \&. ' :', 15, 15, 85, null, WBC_RIGHT);
47         $this\->wbInputName = $bearsamppWinbinder\->createInputText($this\->wbWindow, $initName, 105, 13, 150, null);
48 
49         $this\->wbLabelDest = $bearsamppWinbinder\->createLabel($this\->wbWindow, $bearsamppLang\->getValue(Lang::ALIAS_DEST_LABEL) \&. ' :', 15, 45, 85, null, WBC_RIGHT);
50         $this\->wbInputDest = $bearsamppWinbinder\->createInputText($this\->wbWindow, $initDest, 105, 43, 190, null, null, WBC_READONLY);
51         $this\->wbBtnDest = $bearsamppWinbinder\->createButton($this\->wbWindow, $bearsamppLang\->getValue(Lang::BUTTON_BROWSE), 300, 43, 110);
52 
53         $this\->wbLabelExp = $bearsamppWinbinder\->createLabel($this\->wbWindow, sprintf($bearsamppLang\->getValue(Lang::ALIAS_EXP_LABEL), $apachePortUri, $initName, $initDest), 15, 80, 470, 50);
54 
55         $this\->wbProgressBar = $bearsamppWinbinder\->createProgressBar($this\->wbWindow, self::GAUGE_SAVE + 1, 15, 137, 275);
56         $this\->wbBtnSave = $bearsamppWinbinder\->createButton($this\->wbWindow, $bearsamppLang\->getValue(Lang::BUTTON_SAVE), 300, 132);
57         $this\->wbBtnCancel = $bearsamppWinbinder\->createButton($this\->wbWindow, $bearsamppLang\->getValue(Lang::BUTTON_CANCEL), 387, 132);
58 
59         $bearsamppWinbinder\->setHandler($this\->wbWindow, $this, 'processWindow');
60         $bearsamppWinbinder\->mainLoop();
61         $bearsamppWinbinder\->reset();
62     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fBLang\\ADD_ALIAS_TITLE\fP, \fBLang\\ALIAS_DEST_LABEL\fP, \fBLang\\ALIAS_EXP_LABEL\fP, \fBLang\\ALIAS_NAME_LABEL\fP, \fBLang\\BUTTON_BROWSE\fP, \fBLang\\BUTTON_CANCEL\fP, and \fBLang\\BUTTON_SAVE\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "processWindow ( $window,  $id,  $ctrl,  $param1,  $param2)"
Processes window events and handles user interactions\&.

.PP
\fBParameters\fP
.RS 4
\fI$window\fP The window resource\&. 
.br
\fI$id\fP The control ID\&. 
.br
\fI$ctrl\fP The control resource\&. 
.br
\fI$param1\fP Additional parameter 1\&. 
.br
\fI$param2\fP Additional parameter 2\&. 
.RE
.PP

.PP
Definition at line \fB73\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.nf
74     {
75         global $bearsamppRoot, $bearsamppBins, $bearsamppLang, $bearsamppWinbinder;
76 
77         $apachePortUri = $bearsamppBins\->getApache()\->getPort() != 80 ? ':' \&. $bearsamppBins\->getApache()\->getPort() : '';
78         $aliasName = $bearsamppWinbinder\->getText($this\->wbInputName[WinBinder::CTRL_OBJ]);
79         $aliasDest = $bearsamppWinbinder\->getText($this\->wbInputDest[WinBinder::CTRL_OBJ]);
80 
81         switch ($id) {
82             case $this\->wbInputName[WinBinder::CTRL_ID]:
83                 $bearsamppWinbinder\->setText(
84                     $this\->wbLabelExp[WinBinder::CTRL_OBJ],
85                     sprintf($bearsamppLang\->getValue(Lang::ALIAS_EXP_LABEL), $apachePortUri, $aliasName, $aliasDest)
86                 );
87                 $bearsamppWinbinder\->setEnabled($this\->wbBtnSave[WinBinder::CTRL_OBJ], empty($aliasName) ? false : true);
88                 break;
89             case $this\->wbBtnDest[WinBinder::CTRL_ID]:
90                 $aliasDest = $bearsamppWinbinder\->sysDlgPath($window, $bearsamppLang\->getValue(Lang::ALIAS_DEST_PATH), $aliasDest);
91                 if ($aliasDest && is_dir($aliasDest)) {
92                     $bearsamppWinbinder\->setText($this\->wbInputDest[WinBinder::CTRL_OBJ], $aliasDest \&. '\\\\');
93                     $bearsamppWinbinder\->setText(
94                         $this\->wbLabelExp[WinBinder::CTRL_OBJ],
95                         sprintf($bearsamppLang\->getValue(Lang::ALIAS_EXP_LABEL), $apachePortUri, $aliasName, $aliasDest \&. '\\\\')
96                     );
97                 }
98                 break;
99             case $this\->wbBtnSave[WinBinder::CTRL_ID]:
100                 $bearsamppWinbinder\->setProgressBarMax($this\->wbProgressBar, self::GAUGE_SAVE + 1);
101                 $bearsamppWinbinder\->incrProgressBar($this\->wbProgressBar);
102 
103                 if (!ctype_alnum($aliasName)) {
104                     $bearsamppWinbinder\->messageBoxError(
105                         sprintf($bearsamppLang\->getValue(Lang::ALIAS_NOT_VALID_ALPHA), $aliasName),
106                         $bearsamppLang\->getValue(Lang::ADD_ALIAS_TITLE));
107                     $bearsamppWinbinder\->resetProgressBar($this\->wbProgressBar);
108                     break;
109                 }
110 
111                 if (is_file($bearsamppRoot\->getAliasPath() \&. '/' \&. $aliasName \&. '\&.conf')) {
112                     $bearsamppWinbinder\->messageBoxError(
113                         sprintf($bearsamppLang\->getValue(Lang::ALIAS_ALREADY_EXISTS), $aliasName),
114                         $bearsamppLang\->getValue(Lang::ADD_ALIAS_TITLE));
115                     $bearsamppWinbinder\->resetProgressBar($this\->wbProgressBar);
116                     break;
117                 }
118                 if (file_put_contents($bearsamppRoot\->getAliasPath() \&. '/' \&. $aliasName \&. '\&.conf', $bearsamppBins\->getApache()\->getAliasContent($aliasName, $aliasDest)) !== false) {
119                     $bearsamppWinbinder\->incrProgressBar($this\->wbProgressBar);
120 
121                     $bearsamppBins\->getApache()\->getService()\->restart();
122                     $bearsamppWinbinder\->incrProgressBar($this\->wbProgressBar);
123 
124                     $bearsamppWinbinder\->messageBoxInfo(
125                         sprintf($bearsamppLang\->getValue(Lang::ALIAS_CREATED), $aliasName, $apachePortUri, $aliasName, $aliasDest),
126                         $bearsamppLang\->getValue(Lang::ADD_ALIAS_TITLE));
127                     $bearsamppWinbinder\->destroyWindow($window);
128                 } else {
129                     $bearsamppWinbinder\->messageBoxError($bearsamppLang\->getValue(Lang::ALIAS_CREATED_ERROR), $bearsamppLang\->getValue(Lang::ADD_ALIAS_TITLE));
130                     $bearsamppWinbinder\->resetProgressBar($this\->wbProgressBar);
131                 }
132                 break;
133             case IDCLOSE:
134             case $this\->wbBtnCancel[WinBinder::CTRL_ID]:
135                 $bearsamppWinbinder\->destroyWindow($window);
136                 break;
137         }
138     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fB$bearsamppRoot\fP, \fBLang\\ADD_ALIAS_TITLE\fP, \fBLang\\ALIAS_ALREADY_EXISTS\fP, \fBLang\\ALIAS_CREATED\fP, \fBLang\\ALIAS_CREATED_ERROR\fP, \fBLang\\ALIAS_DEST_PATH\fP, \fBLang\\ALIAS_EXP_LABEL\fP, \fBLang\\ALIAS_NOT_VALID_ALPHA\fP, \fBWinBinder\\CTRL_ID\fP, and \fBWinBinder\\CTRL_OBJ\fP\&.
.SH "Field Documentation"
.PP 
.SS "$wbBtnCancel\fR [private]\fP"

.PP
Definition at line \fB25\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SS "$wbBtnDest\fR [private]\fP"

.PP
Definition at line \fB21\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SS "$wbBtnSave\fR [private]\fP"

.PP
Definition at line \fB24\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SS "$wbInputDest\fR [private]\fP"

.PP
Definition at line \fB20\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SS "$wbInputName\fR [private]\fP"

.PP
Definition at line \fB18\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SS "$wbLabelDest\fR [private]\fP"

.PP
Definition at line \fB19\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SS "$wbLabelExp\fR [private]\fP"

.PP
Definition at line \fB22\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SS "$wbLabelName\fR [private]\fP"

.PP
Definition at line \fB17\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SS "$wbProgressBar\fR [private]\fP"

.PP
Definition at line \fB23\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SS "$wbWindow\fR [private]\fP"

.PP
Definition at line \fB16\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.
.SS "const GAUGE_SAVE = 2"

.PP
Definition at line \fB27\fP of file \fBclass\&.action\&.addAlias\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
