ActionLaunchStartup
NAME
ActionLaunchStartup
SYNOPSIS
Public Member Functions
__construct ($args)
Detailed Description
Class ActionLaunchStartup
This class manages the application's launch startup settings. It initializes the settings based on the provided arguments and updates the configuration accordingly.
Definition at line 16 of file class.action.launchStartup.php.
Constructor & Destructor Documentation
__construct ( $args)
ActionLaunchStartup constructor.
This constructor uses the provided arguments to determine whether to enable or disable the application's launch at startup feature. It starts the loading process, updates the launch startup configuration based on the provided argument, and modifies the system's startup settings accordingly.
Parameters
$args An array of arguments where the first element should be either Config\ENABLED or Config\DISABLED to indicate the desired launch startup setting.
Definition at line 28 of file class.action.launchStartup.php.
    {
        global $bearsamppConfig;
        if (isset($args[0])) {
            Util::startLoading();
            $launchStartup = $args[0] == Config::ENABLED;
            if ($launchStartup) {
                Util::enableLaunchStartup();
            } else {
                Util::disableLaunchStartup();
            }
            $bearsamppConfig->replace(Config::CFG_LAUNCH_STARTUP, $args[0]);
        }
    }
References $bearsamppConfig, Config\CFG_LAUNCH_STARTUP, Util\disableLaunchStartup(), Config\ENABLED, Util\enableLaunchStartup(), and Util\startLoading().
Author
Generated automatically by Doxygen for Bearsampp from the source code.