.TH "ActionCheckVersion" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionCheckVersion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($args)"
.br
.ti -1c
.RI "\fBprocessWindow\fP ($window, $id, $ctrl, $param1, $param2)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBDISPLAY_OK\fP = 'displayOk'"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBshowVersionOkMessageBox\fP ($lang, $winbinder)"
.br
.ti -1c
.RI "\fBshowVersionUpdateWindow\fP ($lang, $winbinder, $core, $githubLatestVersion)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$currentVersion\fP"
.br
.ti -1c
.RI "\fB$githubLatestVersionUrl\fP"
.br
.ti -1c
.RI "\fB$latestVersion\fP"
.br
.ti -1c
.RI "\fB$wbBtnOk\fP"
.br
.ti -1c
.RI "\fB$wbImage\fP"
.br
.ti -1c
.RI "\fB$wbLinkChangelog\fP"
.br
.ti -1c
.RI "\fB$wbLinkFull\fP"
.br
.ti -1c
.RI "\fB$wbWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $args)"
Constructor for the \fBActionCheckVersion\fP class\&.

.PP
\fBParameters\fP
.RS 4
\fI$args\fP Command line arguments passed to the script\&. 
.RE
.PP

.PP
Definition at line \fB39\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.nf
40     {
41         global $bearsamppCore, $bearsamppLang, $bearsamppWinbinder, $appGithubHeader;
42 
43         // Check if we're being called from the version check menu item
44         $isMenuCheck = !empty($args[0]) && $args[0] == self::DISPLAY_OK;
45 
46         // Start loading only if the exec file doesn't exist or if we're doing a menu check
47         if (!file_exists($bearsamppCore\->getExec()) || $isMenuCheck) {
48             Util::startLoading();
49             $this\->currentVersion = $bearsamppCore\->getAppVersion();
50 
51             // Assuming getLatestVersion now returns an array with version and URL
52             $githubVersionData = Util::getLatestVersion(APP_GITHUB_LATEST_URL);
53 
54             if ($githubVersionData != null && isset($githubVersionData['version'], $githubVersionData['html_url'])) {
55                 $githubLatestVersion = $githubVersionData['version'];
56                 $this\->githubLatestVersionUrl = $githubVersionData['html_url']; // URL of the latest version
57                 if (version_compare($this\->currentVersion, $githubLatestVersion, '<')) {
58                     $this\->showVersionUpdateWindow($bearsamppLang, $bearsamppWinbinder, $bearsamppCore, $githubLatestVersion);
59                 } elseif ($isMenuCheck) {
60                     $this\->showVersionOkMessageBox($bearsamppLang, $bearsamppWinbinder);
61                 }
62             }
63         }
64     }
.PP
.fi

.PP
References \fB$bearsamppCore\fP, \fB$bearsamppLang\fP, \fB$githubLatestVersion\fP, \fB$githubVersionData\fP, \fBAPP_GITHUB_LATEST_URL\fP, \fBUtil\\getLatestVersion()\fP, \fBshowVersionOkMessageBox()\fP, \fBshowVersionUpdateWindow()\fP, and \fBUtil\\startLoading()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "processWindow ( $window,  $id,  $ctrl,  $param1,  $param2)"
Processes window events and handles user interactions\&.

.PP
\fBParameters\fP
.RS 4
\fI$window\fP The window resource\&. 
.br
\fI$id\fP The control ID that triggered the event\&. 
.br
\fI$ctrl\fP The control resource\&. 
.br
\fI$param1\fP Additional parameter 1\&. 
.br
\fI$param2\fP Additional parameter 2\&. 
.RE
.PP

.PP
Definition at line \fB118\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.nf
119     {
120         global $bearsamppConfig, $bearsamppWinbinder;
121 
122         switch ($id) {
123             case $this\->wbLinkFull[WinBinder::CTRL_ID]:
124                 $latestVersionInfo = Util::getLatestVersion(APP_GITHUB_LATEST_URL);
125                 if ($latestVersionInfo && isset($latestVersionInfo['html_url'])) {
126                     $browserPath = $bearsamppConfig\->getBrowser();
127                     if (!$bearsamppWinbinder\->exec($browserPath, $latestVersionInfo['html_url'])) {
128                         Util::logError("Failed to open browser at path: $browserPath with URL: " \&. $latestVersionInfo['html_url']);
129                     }
130                 } else {
131                     Util::logError("Failed to retrieve latest version info or 'html_url' not set\&.");
132                 }
133                 break;
134             case IDCLOSE:
135             case $this\->wbBtnOk[WinBinder::CTRL_ID]:
136                 $bearsamppWinbinder\->destroyWindow($window);
137                 break;
138             default:
139                 Util::logError("Unhandled window control ID: $id");
140         }
141     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, \fBAPP_GITHUB_LATEST_URL\fP, \fBWinBinder\\CTRL_ID\fP, \fBUtil\\getLatestVersion()\fP, and \fBUtil\\logError()\fP\&.
.SS "showVersionOkMessageBox ( $lang,  $winbinder)\fR [private]\fP"
Displays a message box indicating that the current version is the latest\&.

.PP
\fBParameters\fP
.RS 4
\fI$lang\fP Language processor instance\&. 
.br
\fI$winbinder\fP \fBWinBinder\fP instance for creating windows and controls\&. 
.RE
.PP

.PP
Definition at line \fB100\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.nf
101     {
102         Util::stopLoading();
103         $winbinder\->messageBoxInfo(
104             $lang\->getValue(Lang::CHECK_VERSION_LATEST_TEXT),
105             $lang\->getValue(Lang::CHECK_VERSION_TITLE)
106         );
107     }
.PP
.fi

.PP
References \fBLang\\CHECK_VERSION_LATEST_TEXT\fP, \fBLang\\CHECK_VERSION_TITLE\fP, and \fBUtil\\stopLoading()\fP\&.
.PP
Referenced by \fB__construct()\fP\&.
.SS "showVersionUpdateWindow ( $lang,  $winbinder,  $core,  $githubLatestVersion)\fR [private]\fP"
Displays a window with the latest version information\&.

.PP
\fBParameters\fP
.RS 4
\fI$lang\fP Language processor instance\&. 
.br
\fI$winbinder\fP \fBWinBinder\fP instance for creating windows and controls\&. 
.br
\fI$core\fP \fBCore\fP instance for accessing application resources\&. 
.br
\fI$githubLatestVersion\fP The latest version available on GitHub\&. 
.RE
.PP

.PP
Definition at line \fB74\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.nf
75     {
76         $labelFullLink = $lang\->getValue(Lang::DOWNLOAD) \&. ' ' \&. APP_TITLE \&. ' ' \&. $githubLatestVersion;
77 
78         $winbinder\->reset();
79         $this\->wbWindow = $winbinder\->createAppWindow($lang\->getValue(Lang::CHECK_VERSION_TITLE), 380, 170, WBC_NOTIFY, WBC_KEYDOWN | WBC_KEYUP);
80 
81         $winbinder\->createLabel($this\->wbWindow, $lang\->getValue(Lang::CHECK_VERSION_AVAILABLE_TEXT), 80, 35, 370, 120);
82 
83         $this\->wbLinkFull = $winbinder\->createHyperLink($this\->wbWindow, $labelFullLink, 80, 87, 200, 20, WBC_LINES | WBC_RIGHT);
84 
85         $this\->wbBtnOk = $winbinder\->createButton($this\->wbWindow, $lang\->getValue(Lang::BUTTON_OK), 280, 103);
86         $this\->wbImage = $winbinder\->drawImage($this\->wbWindow, $core\->getImagesPath() \&. '/about\&.bmp');
87 
88         Util::stopLoading();
89         $winbinder\->setHandler($this\->wbWindow, $this, 'processWindow');
90         $winbinder\->mainLoop();
91         $winbinder\->reset();
92     }
.PP
.fi

.PP
References \fB$githubLatestVersion\fP, \fBAPP_TITLE\fP, \fBLang\\BUTTON_OK\fP, \fBLang\\CHECK_VERSION_AVAILABLE_TEXT\fP, \fBLang\\CHECK_VERSION_TITLE\fP, \fBLang\\DOWNLOAD\fP, and \fBUtil\\stopLoading()\fP\&.
.PP
Referenced by \fB__construct()\fP\&.
.SH "Field Documentation"
.PP 
.SS "$currentVersion\fR [private]\fP"

.PP
Definition at line \fB30\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.SS "$githubLatestVersionUrl\fR [private]\fP"

.PP
Definition at line \fB32\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.SS "$latestVersion\fR [private]\fP"

.PP
Definition at line \fB31\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.SS "$wbBtnOk\fR [private]\fP"

.PP
Definition at line \fB28\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.SS "$wbImage\fR [private]\fP"

.PP
Definition at line \fB25\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.SS "$wbLinkChangelog\fR [private]\fP"

.PP
Definition at line \fB26\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.SS "$wbLinkFull\fR [private]\fP"

.PP
Definition at line \fB27\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.SS "$wbWindow\fR [private]\fP"

.PP
Definition at line \fB24\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.SS "const DISPLAY_OK = 'displayOk'"

.PP
Definition at line \fB22\fP of file \fBclass\&.action\&.checkVersion\&.php\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuRight()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
