ActionLoading
NAME
ActionLoading
SYNOPSIS
Public Member Functions
__construct ($args)
incrProgressBar ($nb=1)
processLoading ($window, $id, $ctrl, $param1, $param2)
Data Fields
const GAUGE = 20
const WINDOW_HEIGHT = 90
const WINDOW_WIDTH = 360
Private Member Functions
checkAllServicesStarted ()
Private Attributes
$wbProgressBar
$wbWindow
Detailed Description
Class ActionLoading
This class handles the loading action, including the creation and management of a progress bar window.
Definition at line 16 of file class.action.loading.php.
Constructor & Destructor Documentation
__construct ( $args)
ActionLoading constructor.
Initializes the loading action, creates the progress bar window, and starts the main loop.
Parameters
$args The arguments passed to the constructor.
Definition at line 40 of file class.action.loading.php.
    {
        global $bearsamppCore, $bearsamppLang, $bearsamppWinbinder;
        $bearsamppWinbinder->reset();
        $bearsamppCore->addLoadingPid(Win32Ps::getCurrentPid());
        // Screen information
        $screenArea = explode(' ', $bearsamppWinbinder->getSystemInfo(WinBinder::SYSINFO_WORKAREA));
        $screenWidth = intval($screenArea[2]);
        $screenHeight = intval($screenArea[3]);
        $xPos = $screenWidth - self::WINDOW_WIDTH;
        $yPos = $screenHeight - self::WINDOW_HEIGHT - 5;
        // Create the window and progress bar
        $this->wbWindow = $bearsamppWinbinder->createWindow(null, ToolDialog, null, $xPos, $yPos, self::WINDOW_WIDTH, self::WINDOW_HEIGHT, WBC_TOP, null);
        $bearsamppWinbinder->createLabel($this->wbWindow, $bearsamppLang->getValue(Lang::LOADING), 42, 2, 295, null, WBC_LEFT);
        $this->wbProgressBar = $bearsamppWinbinder->createProgressBar($this->wbWindow, self::GAUGE, 42, 20, 290, 15);
        // Set the handler and start the main loop
        $bearsamppWinbinder->setHandler($this->wbWindow, $this, 'processLoading', 10);
        $bearsamppWinbinder->mainLoop();
    }
References $bearsamppCore, $bearsamppLang, Win32Ps\getCurrentPid(), Lang\LOADING, and WinBinder\SYSINFO_WORKAREA.
Member Function Documentation
checkAllServicesStarted () [private]
Checks if all services have started successfully
Returns
bool True if all services are running, false otherwise
Definition at line 152 of file class.action.loading.php.
    {
        global $bearsamppBins, $bearsamppCore, $bearsamppRoot;
        
        Util::logTrace('Checking if all services have started successfully');
        
        $allStarted = true;
        foreach ($bearsamppBins->getServices() as $sName => $service) {
            // Skip if service is not enabled
            if (!$service->isEnable()) {
                Util::logTrace('Service ' . $sName . ' is disabled, skipping check');
                continue;
            }
            
            // Add timeout for service status check
            $checkStartTime = microtime(true);
            $checkTimeout = 5; // 5 seconds timeout
            $serviceRunning = false;
            
            try {
                // Use a non-blocking check with timeout
                $tempFile = $bearsamppCore->getTmpPath() . '/service_check_' . uniqid() . '.tmp';
                
                // Start a background process to check the service
                $checkCmd = 'php -r "' .
                    'require \'' . $bearsamppRoot->getLibsPath() . '/classes/class.win32service.php\'; ' .
                    '$service = new Win32Service(\'' . $service->getName() . '\'); ' .
                    '$status = $service->status(); ' .
                    'file_put_contents(\'' . $tempFile . '\', $status == Win32Service::STATE_RUNNING ? \'1\' : \'0\'); ' .
                    'exit(0);" > nul 2>&1';
                
                // Execute the command in background
                pclose(popen('start /B ' . $checkCmd, 'r'));
                
                // Wait for the result with timeout
                $startWait = microtime(true);
                while (!file_exists($tempFile) && (microtime(true) - $startWait < $checkTimeout)) {
                    usleep(100000); // 100ms
                }
                
                // Check if we got a result
                if (file_exists($tempFile)) {
                    $result = file_get_contents($tempFile);
                    $serviceRunning = ($result === '1');
                    unlink($tempFile);
                    Util::logTrace('Service ' . $sName . ' status check: ' . ($serviceRunning ? 'running' : 'not running'));
                } else {
                    Util::logTrace('Service ' . $sName . ' status check timed out');
                    $serviceRunning = false;
                }
            } catch (\Exception $e) {
                Util::logTrace('Exception during service status check for ' . $sName . ': ' . $e->getMessage());
                $serviceRunning = false;
            }
            
            if (!$serviceRunning) {
                Util::logTrace('Service ' . $sName . ' is not running');
                $allStarted = false;
                break;
            }
        }
        
        Util::logTrace('All services started check result: ' . ($allStarted ? 'true' : 'false'));
        return $allStarted;
    }
References $bearsamppBins, $bearsamppCore, $bearsamppRoot, $result, and Util\logTrace().
Referenced by processLoading().
incrProgressBar ( $nb = 1)
Increments the progress bar by a specified number of steps.
Parameters
$nb The number of steps to increment the progress bar by. Default is 1.
Definition at line 69 of file class.action.loading.php.
    {
        global $bearsamppCore, $bearsamppWinbinder;
        for ($i = 0; $i < $nb; $i++) {
            $bearsamppWinbinder->incrProgressBar($this->wbProgressBar);
            $bearsamppWinbinder->drawImage($this->wbWindow, $bearsamppCore->getImagesPath() . '/bearsampp.bmp', 4, 2, 32, 32);
        }
        $bearsamppWinbinder->wait();
        $bearsamppWinbinder->wait($this->wbWindow);
    }
References $bearsamppCore.
Referenced by processLoading().
processLoading ( $window, $id, $ctrl, $param1, $param2)
Processes the loading action, including handling window events and updating the progress bar.
Parameters
$window The window object.
$id The ID of the event.
$ctrl The control object.
$param1 The first parameter of the event.
$param2 The second parameter of the event.
Definition at line 91 of file class.action.loading.php.
    {
        global $bearsamppRoot, $bearsamppWinbinder;
        switch ($id) {
            case IDCLOSE:
                Win32Ps::kill(Win32Ps::getCurrentPid());
                break;
        }
        // Set a maximum number of iterations to prevent infinite loops
        $maxIterations = 10;
        $iterations = 0;
        // Set a timeout for the entire loading process
        $startTime = microtime(true); // Use microtime for more precise timing
        $maxLoadingTime = 15; // 15 seconds maximum
        while ($iterations < $maxIterations && (microtime(true) - $startTime) < $maxLoadingTime) {
            $bearsamppRoot->removeErrorHandling();
            $bearsamppWinbinder->resetProgressBar($this->wbProgressBar);
            usleep(100000);
            for ($i = 0; $i < self::GAUGE && (microtime(true) - $startTime) < $maxLoadingTime; $i++) {
                $this->incrProgressBar();
                usleep(100000);
            }
            // Check if all services have started successfully
            $allServicesStarted = $this->checkAllServicesStarted();
            if ($allServicesStarted) {
                Util::logTrace('All services started successfully');
                break;
            }
            $iterations++;
            Util::logTrace('Loading iteration ' . $iterations . ' completed, checking services again');
        }
        if ($iterations >= $maxIterations) {
            Util::logTrace('Maximum iterations reached (' . $maxIterations . '), some services may not have started properly');
        }
        
        if ((microtime(true) - $startTime) >= $maxLoadingTime) {
            Util::logTrace('Loading timeout reached (' . $maxLoadingTime . ' seconds), some services may not have started properly');
        }
        
        // Add a small delay before killing the process to ensure UI updates are complete
        usleep(500000); // 500ms
        
        // Close the loading window
        Util::logTrace('Closing loading window');
        Win32Ps::kill(Win32Ps::getCurrentPid());
    }
References $bearsamppRoot, checkAllServicesStarted(), Win32Ps\getCurrentPid(), incrProgressBar(), Win32Ps\kill(), and Util\logTrace().
Field Documentation
$wbProgressBar [private]
Definition at line 31 of file class.action.loading.php.
$wbWindow [private]
Definition at line 28 of file class.action.loading.php.
const GAUGE = 20
Definition at line 25 of file class.action.loading.php.
const WINDOW_HEIGHT = 90
Definition at line 22 of file class.action.loading.php.
const WINDOW_WIDTH = 360
Definition at line 19 of file class.action.loading.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.