ActionStartup
NAME
ActionStartup
SYNOPSIS
Public Member Functions
__construct ($args)
processWindow ($window, $id, $ctrl, $param1, $param2)
Data Fields
const GAUGE_OTHERS = 19
const GAUGE_SERVICES = 5
Private Member Functions
changePath ()
checkApacheServiceWithTimeout ($service)
checkBinsRegKey ()
checkBrowser ()
checkLaunchStartup ()
checkMySQLServiceWithTimeout ($service, $bin)
checkPath ()
checkPathRegKey ()
checkSystemPathRegKey ()
cleanOldBehaviors ()
cleanTmpFolders ()
createSslCrts ()
installServices ()
killOldInstances ()
refreshAliases ()
refreshGitRepos ()
refreshHostname ()
refreshVhosts ()
rotationLogs ()
savePath ()
scanFolders ()
sysInfos ()
updateConfig ()
writeLog ($log)
Private Attributes
$error
$filesToScan
$restart
$rootPath
$splash
$startTime
Detailed Description
Class ActionStartup Handles the startup process of the Bearsampp application, including initializing services, cleaning temporary files, refreshing configurations, and more.
Definition at line 16 of file class.action.startup.php.
Constructor & Destructor Documentation
__construct ( $args)
ActionStartup constructor. Initializes the startup process, including the splash screen and various configurations.
Parameters
$args Command line arguments.
Definition at line 35 of file class.action.startup.php.
    {
        global $bearsamppRoot, $bearsamppCore, $bearsamppLang, $bearsamppBins, $bearsamppWinbinder;
        $this->writeLog( 'Starting ' . APP_TITLE );
        // Init
        $this->splash = new Splash();
        $this->restart = false;
        $this->startTime = Util::getMicrotime();
        $this->error = '';
        $this->rootPath = $bearsamppRoot->getRootPath();
        $this->filesToScan = array();
        $gauge = self::GAUGE_SERVICES * count( $bearsamppBins->getServices() );
        $gauge += self::GAUGE_OTHERS + 1;
        // Start splash screen
        $this->splash->init(
            $bearsamppLang->getValue( Lang::STARTUP ),
            $gauge,
            sprintf( $bearsamppLang->getValue( Lang::STARTUP_STARTING_TEXT ), APP_TITLE . ' ' . $bearsamppCore->getAppVersion() )
        );
        $bearsamppWinbinder->setHandler( $this->splash->getWbWindow(), $this, 'processWindow', 1000 );
        $bearsamppWinbinder->mainLoop();
        $bearsamppWinbinder->reset();
    }
References $bearsamppBins, $bearsamppCore, $bearsamppLang, $bearsamppRoot, APP_TITLE, Util\getMicrotime(), Lang\STARTUP, Lang\STARTUP_STARTING_TEXT, and writeLog().
Member Function Documentation
changePath () [private]
Changes the application path and logs the number of files and occurrences changed.
Definition at line 664 of file class.action.startup.php.
    {
        global $bearsamppLang;
        $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_CHANGE_PATH_TEXT ), $this->rootPath ) );
        $this->splash->incrProgressBar();
        $result = Util::changePath( $this->filesToScan, $this->rootPath );
        $this->writeLog( 'Nb files changed: ' . $result['countChangedFiles'] );
        $this->writeLog( 'Nb occurences changed: ' . $result['countChangedOcc'] );
    }
References $bearsamppLang, $result, Util\changePath(), Lang\STARTUP_CHANGE_PATH_TEXT, and writeLog().
Referenced by processWindow().
checkApacheServiceWithTimeout ( $service) [private]
Specialized method to check Apache service with timeout protection. Apache service checks can sometimes hang, so this method provides a safer way to check.
Parameters
$service The Apache service object
Returns
mixed Service info array or false if service not installed or check timed out
Definition at line 1129 of file class.action.startup.php.
    {
        Util::logTrace('Starting specialized Apache service check with timeout protection');
        // Set a timeout for the Apache service check
        $serviceCheckStartTime = microtime(true);
        $serviceCheckTimeout = 10; // 10 seconds timeout
        try {
            // Use a non-blocking approach to check service
            $serviceInfos = false;
            // First try a quick check if the service exists in the list
            $serviceList = Win32Service::getServices();
            if (is_array($serviceList) && isset($serviceList[$service->getName()])) {
                Util::logTrace('Apache service found in service list, getting details');
                // Service exists, now try to get its details with timeout protection
                $startTime = microtime(true);
                $serviceInfos = $service->infos();
                // Check if we've exceeded our timeout
                if (microtime(true) - $serviceCheckStartTime > $serviceCheckTimeout) {
                    Util::logTrace("Apache service check timeout exceeded, assuming service needs reinstall");
                    return false;
                }
            } else {
                Util::logTrace('Apache service not found in service list');
                return false;
            }
            return $serviceInfos;
        } catch (\Exception $e) {
            Util::logTrace("Exception during Apache service check: " . $e->getMessage());
            return false;
        } catch (\Throwable $e) {
            Util::logTrace("Throwable during Apache service check: " . $e->getMessage());
            return false;
        }
    }
References $startTime, and Util\logTrace().
Referenced by installServices().
checkBinsRegKey () [private]
Checks and updates the application bins registry key. If the current registry key does not match the generated key, it updates the registry key. Logs the current and generated registry keys. Sets an error message if the registry key update fails. Sets a restart flag if the registry key is updated.
Definition at line 723 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppRegistry;
        $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_TEXT ), Registry::APP_BINS_REG_ENTRY ) );
        $this->splash->incrProgressBar();
        $currentAppBinsRegKey = Util::getAppBinsRegKey();
        $genAppBinsRegKey = Util::getAppBinsRegKey( false );
        $this->writeLog( 'Current app bins reg key: ' . $currentAppBinsRegKey );
        $this->writeLog( 'Gen app bins reg key: ' . $genAppBinsRegKey );
        if ( $currentAppBinsRegKey != $genAppBinsRegKey ) {
            if ( !Util::setAppBinsRegKey( $genAppBinsRegKey ) ) {
                if ( !empty( $this->error ) ) {
                    $this->error .= PHP_EOL . PHP_EOL;
                }
                $this->error .= sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_ERROR_TEXT ), Registry::APP_BINS_REG_ENTRY );
                $this->error .= PHP_EOL . $bearsamppRegistry->getLatestError();
            }
            else {
                $this->writeLog( 'Need restart: checkBinsRegKey' );
                $this->restart = true;
            }
        }
    }
References $bearsamppLang, Registry\APP_BINS_REG_ENTRY, Util\getAppBinsRegKey(), Util\setAppBinsRegKey(), Lang\STARTUP_REGISTRY_ERROR_TEXT, Lang\STARTUP_REGISTRY_TEXT, and writeLog().
Referenced by processWindow().
checkBrowser () [private]
Checks and sets the default browser configuration.
Definition at line 578 of file class.action.startup.php.
    {
        global $bearsamppConfig, $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_CHECK_BROWSER_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Check browser' );
        $currentBrowser = $bearsamppConfig->getBrowser();
        if ( empty( $currentBrowser ) || !file_exists( $currentBrowser ) ) {
            $bearsamppConfig->replace( Config::CFG_BROWSER, Vbs::getDefaultBrowser() );
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\CFG_BROWSER, Vbs\getDefaultBrowser(), Lang\STARTUP_CHECK_BROWSER_TEXT, and writeLog().
Referenced by processWindow().
checkLaunchStartup () [private]
Checks and sets the launch startup configuration.
Definition at line 561 of file class.action.startup.php.
    {
        global $bearsamppConfig;
        $this->writeLog( 'Check launch startup' );
        if ( $bearsamppConfig->isLaunchStartup() ) {
            Util::enableLaunchStartup();
        }
        else {
            Util::disableLaunchStartup();
        }
    }
References $bearsamppConfig, Util\disableLaunchStartup(), Util\enableLaunchStartup(), and writeLog().
Referenced by processWindow().
checkMySQLServiceWithTimeout ( $service, $bin) [private]
Specialized method to check MySQL service with timeout protection. MySQL service checks can sometimes hang, so this method provides a safer way to check.
Parameters
$service The MySQL service object
$bin The MySQL bin object
Returns
mixed Service info array or false if service not installed or check timed out
Definition at line 1178 of file class.action.startup.php.
    {
        Util::logTrace('Starting specialized MySQL service check with timeout protection');
        // Set a timeout for the MySQL service check
        $serviceCheckStartTime = microtime(true);
        $serviceCheckTimeout = 8; // 8 seconds timeout
        try {
            // Use a non-blocking approach to check service
            $serviceInfos = false;
            // First check if the service exists in the list
            $serviceList = Win32Service::getServices();
            if (is_array($serviceList) && isset($serviceList[$service->getName()])) {
                Util::logTrace('MySQL service found in service list, getting details');
                // Service exists, now try to get its details with timeout protection
                $serviceInfos = $service->infos();
                // Check if we've exceeded our timeout
                if (microtime(true) - $serviceCheckStartTime > $serviceCheckTimeout) {
                    Util::logTrace("MySQL service check timeout exceeded, assuming service needs reinstall");
                    return false;
                }
            } else {
                Util::logTrace('MySQL service not found in service list');
                return false;
            }
            return $serviceInfos;
        } catch (\Exception $e) {
            Util::logTrace("Exception during MySQL service check: " . $e->getMessage());
            return false;
        } catch (\Throwable $e) {
            Util::logTrace("Throwable during MySQL service check: " . $e->getMessage());
            return false;
        }
    }
References Util\logTrace().
Referenced by installServices().
checkPath () [private]
Checks the application path and logs the last path content.
Definition at line 637 of file class.action.startup.php.
    {
        global $bearsamppCore, $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_CHECK_PATH_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Last path: ' . $bearsamppCore->getLastPathContent() );
    }
References $bearsamppCore, $bearsamppLang, Lang\STARTUP_CHECK_PATH_TEXT, and writeLog().
Referenced by processWindow().
checkPathRegKey () [private]
Checks and updates the application path registry key.
Definition at line 690 of file class.action.startup.php.
    {
        global $bearsamppRoot, $bearsamppLang, $bearsamppRegistry;
        $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_TEXT ), Registry::APP_PATH_REG_ENTRY ) );
        $this->splash->incrProgressBar();
        $currentAppPathRegKey = Util::getAppPathRegKey();
        $genAppPathRegKey = Util::formatWindowsPath( $bearsamppRoot->getRootPath() );
        $this->writeLog( 'Current app path reg key: ' . $currentAppPathRegKey );
        $this->writeLog( 'Gen app path reg key: ' . $genAppPathRegKey );
        if ( $currentAppPathRegKey != $genAppPathRegKey ) {
            if ( !Util::setAppPathRegKey( $genAppPathRegKey ) ) {
                if ( !empty( $this->error ) ) {
                    $this->error .= PHP_EOL . PHP_EOL;
                }
                $this->error .= sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_ERROR_TEXT ), Registry::APP_PATH_REG_ENTRY );
                $this->error .= PHP_EOL . $bearsamppRegistry->getLatestError();
            }
            else {
                $this->writeLog( 'Need restart: checkPathRegKey' );
                $this->restart = true;
            }
        }
    }
References $bearsamppLang, $bearsamppRoot, Registry\APP_PATH_REG_ENTRY, Util\formatWindowsPath(), Util\getAppPathRegKey(), Util\setAppPathRegKey(), Lang\STARTUP_REGISTRY_ERROR_TEXT, Lang\STARTUP_REGISTRY_TEXT, and writeLog().
Referenced by processWindow().
checkSystemPathRegKey () [private]
Checks and updates the system PATH registry key. Ensures the application bins registry entry is at the beginning of the system PATH. Logs the current and new system PATH. Sets an error message if the system PATH update fails. Sets a restart flag if the system PATH is updated.
Definition at line 756 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppRegistry;
        $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_TEXT ), Registry::SYSPATH_REG_ENTRY ) );
        $this->splash->incrProgressBar();
        $currentSysPathRegKey = Util::getSysPathRegKey();
        $this->writeLog( 'Current system PATH: ' . $currentSysPathRegKey );
        $newSysPathRegKey = str_replace( '%' . Registry::APP_BINS_REG_ENTRY . '%;', '', $currentSysPathRegKey );
        $newSysPathRegKey = str_replace( '%' . Registry::APP_BINS_REG_ENTRY . '%', '', $newSysPathRegKey );
        $newSysPathRegKey = '%' . Registry::APP_BINS_REG_ENTRY . '%;' . $newSysPathRegKey;
        $this->writeLog( 'New system PATH: ' . $newSysPathRegKey );
        if ( $currentSysPathRegKey != $newSysPathRegKey ) {
            if ( !Util::setSysPathRegKey( $newSysPathRegKey ) ) {
                if ( !empty( $this->error ) ) {
                    $this->error .= PHP_EOL . PHP_EOL;
                }
                $this->error .= sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_ERROR_TEXT ), Registry::SYSPATH_REG_ENTRY );
                $this->error .= PHP_EOL . $bearsamppRegistry->getLatestError();
            }
            else {
                $this->writeLog( 'Need restart: checkSystemPathRegKey' );
                $this->restart = true;
            }
        }
        else {
            $this->writeLog( 'Refresh system PATH: ' . $currentSysPathRegKey );
            Util::setSysPathRegKey( str_replace( '%' . Registry::APP_BINS_REG_ENTRY . '%', '', $currentSysPathRegKey ) );
            Util::setSysPathRegKey( $currentSysPathRegKey );
        }
    }
References $bearsamppLang, Registry\APP_BINS_REG_ENTRY, Util\getSysPathRegKey(), Util\setSysPathRegKey(), Lang\STARTUP_REGISTRY_ERROR_TEXT, Lang\STARTUP_REGISTRY_TEXT, Registry\SYSPATH_REG_ENTRY, and writeLog().
Referenced by processWindow().
cleanOldBehaviors () [private]
Cleans old behaviors by removing outdated registry entries.
Definition at line 492 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppRegistry;
        $this->writeLog( 'Clean old behaviors' );
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_CLEAN_OLD_BEHAVIORS_TEXT ) );
        $this->splash->incrProgressBar();
        // App >= 1.0.13
        $bearsamppRegistry->deleteValue(
            Registry::HKEY_LOCAL_MACHINE,
            'SOFTWARE\Microsoft\Windows\CurrentVersion\Run',
            APP_TITLE
        );
    }
References $bearsamppLang, APP_TITLE, Registry\HKEY_LOCAL_MACHINE, Lang\STARTUP_CLEAN_OLD_BEHAVIORS_TEXT, and writeLog().
Referenced by processWindow().
cleanTmpFolders () [private]
Cleans temporary folders by removing unnecessary files.
Definition at line 477 of file class.action.startup.php.
    {
        global $bearsamppRoot, $bearsamppLang, $bearsamppCore;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_CLEAN_TMP_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Clear tmp folders' );
        Util::clearFolder( $bearsamppRoot->getTmpPath(), array('cachegrind', 'composer', 'openssl', 'mailpit', 'xlight', 'npm-cache', 'pip', '.gitignore') );
        Util::clearFolder( $bearsamppCore->getTmpPath(), array('.gitignore') );
    }
References $bearsamppCore, $bearsamppLang, $bearsamppRoot, Util\clearFolder(), Lang\STARTUP_CLEAN_TMP_TEXT, and writeLog().
Referenced by processWindow().
createSslCrts () [private]
Creates SSL certificates if they do not already exist. Logs the creation process.
Definition at line 812 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppOpenSsl;
        $this->splash->incrProgressBar();
        if ( !$bearsamppOpenSsl->existsCrt( 'localhost' ) ) {
            $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_GEN_SSL_CRT_TEXT ), 'localhost' ) );
            $bearsamppOpenSsl->createCrt( 'localhost' );
        }
    }
References $bearsamppLang, and Lang\STARTUP_GEN_SSL_CRT_TEXT.
Referenced by processWindow().
installServices () [private]
Installs and starts services for the application. Checks if services are already installed and updates them if necessary. Logs the installation process and any errors encountered.
Definition at line 829 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppBins, $bearsamppRoot;
        Util::logTrace('Starting installServices method');
        if (!$this->restart) {
            Util::logTrace('Normal startup mode - processing services');
            foreach ($bearsamppBins->getServices() as $sName => $service) {
                $serviceError = '';
                $serviceRestart = false;
                $serviceAlreadyInstalled = false;
                $serviceToRemove = false;
                $startServiceTime = Util::getMicrotime();
                Util::logTrace('Processing service: ' . $sName);
                $syntaxCheckCmd = null;
                $bin = null;
                $port = 0;
                if ($sName == BinMailpit::SERVICE_NAME) {
                    $bin = $bearsamppBins->getMailpit();
                    $port = $bearsamppBins->getMailpit()->getSmtpPort();
                    Util::logTrace('Service identified as Mailpit, port: ' . $port);
                } elseif ($sName == BinMemcached::SERVICE_NAME) {
                    $bin = $bearsamppBins->getMemcached();
                    $port = $bearsamppBins->getMemcached()->getPort();
                    Util::logTrace('Service identified as Memcached, port: ' . $port);
                } elseif ($sName == BinApache::SERVICE_NAME) {
                    $bin = $bearsamppBins->getApache();
                    $port = $bearsamppBins->getApache()->getPort();
                    $syntaxCheckCmd = BinApache::CMD_SYNTAX_CHECK;
                    Util::logTrace('Service identified as Apache, port: ' . $port);
                } elseif ($sName == BinMysql::SERVICE_NAME) {
                    $bin = $bearsamppBins->getMysql();
                    $port = $bearsamppBins->getMysql()->getPort();
                    $syntaxCheckCmd = BinMysql::CMD_SYNTAX_CHECK;
                    Util::logTrace('Service identified as MySQL, port: ' . $port);
                    // Pre-initialize MySQL data if needed
                    if (!file_exists($bin->getDataDir()) || count(glob($bin->getDataDir() . '/*')) === 0) {
                        Util::logTrace('Pre-initializing MySQL data directory');
                        $this->splash->setTextLoading(sprintf($bearsamppLang->getValue(Lang::STARTUP_CHECK_SERVICE_TEXT), $name . ' (initializing data)'));
                        $bin->initData();
                    }
                } elseif ($sName == BinMariadb::SERVICE_NAME) {
                    $bin = $bearsamppBins->getMariadb();
                    $port = $bearsamppBins->getMariadb()->getPort();
                    $syntaxCheckCmd = BinMariadb::CMD_SYNTAX_CHECK;
                    Util::logTrace('Service identified as MariaDB, port: ' . $port);
                } elseif ($sName == BinPostgresql::SERVICE_NAME) {
                    $bin = $bearsamppBins->getPostgresql();
                    $port = $bearsamppBins->getPostgresql()->getPort();
                    Util::logTrace('Service identified as PostgreSQL, port: ' . $port);
                } elseif ($sName == BinXlight::SERVICE_NAME) {
                    $bin = $bearsamppBins->getXlight();
                    $port = $bearsamppBins->getXlight()->getPort();
                    Util::logTrace('Service identified as Xlight, port: ' . $port);
                }
                $name = $bin->getName() . ' ' . $bin->getVersion() . ' (' . $service->getName() . ')';
                Util::logTrace('Full service name: ' . $name);
                $this->splash->incrProgressBar();
                $this->splash->setTextLoading(sprintf($bearsamppLang->getValue(Lang::STARTUP_CHECK_SERVICE_TEXT), $name));
                Util::logTrace('Checking if service is already installed');
                // Add a timeout for the service check operation
                $serviceCheckStartTime = microtime(true);
                $serviceCheckTimeout = 15; // 15 seconds timeout
                // Use specialized check for Apache and MySQL services due to known issues with hanging
                if ($sName == BinApache::SERVICE_NAME) {
                    Util::logTrace('Using specialized Apache service check');
                    $serviceInfos = $this->checkApacheServiceWithTimeout($service);
                } else if ($sName == BinMysql::SERVICE_NAME) {
                    Util::logTrace('Using specialized MySQL service check');
                    $serviceInfos = $this->checkMySQLServiceWithTimeout($service, $bin);
                    // If service exists but is hanging, force restart
                    if ($serviceInfos === false && $service->isInstalled()) {
                        Util::logTrace('MySQL service appears to be hanging, forcing restart');
                        Win32Ps::killBins(['mysqld.exe']);
                        $service->delete();
                        $serviceToRemove = true;
                    }
                } else {
                    try {
                        // Call infos() with a timeout check for other services
                        $serviceInfos = $service->infos();
                        // Check if we've exceeded our timeout
                        if (microtime(true) - $serviceCheckStartTime > $serviceCheckTimeout) {
                            Util::logTrace("Service check timeout exceeded, assuming service is not installed");
                            $serviceInfos = false;
                        }
                    } catch (\Exception $e) {
                        Util::logTrace("Exception during service check: " . $e->getMessage() . ", assuming service is not installed");
                        $serviceInfos = false;
                    } catch (\Throwable $e) {
                        Util::logTrace("Throwable during service check: " . $e->getMessage() . ", assuming service is not installed");
                        $serviceInfos = false;
                    }
                }
                if ($serviceInfos !== false) {
                    $serviceAlreadyInstalled = true;
                    $this->writeLog($name . ' service already installed');
                    Util::logTrace('Service already installed, retrieving details');
                    foreach ($serviceInfos as $key => $value) {
                        $this->writeLog('-> ' . $key . ': ' . $value);
                        Util::logTrace('Service info - ' . $key . ': ' . $value);
                    }
                    // Special handling for PostgreSQL service
                    if ($sName == BinPostgresql::SERVICE_NAME) {
                        // For PostgreSQL, only compare the executable path, not the parameters
                        $serviceGenPathName = trim(str_replace('"', '', $service->getBinPath()));
                        $installedPathParts = explode(' ', $serviceInfos[Win32Service::VBS_PATH_NAME], 2);
                        $serviceVbsPathName = trim(str_replace('"', '', $installedPathParts[0]));
                        Util::logTrace('PostgreSQL service - comparing only executable paths');
                        Util::logTrace('Generated path: ' . $serviceGenPathName);
                        Util::logTrace('Installed path: ' . $serviceVbsPathName);
                    } else {
                        // For other services, use the normal comparison with enhanced debugging
                        $serviceGenPathName = trim(str_replace('"', '', $service->getBinPath() . ($service->getParams() ? ' ' . $service->getParams() : '')));
                        $serviceVbsPathName = trim(str_replace('"', '', $serviceInfos[Win32Service::VBS_PATH_NAME]));
                        Util::logTrace('Comparing service paths - Generated: ' . $serviceGenPathName . ' vs Installed: ' . $serviceVbsPathName);
                        // Add detailed debugging to identify invisible characters
                        Util::logTrace('Generated path length: ' . strlen($serviceGenPathName));
                        Util::logTrace('Installed path length: ' . strlen($serviceVbsPathName));
                        // Output character codes to identify invisible characters
                        $genChars = 'Generated path char codes: ';
                        for ($i = 0; $i < strlen($serviceGenPathName); $i++) {
                            $genChars .= ord($serviceGenPathName[$i]) . ' ';
                        }
                        Util::logTrace($genChars);
                        $instChars = 'Installed path char codes: ';
                        for ($i = 0; $i < strlen($serviceVbsPathName); $i++) {
                            $instChars .= ord($serviceVbsPathName[$i]) . ' ';
                        }
                        Util::logTrace($instChars);
                    }
                    // Try a more robust comparison that normalizes whitespace
                    $normalizedGenPath = preg_replace('/\s+/', ' ', $serviceGenPathName);
                    $normalizedVbsPath = preg_replace('/\s+/', ' ', $serviceVbsPathName);
                    if ($normalizedGenPath === $normalizedVbsPath) {
                        Util::logTrace('Paths match after normalizing whitespace - skipping service reinstall');
                    } else if ($serviceGenPathName != $serviceVbsPathName) {
                        $serviceToRemove = true;
                        $this->writeLog($name . ' service has to be removed');
                        $this->writeLog('-> serviceGenPathName: ' . $serviceGenPathName);
                        $this->writeLog('-> serviceVbsPathName: ' . $serviceVbsPathName);
                        Util::logTrace("Service paths don't match - service will be removed and reinstalled");
                    }
                } else {
                    Util::logTrace('Service not installed yet');
                }
                $this->splash->incrProgressBar();
                if ($serviceToRemove) {
                    Util::logTrace('Attempting to remove service: ' . $name);
                    if (!$service->delete()) {
                        Util::logTrace('Failed to remove service, restart required');
                        $serviceRestart = true;
                    } else {
                        Util::logTrace('Service removed successfully');
                    }
                }
                if (!$serviceRestart) {
                    Util::logTrace('Checking if port ' . $port . ' is in use');
                    $isPortInUse = Util::isPortInUse($port);
                    if ($isPortInUse === false) {
                        Util::logTrace('Port ' . $port . ' is available');
                        $this->splash->incrProgressBar();
                        if (!$serviceAlreadyInstalled || $serviceToRemove) {
                            Util::logTrace('Installing new service: ' . $name);
                            $this->splash->setTextLoading(sprintf($bearsamppLang->getValue(Lang::STARTUP_INSTALL_SERVICE_TEXT), $name));
                            if (!$service->create()) {
                                $serviceError .= sprintf($bearsamppLang->getValue(Lang::STARTUP_SERVICE_CREATE_ERROR), $service->getError());
                                Util::logTrace('Service creation failed: ' . $service->getError());
                            } else {
                                Util::logTrace('Service created successfully');
                            }
                        }
                        $this->splash->incrProgressBar();
                        $this->splash->setTextLoading(sprintf($bearsamppLang->getValue(Lang::STARTUP_START_SERVICE_TEXT), $name));
                        Util::logTrace('Starting service: ' . $name);
                        if (!$service->start()) {
                            if (!empty($serviceError)) {
                                $serviceError .= PHP_EOL;
                            }
                            $serviceError .= sprintf($bearsamppLang->getValue(Lang::STARTUP_SERVICE_START_ERROR), $service->getError());
                            Util::logTrace('Service start failed: ' . $service->getError());
                            if (!empty($syntaxCheckCmd)) {
                                Util::logTrace('Running syntax check command for ' . $name);
                                // Set a timeout for syntax check
                                $syntaxCheckStartTime = microtime(true);
                                $syntaxCheckTimeout = 5; // 5 seconds
                                try {
                                    $cmdSyntaxCheck = $bin->getCmdLineOutput($syntaxCheckCmd);
                                    // Check if we've exceeded our timeout
                                    if (microtime(true) - $syntaxCheckStartTime > $syntaxCheckTimeout) {
                                        Util::logTrace('Syntax check timeout exceeded, assuming syntax is OK');
                                        $cmdSyntaxCheck = ['syntaxOk' => true];
                                    }
                                    if (!$cmdSyntaxCheck['syntaxOk']) {
                                        $serviceError .= PHP_EOL . sprintf($bearsamppLang->getValue(Lang::STARTUP_SERVICE_SYNTAX_ERROR), $cmdSyntaxCheck['content']);
                                        Util::logTrace('Syntax check failed: ' . $cmdSyntaxCheck['content']);
                                    } else {
                                        Util::logTrace('Syntax check passed but service still failed to start');
                                    }
                                } catch (\Exception $e) {
                                    Util::logTrace('Exception during syntax check: ' . $e->getMessage());
                                    // Don't add error, just continue
                                } catch (\Throwable $e) {
                                    Util::logTrace('Throwable during syntax check: ' . $e->getMessage());
                                    // Don't add error, just continue
                                }
                            }
                        } else {
                            Util::logTrace('Service started successfully');
                        }
                        $this->splash->incrProgressBar();
                    } else {
                        Util::logTrace('Port ' . $port . ' is already in use by: ' . $isPortInUse);
                        if (!empty($serviceError)) {
                            $serviceError .= PHP_EOL;
                        }
                        $serviceError .= sprintf($bearsamppLang->getValue(Lang::STARTUP_SERVICE_PORT_ERROR), $port, $isPortInUse);
                        $this->splash->incrProgressBar(3);
                    }
                } else {
                    $this->writeLog('Need restart: installService ' . $bin->getName());
                    Util::logTrace('Restart required for service: ' . $bin->getName());
                    $this->restart = true;
                    $this->splash->incrProgressBar(3);
                }
                if (!empty($serviceError)) {
                    Util::logTrace('Service error occurred: ' . $serviceError);
                    if (!empty($this->error)) {
                        $this->error .= PHP_EOL . PHP_EOL;
                    }
                    $this->error .= sprintf($bearsamppLang->getValue(Lang::STARTUP_SERVICE_ERROR), $name) . PHP_EOL . $serviceError;
                } else {
                    $installTime = round(Util::getMicrotime() - $startServiceTime, 3);
                    $this->writeLog($name . ' service installed in ' . $installTime . 's');
                    Util::logTrace('Service ' . $name . ' installed successfully in ' . $installTime . ' seconds');
                }
            }
        } else {
            Util::logTrace('Restart mode - skipping service installation');
            $this->splash->incrProgressBar(self::GAUGE_SERVICES * count($bearsamppBins->getServices()));
        }
        Util::logTrace('Completed installServices method');
    }
References $bearsamppBins, $bearsamppLang, $bearsamppRoot, $port, checkApacheServiceWithTimeout(), checkMySQLServiceWithTimeout(), BinApache\CMD_SYNTAX_CHECK, BinMariadb\CMD_SYNTAX_CHECK, BinMysql\CMD_SYNTAX_CHECK, Util\getMicrotime(), Util\isPortInUse(), Win32Ps\killBins(), Util\logTrace(), BinApache\SERVICE_NAME, BinMailpit\SERVICE_NAME, BinMariadb\SERVICE_NAME, BinMemcached\SERVICE_NAME, BinMysql\SERVICE_NAME, BinPostgresql\SERVICE_NAME, BinXlight\SERVICE_NAME, Lang\STARTUP_CHECK_SERVICE_TEXT, Lang\STARTUP_INSTALL_SERVICE_TEXT, Lang\STARTUP_SERVICE_CREATE_ERROR, Lang\STARTUP_SERVICE_ERROR, Lang\STARTUP_SERVICE_PORT_ERROR, Lang\STARTUP_SERVICE_START_ERROR, Lang\STARTUP_SERVICE_SYNTAX_ERROR, Lang\STARTUP_START_SERVICE_TEXT, Win32Service\VBS_PATH_NAME, and writeLog().
Referenced by processWindow().
killOldInstances () [private]
Kills old instances of Bearsampp processes.
Definition at line 512 of file class.action.startup.php.
    {
        global $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_KILL_OLD_PROCS_TEXT ) );
        $this->splash->incrProgressBar();
        // Stop services
        /*foreach ($bearsamppBins->getServices() as $sName => $service) {
            $serviceInfos = $service->infos();
            if ($serviceInfos === false) {
                continue;
            }
            $service->stop();
        }*/
        // Stop third party procs
        $procsKilled = Win32Ps::killBins();
        if ( !empty( $procsKilled ) ) {
            $this->writeLog( 'Procs killed:' );
            $procsKilledSort = array();
            foreach ( $procsKilled as $proc ) {
                $unixExePath = Util::formatUnixPath( $proc[Win32Ps::EXECUTABLE_PATH] );
                $procsKilledSort[] = '-> ' . basename( $unixExePath ) . ' (PID ' . $proc[Win32Ps::PROCESS_ID] . ') in ' . $unixExePath;
            }
            sort( $procsKilledSort );
            foreach ( $procsKilledSort as $proc ) {
                $this->writeLog( $proc );
            }
        }
    }
References $bearsamppLang, $proc, Win32Ps\EXECUTABLE_PATH, Util\formatUnixPath(), Win32Ps\killBins(), Win32Ps\PROCESS_ID, Lang\STARTUP_KILL_OLD_PROCS_TEXT, and writeLog().
Referenced by processWindow().
processWindow ( $window, $id, $ctrl, $param1, $param2)
Processes the main window events during startup.
Parameters
$window The window handle.
$id The event ID.
$ctrl The control that triggered the event.
$param1 Additional parameter 1.
$param2 Additional parameter 2.
Definition at line 73 of file class.action.startup.php.
    {
        global $bearsamppRoot, $bearsamppCore, $bearsamppLang, $bearsamppBins, $bearsamppTools, $bearsamppApps, $bearsamppWinbinder;
        Util::logTrace('Starting processWindow method');
        // Rotation logs
        Util::logTrace('Performing log rotation');
        $this->rotationLogs();
        // Clean
        Util::logTrace('Starting cleanup operations');
        $this->cleanTmpFolders();
        $this->cleanOldBehaviors();
        // List procs
        Util::logTrace('Listing running processes');
        if ($bearsamppRoot->getProcs() !== false) {
            $this->writeLog('List procs:');
            $listProcs = array();
            foreach ($bearsamppRoot->getProcs() as $proc) {
                $unixExePath = Util::formatUnixPath($proc[Win32Ps::EXECUTABLE_PATH]);
                $listProcs[] = '-> ' . basename($unixExePath) . ' (PID ' . $proc[Win32Ps::PROCESS_ID] . ') in ' . $unixExePath;
            }
            sort($listProcs);
            foreach ($listProcs as $proc) {
                $this->writeLog($proc);
            }
            Util::logTrace('Found ' . count($listProcs) . ' running processes');
        } else {
            Util::logTrace('No processes found or unable to retrieve process list');
        }
        // List modules
        Util::logTrace('Listing bins modules');
        $this->writeLog('List bins modules:');
        foreach ($bearsamppBins->getAll() as $module) {
            if (!$module->isEnable()) {
                $this->writeLog('-> ' . $module->getName() . ': ' . $bearsamppLang->getValue(Lang::DISABLED));
                Util::logTrace('Bin module ' . $module->getName() . ' is disabled');
            } else {
                $this->writeLog('-> ' . $module->getName() . ': ' . $module->getVersion() . ' (' . $module->getRelease() . ')');
                Util::logTrace('Bin module ' . $module->getName() . ': ' . $module->getVersion() . ' (' . $module->getRelease() . ')');
            }
        }
        Util::logTrace('Listing tools modules');
        $this->writeLog('List tools modules:');
        foreach ($bearsamppTools->getAll() as $module) {
            if (!$module->isEnable()) {
                $this->writeLog('-> ' . $module->getName() . ': ' . $bearsamppLang->getValue(Lang::DISABLED));
                Util::logTrace('Tool module ' . $module->getName() . ' is disabled');
            } else {
                $this->writeLog('-> ' . $module->getName() . ': ' . $module->getVersion() . ' (' . $module->getRelease() . ')');
                Util::logTrace('Tool module ' . $module->getName() . ': ' . $module->getVersion() . ' (' . $module->getRelease() . ')');
            }
        }
        Util::logTrace('Listing apps modules');
        $this->writeLog('List apps modules:');
        foreach ($bearsamppApps->getAll() as $module) {
            if (!$module->isEnable()) {
                $this->writeLog('-> ' . $module->getName() . ': ' . $bearsamppLang->getValue(Lang::DISABLED));
                Util::logTrace('App module ' . $module->getName() . ' is disabled');
            } else {
                $this->writeLog('-> ' . $module->getName() . ': ' . $module->getVersion() . ' (' . $module->getRelease() . ')');
                Util::logTrace('App module ' . $module->getName() . ': ' . $module->getVersion() . ' (' . $module->getRelease() . ')');
            }
        }
        // Kill old instances
        Util::logTrace('Killing old instances');
        $this->killOldInstances();
        // Prepare app
        Util::logTrace('Preparing application - refreshing hostname');
        $this->refreshHostname();
        Util::logTrace('Checking launch startup settings');
        $this->checkLaunchStartup();
        Util::logTrace('Checking browser configuration');
        $this->checkBrowser();
        Util::logTrace('Gathering system information');
        $this->sysInfos();
        Util::logTrace('Refreshing aliases');
        $this->refreshAliases();
        Util::logTrace('Refreshing virtual hosts');
        $this->refreshVhosts();
        // Check app path
        Util::logTrace('Checking application path');
        $this->checkPath();
        Util::logTrace('Scanning folders');
        $this->scanFolders();
        Util::logTrace('Changing paths in files');
        $this->changePath();
        Util::logTrace('Saving current path');
        $this->savePath();
        // Check BEARSAMPP_PATH, BEARSAMPP_BINS and System Path reg keys
        Util::logTrace('Checking PATH registry key');
        $this->checkPathRegKey();
        Util::logTrace('Checking BINS registry key');
        $this->checkBinsRegKey();
        Util::logTrace('Checking System PATH registry key');
        $this->checkSystemPathRegKey();
        // Update config
        Util::logTrace('Updating configuration');
        $this->updateConfig();
        // Create SSL certificates
        Util::logTrace('Creating SSL certificates');
        $this->createSslCrts();
        // Install
        Util::logTrace('Installing services');
        $this->installServices();
        // Actions if everything OK
        if (!$this->restart && empty($this->error)) {
            Util::logTrace('Startup completed successfully - refreshing Git repositories');
            $this->refreshGitRepos();
            $startupTime = round(Util::getMicrotime() - $this->startTime, 3);
            $this->writeLog('Started in ' . $startupTime . 's');
            Util::logTrace('Application started successfully in ' . $startupTime . ' seconds');
        } else {
            Util::logTrace('Startup issues detected - incrementing progress bar');
            $this->splash->incrProgressBar(2);
        }
        if ($this->restart) {
            Util::logTrace('Restart required - preparing to restart application');
            $this->writeLog(APP_TITLE . ' has to be restarted');
            $this->splash->setTextLoading(
                sprintf(
                    $bearsamppLang->getValue(Lang::STARTUP_PREPARE_RESTART_TEXT),
                    APP_TITLE . ' ' . $bearsamppCore->getAppVersion()
                )
            );
            Util::logTrace('Deleting all services before restart');
            foreach ($bearsamppBins->getServices() as $sName => $service) {
                Util::logTrace('Deleting service: ' . $sName);
                $service->delete();
            }
            Util::logTrace('Setting execution action to RESTART');
            $bearsamppCore->setExec(ActionExec::RESTART);
        }
        if (!empty($this->error)) {
            Util::logTrace('Errors occurred during startup: ' . $this->error);
            $this->writeLog('Error: ' . $this->error);
            $bearsamppWinbinder->messageBoxError($this->error, $bearsamppLang->getValue(Lang::STARTUP_ERROR_TITLE));
        }
        Util::logTrace('Starting loading screen');
        Util::startLoading();
        Util::logTrace('Loading process completed');
        // Closing cli to finish startup
        Util::logTrace('Finishing startup process');
        $currentPid = Win32Ps::getCurrentPid();
        // Add timeout parameter (15 seconds) to prevent hanging
        ActionQuit::terminatePhpProcesses($currentPid, null, null, 15);
        // Safely reset WinBinder instead of trying to destroy specific windows
        $bearsamppWinbinder->reset();
        // Force exit if we're still running after termination attempt
        Util::logTrace('Forcing exit as final fallback');
        exit(0);
    }
References $bearsamppBins, $bearsamppCore, $bearsamppLang, $bearsamppRoot, $proc, APP_TITLE, changePath(), checkBinsRegKey(), checkBrowser(), checkLaunchStartup(), checkPath(), checkPathRegKey(), checkSystemPathRegKey(), cleanOldBehaviors(), cleanTmpFolders(), createSslCrts(), Lang\DISABLED, Win32Ps\EXECUTABLE_PATH, exit, Util\formatUnixPath(), Win32Ps\getCurrentPid(), Util\getMicrotime(), installServices(), killOldInstances(), Util\logTrace(), Win32Ps\PROCESS_ID, refreshAliases(), refreshGitRepos(), refreshHostname(), refreshVhosts(), ActionExec\RESTART, rotationLogs(), savePath(), scanFolders(), Util\startLoading(), Lang\STARTUP_ERROR_TITLE, Lang\STARTUP_PREPARE_RESTART_TEXT, sysInfos(), ActionQuit\terminatePhpProcesses(), updateConfig(), and writeLog().
refreshAliases () [private]
Refreshes the aliases in the Apache configuration.
Definition at line 609 of file class.action.startup.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppBins;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_REFRESH_ALIAS_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Refresh aliases' );
        $bearsamppBins->getApache()->refreshAlias( $bearsamppConfig->isOnline() );
    }
References $bearsamppBins, $bearsamppConfig, $bearsamppLang, Lang\STARTUP_REFRESH_ALIAS_TEXT, and writeLog().
Referenced by processWindow().
refreshGitRepos () [private]
Refreshes Git repositories if the scan on startup is enabled. Logs the number of repositories found.
Definition at line 1109 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppTools;
        $this->splash->incrProgressBar();
        if ( $bearsamppTools->getGit()->isScanStartup() ) {
            $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_REFRESH_GIT_REPOS_TEXT ) );
            $repos = $bearsamppTools->getGit()->findRepos( false );
            $this->writeLog( 'Update GIT repos: ' . count( $repos ) . ' found' );
        }
    }
References $bearsamppLang, Lang\STARTUP_REFRESH_GIT_REPOS_TEXT, and writeLog().
Referenced by processWindow().
refreshHostname () [private]
Refreshes the hostname in the configuration.
Definition at line 547 of file class.action.startup.php.
    {
        global $bearsamppConfig, $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_REFRESH_HOSTNAME_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Refresh hostname' );
        $bearsamppConfig->replace( Config::CFG_HOSTNAME, gethostname() );
    }
References $bearsamppConfig, $bearsamppLang, Config\CFG_HOSTNAME, Lang\STARTUP_REFRESH_HOSTNAME_TEXT, and writeLog().
Referenced by processWindow().
refreshVhosts () [private]
Refreshes the virtual hosts in the Apache configuration.
Definition at line 623 of file class.action.startup.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppBins;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_REFRESH_VHOSTS_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Refresh vhosts' );
        $bearsamppBins->getApache()->refreshVhosts( $bearsamppConfig->isOnline() );
    }
References $bearsamppBins, $bearsamppConfig, $bearsamppLang, Lang\STARTUP_REFRESH_VHOSTS_TEXT, and writeLog().
Referenced by processWindow().
rotationLogs () [private]
Rotates the logs by archiving old logs and purging old archives. Enhanced with file lock checking to prevent permission denied errors.
Definition at line 263 of file class.action.startup.php.
    {
        global $bearsamppRoot, $bearsamppCore, $bearsamppConfig, $bearsamppLang, $bearsamppBins;
        Util::logTrace("Starting log rotation process");
        $this->splash->setTextLoading($bearsamppLang->getValue(Lang::STARTUP_ROTATION_LOGS_TEXT));
        $this->splash->incrProgressBar();
        $archivesPath = $bearsamppRoot->getLogsPath() . '/archives';
        if (!is_dir($archivesPath)) {
            Util::logTrace("Creating archives directory: " . $archivesPath);
            mkdir($archivesPath, 0777, true);
            return;
        }
        $date = date('Y-m-d-His', time());
        $archiveLogsPath = $archivesPath . '/' . $date;
        $archiveScriptsPath = $archiveLogsPath . '/scripts';
        // Create archive folders
        Util::logTrace("Creating archive directories for current rotation");
        if (!is_dir($archiveLogsPath)) {
            Util::logTrace("Creating logs archive directory: " . $archiveLogsPath);
            mkdir($archiveLogsPath, 0777, true);
        } else {
            Util::logTrace("Logs archive directory already exists: " . $archiveLogsPath);
        }
        if (!is_dir($archiveScriptsPath)) {
            Util::logTrace("Creating scripts archive directory: " . $archiveScriptsPath);
            mkdir($archiveScriptsPath, 0777, true);
        } else {
            Util::logTrace("Scripts archive directory already exists: " . $archiveScriptsPath);
        }
        // Count archives
        Util::logTrace("Counting existing archives");
        $archives = array();
        $handle = @opendir($archivesPath);
        if (!$handle) {
            Util::logTrace("Failed to open archives directory: " . $archivesPath);
            return;
        }
        while (false !== ($file = readdir($handle))) {
            if ($file == '.' || $file == '..') {
                continue;
            }
            $archives[] = $archivesPath . '/' . $file;
        }
        closedir($handle);
        sort($archives);
        Util::logTrace("Found " . count($archives) . " existing archives");
        // Remove old archives
        if (count($archives) > $bearsamppConfig->getMaxLogsArchives()) {
            $total = count($archives) - $bearsamppConfig->getMaxLogsArchives();
            Util::logTrace("Removing " . $total . " old archives");
            for ($i = 0; $i < $total; $i++) {
                Util::logTrace("Deleting old archive: " . $archives[$i]);
                Util::deleteFolder($archives[$i]);
            }
        }
        // Helper function to check if a file is locked
        $isFileLocked = function($filePath) {
            if (!file_exists($filePath)) {
                return false;
            }
            $handle = @fopen($filePath, 'r+');
            if ($handle === false) {
                Util::logTrace("File appears to be locked: " . $filePath);
                return true; // File is locked
            }
            fclose($handle);
            return false; // File is not locked
        };
        // Logs
        Util::logTrace("Archiving log files");
        $srcPath = $bearsamppRoot->getLogsPath();
        $handle = @opendir($srcPath);
        if (!$handle) {
            Util::logTrace("Failed to open logs directory: " . $srcPath);
            return;
        }
        $logsCopied = 0;
        $logsSkipped = 0;
        while (false !== ($file = readdir($handle))) {
            if ($file == '.' || $file == '..' || is_dir($srcPath . '/' . $file)) {
                continue;
            }
            $sourceFile = $srcPath . '/' . $file;
            $destFile = $archiveLogsPath . '/' . $file;
            // Check if file is locked before attempting to copy
            if ($isFileLocked($sourceFile)) {
                Util::logTrace("Skipping locked log file: " . $file);
                $logsSkipped++;
                continue;
            }
            try {
                if (copy($sourceFile, $destFile)) {
                    $logsCopied++;
                    Util::logTrace("Archived log file: " . $file);
                } else {
                    $logsSkipped++;
                    Util::logTrace("Failed to copy log file: " . $file);
                }
            } catch (Exception $e) {
                $logsSkipped++;
                Util::logTrace("Exception copying log file " . $file . ": " . $e->getMessage());
            }
        }
        closedir($handle);
        Util::logTrace("Logs archived: " . $logsCopied . " copied, " . $logsSkipped . " skipped");
        // Scripts
        Util::logTrace("Archiving script files");
        $srcPath = $bearsamppCore->getTmpPath();
        $handle = @opendir($srcPath);
        if (!$handle) {
            Util::logTrace("Failed to open tmp directory: " . $srcPath);
            return;
        }
        $scriptsCopied = 0;
        $scriptsSkipped = 0;
        while (false !== ($file = readdir($handle))) {
            if ($file == '.' || $file == '..' || is_dir($srcPath . '/' . $file)) {
                continue;
            }
            $sourceFile = $srcPath . '/' . $file;
            $destFile = $archiveScriptsPath . '/' . $file;
            // Check if file is locked before attempting to copy
            if ($isFileLocked($sourceFile)) {
                Util::logTrace("Skipping locked script file: " . $file);
                $scriptsSkipped++;
                continue;
            }
            try {
                if (copy($sourceFile, $destFile)) {
                    $scriptsCopied++;
                    Util::logTrace("Archived script file: " . $file);
                } else {
                    $scriptsSkipped++;
                    Util::logTrace("Failed to copy script file: " . $file);
                }
            } catch (Exception $e) {
                $scriptsSkipped++;
                Util::logTrace("Exception copying script file " . $file . ": " . $e->getMessage());
            }
        }
        closedir($handle);
        Util::logTrace("Scripts archived: " . $scriptsCopied . " copied, " . $scriptsSkipped . " skipped");
        // Purge logs - only delete files that aren't locked
        Util::logTrace("Purging log files");
        $logsPath = $bearsamppRoot->getLogsPath();
        $handle = @opendir($logsPath);
        if (!$handle) {
            Util::logTrace("Failed to open logs directory for purging: " . $logsPath);
            return;
        }
        $logsDeleted = 0;
        $logsPurgeSkipped = 0;
        while (false !== ($file = readdir($handle))) {
            if ($file == '.' || $file == '..' || $file == 'archives' || $file == '.gitignore' || is_dir($logsPath . '/' . $file)) {
                continue;
            }
            $filePath = $logsPath . '/' . $file;
            // Check if file is locked before attempting to delete
            if ($isFileLocked($filePath)) {
                Util::logTrace("Skipping locked log file during purge: " . $file);
                $logsPurgeSkipped++;
                continue;
            }
            try {
                if (unlink($filePath)) {
                    $logsDeleted++;
                    Util::logTrace("Purged log file: " . $file);
                } else {
                    $logsPurgeSkipped++;
                    Util::logTrace("Failed to purge log file: " . $file);
                }
            } catch (Exception $e) {
                $logsPurgeSkipped++;
                Util::logTrace("Exception purging log file " . $file . ": " . $e->getMessage());
            }
        }
        closedir($handle);
        Util::logTrace("Logs purged: " . $logsDeleted . " deleted, " . $logsPurgeSkipped . " skipped");
        Util::logTrace("Log rotation completed");
    }
References $bearsamppBins, $bearsamppConfig, $bearsamppCore, $bearsamppLang, $bearsamppRoot, Util\deleteFolder(), Util\logTrace(), and Lang\STARTUP_ROTATION_LOGS_TEXT.
Referenced by processWindow().
savePath () [private]
Saves the current application path.
Definition at line 679 of file class.action.startup.php.
    {
        global $bearsamppCore;
        file_put_contents( $bearsamppCore->getLastPath(), $this->rootPath );
        $this->writeLog( 'Save current path: ' . $this->rootPath );
    }
References $bearsamppCore, and writeLog().
Referenced by processWindow().
scanFolders () [private]
Scans folders and logs the number of files to scan.
Definition at line 650 of file class.action.startup.php.
    {
        global $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_SCAN_FOLDERS_TEXT ) );
        $this->splash->incrProgressBar();
        $this->filesToScan = Util::getFilesToScan();
        $this->writeLog( 'Files to scan: ' . count( $this->filesToScan ) );
    }
References $bearsamppLang, Util\getFilesToScan(), Lang\STARTUP_SCAN_FOLDERS_TEXT, and writeLog().
Referenced by processWindow().
sysInfos () [private]
Logs system information.
Definition at line 595 of file class.action.startup.php.
    {
        global $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_SYS_INFOS ) );
        $this->splash->incrProgressBar();
        $os = Batch::getOsInfo();
        $this->writeLog( sprintf( 'OS: %s', $os ) );
    }
References $bearsamppLang, Batch\getOsInfo(), Lang\STARTUP_SYS_INFOS, and writeLog().
Referenced by processWindow().
updateConfig () [private]
Updates the configuration for bins, tools, and apps. Logs the update process.
Definition at line 795 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppBins, $bearsamppTools, $bearsamppApps;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_UPDATE_CONFIG_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Update config' );
        $bearsamppBins->update();
        $bearsamppTools->update();
        $bearsamppApps->update();
    }
References $bearsamppBins, $bearsamppLang, Lang\STARTUP_UPDATE_CONFIG_TEXT, and writeLog().
Referenced by processWindow().
writeLog ( $log) [private]
Writes a log message to the startup log file.
Parameters
$log The log message to write.
Definition at line 1223 of file class.action.startup.php.
    {
        global $bearsamppRoot;
        Util::logDebug( $log, $bearsamppRoot->getStartupLogFilePath() );
    }
References $bearsamppRoot, and Util\logDebug().
Referenced by __construct(), changePath(), checkBinsRegKey(), checkBrowser(), checkLaunchStartup(), checkPath(), checkPathRegKey(), checkSystemPathRegKey(), cleanOldBehaviors(), cleanTmpFolders(), installServices(), killOldInstances(), processWindow(), refreshAliases(), refreshGitRepos(), refreshHostname(), refreshVhosts(), savePath(), scanFolders(), sysInfos(), and updateConfig().
Field Documentation
$error [private]
Definition at line 21 of file class.action.startup.php.
$filesToScan [private]
Definition at line 24 of file class.action.startup.php.
$restart [private]
Definition at line 19 of file class.action.startup.php.
$rootPath [private]
Definition at line 23 of file class.action.startup.php.
$splash [private]
Definition at line 18 of file class.action.startup.php.
$startTime [private]
Definition at line 20 of file class.action.startup.php.
Referenced by checkApacheServiceWithTimeout().
const GAUGE_OTHERS = 19
Definition at line 27 of file class.action.startup.php.
const GAUGE_SERVICES = 5
Definition at line 26 of file class.action.startup.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.