.TH "ActionDebugApache" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionDebugApache
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBActionDebugApache\fP

.PP
This class handles the debugging of Apache configurations and settings\&. It retrieves various Apache debug information based on the provided arguments and displays the information in a message box or editor\&. 
.PP
Definition at line \fB17\fP of file \fBclass\&.action\&.debugApache\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $args)"
Constructor for \fBActionDebugApache\fP\&.

.PP
\fBParameters\fP
.RS 4
\fI$args\fP An array of arguments specifying the type of Apache debug information to retrieve\&. 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBclass\&.action\&.debugApache\&.php\fP\&.
.nf
25     {
26         global $bearsamppLang, $bearsamppBins, $bearsamppTools, $bearsamppWinbinder;
27 
28         if (isset($args[0]) && !empty($args[0])) {
29             $editor = false;
30             $msgBoxError = false;
31             $caption = $bearsamppLang\->getValue(Lang::DEBUG) \&. ' ' \&. $bearsamppLang\->getValue(Lang::APACHE) \&. ' \- ';
32 
33             // Determine the type of debug information requested and set the caption accordingly
34             if ($args[0] == BinApache::CMD_VERSION_NUMBER) {
35                 $caption \&.= $bearsamppLang\->getValue(Lang::DEBUG_APACHE_VERSION_NUMBER);
36             } elseif ($args[0] == BinApache::CMD_COMPILE_SETTINGS) {
37                 $caption \&.= $bearsamppLang\->getValue(Lang::DEBUG_APACHE_COMPILE_SETTINGS);
38             } elseif ($args[0] == BinApache::CMD_COMPILED_MODULES) {
39                 $caption \&.= $bearsamppLang\->getValue(Lang::DEBUG_APACHE_COMPILED_MODULES);
40             } elseif ($args[0] == BinApache::CMD_CONFIG_DIRECTIVES) {
41                 $editor = true;
42                 $caption \&.= $bearsamppLang\->getValue(Lang::DEBUG_APACHE_CONFIG_DIRECTIVES);
43             } elseif ($args[0] == BinApache::CMD_VHOSTS_SETTINGS) {
44                 $editor = true;
45                 $caption \&.= $bearsamppLang\->getValue(Lang::DEBUG_APACHE_VHOSTS_SETTINGS);
46             } elseif ($args[0] == BinApache::CMD_LOADED_MODULES) {
47                 $editor = true;
48                 $caption \&.= $bearsamppLang\->getValue(Lang::DEBUG_APACHE_LOADED_MODULES);
49             } elseif ($args[0] == BinApache::CMD_SYNTAX_CHECK) {
50                 $caption \&.= $bearsamppLang\->getValue(Lang::DEBUG_APACHE_SYNTAX_CHECK);
51             }
52             $caption \&.= ' (' \&. $args[0] \&. ')';
53 
54             // Retrieve the debug output from Apache
55             $debugOutput = $bearsamppBins\->getApache()\->getCmdLineOutput($args[0]);
56 
57             // Handle syntax check specifically
58             if ($args[0] == BinApache::CMD_SYNTAX_CHECK) {
59                 $msgBoxError = !$debugOutput['syntaxOk'];
60                 $debugOutput['content'] = $debugOutput['syntaxOk'] ? 'Syntax OK !' : $debugOutput['content'];
61             }
62 
63             // Display the debug output in an editor or message box
64             if ($editor) {
65                 Util::openFileContent($caption, $debugOutput['content']);
66             } else {
67                 if ($msgBoxError) {
68                     $bearsamppWinbinder\->messageBoxError(
69                         $debugOutput['content'],
70                         $caption
71                     );
72                 } else {
73                     $bearsamppWinbinder\->messageBoxInfo(
74                         $debugOutput['content'],
75                         $caption
76                     );
77                 }
78             }
79         }
80     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fBLang\\APACHE\fP, \fBBinApache\\CMD_COMPILE_SETTINGS\fP, \fBBinApache\\CMD_COMPILED_MODULES\fP, \fBBinApache\\CMD_CONFIG_DIRECTIVES\fP, \fBBinApache\\CMD_LOADED_MODULES\fP, \fBBinApache\\CMD_SYNTAX_CHECK\fP, \fBBinApache\\CMD_VERSION_NUMBER\fP, \fBBinApache\\CMD_VHOSTS_SETTINGS\fP, \fBLang\\DEBUG\fP, \fBLang\\DEBUG_APACHE_COMPILE_SETTINGS\fP, \fBLang\\DEBUG_APACHE_COMPILED_MODULES\fP, \fBLang\\DEBUG_APACHE_CONFIG_DIRECTIVES\fP, \fBLang\\DEBUG_APACHE_LOADED_MODULES\fP, \fBLang\\DEBUG_APACHE_SYNTAX_CHECK\fP, \fBLang\\DEBUG_APACHE_VERSION_NUMBER\fP, \fBLang\\DEBUG_APACHE_VHOSTS_SETTINGS\fP, and \fBUtil\\openFileContent()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
