.TH "ActionSwitchOnline" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionSwitchOnline
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($args)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBswitchAlias\fP ($putOnline)"
.br
.ti -1c
.RI "\fBswitchApache\fP ($putOnline)"
.br
.ti -1c
.RI "\fBswitchVhosts\fP ($putOnline)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBActionSwitchOnline\fP Handles the switching of the application between online and offline modes\&. 
.PP
Definition at line \fB14\fP of file \fBclass\&.action\&.switchOnline\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $args)"
\fBActionSwitchOnline\fP constructor\&. Initializes the online/offline switch based on the provided arguments\&.

.PP
\fBParameters\fP
.RS 4
\fI$args\fP Arguments to determine the online/offline state\&. 
.RE
.PP

.PP
Definition at line \fB22\fP of file \fBclass\&.action\&.switchOnline\&.php\fP\&.
.nf
23     {
24         global $bearsamppConfig;
25 
26         if (isset($args[0]) && $args[0] == Config::ENABLED || $args[0] == Config::DISABLED) {
27             Util::startLoading();
28             $putOnline = $args[0] == Config::ENABLED;
29 
30             $this\->switchApache($putOnline);
31             $this\->switchAlias($putOnline);
32             $this\->switchVhosts($putOnline);
33             $bearsamppConfig\->replace(Config::CFG_ONLINE, $args[0]);
34         }
35     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, \fBConfig\\CFG_ONLINE\fP, \fBConfig\\DISABLED\fP, \fBConfig\\ENABLED\fP, \fBUtil\\startLoading()\fP, \fBswitchAlias()\fP, \fBswitchApache()\fP, and \fBswitchVhosts()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "switchAlias ( $putOnline)\fR [private]\fP"
Switches the Apache aliases based on the online/offline state\&.

.PP
\fBParameters\fP
.RS 4
\fI$putOnline\fP True to put online, false to put offline\&. 
.RE
.PP

.PP
Definition at line \fB53\fP of file \fBclass\&.action\&.switchOnline\&.php\fP\&.
.nf
54     {
55         global $bearsamppBins;
56         $bearsamppBins\->getApache()\->refreshAlias($putOnline);
57     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP\&.
.PP
Referenced by \fB__construct()\fP\&.
.SS "switchApache ( $putOnline)\fR [private]\fP"
Switches the Apache configuration based on the online/offline state\&.

.PP
\fBParameters\fP
.RS 4
\fI$putOnline\fP True to put online, false to put offline\&. 
.RE
.PP

.PP
Definition at line \fB42\fP of file \fBclass\&.action\&.switchOnline\&.php\fP\&.
.nf
43     {
44         global $bearsamppBins;
45         $bearsamppBins\->getApache()\->refreshConf($putOnline);
46     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP\&.
.PP
Referenced by \fB__construct()\fP\&.
.SS "switchVhosts ( $putOnline)\fR [private]\fP"
Switches the Apache virtual hosts based on the online/offline state\&.

.PP
\fBParameters\fP
.RS 4
\fI$putOnline\fP True to put online, false to put offline\&. 
.RE
.PP

.PP
Definition at line \fB64\fP of file \fBclass\&.action\&.switchOnline\&.php\fP\&.
.nf
65     {
66         global $bearsamppBins;
67         $bearsamppBins\->getApache()\->refreshVhosts($putOnline);
68     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP\&.
.PP
Referenced by \fB__construct()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
