.TH "ActionSwitchPhpExtension" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionSwitchPhpExtension
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($args)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBSWITCH_OFF\fP = 'off'"
.br
.ti -1c
.RI "const \fBSWITCH_ON\fP = 'on'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBActionSwitchPhpExtension\fP

.PP
This class is responsible for enabling or disabling PHP extensions by modifying the php\&.ini configuration file\&. 
.PP
Definition at line \fB15\fP of file \fBclass\&.action\&.switchPhpExtension\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $args)"
\fBActionSwitchPhpExtension\fP constructor\&.

.PP
\fBParameters\fP
.RS 4
\fI$args\fP An array containing the extension name and the action (on/off)\&. 
.RE
.PP

.PP
Definition at line \fB25\fP of file \fBclass\&.action\&.switchPhpExtension\&.php\fP\&.
.nf
26     {
27         global $bearsamppBins;
28 
29         if (isset($args[0]) && !empty($args[0]) && isset($args[1]) && !empty($args[1])) {
30             $onContent  = 'extension=' \&. $args[0];
31             $offContent = ';extension=' \&. $args[0];
32 
33             $phpiniContent = file_get_contents($bearsamppBins\->getPhp()\->getConf());
34             if ($args[1] == self::SWITCH_ON) {
35                 $phpiniContent = str_replace($offContent, $onContent, $phpiniContent);
36             } elseif ($args[1] == self::SWITCH_OFF) {
37                 $phpiniContent = str_replace($onContent, $offContent, $phpiniContent);
38             }
39 
40             $phpiniContentOr = file_get_contents($bearsamppBins\->getPhp()\->getConf());
41             if ($phpiniContent == $phpiniContentOr && file_exists($bearsamppBins\->getPhp()\->getSymlinkPath() \&. '/ext/php_' \&. $args[0] \&. '\&.dll')) {
42                 $extsIni       = $bearsamppBins\->getPhp()\->getExtensionsFromConf();
43                 $latestExt     = (end($extsIni) == '0' ? ';' : '');
44                 $latestExt     \&.= 'extension=' \&. key($extsIni);
45                 $phpiniContent = str_replace(
46                     $latestExt,
47                     $latestExt \&. PHP_EOL \&. $onContent,
48                     $phpiniContent
49                 );
50             }
51 
52             file_put_contents($bearsamppBins\->getPhp()\->getConf(), $phpiniContent);
53         }
54     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP\&.
.SH "Field Documentation"
.PP 
.SS "const SWITCH_OFF = 'off'"

.PP
Definition at line \fB18\fP of file \fBclass\&.action\&.switchPhpExtension\&.php\fP\&.
.PP
Referenced by \fBTplAppPhp\\getActionSwitchPhpExtension()\fP, \fBBinPhp\\getExtensionsFromConf()\fP, and \fBBinPhp\\getExtensionsFromFolder()\fP\&.
.SS "const SWITCH_ON = 'on'"

.PP
Definition at line \fB17\fP of file \fBclass\&.action\&.switchPhpExtension\&.php\fP\&.
.PP
Referenced by \fBTplAppPhp\\getActionSwitchPhpExtension()\fP, \fBBinPhp\\getExtensionsFromConf()\fP, \fBBinPhp\\getExtensionsLoaded()\fP, and \fBTplAppPhp\\getMenuPhpExtensions()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
