ActionExec
NAME
ActionExec
SYNOPSIS
Public Member Functions
__construct ($args)
Data Fields
const QUIT = 'quit'
const RESTART = 'restart'
Detailed Description
Class ActionExec
This class handles the execution of specific actions based on the content of a file. The actions include quitting the application or reloading it. The actions are read from a file whose path is provided by the global $bearsamppCore object.
Definition at line 18 of file class.action.exec.php.
Constructor & Destructor Documentation
__construct ( $args)
ActionExec constructor.
This constructor reads the action from a file specified by $bearsamppCore->getExec(). If the action is 'quit', it calls Batch\exitApp(). If the action is 'restart', it calls Batch\restartApp(). After executing the action, it deletes the action file.
Parameters
$args Arguments passed to the constructor (not used in the current implementation).
Definition at line 39 of file class.action.exec.php.
    {
        global $bearsamppCore;
        Util::logTrace('ActionExec constructor called');
        $execFile = $bearsamppCore->getExec();
        Util::logTrace('Checking for exec file: ' . $execFile);
        if (file_exists($execFile)) {
            Util::logTrace('Exec file exists');
            $action = file_get_contents($execFile);
            Util::logTrace('Action read from exec file: "' . $action . '"');
            if ($action == self::QUIT) {
                Util::logTrace('Executing quit action');
                Batch::exitApp();
            } elseif ($action == self::RESTART) {
                Util::logTrace('Executing restart action');
                Batch::restartApp();
            } else {
                Util::logTrace('Unknown action: "' . $action . '"');
            }
            Util::logTrace('Deleting exec file');
            $unlinkResult = @unlink($execFile);
            Util::logTrace('Unlink result: ' . ($unlinkResult ? 'success' : 'failed'));
        } else {
            Util::logTrace('Exec file does not exist: ' . $execFile);
        }
    }
References $bearsamppCore, Batch\exitApp(), Util\logTrace(), and Batch\restartApp().
Field Documentation
const QUIT = 'quit'
Constant representing the 'quit' action.
Definition at line 23 of file class.action.exec.php.
const RESTART = 'restart'
Constant representing the 'reload' action.
Definition at line 28 of file class.action.exec.php.
Referenced by ActionManualRestart\__construct(), ActionStartup\processWindow(), and ActionSwitchVersion\processWindow().
Author
Generated automatically by Doxygen for Bearsampp from the source code.