.TH "ActionSwitchPhpParam" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionSwitchPhpParam
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($args)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBSWITCH_OFF\fP = 'off'"
.br
.ti -1c
.RI "const \fBSWITCH_ON\fP = 'on'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBActionSwitchPhpParam\fP

.PP
This class handles the switching of PHP parameters on and off\&. It modifies the PHP configuration file based on the provided arguments\&. 
.PP
Definition at line \fB16\fP of file \fBclass\&.action\&.switchPhpParam\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $args)"
Constructor for \fBActionSwitchPhpParam\fP\&.

.PP
\fBParameters\fP
.RS 4
\fI$args\fP An array containing the PHP setting name and the desired state ('on' or 'off')\&. 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBclass\&.action\&.switchPhpParam\&.php\fP\&.
.nf
27     {
28         global $bearsamppLang, $bearsamppBins, $bearsamppWinbinder;
29 
30         // Check if the required arguments are provided and not empty
31         if (isset($args[0]) && !empty($args[0]) && isset($args[1]) && !empty($args[1])) {
32             // Check if the PHP setting exists
33             if (!$bearsamppBins\->getPhp()\->isSettingExists($args[0])) {
34                 $bearsamppWinbinder\->messageBoxError(
35                     sprintf($bearsamppLang\->getValue(Lang::SWITCH_PHP_SETTING_NOT_FOUND), $args[0], $bearsamppBins\->getPhp()\->getVersion()),
36                     $bearsamppLang\->getValue(Lang::SWITCH_PHP_SETTING_TITLE)
37                 );
38                 return;
39             }
40 
41             // Retrieve the current settings values
42             $settingsValues = $bearsamppBins\->getPhp()\->getSettingsValues();
43             if (isset($settingsValues[$args[0]])) {
44                 $onContent = $args[0] \&. ' = ' \&. $settingsValues[$args[0]][0];
45                 $offContent = $args[0] \&. ' = ' \&. $settingsValues[$args[0]][1];
46 
47                 // Read the current PHP configuration file content
48                 $phpiniContent = file_get_contents($bearsamppBins\->getPhp()\->getConf());
49                 if ($args[1] == self::SWITCH_ON) {
50                     // Replace the off setting with the on setting
51                     $phpiniContent = str_replace($offContent, $onContent, $phpiniContent);
52                 } elseif ($args[1] == self::SWITCH_OFF) {
53                     // Replace the on setting with the off setting
54                     $phpiniContent = str_replace($onContent, $offContent, $phpiniContent);
55                 }
56 
57                 // Write the updated content back to the PHP configuration file
58                 file_put_contents($bearsamppBins\->getPhp()\->getConf(), $phpiniContent);
59             }
60         }
61     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fBLang\\SWITCH_PHP_SETTING_NOT_FOUND\fP, and \fBLang\\SWITCH_PHP_SETTING_TITLE\fP\&.
.SH "Field Documentation"
.PP 
.SS "const SWITCH_OFF = 'off'"

.PP
Definition at line \fB19\fP of file \fBclass\&.action\&.switchPhpParam\&.php\fP\&.
.PP
Referenced by \fBTplAppPhp\\getActionSwitchPhpSetting()\fP\&.
.SS "const SWITCH_ON = 'on'"

.PP
Definition at line \fB18\fP of file \fBclass\&.action\&.switchPhpParam\&.php\fP\&.
.PP
Referenced by \fBTplAppPhp\\getActionSwitchPhpSetting()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
