.TH "ActionSwitchLogsVerbose" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionSwitchLogsVerbose
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBActionSwitchLogsVerbose\fP

.PP
This class handles the action of switching the verbosity level of logs\&. 
.PP
Definition at line \fB15\fP of file \fBclass\&.action\&.switchLogsVerbose\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $args)"
\fBActionSwitchLogsVerbose\fP constructor\&.

.PP
\fBParameters\fP
.RS 4
\fI$args\fP An array of arguments where the first element should be the verbosity level (0-3)\&. 
.RE
.PP

.PP
Definition at line \fB22\fP of file \fBclass\&.action\&.switchLogsVerbose\&.php\fP\&.
.nf
23     {
24         global $bearsamppConfig;
25 
26         // Check if the first argument is set, is numeric, and within the valid range (0\-3)
27         if (isset($args[0]) && is_numeric($args[0]) && $args[0] >= 0 && $args[0] <= 3) {
28             // Replace the current verbosity level in the configuration
29             $bearsamppConfig\->replace(Config::CFG_LOGS_VERBOSE, $args[0]);
30         }
31     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, and \fBConfig\\CFG_LOGS_VERBOSE\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
