.TH "ActionDebugPostgresql" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionDebugPostgresql
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBActionDebugPostgresql\fP

.PP
This class handles the debugging actions for PostgreSQL within the \fBBearsampp\fP application\&. It retrieves and displays PostgreSQL command line output based on the provided arguments\&. 
.PP
Definition at line \fB16\fP of file \fBclass\&.action\&.debugPostgresql\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $args)"
Constructor for \fBActionDebugPostgresql\fP\&.

.PP
\fBParameters\fP
.RS 4
\fI$args\fP An array of arguments where the first element is expected to be a PostgreSQL command\&.
.RE
.PP
This constructor initializes the debugging process for PostgreSQL\&. It checks the provided arguments, retrieves the command line output for the specified PostgreSQL command, and displays it in a message box\&.

.PP
Global variables used:
.IP "\(bu" 2
$bearsamppLang: Provides language-specific strings\&.
.IP "\(bu" 2
$bearsamppBins: Provides access to \fBBearsampp\fP binaries, including PostgreSQL\&.
.IP "\(bu" 2
$bearsamppWinbinder: Handles the display of message boxes\&. 
.PP

.PP
Definition at line \fB31\fP of file \fBclass\&.action\&.debugPostgresql\&.php\fP\&.
.nf
32     {
33         global $bearsamppLang, $bearsamppBins, $bearsamppTools, $bearsamppWinbinder;
34 
35         if (isset($args[0]) && !empty($args[0])) {
36             $editor = false;
37             $msgBoxError = false;
38             $caption = $bearsamppLang\->getValue(Lang::DEBUG) \&. ' ' \&. $bearsamppLang\->getValue(Lang::POSTGRESQL) \&. ' \- ';
39             if ($args[0] == BinPostgresql::CMD_VERSION) {
40                 $caption \&.= $bearsamppLang\->getValue(Lang::DEBUG_POSTGRESQL_VERSION);
41             }
42             $caption \&.= ' (' \&. $args[0] \&. ')';
43 
44             $debugOutput = $bearsamppBins\->getPostgresql()\->getCmdLineOutput($args[0]);
45 
46             if ($editor) {
47                 Util::openFileContent($caption, $debugOutput);
48             } else {
49                 if ($msgBoxError) {
50                     $bearsamppWinbinder\->messageBoxError(
51                         $debugOutput,
52                         $caption
53                     );
54                 } else {
55                     $bearsamppWinbinder\->messageBoxInfo(
56                         $debugOutput,
57                         $caption
58                     );
59                 }
60             }
61         }
62     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fBBinPostgresql\\CMD_VERSION\fP, \fBLang\\DEBUG\fP, \fBLang\\DEBUG_POSTGRESQL_VERSION\fP, \fBUtil\\openFileContent()\fP, and \fBLang\\POSTGRESQL\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
