ActionAbout
NAME
ActionAbout
SYNOPSIS
Public Member Functions
__construct ($args)
processWindow ($window, $id, $ctrl, $param1, $param2)
Data Fields
const GAUGE_SAVE = 2
Private Attributes
$wbBtnOk
$wbImage
$wbLinkDonate
$wbLinkGithub
$wbLinkHomepage
$wbWindow
Detailed Description
Class ActionAbout Handles the creation and management of the "About" window in the Bearsampp application.
Definition at line 15 of file class.action.about.php.
Constructor & Destructor Documentation
__construct ( $args)
ActionAbout constructor. Initializes the "About" window and its components.
Parameters
$args Arguments passed to the constructor.
Definition at line 31 of file class.action.about.php.
    {
        global $bearsamppCore, $bearsamppLang, $bearsamppWinbinder;
        $bearsamppWinbinder->reset();
        $this->wbWindow = $bearsamppWinbinder->createAppWindow($bearsamppLang->getValue(Lang::ABOUT_TITLE), 520, 250, WBC_NOTIFY, WBC_KEYDOWN | WBC_KEYUP);
        // Get the about text
        $aboutText = sprintf($bearsamppLang->getValue(Lang::ABOUT_TEXT), APP_TITLE . ' ' . $bearsamppCore->getAppVersion(), date('Y'), APP_AUTHOR_NAME);
        // Split the text using the custom newline marker "@nl@"
        $textLines = explode('@nl@', $aboutText);
        // Display each line at a specific position
        $yPos = 20;
        $lineHeight = 20;
        foreach ($textLines as $line) {
            $bearsamppWinbinder->createLabel($this->wbWindow, trim($line), 80, $yPos, 470, $lineHeight);
            $yPos += $lineHeight;
        }
        // Add exactly one line of blank space
        $yPos = 125;
        // Add hyperlinks
        $bearsamppWinbinder->createLabel($this->wbWindow, $bearsamppLang->getValue(Lang::WEBSITE) . ' :', 80, $yPos, 100, 15);
        $this->wbLinkHomepage = $bearsamppWinbinder->createHyperLink($this->wbWindow, Util::getWebsiteUrlNoUtm(), 180, $yPos, 300, 15, WBC_LINES);
        $yPos += 20;
        $bearsamppWinbinder->createLabel($this->wbWindow, $bearsamppLang->getValue(Lang::DONATE) . ' :', 80, $yPos, 100, 15);
        $this->wbLinkDonate = $bearsamppWinbinder->createHyperLink($this->wbWindow, Util::getWebsiteUrlNoUtm('donate'), 180, $yPos, 300, 15, WBC_LINES);
        $yPos += 20;
        $bearsamppWinbinder->createLabel($this->wbWindow, $bearsamppLang->getValue(Lang::GITHUB) . ' :', 80, $yPos, 100, 15);
        $this->wbLinkGithub = $bearsamppWinbinder->createHyperLink($this->wbWindow, Util::getGithubUserUrl(), 180, $yPos, 300, 15, WBC_LINES);
        $yPos += 10;
        $this->wbBtnOk = $bearsamppWinbinder->createButton($this->wbWindow, $bearsamppLang->getValue(Lang::BUTTON_OK), 390, 180);
        $this->wbImage = $bearsamppWinbinder->drawImage($this->wbWindow, $bearsamppCore->getImagesPath() . '/about.bmp');
        $bearsamppWinbinder->setHandler($this->wbWindow, $this, 'processWindow');
        $bearsamppWinbinder->mainLoop();
        $bearsamppWinbinder->reset();
    }
References $bearsamppCore, $bearsamppLang, Lang\ABOUT_TEXT, Lang\ABOUT_TITLE, APP_AUTHOR_NAME, APP_TITLE, Lang\BUTTON_OK, Lang\DONATE, Util\getGithubUserUrl(), Util\getWebsiteUrlNoUtm(), Lang\GITHUB, and Lang\WEBSITE.
Member Function Documentation
processWindow ( $window, $id, $ctrl, $param1, $param2)
Processes window events and handles user interactions.
Parameters
$window The window identifier.
$id The control identifier.
$ctrl The control object.
$param1 Additional parameter 1.
$param2 Additional parameter 2.
Definition at line 86 of file class.action.about.php.
    {
        global $bearsamppConfig, $bearsamppWinbinder;
        switch ($id) {
            case $this->wbLinkHomepage[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->exec($bearsamppConfig->getBrowser(), Util::getWebsiteUrl());
                break;
            case $this->wbLinkDonate[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->exec($bearsamppConfig->getBrowser(), Util::getWebsiteUrl('donate'));
                break;
            case $this->wbLinkGithub[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->exec($bearsamppConfig->getBrowser(), Util::getGithubUserUrl());
                break;
            case IDCLOSE:
            case $this->wbBtnOk[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->destroyWindow($window);
                break;
        }
    }
References $bearsamppConfig, WinBinder\CTRL_ID, Util\getGithubUserUrl(), and Util\getWebsiteUrl().
Field Documentation
$wbBtnOk [private]
Definition at line 23 of file class.action.about.php.
$wbImage [private]
Definition at line 19 of file class.action.about.php.
$wbLinkDonate [private]
Definition at line 21 of file class.action.about.php.
$wbLinkGithub [private]
Definition at line 22 of file class.action.about.php.
$wbLinkHomepage [private]
Definition at line 20 of file class.action.about.php.
$wbWindow [private]
Definition at line 18 of file class.action.about.php.
const GAUGE_SAVE = 2
Definition at line 17 of file class.action.about.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.