.TH "ActionGenSslCertificate" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionGenSslCertificate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($args)"
.br
.ti -1c
.RI "\fBprocessWindow\fP ($window, $id, $ctrl, $param1, $param2)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBGAUGE_SAVE\fP = 2"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$wbBtnCancel\fP"
.br
.ti -1c
.RI "\fB$wbBtnDest\fP"
.br
.ti -1c
.RI "\fB$wbBtnSave\fP"
.br
.ti -1c
.RI "\fB$wbInputDest\fP"
.br
.ti -1c
.RI "\fB$wbInputName\fP"
.br
.ti -1c
.RI "\fB$wbLabelDest\fP"
.br
.ti -1c
.RI "\fB$wbLabelName\fP"
.br
.ti -1c
.RI "\fB$wbProgressBar\fP"
.br
.ti -1c
.RI "\fB$wbWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBActionGenSslCertificate\fP

.PP
This class handles the generation of SSL certificates through a \fBWinBinder\fP GUI\&. It provides a user interface for inputting the server name and target directory, and includes functionality for browsing directories, saving the certificate, and displaying progress\&. 
.PP
Definition at line \fB17\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $args)"
Constructor for \fBActionGenSslCertificate\fP\&.

.PP
Initializes the \fBWinBinder\fP window and its controls, sets up event handlers, and starts the main loop\&.

.PP
\fBParameters\fP
.RS 4
\fI$args\fP Command line arguments passed to the script\&. 
.RE
.PP

.PP
Definition at line \fB38\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.nf
39     {
40         global $bearsamppRoot, $bearsamppLang, $bearsamppWinbinder;
41 
42         $initServerName = 'test\&.local';
43         $initDocumentRoot = Util::formatWindowsPath($bearsamppRoot\->getSslPath());
44 
45         $bearsamppWinbinder\->reset();
46         $this\->wbWindow = $bearsamppWinbinder\->createAppWindow($bearsamppLang\->getValue(Lang::GENSSL_TITLE), 490, 160, WBC_NOTIFY, WBC_KEYDOWN | WBC_KEYUP);
47 
48         $this\->wbLabelName = $bearsamppWinbinder\->createLabel($this\->wbWindow, $bearsamppLang\->getValue(Lang::NAME) \&. ' :', 15, 15, 85, null, WBC_RIGHT);
49         $this\->wbInputName = $bearsamppWinbinder\->createInputText($this\->wbWindow, $initServerName, 105, 13, 150, null);
50 
51         $this\->wbLabelDest = $bearsamppWinbinder\->createLabel($this\->wbWindow, $bearsamppLang\->getValue(Lang::TARGET) \&. ' :', 15, 45, 85, null, WBC_RIGHT);
52         $this\->wbInputDest = $bearsamppWinbinder\->createInputText($this\->wbWindow, $initDocumentRoot, 105, 43, 190, null, null, WBC_READONLY);
53         $this\->wbBtnDest = $bearsamppWinbinder\->createButton($this\->wbWindow, $bearsamppLang\->getValue(Lang::BUTTON_BROWSE), 300, 43, 110);
54 
55         $this\->wbProgressBar = $bearsamppWinbinder\->createProgressBar($this\->wbWindow, self::GAUGE_SAVE + 1, 15, 97, 275);
56         $this\->wbBtnSave = $bearsamppWinbinder\->createButton($this\->wbWindow, $bearsamppLang\->getValue(Lang::BUTTON_SAVE), 300, 92);
57         $this\->wbBtnCancel = $bearsamppWinbinder\->createButton($this\->wbWindow, $bearsamppLang\->getValue(Lang::BUTTON_CANCEL), 387, 92);
58 
59         $bearsamppWinbinder\->setHandler($this\->wbWindow, $this, 'processWindow');
60         $bearsamppWinbinder\->mainLoop();
61         $bearsamppWinbinder\->reset();
62     }
.PP
.fi

.PP
References \fB$bearsamppLang\fP, \fB$bearsamppRoot\fP, \fBLang\\BUTTON_BROWSE\fP, \fBLang\\BUTTON_CANCEL\fP, \fBLang\\BUTTON_SAVE\fP, \fBUtil\\formatWindowsPath()\fP, \fBLang\\GENSSL_TITLE\fP, \fBLang\\NAME\fP, and \fBLang\\TARGET\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "processWindow ( $window,  $id,  $ctrl,  $param1,  $param2)"
Processes window events\&.

.PP
Handles button clicks and other window events, such as browsing for a directory, saving the SSL certificate, and closing the window\&.

.PP
\fBParameters\fP
.RS 4
\fI$window\fP The window resource\&. 
.br
\fI$id\fP The control ID that triggered the event\&. 
.br
\fI$ctrl\fP The control resource that triggered the event\&. 
.br
\fI$param1\fP Additional parameter 1\&. 
.br
\fI$param2\fP Additional parameter 2\&. 
.RE
.PP

.PP
Definition at line \fB76\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.nf
77     {
78         global $bearsamppLang, $bearsamppOpenSsl, $bearsamppWinbinder;
79 
80         $name = $bearsamppWinbinder\->getText($this\->wbInputName[WinBinder::CTRL_OBJ]);
81         $target = $bearsamppWinbinder\->getText($this\->wbInputDest[WinBinder::CTRL_OBJ]);
82 
83         switch ($id) {
84             case $this\->wbBtnDest[WinBinder::CTRL_ID]:
85                 $target = $bearsamppWinbinder\->sysDlgPath($window, $bearsamppLang\->getValue(Lang::GENSSL_PATH), $target);
86                 if ($target && is_dir($target)) {
87                     $bearsamppWinbinder\->setText($this\->wbInputDest[WinBinder::CTRL_OBJ], $target \&. '\\\\');
88                 }
89                 break;
90             case $this\->wbBtnSave[WinBinder::CTRL_ID]:
91                 $bearsamppWinbinder\->setProgressBarMax($this\->wbProgressBar, self::GAUGE_SAVE + 1);
92                 $bearsamppWinbinder\->incrProgressBar($this\->wbProgressBar);
93 
94                 $target = Util::formatUnixPath($target);
95                 if ($bearsamppOpenSsl\->createCrt($name, $target)) {
96                     $bearsamppWinbinder\->incrProgressBar($this\->wbProgressBar);
97                     $bearsamppWinbinder\->messageBoxInfo(
98                             sprintf($bearsamppLang\->getValue(Lang::GENSSL_CREATED), $name),
99                             $bearsamppLang\->getValue(Lang::GENSSL_TITLE));
100                     $bearsamppWinbinder\->destroyWindow($window);
101                 } else {
102                     $bearsamppWinbinder\->messageBoxError($bearsamppLang\->getValue(Lang::GENSSL_CREATED_ERROR), $bearsamppLang\->getValue(Lang::GENSSL_TITLE));
103                     $bearsamppWinbinder\->resetProgressBar($this\->wbProgressBar);
104                 }
105                 break;
106             case IDCLOSE:
107             case $this\->wbBtnCancel[WinBinder::CTRL_ID]:
108                 $bearsamppWinbinder\->destroyWindow($window);
109                 break;
110         }
111     }
.PP
.fi

.PP
References \fB$bearsamppLang\fP, \fBWinBinder\\CTRL_ID\fP, \fBWinBinder\\CTRL_OBJ\fP, \fBUtil\\formatUnixPath()\fP, \fBLang\\GENSSL_CREATED\fP, \fBLang\\GENSSL_CREATED_ERROR\fP, \fBLang\\GENSSL_PATH\fP, and \fBLang\\GENSSL_TITLE\fP\&.
.SH "Field Documentation"
.PP 
.SS "$wbBtnCancel\fR [private]\fP"

.PP
Definition at line \fB27\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.SS "$wbBtnDest\fR [private]\fP"

.PP
Definition at line \fB24\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.SS "$wbBtnSave\fR [private]\fP"

.PP
Definition at line \fB26\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.SS "$wbInputDest\fR [private]\fP"

.PP
Definition at line \fB23\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.SS "$wbInputName\fR [private]\fP"

.PP
Definition at line \fB21\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.SS "$wbLabelDest\fR [private]\fP"

.PP
Definition at line \fB22\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.SS "$wbLabelName\fR [private]\fP"

.PP
Definition at line \fB20\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.SS "$wbProgressBar\fR [private]\fP"

.PP
Definition at line \fB25\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.SS "$wbWindow\fR [private]\fP"

.PP
Definition at line \fB19\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.
.SS "const GAUGE_SAVE = 2"

.PP
Definition at line \fB29\fP of file \fBclass\&.action\&.genSslCertificate\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
