ActionSwitchOnline
NAME
ActionSwitchOnline
SYNOPSIS
Public Member Functions
__construct ($args)
Private Member Functions
switchAlias ($putOnline)
switchApache ($putOnline)
switchVhosts ($putOnline)
Detailed Description
Class ActionSwitchOnline Handles the switching of the application between online and offline modes.
Definition at line 14 of file class.action.switchOnline.php.
Constructor & Destructor Documentation
__construct ( $args)
ActionSwitchOnline constructor. Initializes the online/offline switch based on the provided arguments.
Parameters
$args Arguments to determine the online/offline state.
Definition at line 22 of file class.action.switchOnline.php.
    {
        global $bearsamppConfig;
        if (isset($args[0]) && $args[0] == Config::ENABLED || $args[0] == Config::DISABLED) {
            Util::startLoading();
            $putOnline = $args[0] == Config::ENABLED;
            $this->switchApache($putOnline);
            $this->switchAlias($putOnline);
            $this->switchVhosts($putOnline);
            $bearsamppConfig->replace(Config::CFG_ONLINE, $args[0]);
        }
    }
References $bearsamppConfig, Config\CFG_ONLINE, Config\DISABLED, Config\ENABLED, Util\startLoading(), switchAlias(), switchApache(), and switchVhosts().
Member Function Documentation
switchAlias ( $putOnline) [private]
Switches the Apache aliases based on the online/offline state.
Parameters
$putOnline True to put online, false to put offline.
Definition at line 53 of file class.action.switchOnline.php.
    {
        global $bearsamppBins;
        $bearsamppBins->getApache()->refreshAlias($putOnline);
    }
References $bearsamppBins.
Referenced by __construct().
switchApache ( $putOnline) [private]
Switches the Apache configuration based on the online/offline state.
Parameters
$putOnline True to put online, false to put offline.
Definition at line 42 of file class.action.switchOnline.php.
    {
        global $bearsamppBins;
        $bearsamppBins->getApache()->refreshConf($putOnline);
    }
References $bearsamppBins.
Referenced by __construct().
switchVhosts ( $putOnline) [private]
Switches the Apache virtual hosts based on the online/offline state.
Parameters
$putOnline True to put online, false to put offline.
Definition at line 64 of file class.action.switchOnline.php.
    {
        global $bearsamppBins;
        $bearsamppBins->getApache()->refreshVhosts($putOnline);
    }
References $bearsamppBins.
Referenced by __construct().
Author
Generated automatically by Doxygen for Bearsampp from the source code.