ActionManualRestart
NAME
ActionManualRestart
SYNOPSIS
Public Member Functions
__construct ($args)
Detailed Description
Class ActionManualRestart
This class handles the manual restart of services in the Bearsampp application. It stops all running services, kills all related processes, and sets the application to restart.
Definition at line 18 of file class.action.manualRestart.php.
Constructor & Destructor Documentation
__construct ( $args)
ActionManualRestart constructor.
Parameters
$args Arguments passed to the constructor.
This constructor initializes the manual restart process by performing the following steps:
1.
Starts the loading process.
2.
Deletes all services managed by Bearsampp.
3.
Kills all related processes.
4.
Sets the application to restart.
5.
Stops the loading process.
Definition at line 32 of file class.action.manualRestart.php.
    {
        global $bearsamppCore, $bearsamppBins;
        Util::logTrace("Starting ActionManualRestart constructor");
        // Start the loading process
        Util::logTrace("Starting loading process");
        Util::startLoading();
        // Delete all services managed by Bearsampp
        Util::logTrace("Deleting all services managed by Bearsampp");
        foreach ($bearsamppBins->getServices() as $sName => $service) {
            Util::logTrace("Deleting service: " . $sName);
            $service->delete();
        }
        // Kill all related processes
        Util::logTrace("Killing all related processes");
        Win32Ps::killBins(true);
        // Set the application to restart
        Util::logTrace("Setting application to restart");
        $bearsamppCore->setExec(ActionExec::RESTART);
        // Stop the loading process
        Util::logTrace("Stopping loading process");
        Util::stopLoading();
    }
References $bearsamppBins, $bearsamppCore, Win32Ps\killBins(), Util\logTrace(), ActionExec\RESTART, Util\startLoading(), and Util\stopLoading().
Author
Generated automatically by Doxygen for Bearsampp from the source code.