ActionSwitchVersion
NAME
ActionSwitchVersion
SYNOPSIS
Public Member Functions
__construct ($args)
processWindow ($window, $id, $ctrl, $param1, $param2)
Data Fields
const CONFIG_KEY_VERSION = 'version'
const CONFIG_SECTION_APACHE = 'apache'
const CONFIG_SECTION_MAILPIT = 'mailpit'
const CONFIG_SECTION_MARIADB = 'mariadb'
const CONFIG_SECTION_MEMCACHED = 'memcached'
const CONFIG_SECTION_MYSQL = 'mysql'
const CONFIG_SECTION_NODEJS = 'nodejs'
const CONFIG_SECTION_PHP = 'php'
const CONFIG_SECTION_POSTGRESQL = 'postgresql'
const CONFIG_SECTION_XLIGHT = 'xlight'
const GAUGE_OTHERS = 7
const GAUGE_SERVICES = 1
Private Member Functions
updateConfigVersion ()
Private Attributes
$bearsamppSplash
$bin
$boxTitle
$changePort
$currentVersion
$pathsToScan = []
$service
$version
Detailed Description
Class ActionSwitchVersion Handles the switching of versions for various services and binaries in the Bearsampp application.
Definition at line 15 of file class.action.switchVersion.php.
Constructor & Destructor Documentation
__construct ( $args)
ActionSwitchVersion constructor. Initializes the class with the provided arguments and sets up the splash screen.
Parameters
$args Command line arguments for switching versions.
Definition at line 49 of file class.action.switchVersion.php.
    {
        global $bearsamppLang, $bearsamppBins, $bearsamppWinbinder;
        if (isset($args[0]) && !empty($args[0]) && isset($args[1]) && !empty($args[1])) {
            $this->pathsToScan = array();
            $this->version = $args[1];
            if ($args[0] == $bearsamppBins->getApache()->getName()) {
                $this->bin = $bearsamppBins->getApache();
                $this->currentVersion = $bearsamppBins->getApache()->getVersion();
                $this->service = $bearsamppBins->getApache()->getService();
                $this->changePort = true;
                $folderList = Util::getFolderList($bearsamppBins->getApache()->getRootPath());
                foreach ($folderList as $folder) {
                    $this->pathsToScan[] = array(
                        'path' => $bearsamppBins->getApache()->getRootPath() . '/' . $folder,
                        'includes' => array('.ini', '.conf'),
                        'recursive' => true
                    );
                }
            } elseif ($args[0] == $bearsamppBins->getPhp()->getName()) {
                $this->bin = $bearsamppBins->getPhp();
                $this->currentVersion = $bearsamppBins->getPhp()->getVersion();
                $this->service = $bearsamppBins->getApache()->getService();
                $this->changePort = false;
                $folderList = Util::getFolderList($bearsamppBins->getPhp()->getRootPath());
                foreach ($folderList as $folder) {
                    $this->pathsToScan[] = array(
                        'path' => $bearsamppBins->getPhp()->getRootPath() . '/' . $folder,
                        'includes' => array('.php', '.bat', '.ini', '.reg', '.inc'),
                        'recursive' => true
                    );
                }
            } elseif ($args[0] == $bearsamppBins->getMysql()->getName()) {
                $this->bin = $bearsamppBins->getMysql();
                $this->currentVersion = $bearsamppBins->getMysql()->getVersion();
                $this->service = $bearsamppBins->getMysql()->getService();
                $this->changePort = true;
                $folderList = Util::getFolderList($bearsamppBins->getMysql()->getRootPath());
                foreach ($folderList as $folder) {
                    $this->pathsToScan[] = array(
                        'path' => $bearsamppBins->getMysql()->getRootPath() . '/' . $folder,
                        'includes' => array('my.ini'),
                        'recursive' => false
                    );
                }
            } elseif ($args[0] == $bearsamppBins->getMariadb()->getName()) {
                $this->bin = $bearsamppBins->getMariadb();
                $this->currentVersion = $bearsamppBins->getMariadb()->getVersion();
                $this->service = $bearsamppBins->getMariadb()->getService();
                $this->changePort = true;
                $folderList = Util::getFolderList($bearsamppBins->getMariadb()->getRootPath());
                foreach ($folderList as $folder) {
                    $this->pathsToScan[] = array(
                        'path' => $bearsamppBins->getMariadb()->getRootPath() . '/' . $folder,
                        'includes' => array('my.ini'),
                        'recursive' => false
                    );
                }
            } elseif ($args[0] == $bearsamppBins->getPostgresql()->getName()) {
                $this->bin = $bearsamppBins->getPostgresql();
                $this->currentVersion = $bearsamppBins->getPostgresql()->getVersion();
                $this->service = $bearsamppBins->getPostgresql()->getService();
                $this->changePort = true;
                $folderList = Util::getFolderList($bearsamppBins->getPostgresql()->getRootPath());
                foreach ($folderList as $folder) {
                    $this->pathsToScan[] = array(
                        'path' => $bearsamppBins->getPostgresql()->getRootPath() . '/' . $folder,
                        'includes' => array('.ber', '.conf', '.bat'),
                        'recursive' => true
                    );
                }
            } elseif ($args[0] == $bearsamppBins->getNodejs()->getName()) {
                $this->bin = $bearsamppBins->getNodejs();
                $this->currentVersion = $bearsamppBins->getNodejs()->getVersion();
                $this->service = null;
                $this->changePort = false;
                $folderList = Util::getFolderList($bearsamppBins->getNodejs()->getRootPath());
                foreach ($folderList as $folder) {
                    $this->pathsToScan[] = array(
                        'path' => $bearsamppBins->getNodejs()->getRootPath() . '/' . $folder . '/etc',
                        'includes' => array('npmrc'),
                        'recursive' => true
                    );
                    $this->pathsToScan[] = array(
                        'path' => $bearsamppBins->getNodejs()->getRootPath() . '/' . $folder . '/node_modules/npm',
                        'includes' => array('npmrc'),
                        'recursive' => false
                    );
                }
            } elseif ($args[0] == $bearsamppBins->getMemcached()->getName()) {
                $this->bin = $bearsamppBins->getMemcached();
                $this->currentVersion = $bearsamppBins->getMemcached()->getVersion();
                $this->service = $bearsamppBins->getMemcached()->getService();
                $this->changePort = true;
            } elseif ($args[0] == $bearsamppBins->getMailpit()->getName()) {
                $this->bin = $bearsamppBins->getMailpit();
                $this->currentVersion = $bearsamppBins->getMailpit()->getVersion();
                $this->service = $bearsamppBins->getMailpit()->getService();
                $this->changePort = false;
                $folderList = Util::getFolderList($bearsamppBins->getMailpit()->getRootPath());
                foreach ($folderList as $folder) {
                    $this->pathsToScan[] = array(
                        'path' => $bearsamppBins->getMailpit()->getRootPath() . '/' . $folder,
                        'includes' => array('.conf'),
                        'recursive' => true
                    );
                }
            } elseif ($args[0] == $bearsamppBins->getXlight()->getName()) {
                $this->bin = $bearsamppBins->getXlight();
                $this->currentVersion = $bearsamppBins->getXlight()->getVersion();
                $this->service = $bearsamppBins->getXlight()->getService();
                $this->changePort = true;
                $folderList = Util::getFolderList($bearsamppBins->getXlight()->getRootPath());
                foreach ($folderList as $folder) {
                    $this->pathsToScan[] = array(
                        'path' => $bearsamppBins->getXlight()->getRootPath() . '/' . $folder,
                        'includes' => array('.conf, ftpd.hosts, ftpd.option, ftpd.password, ftpd.rules, ftpd.users, .ini'),
                        'recursive' => true
                    );
                }
            }
            $this->boxTitle = sprintf($bearsamppLang->getValue(Lang::SWITCH_VERSION_TITLE), $this->bin->getName(), $this->version);
            // Start splash screen
            $this->bearsamppSplash = new Splash();
            $this->bearsamppSplash->init(
                $this->boxTitle,
                self::GAUGE_SERVICES * count($bearsamppBins->getServices()) + self::GAUGE_OTHERS,
                $this->boxTitle
            );
            $bearsamppWinbinder->setHandler($this->bearsamppSplash->getWbWindow(), $this, 'processWindow', 1000);
            $bearsamppWinbinder->mainLoop();
            $bearsamppWinbinder->reset();
        }
    }
References $bearsamppBins, $bearsamppLang, Util\getFolderList(), and Lang\SWITCH_VERSION_TITLE.
Member Function Documentation
processWindow ( $window, $id, $ctrl, $param1, $param2)
Processes the window events for the splash screen.
Parameters
$window The window handle.
$id The event ID.
$ctrl The control handle.
$param1 The first parameter.
$param2 The second parameter.
Definition at line 198 of file class.action.switchVersion.php.
    {
        global $bearsamppCore, $bearsamppLang, $bearsamppBins, $bearsamppWinbinder;
        if ($this->version == $this->currentVersion) {
            $bearsamppWinbinder->messageBoxWarning(sprintf($bearsamppLang->getValue(Lang::SWITCH_VERSION_SAME_ERROR), $this->bin->getName(), $this->version), $this->boxTitle);
            $bearsamppWinbinder->destroyWindow($window);
        }
        // scan folder
        $this->bearsamppSplash->incrProgressBar();
        if (!empty($this->pathsToScan)) {
            Util::changePath(Util::getFilesToScan($this->pathsToScan));
        }
        // switch
        $this->bearsamppSplash->incrProgressBar();
        if ($this->bin->switchVersion($this->version, true) === false) {
            $this->bearsamppSplash->incrProgressBar(self::GAUGE_SERVICES * count($bearsamppBins->getServices()) + self::GAUGE_OTHERS);
            $bearsamppWinbinder->destroyWindow($window);
        }
        // stop service
        if ($this->service != null) {
            $binName = $this->bin->getName() == $bearsamppLang->getValue(Lang::PHP) ? $bearsamppLang->getValue(Lang::APACHE) : $this->bin->getName();
            $this->bearsamppSplash->setTextLoading(sprintf($bearsamppLang->getValue(Lang::STOP_SERVICE_TITLE), $binName));
            $this->bearsamppSplash->incrProgressBar();
            $this->service->stop();
        } else {
            $this->bearsamppSplash->incrProgressBar();
        }
        // reload config
        $this->bearsamppSplash->setTextLoading($bearsamppLang->getValue(Lang::SWITCH_VERSION_RELOAD_CONFIG));
        $this->bearsamppSplash->incrProgressBar();
        Root::loadConfig();
        // reload bins
        $this->bearsamppSplash->setTextLoading($bearsamppLang->getValue(Lang::SWITCH_VERSION_RELOAD_BINS));
        $this->bearsamppSplash->incrProgressBar();
        $bearsamppBins->reload();
        // change port
        if ($this->changePort) {
            $this->bin->reload();
            $this->bin->changePort($this->bin->getPort());
        }
        // start service
        if ($this->service != null) {
            $binName = $this->bin->getName() == $bearsamppLang->getValue(Lang::PHP) ? $bearsamppLang->getValue(Lang::APACHE) : $this->bin->getName();
            $this->bearsamppSplash->setTextLoading(sprintf($bearsamppLang->getValue(Lang::START_SERVICE_TITLE), $binName));
            $this->bearsamppSplash->incrProgressBar();
            $this->service->start();
        } else {
            $this->bearsamppSplash->incrProgressBar();
        }
        $this->bearsamppSplash->incrProgressBar(self::GAUGE_SERVICES * count($bearsamppBins->getServices()) + 1);
        // Update configuration file with the new version
        Util::logTrace('Updating ini & menu...');
        $this->updateConfigVersion();
        Util::logTrace('Creating modal...');
        $bearsamppWinbinder->messageBoxInfo(
            sprintf($bearsamppLang->getValue(Lang::SWITCH_VERSION_OK), $this->bin->getName(), $this->version),
            $this->boxTitle
        );
        Util::logTrace('Destroying modal window...');
        $bearsamppWinbinder->destroyWindow($window);
        // Store current registry value for comparison
        $currentRegValue = Util::getAppBinsRegKey(false);
        $regEntry = Registry::APP_BINS_REG_ENTRY;
        Util::logTrace(sprintf(
            'Starting registry adjustment for key: %s | Current value: %s',
            $regEntry,
            $currentRegValue
        ));
        $this->bearsamppSplash->setTextLoading(sprintf(
            $bearsamppLang->getValue(Lang::SWITCH_VERSION_REGISTRY),
            $regEntry
        ));
        $this->bearsamppSplash->incrProgressBar(2);
        // Perform the registry update
        $newRegValue = Util::setAppBinsRegKey($currentRegValue);
        Util::logTrace(sprintf(
            'Registry update completed | Key: %s | New value: %s | Previous value: %s',
            $regEntry,
            $newRegValue,
            $currentRegValue
        ));
        Util::logTrace(sprintf(
            'Resetting services: %s',
            $bearsamppLang->getValue(Lang::SWITCH_VERSION_RESET_SERVICES)
        ));
        
        $this->bearsamppSplash->setTextLoading($bearsamppLang->getValue(Lang::SWITCH_VERSION_RESET_SERVICES));
        foreach ($bearsamppBins->getServices() as $sName => $service) {
            Util::logTrace(sprintf('Deleting service: %s', $sName));
            $this->bearsamppSplash->incrProgressBar();
            $service->delete();
            Util::logTrace(sprintf('Service deleted: %s', $sName));
        }
        Util::logTrace('All services reset completed');
        $bearsamppWinbinder->messageBoxInfo(
            sprintf($bearsamppLang->getValue(Lang::SWITCH_VERSION_OK_RESTART), $this->bin->getName(), $this->version, APP_TITLE),
            $this->boxTitle
        );
        Util::logTrace('Running setExec line 317..');
        $bearsamppCore->setExec(ActionExec::RESTART);
        Util::logTrace('Destroying final window...');
        $bearsamppWinbinder->destroyWindow($window);
    }
References $bearsamppBins, $bearsamppCore, $bearsamppLang, $service, Lang\APACHE, Registry\APP_BINS_REG_ENTRY, APP_TITLE, Util\changePath(), Util\getAppBinsRegKey(), Util\getFilesToScan(), Root\loadConfig(), Util\logTrace(), Lang\PHP, ActionExec\RESTART, Util\setAppBinsRegKey(), Lang\START_SERVICE_TITLE, Lang\STOP_SERVICE_TITLE, Lang\SWITCH_VERSION_OK, Lang\SWITCH_VERSION_OK_RESTART, Lang\SWITCH_VERSION_REGISTRY, Lang\SWITCH_VERSION_RELOAD_BINS, Lang\SWITCH_VERSION_RELOAD_CONFIG, Lang\SWITCH_VERSION_RESET_SERVICES, Lang\SWITCH_VERSION_SAME_ERROR, and updateConfigVersion().
updateConfigVersion () [private]
Updates the configuration file with the new version of the binary This ensures version persistence across restarts
Definition at line 327 of file class.action.switchVersion.php.
                                          : void
    {
        $bearsamppConfig = new Config();
        $configSection = '';
        $version = $this->version; // Ensure version is available in scope
        
        // Determine the correct configuration section based on binary type
        if ($this->bin->getName() == $GLOBALS['bearsamppBins']->getApache()->getName()) {
            $configSection = self::CONFIG_SECTION_APACHE;
            Util::logTrace(sprintf('Switch %s version to %s', $configSection, $version));
        } elseif ($this->bin->getName() == $GLOBALS['bearsamppBins']->getPhp()->getName()) {
            $configSection = self::CONFIG_SECTION_PHP;
            Util::logTrace(sprintf('Switch %s version to %s', $configSection, $version));
        } elseif ($this->bin->getName() == $GLOBALS['bearsamppBins']->getMysql()->getName()) {
            $configSection = self::CONFIG_SECTION_MYSQL;
            Util::logTrace(sprintf('Switch %s version to %s', $configSection, $version));
        } elseif ($this->bin->getName() == $GLOBALS['bearsamppBins']->getMariadb()->getName()) {
            $configSection = self::CONFIG_SECTION_MARIADB;
            Util::logTrace(sprintf('Switch %s version to %s', $configSection, $version));
        } elseif ($this->bin->getName() == $GLOBALS['bearsamppBins']->getPostgresql()->getName()) {
            $configSection = self::CONFIG_SECTION_POSTGRESQL;
            Util::logTrace(sprintf('Switch %s version to %s', $configSection, $version));
        } elseif ($this->bin->getName() == $GLOBALS['bearsamppBins']->getNodejs()->getName()) {
            $configSection = self::CONFIG_SECTION_NODEJS;
            Util::logTrace(sprintf('Switch %s version to %s', $configSection, $version));
        } elseif ($this->bin->getName() == $GLOBALS['bearsamppBins']->getMemcached()->getName()) {
            $configSection = self::CONFIG_SECTION_MEMCACHED;
            Util::logTrace(sprintf('Switch %s version to %s', $configSection, $version));
        } elseif ($this->bin->getName() == $GLOBALS['bearsamppBins']->getMailpit()->getName()) {
            $configSection = self::CONFIG_SECTION_MAILPIT;
            Util::logTrace(sprintf('Switch %s version to %s', $configSection, $version));
        } elseif ($this->bin->getName() == $GLOBALS['bearsamppBins']->getXlight()->getName()) {
            $configSection = self::CONFIG_SECTION_XLIGHT;
            Util::logTrace(sprintf('Switch %s version to %s', $configSection, $version));
        }
        
        // Update the configuration if a valid section was found
        if (!empty($configSection)) {
            Util::logTrace('Updating .ini file...');
            $bearsamppConfig->replace($configSection, self::CONFIG_KEY_VERSION, $version);
            // Update tray menu display if TrayMenu class is available
            Util::logTrace('Updating TrayMenu...');
            if (class_exists('TrayMenu')) {
                $trayMenu = TrayMenu::getInstance();
                if (method_exists($trayMenu, 'updateSectionVersion')) {
                    $trayMenu->updateSectionVersion(
                        strtoupper($configSection),
                        $version
                    );
                }
            }
        }
        Util::logTrace('Returning to parent call');
    }
References $bearsamppConfig, $version, and Util\logTrace().
Referenced by processWindow().
Field Documentation
$bearsamppSplash [private]
Definition at line 17 of file class.action.switchVersion.php.
$bin [private]
Definition at line 19 of file class.action.switchVersion.php.
$boxTitle [private]
Definition at line 23 of file class.action.switchVersion.php.
$changePort [private]
Definition at line 22 of file class.action.switchVersion.php.
$currentVersion [private]
Definition at line 20 of file class.action.switchVersion.php.
$pathsToScan = [] [private]
Definition at line 24 of file class.action.switchVersion.php.
$service [private]
Definition at line 21 of file class.action.switchVersion.php.
Referenced by processWindow().
$version [private]
Definition at line 18 of file class.action.switchVersion.php.
Referenced by updateConfigVersion().
const CONFIG_KEY_VERSION = 'version'
Definition at line 41 of file class.action.switchVersion.php.
const CONFIG_SECTION_APACHE = 'apache'
Definition at line 30 of file class.action.switchVersion.php.
const CONFIG_SECTION_MAILPIT = 'mailpit'
Definition at line 37 of file class.action.switchVersion.php.
const CONFIG_SECTION_MARIADB = 'mariadb'
Definition at line 33 of file class.action.switchVersion.php.
const CONFIG_SECTION_MEMCACHED = 'memcached'
Definition at line 36 of file class.action.switchVersion.php.
const CONFIG_SECTION_MYSQL = 'mysql'
Definition at line 32 of file class.action.switchVersion.php.
const CONFIG_SECTION_NODEJS = 'nodejs'
Definition at line 35 of file class.action.switchVersion.php.
const CONFIG_SECTION_PHP = 'php'
Definition at line 31 of file class.action.switchVersion.php.
const CONFIG_SECTION_POSTGRESQL = 'postgresql'
Definition at line 34 of file class.action.switchVersion.php.
const CONFIG_SECTION_XLIGHT = 'xlight'
Definition at line 38 of file class.action.switchVersion.php.
const GAUGE_OTHERS = 7
Definition at line 27 of file class.action.switchVersion.php.
const GAUGE_SERVICES = 1
Definition at line 26 of file class.action.switchVersion.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.