.TH "ActionCheckPort" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionCheckPort
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBActionCheckPort\fP

.PP
This class is responsible for checking the port status of various services (Apache, MySQL, MariaDB, PostgreSQL, Mailpit, Memcached, Xlight) based on the provided arguments\&. 
.PP
Definition at line \fB16\fP of file \fBclass\&.action\&.checkPort\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $args)"
Constructor for \fBActionCheckPort\fP\&.

.PP
\fBParameters\fP
.RS 4
\fI$args\fP An array of arguments where:
.IP "\(bu" 2
$args[0] is the name of the service (e\&.g\&., Apache, MySQL)\&.
.IP "\(bu" 2
$args[1] is the port number to check\&.
.IP "\(bu" 2
$args[2] (optional) indicates if SSL should be used\&.
.PP
.RE
.PP
@global object $bearsamppBins Global object containing instances of various services\&. 
.PP
Definition at line \fB28\fP of file \fBclass\&.action\&.checkPort\&.php\fP\&.
.nf
29     {
30         global $bearsamppBins;
31 
32         // Check if the required arguments are provided and not empty
33         if ( isset( $args[0] ) && !empty( $args[0] ) && isset( $args[1] ) && !empty( $args[1] ) ) {
34             // Determine if SSL is to be used
35             $ssl = isset( $args[2] ) && !empty( $args[2] );
36 
37             // Check the port for the specified service
38             if ( $args[0] == $bearsamppBins\->getApache()\->getName() ) {
39                 $bearsamppBins\->getApache()\->checkPort( $args[1], $ssl, true );
40             }
41             elseif ( $args[0] == $bearsamppBins\->getMysql()\->getName() ) {
42                 $bearsamppBins\->getMysql()\->checkPort( $args[1], true );
43             }
44             elseif ( $args[0] == $bearsamppBins\->getMariadb()\->getName() ) {
45                 $bearsamppBins\->getMariadb()\->checkPort( $args[1], true );
46             }
47             elseif ( $args[0] == $bearsamppBins\->getPostgresql()\->getName() ) {
48                 $bearsamppBins\->getPostgresql()\->checkPort( $args[1], true );
49             }
50             elseif ( $args[0] == $bearsamppBins\->getMailpit()\->getName() ) {
51                 $bearsamppBins\->getMailpit()\->checkPort( $args[1], true );
52             }
53             elseif ( $args[0] == $bearsamppBins\->getMemcached()\->getName() ) {
54                 $bearsamppBins\->getMemcached()\->checkPort( $args[1], true );
55             }
56             elseif ( $args[0] == $bearsamppBins\->getXlight()\->getName() ) {
57                 $bearsamppBins\->getXlight()\->checkPort( $args[1], true );
58             }
59         }
60     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
