ActionQuit
NAME
ActionQuit
SYNOPSIS
Public Member Functions
__construct ($args)
processWindow ($window, $id, $ctrl, $param1, $param2)
Static Public Member Functions
static terminatePhpProcesses ($excludePid, $window=null, $splash=null, $timeout=10)
Data Fields
const GAUGE_OTHERS = 1
const GAUGE_PROCESSES = 1
Private Attributes
$splash
Detailed Description
Class ActionQuit Handles the quitting process of the Bearsampp application. Displays a splash screen and stops all services and processes.
Definition at line 16 of file class.action.quit.php.
Constructor & Destructor Documentation
__construct ( $args)
ActionQuit constructor. Initializes the quitting process, displays the splash screen, and sets up the main loop.
Parameters
$args Command line arguments.
Definition at line 35 of file class.action.quit.php.
    {
        global $bearsamppCore, $bearsamppLang, $bearsamppBins, $bearsamppWinbinder, $arrayOfCurrents;
        // Start splash screen
        $this->splash = new Splash();
        $this->splash->init(
            $bearsamppLang->getValue( Lang::QUIT ),
            self::GAUGE_PROCESSES * count( $bearsamppBins->getServices() ) + self::GAUGE_OTHERS,
            sprintf( $bearsamppLang->getValue( Lang::EXIT_LEAVING_TEXT ), APP_TITLE . ' ' . $bearsamppCore->getAppVersion() )
        );
        // Set handler for the splash screen window
        $bearsamppWinbinder->setHandler( $this->splash->getWbWindow(), $this, 'processWindow', 2000 );
        $bearsamppWinbinder->mainLoop();
        $bearsamppWinbinder->reset();
    }
References $bearsamppBins, $bearsamppCore, $bearsamppLang, APP_TITLE, Lang\EXIT_LEAVING_TEXT, and Lang\QUIT.
Member Function Documentation
processWindow ( $window, $id, $ctrl, $param1, $param2)
Processes the splash screen window events. Stops all services, deletes symlinks, and kills remaining processes.
Parameters
$window The window resource.
$id The event ID.
$ctrl The control ID.
$param1 Additional parameter 1.
$param2 Additional parameter 2.
Definition at line 64 of file class.action.quit.php.
    {
        global $bearsamppBins, $bearsamppLang, $bearsamppWinbinder;
        // Stop all services
        foreach ( $bearsamppBins->getServices() as $sName => $service ) {
            $name = $bearsamppBins->getApache()->getName() . ' ' . $bearsamppBins->getApache()->getVersion();
            if ( $sName == BinMysql::SERVICE_NAME ) {
                $name = $bearsamppBins->getMysql()->getName() . ' ' . $bearsamppBins->getMysql()->getVersion();
            }
            elseif ( $sName == BinMailpit::SERVICE_NAME ) {
                $name = $bearsamppBins->getMailpit()->getName() . ' ' . $bearsamppBins->getMailpit()->getVersion();
            }
            elseif ( $sName == BinMariadb::SERVICE_NAME ) {
                $name = $bearsamppBins->getMariadb()->getName() . ' ' . $bearsamppBins->getMariadb()->getVersion();
            }
            elseif ( $sName == BinPostgresql::SERVICE_NAME ) {
                $name = $bearsamppBins->getPostgresql()->getName() . ' ' . $bearsamppBins->getPostgresql()->getVersion();
            }
            elseif ( $sName == BinMemcached::SERVICE_NAME ) {
                $name = $bearsamppBins->getMemcached()->getName() . ' ' . $bearsamppBins->getMemcached()->getVersion();
            }
            elseif ($sName == BinXlight::SERVICE_NAME) {
                $name = $bearsamppBins->getXlight()->getName() . ' ' . $bearsamppBins->getXlight()->getVersion();
            }
            $name .= ' (' . $service->getName() . ')';
            $this->splash->incrProgressBar();
            $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::EXIT_REMOVE_SERVICE_TEXT ), $name ) );
            $service->delete();
        }
        // Purge "current" symlinks
        Symlinks::deleteCurrentSymlinks();
        // Stop other processes
        $this->splash->incrProgressBar();
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::EXIT_STOP_OTHER_PROCESS_TEXT ) );
        Win32Ps::killBins( true );
        // Terminate any remaining processes
        // Final termination sequence
        $this->splash->setTextLoading('Completing shutdown...');
        if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
            $currentPid = Win32Ps::getCurrentPid();
            // Terminate PHP processes with a timeout of 15 seconds
            self::terminatePhpProcesses($currentPid, $window, $this->splash, 15);
            
            // Force exit if still running
            exit(0);
        }
        // Non-Windows fallback
        $bearsamppWinbinder->destroyWindow($window);
        exit(0);
    }
References $bearsamppBins, $bearsamppLang, Symlinks\deleteCurrentSymlinks(), exit, Lang\EXIT_REMOVE_SERVICE_TEXT, Lang\EXIT_STOP_OTHER_PROCESS_TEXT, Win32Ps\getCurrentPid(), Win32Ps\killBins(), BinMailpit\SERVICE_NAME, BinMariadb\SERVICE_NAME, BinMemcached\SERVICE_NAME, BinMysql\SERVICE_NAME, BinPostgresql\SERVICE_NAME, BinXlight\SERVICE_NAME, and terminatePhpProcesses().
terminatePhpProcesses ( $excludePid, $window = null, $splash = null, $timeout = 10) [static]
Terminates PHP processes with timeout handling.
Parameters
$excludePid Process ID to exclude
$window Window handle or null
$splash Splash screen or null
$timeout Maximum time to wait for termination (seconds)
Returns
void
Definition at line 131 of file class.action.quit.php.
    {
        global $bearsamppWinbinder;
        $currentPid = Win32Ps::getCurrentPid();
        $startTime = microtime(true);
        
        Util::logTrace('Starting PHP process termination (excluding PID: ' . $excludePid . ')');
        $targets = ['php-win.exe', 'php.exe'];
        foreach (Win32Ps::getListProcs() as $proc) {
            // Check if we've exceeded our timeout
            if (microtime(true) - $startTime > $timeout) {
                Util::logTrace('Process termination timeout exceeded, continuing with remaining operations');
                break;
            }
            
            $exe = strtolower(basename($proc[Win32Ps::EXECUTABLE_PATH]));
            $pid = $proc[Win32Ps::PROCESS_ID];
            if (in_array($exe, $targets) && $pid != $excludePid) {
                Util::logTrace('Terminating PHP process: ' . $pid);
                Win32Ps::kill($pid);
                usleep(100000); // 100ms delay between terminations
            }
        }
        // Initiate self-termination with timeout
        if ($splash !== null) {
            $splash->setTextLoading('Final cleanup...');
        }
        
        try {
            Util::logTrace('Initiating self-termination for PID: ' . $currentPid);
            // Add a timeout wrapper around the killProc call
            $killSuccess = Vbs::killProc($currentPid);
            if (!$killSuccess) {
                Util::logTrace('Self-termination via Vbs::killProc failed, using alternative method');
            }
        } catch (\Exception $e) {
            Util::logTrace('Exception during self-termination: ' . $e->getMessage());
        }
        // Destroy window after process termination
        // Fix for PHP 8.2: Check if window is not null before destroying
        if ($window && $bearsamppWinbinder) {
            try {
                Util::logTrace('Destroying window');
                $bearsamppWinbinder->destroyWindow($window);
            } catch (\Exception $e) {
                Util::logTrace('Exception during window destruction: ' . $e->getMessage());
            }
        }
        
        // Force exit if still running after timeout
        if (microtime(true) - $startTime > $timeout * 1.5) {
            Util::logTrace('Forcing exit due to timeout');
            exit(0);
        }
    }
References $proc, $splash, Win32Ps\EXECUTABLE_PATH, exit, Win32Ps\getCurrentPid(), Win32Ps\getListProcs(), Win32Ps\kill(), Vbs\killProc(), Util\logTrace(), and Win32Ps\PROCESS_ID.
Referenced by processWindow(), and ActionStartup\processWindow().
Field Documentation
$splash [private]
Definition at line 21 of file class.action.quit.php.
Referenced by terminatePhpProcesses().
const GAUGE_OTHERS = 1
Definition at line 27 of file class.action.quit.php.
const GAUGE_PROCESSES = 1
Gauge values for progress bar increments.
Definition at line 26 of file class.action.quit.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.