E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.quickpick.php
NAME
E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.quickpick.php
SYNOPSIS
Namespaces
namespace Bearsampp
Variables
$response = array()
if($_SERVER['REQUEST_METHOD']==='POST') else
exit
Variable Documentation
$response = array()
Definition at line 26 of file ajax.quickpick.php.
Referenced by QuickPick\checkDownloadId(), Util\getCurlHttpHeaders(), and QuickPick\installModule().
if ( $_SERVER[ 'REQUEST_METHOD']==='POST') else
Initial value:
{
    $response = ['error' => 'Invalid request method.']
Definition at line 76 of file ajax.quickpick.php.
exit
Definition at line 82 of file ajax.quickpick.php.
Referenced by ActionQuit\processWindow(), ActionStartup\processWindow(), and ActionQuit\terminatePhpProcesses().
Author
Generated automatically by Doxygen for Bearsampp from the source code.