.TH "E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.mariadb.php" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.mariadb.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "global \fB$bearsamppBins\fP"
.br
.ti -1c
.RI "global \fB$bearsamppLang\fP"
.br
.ti -1c
.RI "\fB$port\fP = $bearsamppBins\->getMariadb()\->getPort()"
.br
.ti -1c
.RI "\fB$result\fP"
.br
.ti -1c
.RI "\fB$textDisabled\fP = $bearsamppLang\->getValue(\fBLang::DISABLED\fP)"
.br
.ti -1c
.RI "\fB$textServiceStarted\fP = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STARTED\fP)"
.br
.ti -1c
.RI "\fB$textServiceStopped\fP = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STOPPED\fP)"
.br
.ti -1c
.RI "\fBif\fP($bearsamppBins\->getMariadb() \->isEnable()) \fBelse\fP"
.br
.ti -1c
.RI "\fBforeach\fP ( $bearsamppBins\->getMariadb() \->getVersionList() as $version)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "global $bearsamppBins"

.PP
Definition at line \fB10\fP of file \fBajax\&.mariadb\&.php\fP\&.
.SS "global $bearsamppLang"

.PP
Definition at line \fB10\fP of file \fBajax\&.mariadb\&.php\fP\&.
.SS "$port = $bearsamppBins\->getMariadb()\->getPort()"

.PP
Definition at line \fB28\fP of file \fBajax\&.mariadb\&.php\fP\&.
.SS "$result"
\fBInitial value:\fP
.nf
= array(
    'checkport' => '',
    'versions' => '',
)
.PP
.fi
This script generates information about the status of the MariaDB service and its versions\&. It checks if the MariaDB service is enabled, checks the port, and retrieves the list of versions\&. The output is encoded in JSON format and includes the port status and versions information\&.

.PP
@global object $bearsamppBins Provides access to various binaries including MariaDB\&. @global object $bearsamppLang Provides access to language-specific strings\&. 
.PP
Definition at line \fB22\fP of file \fBajax\&.mariadb\&.php\fP\&.
.SS "$textDisabled = $bearsamppLang\->getValue(\fBLang::DISABLED\fP)"

.PP
Definition at line \fB32\fP of file \fBajax\&.mariadb\&.php\fP\&.
.SS "$textServiceStarted = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STARTED\fP)"

.PP
Definition at line \fB30\fP of file \fBajax\&.mariadb\&.php\fP\&.
.SS "$textServiceStopped = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STOPPED\fP)"

.PP
Definition at line \fB31\fP of file \fBajax\&.mariadb\&.php\fP\&.
.SS "\fBif\fP ( $bearsamppBins\->getMariadb() \->isEnable()) else"
\fBInitial value:\fP
.nf
{
    $result['checkport'] = '<span class="float\-end badge text\-bg\-secondary">' \&. $textDisabled \&. '</span>'
.PP
.fi
Check if the MariaDB service is enabled and update the port status accordingly\&. If the service is enabled, check if the port is open and update the status\&. If the service is disabled, set the status to disabled\&. 
.PP
Definition at line \fB45\fP of file \fBajax\&.mariadb\&.php\fP\&.
.SS "foreach($bearsamppBins\->getMariadb() \->getVersionList() as $version) ( $bearsamppBins\->getMariadb() \->getVersionList() as)"
Retrieve the list of available MariaDB versions and update the versions information\&. Highlight the current version with a primary badge and other versions with a secondary badge\&. 
.PP
Definition at line \fB53\fP of file \fBajax\&.mariadb\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
