.TH "E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.mysql.php" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.mysql.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "global \fB$bearsamppBins\fP"
.br
.ti -1c
.RI "global \fB$bearsamppLang\fP"
.br
.ti -1c
.RI "\fB$port\fP = $bearsamppBins\->getMysql()\->getPort()"
.br
.ti -1c
.RI "\fB$result\fP"
.br
.ti -1c
.RI "\fB$textDisabled\fP = $bearsamppLang\->getValue(\fBLang::DISABLED\fP)"
.br
.ti -1c
.RI "\fB$textServiceStarted\fP = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STARTED\fP)"
.br
.ti -1c
.RI "\fB$textServiceStopped\fP = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STOPPED\fP)"
.br
.ti -1c
.RI "\fBif\fP($bearsamppBins\->getMysql() \->isEnable()) \fBelse\fP"
.br
.ti -1c
.RI "\fBforeach\fP ( $bearsamppBins\->getMysql() \->getVersionList() as $version)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "global $bearsamppBins"

.PP
Definition at line \fB10\fP of file \fBajax\&.mysql\&.php\fP\&.
.SS "global $bearsamppLang"

.PP
Definition at line \fB10\fP of file \fBajax\&.mysql\&.php\fP\&.
.SS "$port = $bearsamppBins\->getMysql()\->getPort()"

.PP
Definition at line \fB26\fP of file \fBajax\&.mysql\&.php\fP\&.
.SS "$result"
\fBInitial value:\fP
.nf
= array(
    'checkport' => '',
    'versions' => '',
)
.PP
.fi
This script checks the status of the MySQL service and retrieves its versions\&. It creates an array with keys 'checkport' and 'versions', which are populated with HTML strings indicating the status of the MySQL service and its available versions, respectively\&. The final result is encoded in JSON format and echoed out\&. 
.PP
Definition at line \fB20\fP of file \fBajax\&.mysql\&.php\fP\&.
.SS "$textDisabled = $bearsamppLang\->getValue(\fBLang::DISABLED\fP)"

.PP
Definition at line \fB30\fP of file \fBajax\&.mysql\&.php\fP\&.
.SS "$textServiceStarted = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STARTED\fP)"

.PP
Definition at line \fB28\fP of file \fBajax\&.mysql\&.php\fP\&.
.SS "$textServiceStopped = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STOPPED\fP)"

.PP
Definition at line \fB29\fP of file \fBajax\&.mysql\&.php\fP\&.
.SS "\fBif\fP ( $bearsamppBins\->getMysql() \->isEnable()) else"
\fBInitial value:\fP
.nf
{
    $result['checkport'] = '<span class="float\-end badge text\-bg\-secondary">' \&. $textDisabled \&. '</span>'
.PP
.fi
Check if MySQL service is enabled and its port status\&. If enabled, check if the port is open and set the appropriate status message\&. If disabled, set the status message to indicate that the service is disabled\&. 
.PP
Definition at line \fB43\fP of file \fBajax\&.mysql\&.php\fP\&.
.SS "foreach($bearsamppBins\->getMysql() \->getVersionList() as $version) ( $bearsamppBins\->getMysql() \->getVersionList() as)"
Retrieve the list of MySQL versions and highlight the current version\&. Add each version to the 'versions' key in the result array, using different badge styles to indicate the current version and other versions\&. 
.PP
Definition at line \fB52\fP of file \fBajax\&.mysql\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
