.TH "E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.xlight.php" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.xlight.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "global \fB$bearsamppBins\fP"
.br
.ti -1c
.RI "global \fB$bearsamppLang\fP"
.br
.ti -1c
.RI "\fB$port\fP = $bearsamppBins\->getXlight()\->getPort()"
.br
.ti -1c
.RI "\fB$result\fP"
.br
.ti -1c
.RI "\fB$textDisabled\fP = $bearsamppLang\->getValue(\fBLang::DISABLED\fP)"
.br
.ti -1c
.RI "\fB$textServiceStarted\fP = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STARTED\fP)"
.br
.ti -1c
.RI "\fB$textServiceStopped\fP = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STOPPED\fP)"
.br
.ti -1c
.RI "\fBif\fP($bearsamppBins\->getXlight() \->checkPort($port)) \fBelse\fP"
.br
.ti -1c
.RI "\fBforeach\fP ( $bearsamppBins\->getXlight() \->getVersionList() as $version)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "global $bearsamppBins"

.PP
Definition at line \fB9\fP of file \fBajax\&.xlight\&.php\fP\&.
.SS "global $bearsamppLang"

.PP
Definition at line \fB9\fP of file \fBajax\&.xlight\&.php\fP\&.
.SS "$port = $bearsamppBins\->getXlight()\->getPort()"

.PP
Definition at line \fB24\fP of file \fBajax\&.xlight\&.php\fP\&.
.SS "$result"
\fBInitial value:\fP
.nf
= array(
    'checkport' => '',
    'versions' => '',
)
.PP
.fi
This script retrieves information about the Xlight service status and versions\&. It checks the SMTP port status and retrieves the list of available versions\&. The results are returned as a JSON-encoded array\&. 
.PP
Definition at line \fB18\fP of file \fBajax\&.xlight\&.php\fP\&.
.SS "$textDisabled = $bearsamppLang\->getValue(\fBLang::DISABLED\fP)"

.PP
Definition at line \fB28\fP of file \fBajax\&.xlight\&.php\fP\&.
.SS "$textServiceStarted = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STARTED\fP)"

.PP
Definition at line \fB26\fP of file \fBajax\&.xlight\&.php\fP\&.
.SS "$textServiceStopped = $bearsamppLang\->getValue(\fBLang::HOMEPAGE_SERVICE_STOPPED\fP)"

.PP
Definition at line \fB27\fP of file \fBajax\&.xlight\&.php\fP\&.
.SS "\fBif\fP ( $bearsamppBins\->getXlight() \->checkPort( $port)) else"
\fBInitial value:\fP
.nf
{
    $result['checkport'] = '<span class="float\-end badge text\-bg\-secondary">' \&. $textDisabled \&. '</span>'
.PP
.fi
Check if the Xlight service is running on the specified port\&. If the port is open, indicate that the service is started\&. If the port is closed, indicate that the service is stopped\&. If the service is disabled, indicate that it is disabled\&. 
.PP
Definition at line \fB42\fP of file \fBajax\&.xlight\&.php\fP\&.
.SS "foreach($bearsamppBins\->getXlight() \->getVersionList() as $version) ( $bearsamppBins\->getXlight() \->getVersionList() as)"
Retrieve the list of available Xlight versions\&. Highlight the current version with a primary badge\&. Other versions are displayed with a secondary badge\&. 
.PP
Definition at line \fB51\fP of file \fBajax\&.xlight\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
