.TH "E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.quickpick.php" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.quickpick.php
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBearsampp\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$response\fP = array()"
.br
.ti -1c
.RI "\fBif\fP($_SERVER['REQUEST_METHOD']==='POST') \fBelse\fP"
.br
.ti -1c
.RI "\fBexit\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$response = array()"

.PP
Definition at line \fB26\fP of file \fBajax\&.quickpick\&.php\fP\&.
.PP
Referenced by \fBQuickPick\\checkDownloadId()\fP, \fBUtil\\getCurlHttpHeaders()\fP, and \fBQuickPick\\installModule()\fP\&.
.SS "\fBif\fP ( $_SERVER[ 'REQUEST_METHOD']==='POST') else"
\fBInitial value:\fP
.nf
{
    $response = ['error' => 'Invalid request method\&.']
.PP
.fi

.PP
Definition at line \fB76\fP of file \fBajax\&.quickpick\&.php\fP\&.
.SS "exit"

.PP
Definition at line \fB82\fP of file \fBajax\&.quickpick\&.php\fP\&.
.PP
Referenced by \fBActionQuit\\processWindow()\fP, \fBActionStartup\\processWindow()\fP, and \fBActionQuit\\terminatePhpProcesses()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
