.TH "E:/Bearsampp-development/sandbox/core/resources/homepage/ajax.php" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/resources/homepage/ajax.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$proc\fP = \fBUtil::cleanPostVar\fP('proc', 'text')"
.br
.ti -1c
.RI "\fB$procMap\fP"
.br
.ti -1c
.RI "\fBif\fP(isset($procMap[$proc]) &&file_exists($procMap[$proc])) \fBelse\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$proc = \fBUtil::cleanPostVar\fP('proc', 'text')"

.PP
Definition at line \fB43\fP of file \fBajax\&.php\fP\&.
.PP
Referenced by \fBActionExt\\__construct()\fP, \fBWin32Ps\\findByPath()\fP, \fBWin32Ps\\findByPid()\fP, \fBWin32Ps\\killBins()\fP, \fBActionStartup\\killOldInstances()\fP, \fBActionStartup\\processWindow()\fP, and \fBActionQuit\\terminatePhpProcesses()\fP\&.
.SS "$procMap"
\fBInitial value:\fP
.nf
= [
    'summary' => __DIR__ \&. '/ajax/ajax\&.summary\&.php',
    'latestversion' => __DIR__ \&. '/ajax/ajax\&.latestversion\&.php',
    'apache' => __DIR__ \&. '/ajax/ajax\&.apache\&.php',
    'mailpit' => __DIR__ \&. '/ajax/ajax\&.mailpit\&.php',
    'memcached' => __DIR__ \&. '/ajax/ajax\&.memcached\&.php',
    'mariadb' => __DIR__ \&. '/ajax/ajax\&.mariadb\&.php',
    'mysql' => __DIR__ \&. '/ajax/ajax\&.mysql\&.php',
    'nodejs' => __DIR__ \&. '/ajax/ajax\&.nodejs\&.php',
    'php' => __DIR__ \&. '/ajax/ajax\&.php\&.php',
    'postgresql' => __DIR__ \&. '/ajax/ajax\&.postgresql\&.php',
    'xlight' => __DIR__ \&. '/ajax/ajax\&.xlight\&.php',
    'quickpick' => __DIR__ \&. '/ajax/ajax\&.quickpick\&.php'
]
.PP
.fi

.PP
Definition at line \fB21\fP of file \fBajax\&.php\fP\&.
.SS "\fBif\fP (isset( $procMap[ $proc]) &&file_exists( $procMap[ $proc])) else"
\fBInitial value:\fP
.nf
{
    
    echo json_encode(['error' => 'Invalid proc parameter'])
.PP
.fi
Check if the cleaned 'proc' parameter exists in our secure mapping\&. If valid, include the corresponding AJAX handler file using the pre-defined path\&. If not valid, return a JSON error message\&. 
.PP
Definition at line \fB55\fP of file \fBajax\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
