.TH "E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.summary.php" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.summary.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$apacheLabel\fP = 'bg\-secondary'"
.br
.ti -1c
.RI "\fB$apacheSslPort\fP = $bearsamppBins\->getApache()\->getSslPort()"
.br
.ti -1c
.RI "global \fB$bearsamppBins\fP"
.br
.ti -1c
.RI "\fB$dlMoreTpl\fP = '<a href='' \&. Util::getWebsiteUrl( 'module/%s', '#releases' ) \&. '' target='_blank' title='' \&. $downloadTitle \&. ''><span class='float\-end' style='margin\-left:\&.5rem;'><i class='fa\-solid fa\-cloud\-arrow\-down'></i></span></a>'"
.br
.ti -1c
.RI "global \fB$downloadTitle\fP"
.br
.ti -1c
.RI "\fB$mailpitLabel\fP = 'bg\-secondary'"
.br
.ti -1c
.RI "\fB$mariadbLabel\fP = 'bg\-secondary'"
.br
.ti -1c
.RI "\fB$memcachedLabel\fP = 'bg\-secondary'"
.br
.ti -1c
.RI "\fB$mysqlLabel\fP = 'bg\-secondary'"
.br
.ti -1c
.RI "\fB$postgresqlLabel\fP = 'bg\-secondary'"
.br
.ti -1c
.RI "\fB$result\fP"
.br
.ti -1c
.RI "\fBif\fP( $bearsamppBins\->getApache() \->isEnable()) \fB$result\fP ['binapache'] = sprintf( $dlMoreTpl, 'apache' )"
.br
.ti -1c
.RI "\fB$result\fP ['binapache'] = '<span class = ' float\-end badge ' \&. $apacheLabel \&. ''>' \&. $bearsamppBins\->getApache()\->getVersion() \&. '</span>'"
.br
.ti -1c
.RI "\fBif\fP( $bearsamppBins\->getMailpit() \->isEnable()) \fB$result\fP ['binmailpit'] = sprintf( $dlMoreTpl, 'mailpit' )"
.br
.ti -1c
.RI "\fB$result\fP ['binmailpit'] = '<span class = ' float\-end badge ' \&. $mailpitLabel \&. ''>' \&. $bearsamppBins\->getMailpit()\->getVersion() \&. '</span>'"
.br
.ti -1c
.RI "\fBif\fP( $bearsamppBins\->getMariadb() \->isEnable()) \fB$result\fP ['binmariadb'] = sprintf( $dlMoreTpl, 'mariadb' )"
.br
.ti -1c
.RI "\fB$result\fP ['binmariadb'] = '<span class = ' float\-end badge ' \&. $mariadbLabel \&. ''>' \&. $bearsamppBins\->getMariadb()\->getVersion() \&. '</span>'"
.br
.ti -1c
.RI "\fBif\fP( $bearsamppBins\->getMemcached() \->isEnable()) \fB$result\fP ['binmemcached'] = sprintf( $dlMoreTpl, 'memcached' )"
.br
.ti -1c
.RI "\fB$result\fP ['binmemcached'] = '<span class = ' float\-end badge ' \&. $memcachedLabel \&. ''>' \&. $bearsamppBins\->getMemcached()\->getVersion() \&. '</span>'"
.br
.ti -1c
.RI "\fBif\fP( $bearsamppBins\->getMysql() \->isEnable()) \fB$result\fP ['binmysql'] = sprintf( $dlMoreTpl, 'mysql' )"
.br
.ti -1c
.RI "\fB$result\fP ['binmysql'] = '<span class = ' float\-end badge ' \&. $mysqlLabel \&. ''>' \&. $bearsamppBins\->getMysql()\->getVersion() \&. '</span>'"
.br
.ti -1c
.RI "\fBif\fP( $bearsamppBins\->getNodejs() \->isEnable()) \fB$result\fP ['binnodejs'] = sprintf( $dlMoreTpl, 'nodejs' )"
.br
.ti -1c
.RI "\fB$result\fP ['binnodejs'] = '<span class = ' float\-end badge ' \&. $nodejsLabel \&. ''>' \&. $bearsamppBins\->getNodejs()\->getVersion() \&. '</span>'"
.br
.ti -1c
.RI "\fBif\fP( $bearsamppBins\->getPhp() \->isEnable()) \fB$result\fP ['binphp'] = sprintf( $dlMoreTpl, 'php' )"
.br
.ti -1c
.RI "\fB$result\fP ['binphp'] = '<span class = ' float\-end badge ' \&. $phpLabel \&. ''>' \&. $bearsamppBins\->getPhp()\->getVersion() \&. '</span>'"
.br
.ti -1c
.RI "\fBif\fP( $bearsamppBins\->getPostgresql() \->isEnable()) \fB$result\fP ['binpostgresql'] = sprintf( $dlMoreTpl, 'postgresql' )"
.br
.ti -1c
.RI "\fB$result\fP ['binpostgresql'] = '<span class = ' float\-end badge ' \&. $postgresqlLabel \&. ''>' \&. $bearsamppBins\->getPostgresql()\->getVersion() \&. '</span>'"
.br
.ti -1c
.RI "\fBif\fP( $bearsamppBins\->getXlight() \->isEnable()) \fB$result\fP ['binxlight'] = sprintf( $dlMoreTpl, 'xlight' )"
.br
.ti -1c
.RI "\fB$result\fP ['binxlight'] = '<span class = ' float\-end badge ' \&. $xlightLabel \&. ''>' \&. $bearsamppBins\->getXlight()\->getVersion() \&. '</span>'"
.br
.ti -1c
.RI "\fB$xlightLabel\fP = 'bg\-secondary'"
.br
.ti -1c
.RI "\fBcatch\fP (Exception $e)"
.br
.ti -1c
.RI "\fBtry\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$apacheLabel = 'bg\-secondary'"

.PP
Definition at line \fB42\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$apacheSslPort = $bearsamppBins\->getApache()\->getSslPort()"

.PP
Definition at line \fB41\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "global $bearsamppBins"

.PP
Definition at line \fB16\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$dlMoreTpl = '<a href='' \&. Util::getWebsiteUrl( 'module/%s', '#releases' ) \&. '' target='_blank' title='' \&. $downloadTitle \&. ''><span class='float\-end' style='margin\-left:\&.5rem;'><i class='fa\-solid fa\-cloud\-arrow\-down'></i></span></a>'"

.PP
Definition at line \fB32\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "global $downloadTitle"
Generates a JSON output containing information about various bins such as Apache, Mailpit, MariaDB, MySQL, PostgreSQL, Memcached, Node\&.js, and PHP\&. The output includes download links, version numbers, and status labels for each bin\&. 
.PP
Definition at line \fB16\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$mailpitLabel = 'bg\-secondary'"

.PP
Definition at line \fB68\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$mariadbLabel = 'bg\-secondary'"

.PP
Definition at line \fB110\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$memcachedLabel = 'bg\-secondary'"

.PP
Definition at line \fB173\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$mysqlLabel = 'bg\-secondary'"

.PP
Definition at line \fB131\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$postgresqlLabel = 'bg\-secondary'"

.PP
Definition at line \fB152\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$result"
\fBInitial value:\fP
.nf
= array(
    'binapache'     => '',
    'binmailpit'    => '',
    'binmariadb'    => '',
    'binmysql'      => '',
    'binpostgresql' => '',
    'binmemcached'  => '',
    'binnodejs'     => '',
    'binphp'        => '',
    'binxlight'     => '',
)
.PP
.fi

.PP
Definition at line \fB19\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "\fBif\fP ($bearsamppBins\->getApache() \->isEnable()) $result[ 'binapache'] = sprintf( $dlMoreTpl, 'apache' )"

.PP
Definition at line \fB54\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$result[ 'binapache'] = '<span class = ' float\-end badge ' \&. $apacheLabel \&. ''>' \&. $bearsamppBins\->getApache()\->getVersion() \&. '</span>'"

.PP
Definition at line \fB55\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "\fBif\fP ($bearsamppBins\->getMailpit() \->isEnable()) $result[ 'binmailpit'] = sprintf( $dlMoreTpl, 'mailpit' )"

.PP
Definition at line \fB75\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$result[ 'binmailpit'] = '<span class = ' float\-end badge ' \&. $mailpitLabel \&. ''>' \&. $bearsamppBins\->getMailpit()\->getVersion() \&. '</span>'"

.PP
Definition at line \fB76\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "\fBif\fP ($bearsamppBins\->getMariadb() \->isEnable()) $result[ 'binmariadb'] = sprintf( $dlMoreTpl, 'mariadb' )"

.PP
Definition at line \fB117\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$result[ 'binmariadb'] = '<span class = ' float\-end badge ' \&. $mariadbLabel \&. ''>' \&. $bearsamppBins\->getMariadb()\->getVersion() \&. '</span>'"

.PP
Definition at line \fB118\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "\fBif\fP ($bearsamppBins\->getMemcached() \->isEnable()) $result[ 'binmemcached'] = sprintf( $dlMoreTpl, 'memcached' )"

.PP
Definition at line \fB180\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$result[ 'binmemcached'] = '<span class = ' float\-end badge ' \&. $memcachedLabel \&. ''>' \&. $bearsamppBins\->getMemcached()\->getVersion() \&. '</span>'"

.PP
Definition at line \fB181\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "\fBif\fP ($bearsamppBins\->getMysql() \->isEnable()) $result[ 'binmysql'] = sprintf( $dlMoreTpl, 'mysql' )"

.PP
Definition at line \fB138\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$result[ 'binmysql'] = '<span class = ' float\-end badge ' \&. $mysqlLabel \&. ''>' \&. $bearsamppBins\->getMysql()\->getVersion() \&. '</span>'"

.PP
Definition at line \fB139\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "\fBif\fP ($bearsamppBins\->getNodejs() \->isEnable()) $result[ 'binnodejs'] = sprintf( $dlMoreTpl, 'nodejs' )"

.PP
Definition at line \fB197\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$result[ 'binnodejs'] = '<span class = ' float\-end badge ' \&. $nodejsLabel \&. ''>' \&. $bearsamppBins\->getNodejs()\->getVersion() \&. '</span>'"

.PP
Definition at line \fB198\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "\fBif\fP ($bearsamppBins\->getPhp() \->isEnable()) $result[ 'binphp'] = sprintf( $dlMoreTpl, 'php' )"

.PP
Definition at line \fB214\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$result[ 'binphp'] = '<span class = ' float\-end badge ' \&. $phpLabel \&. ''>' \&. $bearsamppBins\->getPhp()\->getVersion() \&. '</span>'"

.PP
Definition at line \fB215\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "\fBif\fP ($bearsamppBins\->getPostgresql() \->isEnable()) $result[ 'binpostgresql'] = sprintf( $dlMoreTpl, 'postgresql' )"

.PP
Definition at line \fB159\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$result[ 'binpostgresql'] = '<span class = ' float\-end badge ' \&. $postgresqlLabel \&. ''>' \&. $bearsamppBins\->getPostgresql()\->getVersion() \&. '</span>'"

.PP
Definition at line \fB160\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "\fBif\fP ($bearsamppBins\->getXlight() \->isEnable()) $result[ 'binxlight'] = sprintf( $dlMoreTpl, 'xlight' )"

.PP
Definition at line \fB96\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$result[ 'binxlight'] = '<span class = ' float\-end badge ' \&. $xlightLabel \&. ''>' \&. $bearsamppBins\->getXlight()\->getVersion() \&. '</span>'"

.PP
Definition at line \fB97\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "$xlightLabel = 'bg\-secondary'"

.PP
Definition at line \fB89\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "catch (Exception $e)"
\fBInitial value:\fP
.nf
{
    
    $mailpitPort  = $bearsamppBins\->getMailpit()\->getSmtpPort()
.PP
.fi

.PP
Definition at line \fB217\fP of file \fBajax\&.summary\&.php\fP\&.
.SS "\fBcatch\fP (Exception $e) try"
\fBInitial value:\fP
.nf
{
    
    $apachePort    = $bearsamppBins\->getApache()\->getPort()
.PP
.fi

.PP
Definition at line \fB34\fP of file \fBajax\&.summary\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
