Apps
NAME
Apps
SYNOPSIS
Public Member Functions
__construct ()
getAll ()
getPhpmyadmin ()
getPhppgadmin ()
update ()
Data Fields
const TYPE = 'apps'
Private Attributes
$phpmyadmin
$phppgadmin
Detailed Description
Class Apps
This class manages various application modules within the Bearsampp application. It provides methods to retrieve and update configurations for different tools such as PhpMyAdmin and PhpPgAdmin.
Definition at line 16 of file class.apps.php.
Constructor & Destructor Documentation
__construct ()
Constructor for the Apps class.
Definition at line 36 of file class.apps.php.
    {
    }
Member Function Documentation
getAll ()
Retrieves all application modules.
Returns
array An array containing instances of all application modules.
Definition at line 58 of file class.apps.php.
    {
        return array(
            $this->getPhpmyadmin(),
            $this->getPhppgadmin()
        );
    }
References getPhpmyadmin(), and getPhppgadmin().
Referenced by update().
getPhpmyadmin ()
Retrieves the PhpMyAdmin module instance.
If the instance is not already created, it initializes a new AppPhpmyadmin object.
Returns
AppPhpmyadmin The instance of the PhpMyAdmin module.
Definition at line 73 of file class.apps.php.
    {
        if ($this->phpmyadmin == null) {
            $this->phpmyadmin = new AppPhpmyadmin('phpmyadmin', self::TYPE);
        }
        return $this->phpmyadmin;
    }
References $phpmyadmin.
Referenced by getAll().
getPhppgadmin ()
Retrieves the PhpPgAdmin module instance.
If the instance is not already created, it initializes a new AppPhppgadmin object.
Returns
AppPhppgadmin The instance of the PhpPgAdmin module.
Definition at line 88 of file class.apps.php.
    {
        if ($this->phppgadmin == null) {
            $this->phppgadmin = new AppPhppgadmin('phppgadmin', self::TYPE);
        }
        return $this->phppgadmin;
    }
References $phppgadmin.
Referenced by getAll().
update ()
Updates the configuration for all application modules.
This method logs the update process and iterates through all the tools to update their configurations.
Definition at line 45 of file class.apps.php.
    {
        Util::logInfo('Update apps config');
        foreach ($this->getAll() as $tool) {
            $tool->update();
        }
    }
References getAll(), and Util\logInfo().
Field Documentation
$phpmyadmin [private]
Definition at line 26 of file class.apps.php.
Referenced by getPhpmyadmin().
$phppgadmin [private]
Definition at line 31 of file class.apps.php.
Referenced by getPhppgadmin().
const TYPE = 'apps'
The type of the module.
Definition at line 21 of file class.apps.php.
Referenced by Module\reload().
Author
Generated automatically by Doxygen for Bearsampp from the source code.