BinMysql
NAME
BinMysql
SYNOPSIS
Inherits Module.
Public Member Functions
__construct ($id, $type)
changePort ($port, $checkUsed=false, $wbProgressBar=null)
changeRootPassword ($currentPwd, $newPwd, $wbProgressBar=null)
checkPort ($port, $showWindow=false)
checkRootPassword ($currentPwd=null, $wbProgressBar=null)
getAdmin ()
getCliExe ()
getCmdLineOutput ($cmd)
getConf ()
getDataDir ()
getErrorLog ()
getExe ()
getPort ()
getRootPwd ()
getRootUser ()
getService ()
initData ($path=null, $version=null)
reload ($id=null, $type=null)
setEnable ($enabled, $showWindow=false)
setPort ($port)
setRootPwd ($rootPwd)
setRootUser ($rootUser)
setVersion ($version)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const CMD_SYNTAX_CHECK = '--help --verbose 1>NUL'
const CMD_VARIABLES = 'variables'
const CMD_VERSION = '--version'
const LOCAL_CFG_ADMIN = 'mysqlAdmin'
const LOCAL_CFG_CLI_EXE = 'mysqlCliExe'
const LOCAL_CFG_CONF = 'mysqlConf'
const LOCAL_CFG_EXE = 'mysqlExe'
const LOCAL_CFG_PORT = 'mysqlPort'
const LOCAL_CFG_ROOT_PWD = 'mysqlRootPwd'
const LOCAL_CFG_ROOT_USER = 'mysqlRootUser'
const ROOT_CFG_ENABLE = 'mysqlEnable'
const ROOT_CFG_VERSION = 'mysqlVersion'
const SERVICE_NAME = 'bearsamppmysql'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
Private Attributes
$admin
$cliExe
$conf
$dataDir
$errorLog
$exe
$port
$rootPwd
$rootUser
$service
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinMysql
This class represents the MySQL binary module in the Bearsampp application. It handles the configuration, management, and operations related to MySQL.
Definition at line 16 of file class.bin.mysql.php.
Constructor & Destructor Documentation
__construct ( $id, $type)
Constructs a BinMysql object and initializes the MySQL module.
Parameters
$id The ID of the module.
$type The type of the module.
Definition at line 53 of file class.bin.mysql.php.
    {
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
changePort ( $port, $checkUsed = false, $wbProgressBar = null)
Changes the MySQL port and updates the configuration.
Parameters
$port The new port number.
$checkUsed Whether to check if the port is already in use.
$wbProgressBar The progress bar object for UI updates.
Returns
bool|string True if the port was changed successfully, or an error message if the port is in use.
Definition at line 184 of file class.bin.mysql.php.
    {
        global $bearsamppWinbinder;
        if (!Util::isValidPort($port)) {
            Util::logError($this->getName() . ' port not valid: ' . $port);
            return false;
        }
        $port = intval($port);
        $bearsamppWinbinder->incrProgressBar($wbProgressBar);
        $isPortInUse = Util::isPortInUse($port);
        if (!$checkUsed || $isPortInUse === false) {
            // bearsampp.conf
            $this->setPort($port);
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            // conf
            $this->update();
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            return true;
        }
        Util::logDebug($this->getName() . ' port in used: ' . $port . ' - ' . $isPortInUse);
        return $isPortInUse;
    }
References $port, Module\getName(), Util\isPortInUse(), Util\isValidPort(), Util\logDebug(), Util\logError(), setPort(), and Module\update().
changeRootPassword ( $currentPwd, $newPwd, $wbProgressBar = null)
Changes the MySQL root password.
Parameters
$currentPwd The current root password.
$newPwd The new root password.
$wbProgressBar The progress bar object for UI updates.
Returns
bool|string True if the password was changed successfully, or an error message if the operation failed.
Definition at line 333 of file class.bin.mysql.php.
    {
        global $bearsamppWinbinder;
        $startTime = microtime(true);
        $error = null;
        $timeout = 5; // 5 seconds timeout
        $bearsamppWinbinder->incrProgressBar($wbProgressBar);
        try {
            // Connect using PDO
            $options = [
                \PDO::ATTR_TIMEOUT => $timeout,
                \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION
            ];
            $dsn = 'mysql:host=127.0.0.1;port=' . $this->port;
            $dbLink = new \PDO($dsn, $this->rootUser, $currentPwd, $options);
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            // Determine MySQL version to use appropriate password update syntax
            $stmt = $dbLink->query('SELECT VERSION()');
            $version = $stmt->fetchColumn();
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            // Use appropriate SQL syntax based on MySQL version
            if (version_compare($version, '5.7.6', '>=')) {
                // MySQL 5.7.6 and newer uses ALTER USER
                $sql = "ALTER USER '{$this->rootUser}'@'localhost' IDENTIFIED BY :password";
                $stmt = $dbLink->prepare($sql);
                $stmt->bindParam(':password', $newPwd);
            } else {
                // Older versions use SET PASSWORD
                $sql = "SET PASSWORD FOR '{$this->rootUser}'@'localhost' = PASSWORD(:password)";
                $stmt = $dbLink->prepare($sql);
                $stmt->bindParam(':password', $newPwd);
            }
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            $stmt->execute();
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            $dbLink->query('FLUSH PRIVILEGES');
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            $dbLink = null; // Close connection properly
        } catch (\PDOException $e) {
            $error = $e->getMessage();
        }
        $bearsamppWinbinder->incrProgressBar($wbProgressBar);
        if (!empty($error)) {
            $totalTime = round(microtime(true) - $startTime, 2);
            Util::logTrace("MySQL password change failed in {$totalTime}s: " . $error);
            return $error;
        }
        // bearsampp.conf
        $bearsamppWinbinder->incrProgressBar($wbProgressBar);
        $this->setRootPwd($newPwd);
        // conf
        $this->update();
        $bearsamppWinbinder->incrProgressBar($wbProgressBar);
        $totalTime = round(microtime(true) - $startTime, 2);
        Util::logTrace("MySQL password change completed in {$totalTime}s");
        return true;
    }
References $port, Module\$version, Util\logTrace(), setRootPwd(), and Module\update().
checkPort ( $port, $showWindow = false)
Checks if the specified port is in use by MySQL.
Parameters
$port The port number to check.
$showWindow Whether to show a message box with the result.
Returns
bool True if the port is in use by MySQL, false otherwise.
Definition at line 223 of file class.bin.mysql.php.
    {
        global $bearsamppLang, $bearsamppWinbinder;
        $boxTitle = sprintf($bearsamppLang->getValue(Lang::CHECK_PORT_TITLE), $this->getName(), $port);
        $startTime = microtime(true);
        if (!Util::isValidPort($port)) {
            Util::logError($this->getName() . ' port not valid: ' . $port);
            return false;
        }
        // Quick socket check first - much faster than PDO connection
        $timeout = 1; // Reduced timeout for better performance
        $fp = @fsockopen('127.0.0.1', $port, $errno, $errstr, $timeout);
        if (!$fp) {
            Util::logDebug($this->getName() . ' port ' . $port . ' is not used');
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::PORT_NOT_USED), $port),
                    $boxTitle
                );
            }
            return false;
        }
        fclose($fp);
        // Use cached connection if available for better performance
        static $cachedConnection = null;
        static $lastPort = null;
        if ($cachedConnection === null || $lastPort !== $port) {
            try {
                $options = [
                    \PDO::ATTR_TIMEOUT => $timeout,
                    \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
                    \PDO::MYSQL_ATTR_INIT_COMMAND => "SET SESSION sql_mode=''"
                ];
                $dsn = 'mysql:host=127.0.0.1;port=' . $port;
                $cachedConnection = new \PDO($dsn, $this->rootUser, $this->rootPwd, $options);
                $lastPort = $port;
            } catch (\PDOException $e) {
                Util::logDebug($this->getName() . ' port ' . $port . ' connection failed: ' . $e->getMessage());
                if ($showWindow) {
                    $bearsamppWinbinder->messageBoxWarning(
                        sprintf($bearsamppLang->getValue(Lang::PORT_NOT_USED_BY), $port),
                        $boxTitle
                    );
                }
                return false;
            }
        }
        try {
            // Single optimized query to get both version and type
            $stmt = $cachedConnection->query("SELECT @@version, @@version_comment");
            $row = $stmt->fetch(\PDO::FETCH_NUM);
            if (!$row) {
                return false;
            }
            $version = explode('-', $row[0]);
            $version = count($version) > 1 ? $version[0] : $row[0];
            $isMysql = Util::startWith(strtolower($row[1]), 'mysql');
            if (!$isMysql) {
                Util::logDebug($this->getName() . ' port used by another DBMS: ' . $port);
                if ($showWindow) {
                    $bearsamppWinbinder->messageBoxWarning(
                        sprintf($bearsamppLang->getValue(Lang::PORT_USED_BY_ANOTHER_DBMS), $port),
                        $boxTitle
                    );
                }
                return false;
            }
            Util::logDebug($this->getName() . ' port ' . $port . ' is used by: ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxInfo(
                    sprintf($bearsamppLang->getValue(Lang::PORT_USED_BY), $port, $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            $totalTime = round(microtime(true) - $startTime, 2);
            Util::logTrace("MySQL port check completed in {$totalTime}s");
            return true;
        } catch (\PDOException $e) {
            Util::logDebug($this->getName() . ' port ' . $port . ' validation error: ' . $e->getMessage());
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxWarning(
                    sprintf($bearsamppLang->getValue(Lang::PORT_NOT_USED_BY), $port),
                    $boxTitle
                );
            }
            return false;
        }
    }
References $bearsamppLang, $port, Module\$version, Lang\CHECK_PORT_TITLE, Module\getName(), Util\isValidPort(), Util\logDebug(), Util\logError(), Util\logTrace(), Lang\PORT_NOT_USED, Lang\PORT_NOT_USED_BY, Lang\PORT_USED_BY, Lang\PORT_USED_BY_ANOTHER_DBMS, and Util\startWith().
checkRootPassword ( $currentPwd = null, $wbProgressBar = null)
Checks if the provided root password is correct.
Parameters
$currentPwd The current root password. If null, the stored root password is used.
$wbProgressBar The progress bar object for UI updates.
Returns
bool|string True if the password is correct, or an error message if the operation failed.
Definition at line 417 of file class.bin.mysql.php.
    {
        global $bearsamppWinbinder;
        $startTime = microtime(true);
        $currentPwd = $currentPwd == null ? $this->rootPwd : $currentPwd;
        $error = null;
        $timeout = 2; // Reduced timeout for faster validation
        $bearsamppWinbinder->incrProgressBar($wbProgressBar);
        // Use cached connection for password validation if available
        static $passwordCache = [];
        $cacheKey = md5($this->rootUser . ':' . $currentPwd . ':' . $this->port);
        if (isset($passwordCache[$cacheKey]) && (time() - $passwordCache[$cacheKey]['time']) < 30) {
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            $totalTime = round(microtime(true) - $startTime, 2);
            Util::logTrace("MySQL password check completed from cache in {$totalTime}s");
            return $passwordCache[$cacheKey]['result'];
        }
        try {
            $options = [
                \PDO::ATTR_TIMEOUT => $timeout,
                \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
                \PDO::MYSQL_ATTR_INIT_COMMAND => "SET SESSION sql_mode=''"
            ];
            $dsn = 'mysql:host=127.0.0.1;port=' . $this->port;
            $dbLink = new \PDO($dsn, $this->rootUser, $currentPwd, $options);
            // Quick validation query
            $dbLink->query('SELECT 1');
            $dbLink = null; // Close connection properly
            // Cache successful result
            $passwordCache[$cacheKey] = [
                'result' => true,
                'time' => time()
            ];
        } catch (\PDOException $e) {
            $error = $e->getMessage();
            // Cache failed result for shorter time
            $passwordCache[$cacheKey] = [
                'result' => $error,
                'time' => time() - 25 // Cache for only 5 seconds
            ];
        }
        $bearsamppWinbinder->incrProgressBar($wbProgressBar);
        if (!empty($error)) {
            $totalTime = round(microtime(true) - $startTime, 2);
            Util::logTrace("MySQL password check failed in {$totalTime}s: " . $error);
            return $error;
        }
        $totalTime = round(microtime(true) - $startTime, 2);
        Util::logTrace("MySQL password check completed in {$totalTime}s");
        return true;
    }
References $port, and Util\logTrace().
getAdmin ()
Retrieves the path to the MySQL admin executable.
Returns
string The path to the admin executable.
Definition at line 865 of file class.bin.mysql.php.
    {
        return $this->admin;
    }
References $admin.
Referenced by getCmdLineOutput().
getCliExe ()
Retrieves the path to the MySQL CLI executable.
Returns
string The path to the CLI executable.
Definition at line 855 of file class.bin.mysql.php.
    {
        return $this->cliExe;
    }
References $cliExe.
getCmdLineOutput ( $cmd)
Executes a MySQL command and retrieves the output.
Parameters
$cmd The command to execute.
Returns
array An associative array containing 'syntaxOk' (boolean) and 'content' (string|null).
Definition at line 669 of file class.bin.mysql.php.
    {
        $result = array(
            'syntaxOk' => false,
            'content' => null,
        );
        $bin = $this->getExe();
        $removeLines = 0;
        $outputFrom = '';
        if ($cmd == self::CMD_SYNTAX_CHECK) {
            $outputFrom = '2';
        } elseif ($cmd == self::CMD_VARIABLES) {
            $bin = $this->getAdmin();
            $cmd .= ' --user=' . $this->getRootUser();
            if ($this->getRootPwd()) {
                $cmd .= ' --password=' . $this->getRootPwd();
            }
            $removeLines = 2;
        }
        if (file_exists($bin)) {
            $tmpResult = Batch::exec('mysqlGetCmdLineOutput', '"' . $bin . '" ' . $cmd . ' ' . $outputFrom, 5);
            if ($tmpResult !== false && is_array($tmpResult)) {
                $result['syntaxOk'] = empty($tmpResult) || !Util::contains(trim($tmpResult[count($tmpResult) - 1]), '[ERROR]');
                for ($i = 0; $i < $removeLines; $i++) {
                    unset($tmpResult[$i]);
                }
                $result['content'] = trim(str_replace($bin, '', implode(PHP_EOL, $tmpResult)));
            }
        }
        return $result;
    }
References $result, Util\contains(), Batch\exec(), getAdmin(), getExe(), getRootPwd(), and getRootUser().
getConf ()
Retrieves the path to the MySQL configuration file.
Returns
string The path to the configuration file.
Definition at line 785 of file class.bin.mysql.php.
    {
        return $this->conf;
    }
References $conf.
Referenced by updateConfig().
getDataDir ()
Retrieves the path to the MySQL data directory.
Returns
string The path to the data directory.
Definition at line 875 of file class.bin.mysql.php.
    {
        return $this->dataDir;
    }
References $dataDir.
getErrorLog ()
Retrieves the path to the MySQL error log.
Returns
string The path to the error log.
Definition at line 765 of file class.bin.mysql.php.
    {
        return $this->errorLog;
    }
References $errorLog.
getExe ()
Retrieves the path to the MySQL executable.
Returns
string The path to the MySQL executable.
Definition at line 775 of file class.bin.mysql.php.
    {
        return $this->exe;
    }
References $exe.
Referenced by getCmdLineOutput().
getPort ()
Retrieves the MySQL port number.
Returns
int The port number.
Definition at line 795 of file class.bin.mysql.php.
    {
        return $this->port;
    }
References $port.
getRootPwd ()
Retrieves the MySQL root password.
Returns
string The root password.
Definition at line 835 of file class.bin.mysql.php.
    {
        return $this->rootPwd;
    }
References $rootPwd.
Referenced by getCmdLineOutput().
getRootUser ()
Retrieves the MySQL root username.
Returns
string The root username.
Definition at line 815 of file class.bin.mysql.php.
    {
        return $this->rootUser;
    }
References $rootUser.
Referenced by getCmdLineOutput().
getService ()
Retrieves the MySQL service object.
Returns
Win32Service The MySQL service object.
Definition at line 722 of file class.bin.mysql.php.
    {
        return $this->service;
    }
References $service.
initData ( $path = null, $version = null)
Initializes the MySQL data directory if needed. Triggers reinitialization when the directory exists but is incomplete (e.g., missing performance_schema).
Parameters
$path The path to the MySQL installation. If null, the current path is used.
$version The version of MySQL. If null, the current version is used.
Returns
bool True if initialization was successful or not needed
Definition at line 577 of file class.bin.mysql.php.
    {
        Util::logTrace('Starting MySQL data initialization');
        $startTime = microtime(true);
        $path = $path != null ? $path : $this->getCurrentPath();
        $version = $version != null ? $version : $this->getVersion();
        $dataDir = $path . '/data';
        $perfSchemaDir = $dataDir . '/performance_schema';
        if (version_compare($version, '5.7.0', '<')) {
            Util::logTrace('MySQL version below 5.7.0, skipping initialization');
            return true;
        }
        $needsInit = false;
        if (!is_dir($dataDir)) {
            Util::logTrace('MySQL data directory does not exist; initialization required');
            $needsInit = true;
        } else {
            if (!is_dir($perfSchemaDir)) {
                Util::logTrace('performance_schema directory missing; reinitialization required');
                $needsInit = true;
            }
        }
        if (!$needsInit) {
            Util::logTrace('MySQL data directory already initialized');
            return true;
        }
        // Prepare a clean data directory (mysqld --initialize-insecure requires an empty/nonexistent directory)
        if (is_dir($dataDir)) {
            $backupDir = $dataDir . '_bak_' . date('Ymd_His');
            if (@rename($dataDir, $backupDir)) {
                Util::logTrace('Backed up existing data directory to: ' . $backupDir);
            } else {
                Util::logTrace('Failed to backup existing data directory; attempting to clear it');
                try {
                    $it = new \RecursiveDirectoryIterator($dataDir, \FilesystemIterator::SKIP_DOTS);
                    $files = new \RecursiveIteratorIterator($it, \RecursiveIteratorIterator::CHILD_FIRST);
                    foreach ($files as $file) {
                        if ($file->isDir()) {
                            @rmdir($file->getPathname());
                        } else {
                            @unlink($file->getPathname());
                        }
                    }
                    @rmdir($dataDir);
                } catch (\Throwable $t) {
                    Util::logTrace('Error clearing data directory: ' . $t->getMessage());
                }
            }
        }
        if (!is_dir($dataDir)) {
            @mkdir($dataDir, 0777, true);
            Util::logTrace('Created clean MySQL data directory');
        }
        // Use Bearsampp built-in initialization (init.bat via Batch)
        try {
            Batch::initializeMysql($path);
        } catch (\Throwable $e) {
            Util::logTrace('Error during MySQL initialization via Batch: ' . $e->getMessage());
            return false;
        }
        // Verify initialization by checking performance_schema existence
        if (!is_dir($perfSchemaDir)) {
            Util::logTrace('MySQL initialization appears to have failed: performance_schema still missing');
            return false;
        }
        $totalTime = round(microtime(true) - $startTime, 2);
        Util::logTrace("MySQL initialization completed in {$totalTime}s");
        return true;
    }
References $dataDir, Module\$version, Module\getCurrentPath(), Module\getVersion(), Batch\initializeMysql(), and Util\logTrace().
Referenced by updateConfig().
reload ( $id = null, $type = null)
Reloads the MySQL module configuration based on the provided ID and type.
Parameters
$id The ID of the module. If null, the current ID is used.
$type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 65 of file class.bin.mysql.php.
    {
        global $bearsamppRoot, $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::MYSQL);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        $this->enable = $this->enable && $bearsamppConfig->getRaw(self::ROOT_CFG_ENABLE);
        $this->service = new Win32Service(self::SERVICE_NAME);
        $this->errorLog = $bearsamppRoot->getLogsPath() . '/mysql.log';
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->conf = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CONF];
            $this->port = $this->bearsamppConfRaw[self::LOCAL_CFG_PORT];
            $this->rootUser = isset($this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_USER]) ? $this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_USER] : 'root';
            $this->rootPwd = isset($this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_PWD]) ? $this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_PWD] : '';
            $this->cliExe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CLI_EXE];
            $this->admin = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_ADMIN];
            $this->dataDir = $this->symlinkPath . '/data';
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
            return;
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
            return;
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
            return;
        }
        if (!is_file($this->conf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->conf));
            return;
        }
        if (!is_numeric($this->port) || $this->port <= 0) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_INVALID_PARAMETER), self::LOCAL_CFG_PORT, $this->port));
            return;
        }
        if (empty($this->rootUser)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_INVALID_PARAMETER), self::LOCAL_CFG_ROOT_USER, $this->rootUser));
            return;
        }
        if (!is_file($this->cliExe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->cliExe));
            return;
        }
        if (!is_file($this->admin)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->admin));
            return;
        }
        $this->service->setDisplayName(APP_TITLE . ' ' . $this->getName());
        $this->service->setBinPath($this->exe);
        $this->service->setParams(self::SERVICE_NAME);
        $this->service->setStartType(Win32Service::SERVICE_DEMAND_START);
        $this->service->setErrorControl(Win32Service::SERVER_ERROR_NORMAL);
    }
References $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, Module\$type, APP_TITLE, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\ERROR_INVALID_PARAMETER, Module\getName(), Util\logError(), Util\logInfo(), Util\logReloadClass(), Lang\MYSQL, Win32Service\SERVER_ERROR_NORMAL, and Win32Service\SERVICE_DEMAND_START.
Referenced by __construct(), setEnable(), and setVersion().
replaceAll ( $params) [protected]
Replaces multiple key-value pairs in the configuration file.
Parameters
$params An associative array of key-value pairs to replace.
Reimplemented from Module.
Definition at line 152 of file class.bin.mysql.php.
    {
        $content = file_get_contents($this->bearsamppConf);
        foreach ($params as $key => $value) {
            $content = preg_replace('|' . $key . ' = .*|', $key . ' = ' . '"' . $value . '"', $content);
            $this->bearsamppConfRaw[$key] = $value;
            switch ($key) {
                case self::LOCAL_CFG_PORT:
                    $this->port = $value;
                    break;
                case self::LOCAL_CFG_ROOT_USER:
                    $this->rootUser = $value;
                    break;
                case self::LOCAL_CFG_ROOT_PWD:
                    $this->rootPwd = $value;
                    break;
            }
        }
        file_put_contents($this->bearsamppConf, $content);
    }
setEnable ( $enabled, $showWindow = false)
Enables or disables the MySQL module and updates the configuration.
Parameters
$enabled Whether to enable or disable the module.
$showWindow Whether to show a message box with the result.
Definition at line 733 of file class.bin.mysql.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppWinbinder;
        if ($enabled == Config::ENABLED && !is_dir($this->currentPath)) {
            Util::logDebug($this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::ENABLE_BUNDLE_NOT_EXIST), $this->getName(), $this->getVersion(), $this->currentPath),
                    sprintf($bearsamppLang->getValue(Lang::ENABLE_TITLE), $this->getName())
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo($this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled'));
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace(self::ROOT_CFG_ENABLE, $enabled);
        $this->reload();
        if ($this->enable) {
            Util::installService($this, $this->port, self::CMD_SYNTAX_CHECK, $showWindow);
        } else {
            Util::removeService($this->service, $this->name);
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\installService(), Util\logDebug(), Util\logInfo(), reload(), and Util\removeService().
setPort ( $port)
Sets the MySQL port number and updates the configuration.
Parameters
$port The port number to set.
Definition at line 805 of file class.bin.mysql.php.
    {
        $this->replace(self::LOCAL_CFG_PORT, $port);
    }
References $port, and Module\replace().
Referenced by changePort().
setRootPwd ( $rootPwd)
Sets the MySQL root password and updates the configuration.
Parameters
$rootPwd The root password to set.
Definition at line 845 of file class.bin.mysql.php.
    {
        $this->replace(self::LOCAL_CFG_ROOT_PWD, $rootPwd);
    }
References $rootPwd, and Module\replace().
Referenced by changeRootPassword().
setRootUser ( $rootUser)
Sets the MySQL root username and updates the configuration.
Parameters
$rootUser The root username to set.
Definition at line 825 of file class.bin.mysql.php.
    {
        $this->replace(self::LOCAL_CFG_ROOT_USER, $rootUser);
    }
References $rootUser, and Module\replace().
setVersion ( $version)
Sets the MySQL version and reloads the configuration.
Parameters
$version The version to set.
Reimplemented from Module.
Definition at line 709 of file class.bin.mysql.php.
    {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Referenced by updateConfig().
switchVersion ( $version, $showWindow = false)
Switches the MySQL version and updates the configuration.
Parameters
$version The new MySQL version.
$showWindow Whether to show a message box with the result.
Returns
bool True if the version was switched successfully, false otherwise.
Definition at line 489 of file class.bin.mysql.php.
    {
        Util::logDebug('Switch ' . $this->name . ' version to ' . $version);
        return $this->updateConfig($version, 0, $showWindow);
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig ( $version = null, $sub = 0, $showWindow = false) [protected]
Updates the MySQL configuration with a specific version.
Parameters
$version The version to update to. If null, the current version is used.
$sub The sub-level for logging indentation.
$showWindow Whether to show a message box with the result.
Returns
bool True if the configuration was updated successfully, false otherwise.
Reimplemented from Module.
Definition at line 505 of file class.bin.mysql.php.
    {
        global $bearsamppLang, $bearsamppBins, $bearsamppApps, $bearsamppWinbinder;
        if (!$this->enable) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'Update ' . $this->name . ' ' . $version . ' config');
        $boxTitle = sprintf($bearsamppLang->getValue(Lang::SWITCH_VERSION_TITLE), $this->getName(), $version);
        $currentPath = str_replace('mysql' . $this->getVersion(), 'mysql' . $version, $this->getCurrentPath());
        $conf = str_replace('mysql' . $this->getVersion(), 'mysql' . $version, $this->getConf());
        $bearsamppConf = str_replace('mysql' . $this->getVersion(), 'mysql' . $version, $this->bearsamppConf);
        if ($this->version != $version) {
            $this->initData($currentPath, $version);
        }
        if (!file_exists($conf) || !file_exists($bearsamppConf)) {
            Util::logError('bearsampp config files not found for ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR), $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file($bearsamppConf);
        if ($bearsamppConfRaw === false || !isset($bearsamppConfRaw[self::ROOT_CFG_VERSION]) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version) {
            Util::logError('bearsampp config file malformed for ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::BEARSAMPP_CONF_MALFORMED_ERROR), $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            return false;
        }
        // bearsampp.conf
        $this->setVersion($version);
        // conf
        Util::replaceInFile($this->getConf(), array(
            '/^port(.*?)=(.*?)(\d+)/' => 'port = ' . $this->port
        ));
        // phpmyadmin
        $bearsamppApps->getPhpmyadmin()->update($sub + 1);
        // php
        $bearsamppBins->getPhp()->update($sub + 1);
        return true;
    }
References $bearsamppBins, Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, $conf, Module\$currentPath, Module\$version, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, getConf(), Module\getCurrentPath(), Module\getName(), Module\getVersion(), initData(), Util\logDebug(), Util\logError(), Util\replaceInFile(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$admin [private]
Definition at line 44 of file class.bin.mysql.php.
Referenced by getAdmin().
$cliExe [private]
Definition at line 43 of file class.bin.mysql.php.
Referenced by getCliExe().
$conf [private]
Definition at line 39 of file class.bin.mysql.php.
Referenced by getConf(), and updateConfig().
$dataDir [private]
Definition at line 45 of file class.bin.mysql.php.
Referenced by getDataDir(), and initData().
$errorLog [private]
Definition at line 36 of file class.bin.mysql.php.
Referenced by getErrorLog().
$exe [private]
Definition at line 38 of file class.bin.mysql.php.
Referenced by getExe().
$port [private]
Definition at line 40 of file class.bin.mysql.php.
Referenced by changePort(), changeRootPassword(), checkPort(), checkRootPassword(), getPort(), and setPort().
$rootPwd [private]
Definition at line 42 of file class.bin.mysql.php.
Referenced by getRootPwd(), and setRootPwd().
$rootUser [private]
Definition at line 41 of file class.bin.mysql.php.
Referenced by getRootUser(), and setRootUser().
$service [private]
Definition at line 35 of file class.bin.mysql.php.
Referenced by getService().
const CMD_SYNTAX_CHECK = '--help --verbose 1>NUL'
Definition at line 33 of file class.bin.mysql.php.
Referenced by ActionDebugMysql\__construct(), ActionService\__construct(), TplAppMysql\getMenuMysqlDebug(), ActionStartup\installServices(), and Win32Service\start().
const CMD_VARIABLES = 'variables'
Definition at line 32 of file class.bin.mysql.php.
Referenced by ActionDebugMysql\__construct(), and TplAppMysql\getMenuMysqlDebug().
const CMD_VERSION = '--version'
Definition at line 31 of file class.bin.mysql.php.
Referenced by ActionDebugMysql\__construct(), and TplAppMysql\getMenuMysqlDebug().
const LOCAL_CFG_ADMIN = 'mysqlAdmin'
Definition at line 25 of file class.bin.mysql.php.
const LOCAL_CFG_CLI_EXE = 'mysqlCliExe'
Definition at line 24 of file class.bin.mysql.php.
const LOCAL_CFG_CONF = 'mysqlConf'
Definition at line 26 of file class.bin.mysql.php.
const LOCAL_CFG_EXE = 'mysqlExe'
Definition at line 23 of file class.bin.mysql.php.
const LOCAL_CFG_PORT = 'mysqlPort'
Definition at line 27 of file class.bin.mysql.php.
const LOCAL_CFG_ROOT_PWD = 'mysqlRootPwd'
Definition at line 29 of file class.bin.mysql.php.
const LOCAL_CFG_ROOT_USER = 'mysqlRootUser'
Definition at line 28 of file class.bin.mysql.php.
const ROOT_CFG_ENABLE = 'mysqlEnable'
Definition at line 20 of file class.bin.mysql.php.
const ROOT_CFG_VERSION = 'mysqlVersion'
Definition at line 21 of file class.bin.mysql.php.
const SERVICE_NAME = 'bearsamppmysql'
Definition at line 18 of file class.bin.mysql.php.
Referenced by ActionService\__construct(), TplAppMysql\getActionInstallMysqlService(), TplAppMysql\getActionRemoveMysqlService(), Bins\getServices(), ActionStartup\installServices(), ActionQuit\processWindow(), and Win32Service\start().
Author
Generated automatically by Doxygen for Bearsampp from the source code.