BinNodejs
NAME
BinNodejs
SYNOPSIS
Inherits Module.
Public Member Functions
__construct ($id, $type)
getConf ()
getExe ()
getLaunch ()
getNpm ()
getVars ()
reload ($id=null, $type=null)
setEnable ($enabled, $showWindow=false)
setVersion ($version)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_CONF = 'nodejsConf'
const LOCAL_CFG_EXE = 'nodejsExe'
const LOCAL_CFG_LAUNCH = 'nodejsLaunch'
const LOCAL_CFG_NPM = 'nodejsNpm'
const LOCAL_CFG_VARS = 'nodejsVars'
const ROOT_CFG_ENABLE = 'nodejsEnable'
const ROOT_CFG_VERSION = 'nodejsVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
Private Attributes
$conf
$exe
$launch
$npm
$vars
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinNodejs
The BinNodejs class extends the Module class and provides functionalities specific to managing the Node.js module within the Bearsampp application. It includes methods for reloading the module configuration, switching versions, enabling/disabling the module, and retrieving various configuration paths such as the executable, configuration file, variables file, npm executable, and launch script.
Constants:
ROOT_CFG_ENABLE: Configuration key for enabling the Node.js module.
ROOT_CFG_VERSION: Configuration key for the Node.js version.
LOCAL_CFG_EXE: Configuration key for the Node.js executable.
LOCAL_CFG_VARS: Configuration key for the Node.js variables.
LOCAL_CFG_NPM: Configuration key for the npm executable.
LOCAL_CFG_LAUNCH: Configuration key for the Node.js launch script.
LOCAL_CFG_CONF: Configuration key for the Node.js configuration file.
Properties:
exe: Path to the Node.js executable.
conf: Path to the Node.js configuration file.
vars: Path to the Node.js variables file.
npm: Path to the npm executable.
launch: Path to the Node.js launch script.
Methods:
__construct($id, $type): Constructs a BinNodejs object and initializes the module with the given ID and type.
reload($id = null, $type = null): Reloads the module configuration based on the provided ID and type.
switchVersion($version, $showWindow = false): Switches the Node.js version to the specified version.
updateConfig($version = null, $sub = 0, $showWindow = false): Updates the module configuration with a specific version.
setVersion($version): Sets the version of the module.
setEnable($enabled, $showWindow = false): Enables or disables the module.
getExe(): Retrieves the executable path for Node.js.
getConf(): Retrieves the configuration file path for Node.js.
getVars(): Retrieves the variables file path for Node.js.
getNpm(): Retrieves the npm executable path for Node.js.
getLaunch(): Retrieves the launch script path for Node.js.
Definition at line 48 of file class.bin.nodejs.php.
Constructor & Destructor Documentation
__construct ( $id, $type)
Constructs a BinNodejs object and initializes the module with the given ID and type.
Parameters
$id The ID of the module.
$type The type of the module.
Definition at line 71 of file class.bin.nodejs.php.
                                            {
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getConf ()
Retrieves the configuration file path for Node.js.
Returns
string The configuration file path.
Definition at line 248 of file class.bin.nodejs.php.
                              {
        return $this->conf;
    }
References $conf.
Referenced by updateConfig().
getExe ()
Retrieves the executable path for Node.js.
Returns
string The executable path.
Definition at line 239 of file class.bin.nodejs.php.
                             {
        return $this->exe;
    }
References $exe.
getLaunch ()
Retrieves the launch script path for Node.js.
Returns
string The launch script path.
Definition at line 275 of file class.bin.nodejs.php.
                                {
        return $this->launch;
    }
References $launch.
getNpm ()
Retrieves the npm executable path for Node.js.
Returns
string The npm executable path.
Definition at line 266 of file class.bin.nodejs.php.
                             {
        return $this->npm;
    }
References $npm.
getVars ()
Retrieves the variables file path for Node.js.
Returns
string The variables file path.
Definition at line 257 of file class.bin.nodejs.php.
                              {
        return $this->vars;
    }
References $vars.
reload ( $id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
$id The ID of the module. If null, the current ID is used.
$type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 82 of file class.bin.nodejs.php.
                                                     {
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::NODEJS);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        $this->enable = $this->enable && $bearsamppConfig->getRaw(self::ROOT_CFG_ENABLE);
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->conf = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CONF];
            $this->vars = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_VARS];
            $this->npm = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_NPM];
            $this->launch = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_LAUNCH];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
            return;
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
            return;
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
        }
        if (!is_file($this->conf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->conf));
        }
        if (!is_file($this->vars)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->vars));
        }
        if (!is_file($this->npm)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->npm));
        }
        if (!is_file($this->launch)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->launch));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Util\logError(), Util\logInfo(), Util\logReloadClass(), and Lang\NODEJS.
Referenced by __construct(), and setVersion().
setEnable ( $enabled, $showWindow = false)
Enables or disables the module.
Parameters
$enabled The enable status (1 for enabled, 0 for disabled).
$showWindow Whether to show a window during the enable/disable process.
Definition at line 215 of file class.bin.nodejs.php.
                                                             {
        global $bearsamppConfig, $bearsamppLang, $bearsamppWinbinder;
        if ($enabled == Config::ENABLED && !is_dir($this->currentPath)) {
            Util::logDebug($this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::ENABLE_BUNDLE_NOT_EXIST), $this->getName(), $this->getVersion(), $this->currentPath),
                    sprintf($bearsamppLang->getValue(Lang::ENABLE_TITLE), $this->getName())
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo($this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled'));
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace(self::ROOT_CFG_ENABLE, $enabled);
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\logDebug(), and Util\logInfo().
setVersion ( $version)
Sets the version of the module.
Parameters
$version The version to set.
Reimplemented from Module.
Definition at line 202 of file class.bin.nodejs.php.
                                         {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Referenced by updateConfig().
switchVersion ( $version, $showWindow = false)
Switches the Node.js version to the specified version.
Parameters
$version The version to switch to.
$showWindow Whether to show a window during the switch process.
Returns
bool True if the switch was successful, false otherwise.
Definition at line 140 of file class.bin.nodejs.php.
                                                                 {
        Util::logDebug('Switch ' . $this->name . ' version to ' . $version);
        return $this->updateConfig($version, 0, $showWindow);
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig ( $version = null, $sub = 0, $showWindow = false) [protected]
Updates the module configuration with a specific version.
Parameters
$version The version to update to. If null, the current version is used.
$sub The sub-level for logging indentation.
$showWindow Whether to show a window during the update process.
Returns
bool True if the update was successful, false otherwise.
Reimplemented from Module.
Definition at line 153 of file class.bin.nodejs.php.
                                                                                    {
        global $bearsamppLang, $bearsamppWinbinder;
        if (!$this->enable) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'Update ' . $this->name . ' ' . $version . ' config');
        $boxTitle = sprintf($bearsamppLang->getValue(Lang::SWITCH_VERSION_TITLE), $this->getName(), $version);
        $conf = str_replace('nodejs' . $this->getVersion(), 'nodejs' . $version, $this->getConf());
        $bearsamppConf = str_replace('nodejs' . $this->getVersion(), 'nodejs' . $version, $this->bearsamppConf);
        if (!file_exists($conf) || !file_exists($bearsamppConf)) {
            Util::logError('bearsampp config files not found for ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR), $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file($bearsamppConf);
        if ($bearsamppConfRaw === false || !isset($bearsamppConfRaw[self::ROOT_CFG_VERSION]) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version) {
            Util::logError('bearsampp config file malformed for ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::BEARSAMPP_CONF_MALFORMED_ERROR), $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            return false;
        }
        // bearsampp.conf
        $this->setVersion($version);
        return true;
    }
References Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, $conf, Module\$version, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, getConf(), Module\getName(), Module\getVersion(), Util\logDebug(), Util\logError(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$conf [private]
Definition at line 60 of file class.bin.nodejs.php.
Referenced by getConf(), and updateConfig().
$exe [private]
Definition at line 59 of file class.bin.nodejs.php.
Referenced by getExe().
$launch [private]
Definition at line 63 of file class.bin.nodejs.php.
Referenced by getLaunch().
$npm [private]
Definition at line 62 of file class.bin.nodejs.php.
Referenced by getNpm().
$vars [private]
Definition at line 61 of file class.bin.nodejs.php.
Referenced by getVars().
const LOCAL_CFG_CONF = 'nodejsConf'
Definition at line 57 of file class.bin.nodejs.php.
const LOCAL_CFG_EXE = 'nodejsExe'
Definition at line 53 of file class.bin.nodejs.php.
const LOCAL_CFG_LAUNCH = 'nodejsLaunch'
Definition at line 56 of file class.bin.nodejs.php.
const LOCAL_CFG_NPM = 'nodejsNpm'
Definition at line 55 of file class.bin.nodejs.php.
const LOCAL_CFG_VARS = 'nodejsVars'
Definition at line 54 of file class.bin.nodejs.php.
const ROOT_CFG_ENABLE = 'nodejsEnable'
Definition at line 50 of file class.bin.nodejs.php.
const ROOT_CFG_VERSION = 'nodejsVersion'
Definition at line 51 of file class.bin.nodejs.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.