BinPhp
NAME
BinPhp
SYNOPSIS
Inherits Module.
Public Member Functions
__construct ($id, $type)
getApacheModule ($apacheVersion, $phpVersion=null)
getCliExe ()
getCliSilentExe ()
getConf ()
getErrorLog ()
getExtensions ()
getExtensionsFromConf ()
getExtensionsFromFolder ()
getExtensionsLoaded ()
getPearExe ()
getPearVersion ($cache=false)
getSettings ()
getSettingsValues ()
getTsDll ($phpVersion=null)
isSettingActive ($name)
isSettingExists ($name)
reload ($id=null, $type=null)
setEnable ($enabled, $showWindow=false)
setVersion ($version)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const INI_ALLOW_CALL_TIME_PASS_REFERENCE = 'allow_call_time_pass_reference'
const INI_ALLOW_URL_FOPEN = 'allow_url_fopen'
const INI_ALLOW_URL_INCLUDE = 'allow_url_include'
const INI_ASP_TAGS = 'asp_tags'
const INI_AUTO_GLOBALS_JIT = 'auto_globals_jit'
const INI_CGI_FIX_PATHINFO = 'cgi.fix_pathinfo'
const INI_CGI_FORCE_REDIRECT = 'cgi.force_redirect'
const INI_DEFINE_SYSLOG_VARIABLES = 'define_syslog_variables'
const INI_DISPLAY_ERRORS = 'display_errors'
const INI_DISPLAY_STARTUP_ERRORS = 'display_startup_errors'
const INI_ENABLE_DL = 'enable_dl'
const INI_EXPOSE_PHP = 'expose_php'
const INI_FILE_UPLOADS = 'file_uploads'
const INI_HTML_ERRORS = 'html_errors'
const INI_IGNORE_REPEATED_ERRORS = 'ignore_repeated_errors'
const INI_IGNORE_REPEATED_SOURCE = 'ignore_repeated_source'
const INI_IMPLICIT_FLUSH = 'implicit_flush'
const INI_LOG_ERRORS = 'log_errors'
const INI_MAGIC_QUOTES_GPC = 'magic_quotes_gpc'
const INI_MAGIC_QUOTES_RUNTIME = 'magic_quotes_runtime'
const INI_MAGIC_QUOTES_SYBASE = 'magic_quotes_sybase'
const INI_MAIL_ADD_X_HEADER = 'mail.add_x_header'
const INI_MSSQL_ALLOW_PERSISTENT = 'mssql.allow_persistent'
const INI_MSSQL_COMPATIBILITY_MODE = 'mssql.compatability_mode'
const INI_MSSQL_SECURE_CONNECTION = 'mssql.secure_connection'
const INI_MYSQL_ALLOW_LOCAL_INFILE = 'mysql.allow_local_infile'
const INI_MYSQL_ALLOW_PERSISTENT = 'mysql.allow_persistent'
const INI_MYSQL_TRACE_MODE = 'mysql.trace_mode'
const INI_MYSQLI_ALLOW_PERSISTENT = 'mysqli.allow_persistent'
const INI_MYSQLI_RECONNECT = 'mysqli.reconnect'
const INI_MYSQLND_COLLECT_MEMORY_STATISTICS = 'mysqlnd.collect_memory_statistics'
const INI_MYSQLND_COLLECT_STATISTICS = 'mysqlnd.collect_statistics'
const INI_ODBC_ALLOW_PERSISTENT = 'odbc.allow_persistent'
const INI_ODBC_CHECK_PERSISTENT = 'odbc.check_persistent'
const INI_OUTPUT_BUFFERING = 'output_buffering'
const INI_PGSQL_ALLOW_PERSISTENT = 'pgsql.allow_persistent'
const INI_PGSQL_AUTO_RESET_PERSISTENT = 'pgsql.auto_reset_persistent'
const INI_PHAR_READONLY = 'phar.readonly'
const INI_PHAR_REQUIRE_HASH = 'phar.require_hash'
const INI_REGISTER_ARGC_ARGV = 'register_argc_argv'
const INI_REGISTER_GLOBALS = 'register_globals'
const INI_REGISTER_LONG_ARRAYS = 'register_long_arrays'
const INI_REPORT_MEMLEAKS = 'report_memleaks'
const INI_SAFE_MODE = 'safe_mode'
const INI_SAFE_MODE_GID = 'safe_mode_gid'
const INI_SESSION_AUTO_START = 'session.auto_start'
const INI_SESSION_BUG_COMPAT_42 = 'session.bug_compat_42'
const INI_SESSION_BUG_COMPAT_WARN = 'session.bug_compat_warn'
const INI_SESSION_COOKIE_HTTPONLY = 'session.cookie_httponly'
const INI_SESSION_USE_COOKIES = 'session.use_cookies'
const INI_SESSION_USE_ONLY_COOKIES = 'session.use_only_cookies'
const INI_SESSION_USE_TRANS_SID = 'session.use_trans_sid'
const INI_SHORT_OPEN_TAG = 'short_open_tag'
const INI_SOAP_WSDL_CACHE_ENABLED = 'soap.wsdl_cache_enabled'
const INI_SQL_SAFE_MODE = 'sql.safe_mode'
const INI_SYBCT_ALLOW_PERSISTENT = 'sybct.allow_persistent'
const INI_TIDY_CLEAN_OUTPUT = 'tidy.clean_output'
const INI_TRACK_ERRORS = 'track_errors'
const INI_XDEBUG_PROFILER_ENABLE = 'xdebug.profiler_enable'
const INI_XDEBUG_PROFILER_ENABLE_TRIGGER = 'xdebug.profiler_enable_trigger'
const INI_XDEBUG_REMOTE_ENABLE = 'xdebug.remote_enable'
const INI_Y2K_COMPLIANCE = 'y2k_compliance'
const INI_ZLIB_OUTPUT_COMPRESSION = 'zlib.output_compression'
const LOCAL_CFG_CLI_EXE = 'phpCliExe'
const LOCAL_CFG_CLI_SILENT_EXE = 'phpCliSilentExe'
const LOCAL_CFG_CONF = 'phpConf'
const LOCAL_CFG_PEAR_EXE = 'phpPearExe'
const ROOT_CFG_ENABLE = 'phpEnable'
const ROOT_CFG_VERSION = 'phpVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
Private Member Functions
isExtensionExcluded ($ext)
Private Attributes
$apacheConf
$cliExe
$cliSilentExe
$conf
$errorLog
$pearExe
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinPhp
This class extends the Module class and provides functionalities specific to managing PHP binaries within the Bearsampp application. It includes methods for reloading configurations, switching versions, updating configurations, and retrieving various PHP settings and extensions.
Definition at line 17 of file class.bin.php.php.
Constructor & Destructor Documentation
__construct ( $id, $type)
Constructor for the BinPhp class.
Parameters
$id The ID of the module.
$type The type of the module.
Definition at line 105 of file class.bin.php.php.
                                            {
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getApacheModule ( $apacheVersion, $phpVersion = null)
Retrieves the path to the Apache module for the specified Apache and PHP versions.
Parameters
$apacheVersion The version of Apache.
$phpVersion The version of PHP. If null, the current PHP version is used.
Returns
string|false The path to the Apache module, or false if not found.
Definition at line 591 of file class.bin.php.php.
                                                                        {
        $apacheVersion = substr(str_replace('.', '', $apacheVersion), 0, 2);
        $phpVersion = $phpVersion == null ? $this->getVersion() : $phpVersion;
        $currentPath = str_replace('php' . $this->getVersion(), 'php' . $phpVersion, $this->getCurrentPath());
        $bearsamppConf = str_replace('php' . $this->getVersion(), 'php' . $phpVersion, $this->bearsamppConf);
        if (in_array($phpVersion, $this->getVersionList()) && file_exists($bearsamppConf)) {
            $apacheCpt = parse_ini_file($bearsamppConf);
            if ($apacheCpt !== false) {
                foreach ($apacheCpt as $aVersion => $apacheModule) {
                    $aVersion = str_replace('apache', '', $aVersion);
                    $aVersion = str_replace('.', '', $aVersion);
                    if ($apacheVersion == $aVersion && file_exists($currentPath . '/' . $apacheModule)) {
                        return $currentPath . '/' . $apacheModule;
                    }
                }
            }
        }
        return false;
    }
References Module\$bearsamppConf, Module\$currentPath, Module\getCurrentPath(), Module\getVersion(), and Module\getVersionList().
Referenced by updateConfig().
getCliExe ()
Retrieves the path to the PHP CLI executable.
Returns
string The path to the PHP CLI executable.
Definition at line 694 of file class.bin.php.php.
                                {
        return $this->cliExe;
    }
References $cliExe.
getCliSilentExe ()
Retrieves the path to the PHP CLI silent executable.
Returns
string The path to the PHP CLI silent executable.
Definition at line 703 of file class.bin.php.php.
                                      {
        return $this->cliSilentExe;
    }
References $cliSilentExe.
getConf ()
Retrieves the path to the PHP configuration file.
Returns
string The path to the PHP configuration file.
Definition at line 712 of file class.bin.php.php.
                              {
        return $this->conf;
    }
References $conf.
Referenced by getExtensionsFromConf(), isSettingActive(), isSettingExists(), and updateConfig().
getErrorLog ()
Retrieves the path to the PHP error log file.
Returns
string The path to the PHP error log file.
Definition at line 685 of file class.bin.php.php.
                                  {
        return $this->errorLog;
    }
References $errorLog.
getExtensions ()
Retrieves the list of PHP extensions from both the configuration file and the extensions folder.
Returns
array An associative array where the key is the extension name and the value is the status (on/off).
Definition at line 492 of file class.bin.php.php.
                                    {
        $fromFolder = $this->getExtensionsFromConf();
        $fromConf = $this->getExtensionsFromFolder();
        $result = array_merge($fromConf, $fromFolder);
        ksort($result);
        return $result;
    }
References $result, getExtensionsFromConf(), and getExtensionsFromFolder().
getExtensionsFromConf ()
Retrieves the list of PHP extensions from the configuration file.
Returns
array An associative array where the key is the extension name and the value is the status (on/off).
Definition at line 518 of file class.bin.php.php.
                                            {
        $result = array();
        $confContent = file($this->getConf());
        foreach ($confContent as $row) {
            $extMatch = array();
            if (preg_match('/^(;)?extension\s*=\s*"?(.+)"?/i', $row, $extMatch)) {
                $name = preg_replace("/^php_/", "", preg_replace("/\.dll$/", "", trim($extMatch[2])));
                if ($this->isExtensionExcluded($name)) {
                    continue;
                }
                if ($extMatch[1] == ';') {
                    $result[$name] = ActionSwitchPhpExtension::SWITCH_OFF;
                } else {
                    $result[$name] = ActionSwitchPhpExtension::SWITCH_ON;
                }
            }
        }
        ksort($result);
        return $result;
    }
References Module\$name, $result, getConf(), isExtensionExcluded(), ActionSwitchPhpExtension\SWITCH_OFF, and ActionSwitchPhpExtension\SWITCH_ON.
Referenced by getExtensions(), and getExtensionsLoaded().
getExtensionsFromFolder ()
Retrieves the list of PHP extensions from the extensions folder.
Returns
array An associative array where the key is the extension name and the value is the status (off).
Definition at line 561 of file class.bin.php.php.
                                              {
        $result = array();
        $handle = @opendir($this->getCurrentPath(). '/ext');
        if (!$handle) {
            return $result;
        }
        while (false !== ($file = readdir($handle))) {
            if ($file != "." && $file != ".." && Util::endWith($file, '.dll')) {
                $name = preg_replace("/^php_/", "", preg_replace("/\.dll$/", "", trim($file)));
                if ($this->isExtensionExcluded($name)) {
                    continue;
                }
                $result[$name] = ActionSwitchPhpExtension::SWITCH_OFF;
            }
        }
        closedir($handle);
        ksort($result);
        return $result;
    }
References Module\$name, $result, Util\endWith(), Module\getCurrentPath(), isExtensionExcluded(), and ActionSwitchPhpExtension\SWITCH_OFF.
Referenced by getExtensions().
getExtensionsLoaded ()
Retrieves the list of currently loaded PHP extensions.
Returns
array An array of extension names that are currently loaded.
Definition at line 546 of file class.bin.php.php.
                                          {
        $result = array();
        foreach ($this->getExtensionsFromConf() as $name => $status) {
            if ($status == ActionSwitchPhpExtension::SWITCH_ON) {
                $result[] = $name;
            }
        }
        return $result;
    }
References Module\$name, $result, getExtensionsFromConf(), and ActionSwitchPhpExtension\SWITCH_ON.
getPearExe ()
Retrieves the path to the PHP PEAR executable.
Returns
string The path to the PHP PEAR executable.
Definition at line 721 of file class.bin.php.php.
                                 {
        return $this->pearExe;
    }
References $pearExe.
getPearVersion ( $cache = false)
Retrieves the version of PEAR.
Parameters
$cache Whether to use the cached version.
Returns
string|null The PEAR version, or null if not found.
Definition at line 731 of file class.bin.php.php.
                                                   {
        $cacheFile = $this->getCurrentPath() . '/pear/version';
        if (!$cache) {
            file_put_contents($cacheFile, Batch::getPearVersion());
        }
        return file_exists($cacheFile) ? file_get_contents($cacheFile) : null;
    }}
References Module\getCurrentPath(), and Batch\getPearVersion().
getSettings ()
Retrieves the PHP settings.
Returns
array An associative array of PHP settings.
Definition at line 266 of file class.bin.php.php.
                                  {
        return array(
            'Language options' => array(
                'Short open tag' => self::INI_SHORT_OPEN_TAG,
                'ASP-style tags' => self::INI_ASP_TAGS,
                'Year 2000 compliance' => self::INI_Y2K_COMPLIANCE,
                'Output buffering' => self::INI_OUTPUT_BUFFERING,
                'Zlib output compression' => self::INI_ZLIB_OUTPUT_COMPRESSION,
                'Implicit flush' => self::INI_IMPLICIT_FLUSH,
                'Allow call time pass reference' => self::INI_ALLOW_CALL_TIME_PASS_REFERENCE,
                'Safe mode' => self::INI_SAFE_MODE,
                'Safe mode GID' => self::INI_SAFE_MODE_GID,
            ),
            'Miscellaneous' => array(
                'Expose PHP' => self::INI_EXPOSE_PHP,
            ),
            'Error handling and logging' => array(
                'Display errors' => self::INI_DISPLAY_ERRORS,
                'Display startup errors' => self::INI_DISPLAY_STARTUP_ERRORS,
                'Log errors' => self::INI_LOG_ERRORS,
                'Ignore repeated errors' => self::INI_IGNORE_REPEATED_ERRORS,
                'Ignore repeated source' => self::INI_IGNORE_REPEATED_SOURCE,
                'Report memory leaks' => self::INI_REPORT_MEMLEAKS,
                'Track errors' => self::INI_TRACK_ERRORS,
                'HTML errors' => self::INI_HTML_ERRORS,
            ),
            'Data Handling' => array(
                'Register globals' => self::INI_REGISTER_GLOBALS,
                'Register long arrays' => self::INI_REGISTER_LONG_ARRAYS,
                'Register argc argv' => self::INI_REGISTER_ARGC_ARGV,
                'Auto globals just in time' => self::INI_AUTO_GLOBALS_JIT,
                'Magic quotes gpc' => self::INI_MAGIC_QUOTES_GPC,
                'Magic quotes runtime' => self::INI_MAGIC_QUOTES_RUNTIME,
                'Magic quotes Sybase' => self::INI_MAGIC_QUOTES_SYBASE,
            ),
            'Paths and Directories' => array(
                'Enable dynamic loading' => self::INI_ENABLE_DL,
                'CGI force redirect' => self::INI_CGI_FORCE_REDIRECT,
                'CGI fix path info' => self::INI_CGI_FIX_PATHINFO,
            ),
            'File uploads' => array(
                'File uploads' => self::INI_FILE_UPLOADS,
            ),
            'Fopen wrappers' => array(
                'Allow url fopen' => self::INI_ALLOW_URL_FOPEN,
                'Allow url include' => self::INI_ALLOW_URL_INCLUDE,
            ),
            'Module settings' => array(
                'Phar' => array(
                    'Read only' => self::INI_PHAR_READONLY,
                    'Require hash' => self::INI_PHAR_REQUIRE_HASH,
                ),
                'Syslog' => array(
                    'Define syslog variables' => self::INI_DEFINE_SYSLOG_VARIABLES,
                ),
                'Mail' => array(
                    'Add X-PHP-Originating-Script' => self::INI_MAIL_ADD_X_HEADER,
                ),
                'SQL' => array(
                    'Safe mode' => self::INI_SQL_SAFE_MODE,
                ),
                'ODBC' => array(
                    'Allow persistent' => self::INI_ODBC_ALLOW_PERSISTENT,
                    'Check persistent' => self::INI_ODBC_CHECK_PERSISTENT,
                ),
                'MySQL' => array(
                    'Allow local infile' => self::INI_MYSQL_ALLOW_LOCAL_INFILE,
                    'Allow persistent' => self::INI_MYSQL_ALLOW_PERSISTENT,
                    'Trace mode' => self::INI_MYSQL_TRACE_MODE,
                ),
                'MySQLi' => array(
                    'Allow persistent' => self::INI_MYSQLI_ALLOW_PERSISTENT,
                    'Reconnect' => self::INI_MYSQLI_RECONNECT,
                ),
                'MySQL Native Driver' => array(
                    'Collect statistics' => self::INI_MYSQLND_COLLECT_STATISTICS,
                    'Collect memory statistics' => self::INI_MYSQLND_COLLECT_MEMORY_STATISTICS,
                ),
                'PostgresSQL' => array(
                    'Allow persistent' => self::INI_PGSQL_ALLOW_PERSISTENT,
                    'Auto reset persistent' => self::INI_PGSQL_AUTO_RESET_PERSISTENT,
                ),
                'Sybase-CT' => array(
                    'Allow persistent' => self::INI_SYBCT_ALLOW_PERSISTENT,
                ),
                'Session' => array(
                    'Use cookies' => self::INI_SESSION_USE_COOKIES,
                    'Use only cookies' => self::INI_SESSION_USE_ONLY_COOKIES,
                    'Auto start' => self::INI_SESSION_AUTO_START,
                    'Cookie HTTP only' => self::INI_SESSION_COOKIE_HTTPONLY,
                    'Bug compat 42' => self::INI_SESSION_BUG_COMPAT_42,
                    'Bug compat warning' => self::INI_SESSION_BUG_COMPAT_WARN,
                    'Use trans sid' => self::INI_SESSION_USE_TRANS_SID,
                ),
                'MSSQL' => array(
                    'Allow persistent' => self::INI_MSSQL_ALLOW_PERSISTENT,
                    'Compatibility mode' => self::INI_MSSQL_COMPATIBILITY_MODE,
                    'Secure connection' => self::INI_MSSQL_SECURE_CONNECTION,
                ),
                'Tidy' => array(
                    'Clean output' => self::INI_TIDY_CLEAN_OUTPUT,
                ),
                'SOAP' => array(
                    'WSDL cache enabled' => self::INI_SOAP_WSDL_CACHE_ENABLED,
                ),
                'XDebug' => array(
                    'Remote enable' => self::INI_XDEBUG_REMOTE_ENABLE,
                    'Profiler enable' => self::INI_XDEBUG_PROFILER_ENABLE,
                    'Profiler enable trigger' => self::INI_XDEBUG_PROFILER_ENABLE_TRIGGER,
                ),
            ),
        );
    }
getSettingsValues ()
Retrieves the default, off, and current values for various PHP settings.
Returns
array An associative array where the key is the setting name and the value is an array containing the default, off, and current values.
Definition at line 385 of file class.bin.php.php.
                                        {
        return array(
            self::INI_SHORT_OPEN_TAG => array('On', 'Off', 'On'),
            self::INI_ASP_TAGS => array('On', 'Off', 'Off'),
            self::INI_Y2K_COMPLIANCE => array('1', '0', '1'),
            self::INI_OUTPUT_BUFFERING => array('4096', 'Off', '4096'),
            self::INI_ZLIB_OUTPUT_COMPRESSION => array('On', 'Off', 'Off'),
            self::INI_IMPLICIT_FLUSH => array('On', 'Off', 'Off'),
            self::INI_ALLOW_CALL_TIME_PASS_REFERENCE => array('On', 'Off', 'On'),
            self::INI_SAFE_MODE => array('On', 'Off', 'Off'),
            self::INI_SAFE_MODE_GID => array('On', 'Off', 'Off'),
            self::INI_EXPOSE_PHP => array('On', 'Off', 'On'),
            self::INI_DISPLAY_ERRORS => array('On', 'Off', 'On'),
            self::INI_DISPLAY_STARTUP_ERRORS => array('On', 'Off', 'On'),
            self::INI_LOG_ERRORS => array('On', 'Off', 'On'),
            self::INI_IGNORE_REPEATED_ERRORS => array('On', 'Off', 'Off'),
            self::INI_IGNORE_REPEATED_SOURCE => array('On', 'Off', 'Off'),
            self::INI_REPORT_MEMLEAKS => array('On', 'Off', 'On'),
            self::INI_TRACK_ERRORS => array('On', 'Off', 'On'),
            self::INI_HTML_ERRORS => array('On', 'Off', 'On'),
            self::INI_REGISTER_GLOBALS => array('On', 'Off', 'Off'),
            self::INI_REGISTER_LONG_ARRAYS => array('On', 'Off', 'Off'),
            self::INI_REGISTER_ARGC_ARGV => array('On', 'Off', 'Off'),
            self::INI_AUTO_GLOBALS_JIT => array('On', 'Off', 'On'),
            self::INI_MAGIC_QUOTES_GPC => array('On', 'Off', 'Off'),
            self::INI_MAGIC_QUOTES_RUNTIME => array('On', 'Off', 'Off'),
            self::INI_MAGIC_QUOTES_SYBASE => array('On', 'Off', 'Off'),
            self::INI_ENABLE_DL => array('On', 'Off', 'Off'),
            self::INI_CGI_FORCE_REDIRECT => array('1', '0', '1'),
            self::INI_FILE_UPLOADS => array('On', 'Off', 'On'),
            self::INI_ALLOW_URL_FOPEN => array('On', 'Off', 'On'),
            self::INI_ALLOW_URL_INCLUDE => array('On', 'Off', 'Off'),
            self::INI_DEFINE_SYSLOG_VARIABLES => array('On', 'Off', 'Off'),
            self::INI_MAIL_ADD_X_HEADER => array('On', 'Off', 'On'),
            self::INI_SQL_SAFE_MODE => array('On', 'Off', 'Off'),
            self::INI_ODBC_ALLOW_PERSISTENT => array('On', 'Off', 'On'),
            self::INI_ODBC_CHECK_PERSISTENT => array('On', 'Off', 'On'),
            self::INI_MYSQL_ALLOW_LOCAL_INFILE => array('On', 'Off', 'Off'),
            self::INI_MYSQL_ALLOW_PERSISTENT => array('On', 'Off', 'On'),
            self::INI_MYSQL_TRACE_MODE => array('On', 'Off', 'Off'),
            self::INI_MYSQLI_ALLOW_PERSISTENT => array('On', 'Off', 'On'),
            self::INI_MYSQLI_RECONNECT => array('On', 'Off', 'Off'),
            self::INI_MYSQLND_COLLECT_STATISTICS => array('On', 'Off', 'On'),
            self::INI_MYSQLND_COLLECT_MEMORY_STATISTICS => array('On', 'Off', 'On'),
            self::INI_PGSQL_ALLOW_PERSISTENT => array('On', 'Off', 'On'),
            self::INI_PGSQL_AUTO_RESET_PERSISTENT => array('On', 'Off', 'Off'),
            self::INI_SYBCT_ALLOW_PERSISTENT => array('On', 'Off', 'On'),
            self::INI_SESSION_USE_COOKIES => array('1', '0', '1'),
            self::INI_SESSION_USE_ONLY_COOKIES => array('1', '0', '1'),
            self::INI_SESSION_AUTO_START => array('1', '0', '0'),
            self::INI_SESSION_COOKIE_HTTPONLY => array('1', '', ''),
            self::INI_SESSION_BUG_COMPAT_42 => array('On', 'Off', 'On'),
            self::INI_SESSION_BUG_COMPAT_WARN => array('On', 'Off', 'On'),
            self::INI_SESSION_USE_TRANS_SID => array('1', '0', '0'),
            self::INI_MSSQL_ALLOW_PERSISTENT => array('On', 'Off', 'On'),
            self::INI_MSSQL_COMPATIBILITY_MODE => array('On', 'Off', 'Off'),
            self::INI_MSSQL_SECURE_CONNECTION => array('On', 'Off', 'Off'),
            self::INI_TIDY_CLEAN_OUTPUT => array('On', 'Off', 'Off'),
            self::INI_SOAP_WSDL_CACHE_ENABLED => array('1', '0', '1'),
            self::INI_XDEBUG_REMOTE_ENABLE => array('On', 'Off', 'On'),
            self::INI_XDEBUG_PROFILER_ENABLE => array('On', 'Off', 'Off'),
            self::INI_XDEBUG_PROFILER_ENABLE_TRIGGER => array('On', 'Off', 'Off'),
        );
    }
Referenced by isSettingActive().
getTsDll ( $phpVersion = null)
Retrieves the name of the PHP Thread Safe (TS) DLL for the specified PHP version.
Parameters
$phpVersion The version of PHP. If null, the current PHP version is used.
Returns
string|false The name of the PHP TS DLL, or false if not found.
Definition at line 620 of file class.bin.php.php.
                                                 {
        $phpVersion = $phpVersion == null ? $this->getVersion() : $phpVersion;
        $currentPath = str_replace('php' . $this->getVersion(), 'php' . $phpVersion, $this->getCurrentPath());
        if (file_exists($currentPath . '/php7ts.dll')) {
            return 'php7ts.dll';
        } elseif (file_exists($currentPath . '/php8ts.dll')) {
            return 'php8ts.dll';
        }
        return false;
    }
References Module\$currentPath, Module\getCurrentPath(), and Module\getVersion().
Referenced by updateConfig().
isExtensionExcluded ( $ext) [private]
Checks if a specific PHP extension is excluded from the list.
Parameters
$ext The name of the extension to check.
Returns
bool True if the extension is excluded, false otherwise.
Definition at line 506 of file class.bin.php.php.
                                               {
        return in_array($ext, array(
            'opcache',
            'xdebug'
        ));
    }
Referenced by getExtensionsFromConf(), and getExtensionsFromFolder().
isSettingActive ( $name)
Checks if a specific PHP setting is active.
Parameters
$name The name of the setting to check.
Returns
bool True if the setting is active, false otherwise.
Definition at line 456 of file class.bin.php.php.
                                           {
        $settingsValues = $this->getSettingsValues();
        $confContent = file($this->getConf());
        foreach ($confContent as $row) {
            $settingMatch = array();
            if (preg_match('/^' . $name . '\s*=\s*(.+)/i', $row, $settingMatch)) {
                return isset($settingMatch[1]) && isset($settingsValues[$name]) && $settingsValues[$name][0] == trim($settingMatch[1]);
            }
        }
        return false;
    }
References Module\$name, getConf(), and getSettingsValues().
isSettingExists ( $name)
Checks if a specific PHP setting exists in the configuration file.
Parameters
$name The name of the setting to check.
Returns
bool True if the setting exists, false otherwise.
Definition at line 476 of file class.bin.php.php.
                                           {
        $confContent = file($this->getConf());
        foreach ($confContent as $row) {
            if (preg_match('/^\s*?;?\s*?' . $name . '\s*=\s*.*/i', $row)) {
                return true;
            }
        }
        return false;
    }
References Module\$name, and getConf().
reload ( $id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
$id The ID of the module. If null, the current ID is used.
$type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 116 of file class.bin.php.php.
                                                     {
        global $bearsamppRoot, $bearsamppConfig, $bearsamppBins, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::PHP);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        $this->enable = $this->enable && $bearsamppConfig->getRaw(self::ROOT_CFG_ENABLE);
        $this->apacheConf = $bearsamppBins->getApache()->getCurrentPath() . '/' . $this->apacheConf; //FIXME: Useful ?
        $this->errorLog = $bearsamppRoot->getLogsPath() . '/php_error.log';
        if ($this->bearsamppConfRaw !== false) {
            $this->cliExe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CLI_EXE];
            $this->cliSilentExe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CLI_SILENT_EXE];
            $this->conf = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CONF];
            $this->pearExe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_PEAR_EXE];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
            return;
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
            return;
        }
        if (!is_file($this->cliExe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->cliExe));
        }
        if (!is_file($this->cliSilentExe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->cliSilentExe));
        }
        if (!is_file($this->conf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->conf));
        }
        if (!is_file($this->pearExe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->pearExe));
        }
    }
References $apacheConf, $bearsamppBins, $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, Module\$type, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Util\logError(), Util\logInfo(), Util\logReloadClass(), and Lang\PHP.
Referenced by __construct(), setEnable(), and setVersion().
setEnable ( $enabled, $showWindow = false)
Enables or disables the module and updates the configuration.
Parameters
$enabled The enable status (Config\ENABLED or Config\DISABLED).
$showWindow Whether to show a window during the process.
Definition at line 654 of file class.bin.php.php.
                                                             {
        global $bearsamppConfig, $bearsamppBins, $bearsamppLang, $bearsamppWinbinder;
        if ($enabled == Config::ENABLED && !is_dir($this->currentPath)) {
            Util::logDebug($this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::ENABLE_BUNDLE_NOT_EXIST), $this->getName(), $this->getVersion(), $this->currentPath),
                    sprintf($bearsamppLang->getValue(Lang::ENABLE_TITLE), $this->getName())
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo($this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled'));
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace(self::ROOT_CFG_ENABLE, $enabled);
        $this->reload();
        $bearsamppBins->getApache()->update();
        if ($bearsamppBins->getApache()->isEnable() && $bearsamppBins->getApache()->getService()->isRunning()) {
            $bearsamppBins->getApache()->getService()->stop();
            Util::startService($bearsamppBins->getApache(), BinApache::CMD_SYNTAX_CHECK, $showWindow);
        }
    }
References $bearsamppBins, $bearsamppConfig, $bearsamppLang, BinApache\CMD_SYNTAX_CHECK, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\logDebug(), Util\logInfo(), reload(), and Util\startService().
setVersion ( $version)
Sets the PHP version and updates the configuration.
Parameters
$version The version to set.
Reimplemented from Module.
Definition at line 638 of file class.bin.php.php.
                                         {
        global $bearsamppConfig;
        $this->version = $version;
        Util::logTrace('Setting php version in .conf to: ' . $this->version);
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        Util::logTrace('Reloading php version...');
        $this->reload();
        Util::logTrace('Reloading of php version complete');
    }
References $bearsamppConfig, Module\$version, Util\logTrace(), and reload().
Referenced by updateConfig().
switchVersion ( $version, $showWindow = false)
Switches the PHP version to the specified version.
Parameters
$version The version to switch to.
$showWindow Whether to show a window during the switch process.
Returns
bool True if the switch was successful, false otherwise.
Definition at line 172 of file class.bin.php.php.
                                                                 {
        Util::logDebug('Switch ' . $this->name . ' version to ' . $version);
        return $this->updateConfig($version, 0, $showWindow);
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig ( $version = null, $sub = 0, $showWindow = false) [protected]
Updates the PHP configuration to the specified version.
Parameters
$version The version to update to. If null, the current version is used.
$sub The sub-level for logging indentation.
$showWindow Whether to show a window during the update process.
Returns
bool True if the update was successful, false otherwise.
Reimplemented from Module.
Definition at line 185 of file class.bin.php.php.
                                                                                    {
        global $bearsamppLang, $bearsamppBins, $bearsamppApps, $bearsamppWinbinder;
        if (!$this->enable) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'Update ' . $this->name . ' ' . $version . ' config');
        $boxTitle = sprintf($bearsamppLang->getValue(Lang::SWITCH_VERSION_TITLE), $this->getName(), $version);
        $conf = str_replace('php' . $this->getVersion(), 'php' . $version, $this->getConf());
        Util::logTrace('Current php version found: ' . $conf);
        $bearsamppConf = str_replace('php' . $this->getVersion(), 'php' . $version, $this->bearsamppConf);
        Util::logTrace('Current bearsampp.conf php version found: ' . $bearsamppConf);
        $tsDll = $this->getTsDll($version);
        $apachePhpModulePath = $this->getApacheModule($bearsamppBins->getApache()->getVersion(), $version);
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'PHP TsDll found: ' . $tsDll);
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'PHP Apache module found: ' . $apachePhpModulePath);
        if (!file_exists($conf) || !file_exists($bearsamppConf)) {
            Util::logError('bearsampp config files not found for ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR), $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file($bearsamppConf);
        if ($bearsamppConfRaw === false || !isset($bearsamppConfRaw[self::ROOT_CFG_VERSION]) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version) {
            Util::logError('bearsampp config file malformed for ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::BEARSAMPP_CONF_MALFORMED_ERROR), $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            return false;
        }
        if ($tsDll === false || $apachePhpModulePath === false) {
            Util::logDebug($this->getName() . ' ' . $version . ' does not seem to be compatible with Apache ' . $bearsamppBins->getApache()->getVersion());
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::PHP_INCPT), $version, $bearsamppBins->getApache()->getVersion()),
                    $boxTitle
                );
            }
            return false;
        }
        // bearsampp.conf
        Util::logTrace('Calling Set Version for php...');
        $this->setVersion($version);
        // conf
        Util::replaceInFile($this->getConf(), array(
            '/^mysql.default_port\s=\s(\d+)/' => 'mysql.default_port = ' . $bearsamppBins->getMysql()->getPort(),
            '/^mysqli.default_port\s=\s(\d+)/' => 'mysqli.default_port = ' . $bearsamppBins->getMysql()->getPort()
        ));
        // apache
        $bearsamppBins->getApache()->update($sub + 1);
        // phpmyadmin
        $bearsamppApps->getPhpmyadmin()->update($sub + 1);
        return true;
    }
References $bearsamppBins, Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, $conf, Module\$version, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, getApacheModule(), getConf(), Module\getName(), getTsDll(), Module\getVersion(), Util\logDebug(), Util\logError(), Util\logTrace(), Lang\PHP_INCPT, Util\replaceInFile(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$apacheConf [private]
Definition at line 91 of file class.bin.php.php.
Referenced by reload().
$cliExe [private]
Definition at line 94 of file class.bin.php.php.
Referenced by getCliExe().
$cliSilentExe [private]
Definition at line 95 of file class.bin.php.php.
Referenced by getCliSilentExe().
$conf [private]
Definition at line 96 of file class.bin.php.php.
Referenced by getConf(), and updateConfig().
$errorLog [private]
Definition at line 92 of file class.bin.php.php.
Referenced by getErrorLog().
$pearExe [private]
Definition at line 97 of file class.bin.php.php.
Referenced by getPearExe().
const INI_ALLOW_CALL_TIME_PASS_REFERENCE = 'allow_call_time_pass_reference'
Definition at line 33 of file class.bin.php.php.
const INI_ALLOW_URL_FOPEN = 'allow_url_fopen'
Definition at line 56 of file class.bin.php.php.
const INI_ALLOW_URL_INCLUDE = 'allow_url_include'
Definition at line 57 of file class.bin.php.php.
const INI_ASP_TAGS = 'asp_tags'
Definition at line 28 of file class.bin.php.php.
const INI_AUTO_GLOBALS_JIT = 'auto_globals_jit'
Definition at line 48 of file class.bin.php.php.
const INI_CGI_FIX_PATHINFO = 'cgi.fix_pathinfo'
Definition at line 54 of file class.bin.php.php.
const INI_CGI_FORCE_REDIRECT = 'cgi.force_redirect'
Definition at line 53 of file class.bin.php.php.
const INI_DEFINE_SYSLOG_VARIABLES = 'define_syslog_variables'
Definition at line 60 of file class.bin.php.php.
const INI_DISPLAY_ERRORS = 'display_errors'
Definition at line 37 of file class.bin.php.php.
const INI_DISPLAY_STARTUP_ERRORS = 'display_startup_errors'
Definition at line 38 of file class.bin.php.php.
const INI_ENABLE_DL = 'enable_dl'
Definition at line 52 of file class.bin.php.php.
const INI_EXPOSE_PHP = 'expose_php'
Definition at line 36 of file class.bin.php.php.
const INI_FILE_UPLOADS = 'file_uploads'
Definition at line 55 of file class.bin.php.php.
const INI_HTML_ERRORS = 'html_errors'
Definition at line 44 of file class.bin.php.php.
const INI_IGNORE_REPEATED_ERRORS = 'ignore_repeated_errors'
Definition at line 40 of file class.bin.php.php.
const INI_IGNORE_REPEATED_SOURCE = 'ignore_repeated_source'
Definition at line 41 of file class.bin.php.php.
const INI_IMPLICIT_FLUSH = 'implicit_flush'
Definition at line 32 of file class.bin.php.php.
const INI_LOG_ERRORS = 'log_errors'
Definition at line 39 of file class.bin.php.php.
const INI_MAGIC_QUOTES_GPC = 'magic_quotes_gpc'
Definition at line 49 of file class.bin.php.php.
const INI_MAGIC_QUOTES_RUNTIME = 'magic_quotes_runtime'
Definition at line 50 of file class.bin.php.php.
const INI_MAGIC_QUOTES_SYBASE = 'magic_quotes_sybase'
Definition at line 51 of file class.bin.php.php.
const INI_MAIL_ADD_X_HEADER = 'mail.add_x_header'
Definition at line 61 of file class.bin.php.php.
const INI_MSSQL_ALLOW_PERSISTENT = 'mssql.allow_persistent'
Definition at line 82 of file class.bin.php.php.
const INI_MSSQL_COMPATIBILITY_MODE = 'mssql.compatability_mode'
Definition at line 83 of file class.bin.php.php.
const INI_MSSQL_SECURE_CONNECTION = 'mssql.secure_connection'
Definition at line 84 of file class.bin.php.php.
const INI_MYSQL_ALLOW_LOCAL_INFILE = 'mysql.allow_local_infile'
Definition at line 65 of file class.bin.php.php.
const INI_MYSQL_ALLOW_PERSISTENT = 'mysql.allow_persistent'
Definition at line 66 of file class.bin.php.php.
const INI_MYSQL_TRACE_MODE = 'mysql.trace_mode'
Definition at line 67 of file class.bin.php.php.
const INI_MYSQLI_ALLOW_PERSISTENT = 'mysqli.allow_persistent'
Definition at line 68 of file class.bin.php.php.
const INI_MYSQLI_RECONNECT = 'mysqli.reconnect'
Definition at line 69 of file class.bin.php.php.
const INI_MYSQLND_COLLECT_MEMORY_STATISTICS = 'mysqlnd.collect_memory_statistics'
Definition at line 71 of file class.bin.php.php.
const INI_MYSQLND_COLLECT_STATISTICS = 'mysqlnd.collect_statistics'
Definition at line 70 of file class.bin.php.php.
const INI_ODBC_ALLOW_PERSISTENT = 'odbc.allow_persistent'
Definition at line 63 of file class.bin.php.php.
const INI_ODBC_CHECK_PERSISTENT = 'odbc.check_persistent'
Definition at line 64 of file class.bin.php.php.
const INI_OUTPUT_BUFFERING = 'output_buffering'
Definition at line 30 of file class.bin.php.php.
const INI_PGSQL_ALLOW_PERSISTENT = 'pgsql.allow_persistent'
Definition at line 72 of file class.bin.php.php.
const INI_PGSQL_AUTO_RESET_PERSISTENT = 'pgsql.auto_reset_persistent'
Definition at line 73 of file class.bin.php.php.
const INI_PHAR_READONLY = 'phar.readonly'
Definition at line 58 of file class.bin.php.php.
const INI_PHAR_REQUIRE_HASH = 'phar.require_hash'
Definition at line 59 of file class.bin.php.php.
const INI_REGISTER_ARGC_ARGV = 'register_argc_argv'
Definition at line 47 of file class.bin.php.php.
const INI_REGISTER_GLOBALS = 'register_globals'
Definition at line 45 of file class.bin.php.php.
const INI_REGISTER_LONG_ARRAYS = 'register_long_arrays'
Definition at line 46 of file class.bin.php.php.
const INI_REPORT_MEMLEAKS = 'report_memleaks'
Definition at line 42 of file class.bin.php.php.
const INI_SAFE_MODE = 'safe_mode'
Definition at line 34 of file class.bin.php.php.
const INI_SAFE_MODE_GID = 'safe_mode_gid'
Definition at line 35 of file class.bin.php.php.
const INI_SESSION_AUTO_START = 'session.auto_start'
Definition at line 77 of file class.bin.php.php.
const INI_SESSION_BUG_COMPAT_42 = 'session.bug_compat_42'
Definition at line 79 of file class.bin.php.php.
const INI_SESSION_BUG_COMPAT_WARN = 'session.bug_compat_warn'
Definition at line 80 of file class.bin.php.php.
const INI_SESSION_COOKIE_HTTPONLY = 'session.cookie_httponly'
Definition at line 78 of file class.bin.php.php.
const INI_SESSION_USE_COOKIES = 'session.use_cookies'
Definition at line 75 of file class.bin.php.php.
const INI_SESSION_USE_ONLY_COOKIES = 'session.use_only_cookies'
Definition at line 76 of file class.bin.php.php.
const INI_SESSION_USE_TRANS_SID = 'session.use_trans_sid'
Definition at line 81 of file class.bin.php.php.
const INI_SHORT_OPEN_TAG = 'short_open_tag'
Definition at line 27 of file class.bin.php.php.
const INI_SOAP_WSDL_CACHE_ENABLED = 'soap.wsdl_cache_enabled'
Definition at line 86 of file class.bin.php.php.
const INI_SQL_SAFE_MODE = 'sql.safe_mode'
Definition at line 62 of file class.bin.php.php.
const INI_SYBCT_ALLOW_PERSISTENT = 'sybct.allow_persistent'
Definition at line 74 of file class.bin.php.php.
const INI_TIDY_CLEAN_OUTPUT = 'tidy.clean_output'
Definition at line 85 of file class.bin.php.php.
const INI_TRACK_ERRORS = 'track_errors'
Definition at line 43 of file class.bin.php.php.
const INI_XDEBUG_PROFILER_ENABLE = 'xdebug.profiler_enable'
Definition at line 88 of file class.bin.php.php.
const INI_XDEBUG_PROFILER_ENABLE_TRIGGER = 'xdebug.profiler_enable_trigger'
Definition at line 89 of file class.bin.php.php.
const INI_XDEBUG_REMOTE_ENABLE = 'xdebug.remote_enable'
Definition at line 87 of file class.bin.php.php.
const INI_Y2K_COMPLIANCE = 'y2k_compliance'
Definition at line 29 of file class.bin.php.php.
const INI_ZLIB_OUTPUT_COMPRESSION = 'zlib.output_compression'
Definition at line 31 of file class.bin.php.php.
const LOCAL_CFG_CLI_EXE = 'phpCliExe'
Definition at line 22 of file class.bin.php.php.
const LOCAL_CFG_CLI_SILENT_EXE = 'phpCliSilentExe'
Definition at line 23 of file class.bin.php.php.
const LOCAL_CFG_CONF = 'phpConf'
Definition at line 24 of file class.bin.php.php.
const LOCAL_CFG_PEAR_EXE = 'phpPearExe'
Definition at line 25 of file class.bin.php.php.
const ROOT_CFG_ENABLE = 'phpEnable'
Definition at line 19 of file class.bin.php.php.
const ROOT_CFG_VERSION = 'phpVersion'
Definition at line 20 of file class.bin.php.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.