Bins
NAME
Bins
SYNOPSIS
Public Member Functions
__construct ()
getAll ()
getApache ()
getMailpit ()
getMariadb ()
getMemcached ()
getMysql ()
getNodejs ()
getPhp ()
getPostgresql ()
getServices ()
getXlight ()
reload ()
update ()
Data Fields
const TYPE = 'bins'
Private Attributes
$apache
$mailpit
$mariadb
$memcached
$mysql
$nodejs
$php
$postgresql
$xlight
Detailed Description
The Bins class manages various bin modules such as Mailpit, Memcached, Apache, PHP, MySQL, MariaDB, PostgreSQL, Node.js and Xlight. It provides methods to initialize, reload, update, and retrieve these modules. The class also handles logging and service management for the enabled bin modules.
Definition at line 16 of file class.bins.php.
Constructor & Destructor Documentation
__construct ()
Constructor for the Bins class. Initializes the Bins object and logs the initialization.
Definition at line 34 of file class.bins.php.
    {
        Util::logInitClass($this);
    }
References Util\logInitClass().
Member Function Documentation
getAll ()
Retrieves all bin modules.
Returns
array An array of all bin modules.
Definition at line 68 of file class.bins.php.
    {
        return array(
            $this->getApache(),
            $this->getMailpit(),
            $this->getMemcached(),
            $this->getMariadb(),
            $this->getMysql(),
            $this->getNodejs(),
            $this->getPhp(),
            $this->getPostgresql(),
            $this->getXlight(),
        );
    }
References getApache(), getMailpit(), getMariadb(), getMemcached(), getMysql(), getNodejs(), getPhp(), getPostgresql(), and getXlight().
Referenced by reload(), and update().
getApache ()
Retrieves the Apache bin module. If the Apache module is not initialized, it creates a new instance.
Returns
BinApache The Apache bin module.
Definition at line 117 of file class.bins.php.
    {
        if ($this->apache == null) {
            $this->apache = new BinApache('apache', self::TYPE);
        }
        return $this->apache;
    }
References $apache.
Referenced by getAll(), and getServices().
getMailpit ()
Retrieves the Mailpit bin module. If the Mailpit module is not initialized, it creates a new instance.
Returns
BinMailpit The Mailpit bin module.
Definition at line 89 of file class.bins.php.
    {
        if ($this->mailpit == null) {
            $this->mailpit = new BinMailpit('mailpit', self::TYPE);
        }
        return $this->mailpit;
    }
References $mailpit.
Referenced by getAll(), and getServices().
getMariadb ()
Retrieves the MariaDB bin module. If the MariaDB module is not initialized, it creates a new instance.
Returns
BinMariadb The MariaDB bin module.
Definition at line 159 of file class.bins.php.
    {
        if ($this->mariadb == null) {
            $this->mariadb = new BinMariadb('mariadb', self::TYPE);
        }
        return $this->mariadb;
    }
References $mariadb.
Referenced by getAll(), and getServices().
getMemcached ()
Retrieves the Memcached bin module. If the Memcached module is not initialized, it creates a new instance.
Returns
BinMemcached The Memcached bin module.
Definition at line 103 of file class.bins.php.
    {
        if ($this->memcached == null) {
            $this->memcached = new BinMemcached('memcached', self::TYPE);
        }
        return $this->memcached;
    }
References $memcached.
Referenced by getAll(), and getServices().
getMysql ()
Retrieves the MySQL bin module. If the MySQL module is not initialized, it creates a new instance.
Returns
BinMysql The MySQL bin module.
Definition at line 145 of file class.bins.php.
    {
        if ($this->mysql == null) {
            $this->mysql = new BinMysql('mysql', self::TYPE);
        }
        return $this->mysql;
    }
References $mysql.
Referenced by getAll(), and getServices().
getNodejs ()
Retrieves the Node.js bin module. If the Node.js module is not initialized, it creates a new instance.
Returns
BinNodejs The Node.js bin module.
Definition at line 187 of file class.bins.php.
    {
        if ($this->nodejs == null) {
            $this->nodejs = new BinNodejs('nodejs', self::TYPE);
        }
        return $this->nodejs;
    }
References $nodejs.
Referenced by getAll().
getPhp ()
Retrieves the PHP bin module. If the PHP module is not initialized, it creates a new instance.
Returns
BinPhp The PHP bin module.
Definition at line 131 of file class.bins.php.
    {
        if ($this->php == null) {
            $this->php = new BinPhp('php', self::TYPE);
        }
        return $this->php;
    }
References $php.
Referenced by getAll().
getPostgresql ()
Retrieves the PostgreSQL bin module. If the PostgreSQL module is not initialized, it creates a new instance.
Returns
BinPostgresql The PostgreSQL bin module.
Definition at line 173 of file class.bins.php.
    {
        if ($this->postgresql == null) {
            $this->postgresql = new BinPostgresql('postgresql', self::TYPE);
        }
        return $this->postgresql;
    }
References $postgresql.
Referenced by getAll(), and getServices().
getServices ()
Retrieves the services for all enabled bin modules.
Returns
array An associative array of service names and their corresponding service objects.
Definition at line 214 of file class.bins.php.
    {
        $result = array();
        if ($this->getMailpit()->isEnable()) {
            $result[BinMailpit::SERVICE_NAME] = $this->getMailpit()->getService();
        }
        if ($this->getMemcached()->isEnable()) {
            $result[BinMemcached::SERVICE_NAME] = $this->getMemcached()->getService();
        }
        if ($this->getApache()->isEnable()) {
            $result[BinApache::SERVICE_NAME] = $this->getApache()->getService();
        }
        if ($this->getMysql()->isEnable()) {
            $result[BinMysql::SERVICE_NAME] = $this->getMysql()->getService();
        }
        if ($this->getMariadb()->isEnable()) {
            $result[BinMariadb::SERVICE_NAME] = $this->getMariadb()->getService();
        }
        if ($this->getPostgresql()->isEnable()) {
            $result[BinPostgresql::SERVICE_NAME] = $this->getPostgresql()->getService();
        }
        if ($this->getXlight()->isEnable()) {
            $result[BinXlight::SERVICE_NAME] = $this->getXlight()->getService();
        }
        return $result;
    }
References $result, getApache(), getMailpit(), getMariadb(), getMemcached(), getMysql(), getPostgresql(), getXlight(), BinApache\SERVICE_NAME, BinMailpit\SERVICE_NAME, BinMariadb\SERVICE_NAME, BinMemcached\SERVICE_NAME, BinMysql\SERVICE_NAME, BinPostgresql\SERVICE_NAME, and BinXlight\SERVICE_NAME.
getXlight ()
Retrieves the Xlight bin module. If the Xlight module is not initialized, it creates a new instance.
Returns
BinXlight The Xlight bin module.
Definition at line 201 of file class.bins.php.
    {
        if ($this->xlight == null) {
            $this->xlight = new BinXlight('xlight', self::TYPE);
        }
        return $this->xlight;
    }
References $xlight.
Referenced by getAll(), and getServices().
reload ()
Reloads the configuration for all bin modules. Logs the reload action and calls the reload method on each bin module.
Definition at line 43 of file class.bins.php.
    {
        Util::logInfo('Reload bins');
        foreach ($this->getAll() as $bin) {
            $bin->reload();
        }
    }
References getAll(), and Util\logInfo().
update ()
Updates the configuration for all bin modules. Logs the update action and calls the update method on each bin module.
Definition at line 55 of file class.bins.php.
    {
        Util::logInfo('Update bins config');
        foreach ($this->getAll() as $bin) {
            $bin->update();
        }
    }
References getAll(), and Util\logInfo().
Field Documentation
$apache [private]
Definition at line 20 of file class.bins.php.
Referenced by getApache().
$mailpit [private]
Definition at line 21 of file class.bins.php.
Referenced by getMailpit().
$mariadb [private]
Definition at line 22 of file class.bins.php.
Referenced by getMariadb().
$memcached [private]
Definition at line 23 of file class.bins.php.
Referenced by getMemcached().
$mysql [private]
Definition at line 24 of file class.bins.php.
Referenced by getMysql().
$nodejs [private]
Definition at line 25 of file class.bins.php.
Referenced by getNodejs().
$php [private]
Definition at line 26 of file class.bins.php.
Referenced by getPhp().
$postgresql [private]
Definition at line 27 of file class.bins.php.
Referenced by getPostgresql().
$xlight [private]
Definition at line 28 of file class.bins.php.
Referenced by getXlight().
const TYPE = 'bins'
Definition at line 18 of file class.bins.php.
Referenced by Module\reload().
Author
Generated automatically by Doxygen for Bearsampp from the source code.