.TH "E:/Bearsampp-development/sandbox/core/classes/class.root.php" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/classes/class.root.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBRoot\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdebugStringPregReplace\fP ($match)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "debugStringPregReplace ( $match)"
Adjusts the trace number in debug backtrace\&.

.PP
\fBParameters\fP
.RS 4
\fI$match\fP The matches from the regular expression\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string The adjusted trace number\&. 
.RE
.PP

.PP
Definition at line \fB603\fP of file \fBclass\&.root\&.php\fP\&.
.nf
604     {
605         return '  #' \&. ($match[1] \- 1);
606     }
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
