Core
NAME
Core
SYNOPSIS
Public Member Functions
__construct ()
__toString ()
addLoadingPid ($pid)
getAjaxPath ($aetrayPath=false)
getAppVersion ()
getExec ($aetrayPath=false)
getFileFromUrl (string $moduleUrl, string $filePath, $progressBar=false)
getHomepagePath ($aetrayPath=false)
getHostsEditorExe ($aetrayPath=false)
getHostsEditorPath ($aetrayPath=false)
getIconsPath ($aetrayPath=false)
getImagesPath ($aetrayPath=false)
getisRootFilePath ($aetrayPath=false)
getLangsPath ($aetrayPath=false)
getLastPath ($aetrayPath=false)
getLastPathContent ()
getLibsPath ($aetrayPath=false)
getLnExe ($aetrayPath=false)
getLnPath ($aetrayPath=false)
getLoadingPid ($aetrayPath=false)
getNssmExe ($aetrayPath=false)
getNssmPath ($aetrayPath=false)
getOpenSslConf ($aetrayPath=false)
getOpenSslExe ($aetrayPath=false)
getOpenSslPath ($aetrayPath=false)
getPhpExe ($aetrayPath=false)
getPhpPath ($aetrayPath=false)
getPwgenExe ($aetrayPath=false)
getPwgenPath ($aetrayPath=false)
getResourcesPath ($aetrayPath=false)
getScript ($type)
getScriptsPath ($aetrayPath=false)
getSetEnvExe ($aetrayPath=false)
getSetEnvPath ($aetrayPath=false)
getTmpPath ($aetrayPath=false)
setExec ($action)
unzipFile ($filePath, $destination, $progressCallback=null)
Data Fields
const APP_VERSION = 'version.dat'
const EXEC = 'exec.dat'
const HOSTSEDITOR_EXE = 'hEdit_x64.exe'
const isRoot_FILE = 'root.php'
const LAST_PATH = 'lastPath.dat'
const LN_EXE = 'ln.exe'
const LOADING_PID = 'loading.pid'
const NSSM_EXE = 'nssm.exe'
const OPENSSL_CONF = 'openssl.cfg'
const OPENSSL_EXE = 'openssl.exe'
const PATH_LIN_PLACEHOLDER = '~BEARSAMPP_LIN_PATH~'
const PATH_WIN_PLACEHOLDER = '~BEARSAMPP_WIN_PATH~'
const PHP_EXE = 'php-win.exe'
const PWGEN_EXE = 'PWGenPortable.exe'
const SCRIPT_EXEC_SILENT = 'execSilent.vbs'
const SETENV_EXE = 'SetEnv.exe'
Detailed Description
Class Core
This class provides core functionalities and constants for the Bearsampp application. It includes methods for retrieving paths, managing application versions, and handling various executable files and configurations.
Definition at line 18 of file class.core.php.
Constructor & Destructor Documentation
__construct ()
Core constructor.
Loads the WinBinder extension if available.
Definition at line 46 of file class.core.php.
    {
        if ( extension_loaded( 'winbinder' ) ) {
            require_once $this->getLibsPath() . '/winbinder/winbinder.php';
        }
    }
References getLibsPath().
Member Function Documentation
__toString ()
Provides a string representation of the core object.
Returns
string A string describing the core object.
Definition at line 455 of file class.core.php.
    {
        return 'core object';
    }
addLoadingPid ( $pid)
Adds a PID to the loading PID file.
Parameters
$pid The PID to add.
Definition at line 265 of file class.core.php.
    {
        file_put_contents( $this->getLoadingPid(), $pid . PHP_EOL, FILE_APPEND );
    }
References getLoadingPid().
getAjaxPath ( $aetrayPath = false)
Definition at line 140 of file class.core.php.
    {
        return $this->getHomepagePath( $aetrayPath ) . '/ajax';
    }
References getHomepagePath().
getAppVersion ()
Retrieves the application version.
Returns
string|null The application version or null if not found.
Definition at line 190 of file class.core.php.
    {
        global $bearsamppLang;
        $filePath = $this->getResourcesPath() . '/' . self::APP_VERSION;
        if ( !is_file( $filePath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), APP_TITLE, $filePath ) );
            return null;
        }
        return trim( file_get_contents( $filePath ) );
    }
References $bearsamppLang, APP_TITLE, Lang\ERROR_CONF_NOT_FOUND, getResourcesPath(), and Util\logError().
getExec ( $aetrayPath = false)
Retrieves the path to the exec file.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the exec file.
Definition at line 233 of file class.core.php.
    {
        return $this->getTmpPath( $aetrayPath ) . '/' . self::EXEC;
    }
References getTmpPath().
Referenced by setExec().
getFileFromUrl (string $moduleUrl, string $filePath, $progressBar = false)
Fetches a file from a given URL and saves it to a specified file path.
This method attempts to retrieve the content from the provided URL and save it to the specified file path. If any error occurs during fetching or saving, it logs the error and returns an error message. If the operation is successful, it returns the file path. The method also logs the file size if the input stream is a valid resource.
Parameters
$moduleUrl The URL from which to fetch the file content.
$filePath The path where the file content should be saved.
$progressBar Optional. Whether to display a progress bar during the download process. Default is false.
Returns
array Returns the file path if successful, or an array with an error message if an error occurs.
Definition at line 606 of file class.core.php.
    {
        // Open the URL for reading
        $inputStream = @fopen( $moduleUrl, 'rb' );
        if ( $inputStream === false ) {
            Util::logError( 'Error fetching content from URL: ' . $moduleUrl );
            return ['error' => 'Error fetching module'];
        }
        // Open the file for writing
        $outputStream = @fopen( $filePath, 'wb' );
        if ( $outputStream === false ) {
            Util::logError( 'Error opening file for writing: ' . $filePath );
            fclose( $inputStream );
            return ['error' => 'Error saving module'];
        }
        // Read and write in chunks to avoid memory overload
        $bufferSize = 8096; // 8KB
        $chunksRead = 0;
        while ( !feof( $inputStream ) ) {
            $buffer = fread( $inputStream, $bufferSize );
            fwrite( $outputStream, $buffer );
            $chunksRead++;
            // Send progress update
            if ( $progressBar ) {
                $progress = $chunksRead;
                echo json_encode( ['progress' => $progress] );
                // Check if output buffering is active before calling ob_flush()
                if ( ob_get_length() !== false ) {
                    ob_flush();
                }
                flush();
            }
        }
        fclose( $inputStream );
        fclose( $outputStream );
        return ['success' => true];
    }
References Util\logError().
getHomepagePath ( $aetrayPath = false)
Definition at line 135 of file class.core.php.
    {
        return $this->getResourcesPath( $aetrayPath ) . '/homepage';
    }
References getResourcesPath().
Referenced by getAjaxPath().
getHostsEditorExe ( $aetrayPath = false)
Retrieves the path to the HostsEditor executable.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the HostsEditor executable.
Definition at line 397 of file class.core.php.
    {
        return $this->getHostsEditorPath( $aetrayPath ) . '/' . self::HOSTSEDITOR_EXE;
    }
References getHostsEditorPath().
getHostsEditorPath ( $aetrayPath = false)
Retrieves the path to the HostsEditor directory.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the HostsEditor directory.
Definition at line 385 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/hostseditor';
    }
References getLibsPath().
Referenced by getHostsEditorExe().
getIconsPath ( $aetrayPath = false)
Retrieves the path to the icons.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the icons.
Definition at line 102 of file class.core.php.
    {
        return $this->getImagesPath($aetrayPath) . '/icons';
    }
References getImagesPath().
getImagesPath ( $aetrayPath = false)
Retrieves the path to the images.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the images.
Definition at line 114 of file class.core.php.
    {
        global $bearsamppCore;
        return $bearsamppCore->getHomepagePath($aetrayPath) . '/img';
    }
References $bearsamppCore.
Referenced by getIconsPath().
getisRootFilePath ( $aetrayPath = false)
Retrieves the path to the root file.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the root file.
Definition at line 178 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/' . self::isRoot_FILE;
    }
References $bearsamppRoot.
getLangsPath ( $aetrayPath = false)
Retrieves the path to the language files.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the language files.
Definition at line 60 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/langs';
    }
References $bearsamppRoot.
getLastPath ( $aetrayPath = false)
Retrieves the path to the last path file.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the last path file.
Definition at line 211 of file class.core.php.
    {
        return $this->getResourcesPath( $aetrayPath ) . '/' . self::LAST_PATH;
    }
References getResourcesPath().
Referenced by getLastPathContent().
getLastPathContent ()
Retrieves the content of the last path file.
Returns
string|false The content of the last path file or false on failure.
Definition at line 221 of file class.core.php.
    {
        return @file_get_contents( $this->getLastPath() );
    }
References getLastPath().
getLibsPath ( $aetrayPath = false)
Retrieves the path to the libraries.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the libraries.
Definition at line 74 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/libs';
    }
References $bearsamppRoot.
Referenced by __construct(), getHostsEditorPath(), getLnPath(), getNssmPath(), getOpenSslPath(), getPhpPath(), getPwgenPath(), getSetEnvPath(), and unzipFile().
getLnExe ( $aetrayPath = false)
Retrieves the path to the LN executable.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the LN executable.
Definition at line 421 of file class.core.php.
    {
        return $this->getLnPath( $aetrayPath ) . '/' . self::LN_EXE;
    }
References getLnPath().
getLnPath ( $aetrayPath = false)
Retrieves the path to the LN directory.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the LN directory.
Definition at line 409 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/ln';
    }
References getLibsPath().
Referenced by getLnExe().
getLoadingPid ( $aetrayPath = false)
Retrieves the path to the loading PID file.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the loading PID file.
Definition at line 255 of file class.core.php.
    {
        return $this->getResourcesPath( $aetrayPath ) . '/' . self::LOADING_PID;
    }
References getResourcesPath().
Referenced by addLoadingPid().
getNssmExe ( $aetrayPath = false)
Retrieves the path to the NSSM executable.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the NSSM executable.
Definition at line 337 of file class.core.php.
    {
        return $this->getNssmPath( $aetrayPath ) . '/' . self::NSSM_EXE;
    }
References getNssmPath().
getNssmPath ( $aetrayPath = false)
Retrieves the path to the NSSM directory.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the NSSM directory.
Definition at line 325 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/nssm';
    }
References getLibsPath().
Referenced by getNssmExe().
getOpenSslConf ( $aetrayPath = false)
Retrieves the path to the OpenSSL configuration file.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the OpenSSL configuration file.
Definition at line 373 of file class.core.php.
    {
        return $this->getOpenSslPath( $aetrayPath ) . '/' . self::OPENSSL_CONF;
    }
References getOpenSslPath().
getOpenSslExe ( $aetrayPath = false)
Retrieves the path to the OpenSSL executable.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the OpenSSL executable.
Definition at line 361 of file class.core.php.
    {
        return $this->getOpenSslPath( $aetrayPath ) . '/' . self::OPENSSL_EXE;
    }
References getOpenSslPath().
getOpenSslPath ( $aetrayPath = false)
Retrieves the path to the OpenSSL directory.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the OpenSSL directory.
Definition at line 349 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/openssl';
    }
References getLibsPath().
Referenced by getOpenSslConf(), and getOpenSslExe().
getPhpExe ( $aetrayPath = false)
Retrieves the path to the PHP executable.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the PHP executable.
Definition at line 289 of file class.core.php.
    {
        return $this->getPhpPath( $aetrayPath ) . '/' . self::PHP_EXE;
    }
References getPhpPath().
getPhpPath ( $aetrayPath = false)
Retrieves the path to the PHP directory.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the PHP directory.
Definition at line 277 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/php';
    }
References getLibsPath().
Referenced by getPhpExe().
getPwgenExe ( $aetrayPath = false)
Retrieves the path to the PWGen executable.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the PWGen executable.
Definition at line 445 of file class.core.php.
    {
        return $this->getPwgenPath( $aetrayPath ) . '/' . self::PWGEN_EXE;
    }
References getPwgenPath().
getPwgenPath ( $aetrayPath = false)
Retrieves the path to the PWGen directory.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the PWGen directory.
Definition at line 433 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/pwgen';
    }
References getLibsPath().
Referenced by getPwgenExe().
getResourcesPath ( $aetrayPath = false)
Retrieves the path to the resources.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the resources.
Definition at line 88 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/resources';
    }
References $bearsamppRoot.
Referenced by getAppVersion(), getHomepagePath(), getLastPath(), and getLoadingPid().
getScript ( $type)
Retrieves the path to a specific script.
Parameters
$type The type of script.
Returns
string The path to the script.
Definition at line 152 of file class.core.php.
    {
        return $this->getScriptsPath() . '/' . $type;
    }
References getScriptsPath().
getScriptsPath ( $aetrayPath = false)
Retrieves the path to the scripts.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the scripts.
Definition at line 128 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/scripts';
    }
References $bearsamppRoot.
Referenced by getScript().
getSetEnvExe ( $aetrayPath = false)
Retrieves the path to the SetEnv executable.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the SetEnv executable.
Definition at line 313 of file class.core.php.
    {
        return $this->getSetEnvPath( $aetrayPath ) . '/' . self::SETENV_EXE;
    }
References getSetEnvPath().
getSetEnvPath ( $aetrayPath = false)
Retrieves the path to the SetEnv directory.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the SetEnv directory.
Definition at line 301 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/setenv';
    }
References getLibsPath().
Referenced by getSetEnvExe().
getTmpPath ( $aetrayPath = false)
Retrieves the path to the temporary directory.
Parameters
$aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the temporary directory.
Definition at line 164 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/tmp';
    }
References $bearsamppRoot.
Referenced by getExec().
setExec ( $action)
Sets the content of the exec file.
Parameters
$action The content to set in the exec file.
Definition at line 243 of file class.core.php.
    {
        file_put_contents( $this->getExec(), $action );
    }
References getExec().
unzipFile ( $filePath, $destination, $progressCallback = null)
Unzips a file to the specified directory and provides progress updates.
This method uses the 7-Zip command-line tool to extract the contents of a zip file. It first tests the archive to determine the number of files to be extracted, then proceeds with the extraction while providing progress updates via a callback function.
Parameters
$filePath The path to the zip file.
$destination The directory to extract the files to.
$progressCallback A callback function to report progress. The callback receives two parameters:
int $currentFile: The current file number being extracted.
int $totalFiles: The total number of files to be extracted.
@global object $bearsamppRoot Global object to get core paths.
Returns
array|false An array containing the result of the extraction on success or failure:
On success: ['success' => true, 'numFiles' => int]
On failure: ['error' => string, 'numFiles' => int]
Returns false if the 7-Zip executable is not found.
Definition at line 480 of file class.core.php.
    {
        global $bearsamppRoot;
        $sevenZipPath = $this->getLibsPath() . '/7zip/7za.exe';
        if ( !file_exists( $sevenZipPath ) ) {
            Util::logError( '7za.exe not found at: ' . $sevenZipPath );
            return false;
        }
        // Command to test the archive and get the number of files
        $testCommand = escapeshellarg( $sevenZipPath ) . ' t ' . escapeshellarg( $filePath ) . ' -y -bsp1';
        $testOutput = shell_exec( $testCommand );
        // Extract the number of files from the test command output
        preg_match( '/Files: (\d+)/', $testOutput, $matches );
        $numFiles = isset( $matches[1] ) ? (int) $matches[1] : 0;
        Util::logTrace( 'Number of files to be extracted: ' . $numFiles );
        // Command to extract the archive
        $command = escapeshellarg( $sevenZipPath ) . ' x ' . escapeshellarg( $filePath ) . ' -y -bsp1 -bb0 -o' . escapeshellarg( $destination );
        Util::logTrace( 'Executing command: ' . $command );
        $process = popen( $command, 'rb' );
        if ( $process ) {
            $buffer = '';
            while ( !feof( $process ) ) {
                $buffer .= fread( $process, 8192 ); // Read in chunks of 8KB
                while ( ($pos = strpos( $buffer, "\r" )) !== false ) {
                    $line = substr( $buffer, 0, $pos );
                    $buffer = substr( $buffer, $pos + 1 );
                    $line = trim( $line ); // Remove any leading/trailing whitespace
                    Util::logTrace( "Processing line: $line" );
                    // Check if the line indicates everything is okay
                    if ( $line === "Everything is Ok" ) {
                        if ( $progressCallback ) {
                            Util::logTrace( "Extraction progress: 100%" );
                            call_user_func( $progressCallback, 100 );
                            Util::logTrace( "Progress callback called with percentage: 100" );
                        }
                    }
                    else if ( $progressCallback && preg_match( '/(?:^|\s)(\d+)%/', $line, $matches ) ) {
                        $currentPercentage = intval( $matches[1] );
                        Util::logTrace( "Extraction progress: $currentPercentage%" );
                        call_user_func( $progressCallback, $currentPercentage );
                        Util::logTrace( "Progress callback called with percentage: $currentPercentage" );
                    }
                    else {
                        Util::logTrace( "Line did not match pattern: $line" );
                    }
                }
            }
            // Process any remaining data in the buffer
            if ( !empty( $buffer ) ) {
                $line = trim( $buffer );
                Util::logTrace( "Processing remaining line: $line" );
                // Check if the remaining line indicates everything is okay
                if ( $line === "Everything is Ok" ) {
                    if ( $progressCallback ) {
                        Util::logTrace( "Extraction progress: 100%" );
                        call_user_func( $progressCallback, 100 );
                        Util::logTrace( "Progress callback called with percentage: 100" );
                    }
                }
                else if ( $progressCallback && preg_match( '/(?:^|\s)(\d+)%/', $line, $matches ) ) {
                    $currentPercentage = intval( $matches[1] );
                    Util::logTrace( "Extraction progress: $currentPercentage%" );
                    call_user_func( $progressCallback, $currentPercentage );
                    Util::logTrace( "Progress callback called with percentage: $currentPercentage" );
                }
                else {
                    Util::logTrace( "Remaining line did not match pattern: $line" );
                }
            }
            $returnVar = pclose( $process );
            Util::logTrace( 'Command return value: ' . $returnVar );
            // Set progress to 100% if the command was successful
            if ( $returnVar === 0 && $progressCallback ) {
                Util::logTrace( "Extraction completed successfully. Setting progress to 100%" );
                call_user_func( $progressCallback, 100 );
                Util::logTrace( "Progress callback called with percentage: 100" );
                // Adding a small delay to ensure the progress bar update is processed
                usleep( 100000 ); // 100 milliseconds
            }
            if ( $returnVar === 0 ) {
                Util::logDebug( 'Successfully unzipped file to: ' . $destination );
                return ['success' => true, 'numFiles' => $numFiles];
            }
            else {
                Util::logError( 'Failed to unzip file. Command return value: ' . $returnVar );
                return ['error' => 'Failed to unzip file', 'numFiles' => $numFiles];
            }
        }
        else {
            Util::logError( 'Failed to open process for command: ' . $command );
            return ['error' => 'Failed to open process', 'numFiles' => $numFiles];
        }
    }
References $bearsamppRoot, getLibsPath(), Util\logDebug(), Util\logError(), and Util\logTrace().
Field Documentation
const APP_VERSION = 'version.dat'
Definition at line 34 of file class.core.php.
const EXEC = 'exec.dat'
Definition at line 36 of file class.core.php.
const HOSTSEDITOR_EXE = 'hEdit_x64.exe'
Definition at line 30 of file class.core.php.
const isRoot_FILE = 'root.php'
Definition at line 21 of file class.core.php.
Referenced by Batch\exitApp(), TplApp\getActionRun(), and Util\startLoading().
const LAST_PATH = 'lastPath.dat'
Definition at line 35 of file class.core.php.
const LN_EXE = 'ln.exe'
Definition at line 31 of file class.core.php.
const LOADING_PID = 'loading.pid'
Definition at line 37 of file class.core.php.
const NSSM_EXE = 'nssm.exe'
Definition at line 27 of file class.core.php.
const OPENSSL_CONF = 'openssl.cfg'
Definition at line 29 of file class.core.php.
const OPENSSL_EXE = 'openssl.exe'
Definition at line 28 of file class.core.php.
const PATH_LIN_PLACEHOLDER = '~BEARSAMPP_LIN_PATH~'
Definition at line 23 of file class.core.php.
Referenced by Util\changePath().
const PATH_WIN_PLACEHOLDER = '~BEARSAMPP_WIN_PATH~'
Definition at line 22 of file class.core.php.
Referenced by Util\changePath().
const PHP_EXE = 'php-win.exe'
Definition at line 25 of file class.core.php.
const PWGEN_EXE = 'PWGenPortable.exe'
Definition at line 32 of file class.core.php.
const SCRIPT_EXEC_SILENT = 'execSilent.vbs'
Definition at line 39 of file class.core.php.
Referenced by WinBinder\exec().
const SETENV_EXE = 'SetEnv.exe'
Definition at line 26 of file class.core.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.