.TH "E:/Bearsampp-development/sandbox/core/classes/tpls Directory Reference" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/classes/tpls Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBapp\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclass\&.tpl\&.aestan\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.consolez\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.service\&.php\fP"
.br
.in -1c
