.TH "E:/Bearsampp-development/sandbox/core/libs/php Directory Reference" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/libs/php Directory Reference
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
 \fR \fP 
.SH "The PHP Interpreter"
.PP
PHP is a popular general-purpose scripting language that is especially suited to web development\&. Fast, flexible and pragmatic, PHP powers everything from your blog to the most popular websites in the world\&. PHP is distributed under the [PHP License v3\&.01](LICENSE)\&.

.PP
\fR\fP \fR\fP \fR\fP \fR\fP
.SS "Documentation"
The PHP manual is available at \fRphp\&.net/docs\fP\&.
.SS "Installation"
.SS "Prebuilt packages and binaries"
Prebuilt packages and binaries can be used to get up and running fast with PHP\&.

.PP
For Windows, the PHP binaries can be obtained from \fRwindows\&.php\&.net\fP\&. After extracting the archive the \fR*\&.exe\fP files are ready to use\&.

.PP
For other systems, see the \fRinstallation chapter\fP\&.
.SS "Building PHP source code"
\fIFor Windows, see \fRBuild your own PHP on Windows\fP\&.\fP

.PP
For a minimal PHP build from Git, you will need autoconf, bison, and re2c\&. For a default build, you will additionally need libxml2 and libsqlite3\&.

.PP
On Ubuntu, you can install these using: 
.PP
.nf
sudo apt install -y pkg-config build-essential autoconf bison re2c \\
                    libxml2-dev libsqlite3-dev

.fi
.PP

.PP
On Fedora, you can install these using: 
.PP
.nf
sudo dnf install re2c bison autoconf make libtool ccache libxml2-devel sqlite-devel

.fi
.PP

.PP
Generate configure: 
.PP
.nf
\&./buildconf

.fi
.PP

.PP
Configure your build\&. \fR--enable-debug\fP is recommended for development, see \fR\&./configure --help\fP for a full list of options\&. 
.PP
.nf
# For development
\&./configure --enable-debug
# For production
\&./configure

.fi
.PP

.PP
Build PHP\&. To speed up the build, specify the maximum number of jobs using \fR-j\fP: 
.PP
.nf
make -j4

.fi
.PP

.PP
The number of jobs should usually match the number of available cores, which can be determined using \fRnproc\fP\&.
.SS "Testing PHP source code"
PHP ships with an extensive test suite, the command \fRmake test\fP is used after successful compilation of the sources to run this test suite\&.

.PP
It is possible to run tests using multiple cores by setting \fR-jN\fP in \fRTEST_PHP_ARGS\fP: 
.PP
.nf
make TEST_PHP_ARGS=-j4 test

.fi
.PP

.PP
Shall run \fRmake test\fP with a maximum of 4 concurrent jobs: Generally the maximum number of jobs should not exceed the number of cores available\&.

.PP
The \fRqa\&.php\&.net\fP site provides more detailed info about testing and quality assurance\&.
.SS "Installing PHP built from source"
After a successful build (and test), PHP may be installed with: 
.PP
.nf
make install

.fi
.PP

.PP
Depending on your permissions and prefix, \fRmake install\fP may need super user permissions\&.
.SS "PHP extensions"
Extensions provide additional functionality on top of PHP\&. PHP consists of many essential bundled extensions\&. Additional extensions can be found in the PHP Extension Community Library - \fRPECL\fP\&.
.SS "Contributing"
The PHP source code is located in the Git repository at \fRgithub\&.com/php/php-src\fP\&. Contributions are most welcome by forking the repository and sending a pull request\&.

.PP
Discussions are done on GitHub, but depending on the topic can also be relayed to the official PHP developer mailing list internals@lists.php.net\&.

.PP
New features require an RFC and must be accepted by the developers\&. See \fRRequest for comments - RFC\fP and \fRVoting on PHP features\fP for more information on the process\&.

.PP
Bug fixes don't require an RFC\&. If the bug has a GitHub issue, reference it in the commit message using \fRGH-NNNNNN\fP\&. Use \fR#NNNNNN\fP for tickets in the old \fRbugs\&.php\&.net\fP bug tracker\&. 
.PP
.nf
Fix GH-7815: php_uname doesn't recognise latest Windows versions
Fix #55371: get_magic_quotes_gpc() throws deprecation warning

.fi
.PP

.PP
See \fRGit workflow\fP for details on how pull requests are merged\&.
.SS "Guidelines for contributors"
See further documents in the repository for more information on how to contribute:

.PP
.IP "\(bu" 2
\fBContributing to PHP\fP
.IP "\(bu" 2
\fBPHP coding standards\fP
.IP "\(bu" 2
\fBMailing list rules\fP
.IP "\(bu" 2
\fBPHP release process\fP
.PP
.SS "Credits"
For the list of people who've put work into PHP, please see the \fRPHP credits page\fP\&. 
