.TH "E:/Bearsampp-development/sandbox/core/classes/tools Directory Reference" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/classes/tools Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclass\&.tool\&.bruno\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tool\&.composer\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tool\&.consolez\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tool\&.ghostscript\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tool\&.git\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tool\&.ngrok\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tool\&.perl\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tool\&.python\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tool\&.ruby\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tools\&.php\fP"
.br
.in -1c
