.TH "E:/Bearsampp-development/sandbox/core Directory Reference" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBclasses\fP"
.br
.ti -1c
.RI "directory \fBlibs\fP"
.br
.ti -1c
.RI "directory \fBresources\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBroot\&.php\fP"
.br
.in -1c
