.TH "E:/Bearsampp-development/sandbox/core/classes/apps Directory Reference" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/classes/apps Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclass\&.app\&.phpmyadmin\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.app\&.phppgadmin\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.apps\&.php\fP"
.br
.in -1c
