.TH "E:/Bearsampp-development/sandbox/core/resources/homepage Directory Reference" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/resources/homepage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBajax\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBajax\&.php\fP"
.br
.ti -1c
.RI "file \fBhomepage\&.php\fP"
.br
.ti -1c
.RI "file \fBping\&.php\fP"
.br
.in -1c
