.TH "E:/Bearsampp-development/sandbox/core/classes/tpls/app Directory Reference" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/classes/tpls/app Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.apache\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.apps\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.browser\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.clearFolders\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.EditConf\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.exit\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.git\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.lang\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.launchStartup\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.logs\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.logsVerbose\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.mailpit\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.mariadb\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.memcached\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.mysql\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.online\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.php\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.postgresql\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.python\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.rebuildIni\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.reload\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.services\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.tools\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.tpl\&.app\&.xlight\&.php\fP"
.br
.in -1c
