.TH "E:/Bearsampp-development/sandbox/core/classes/actions Directory Reference" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/classes/actions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclass\&.action\&.about\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.addAlias\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.addVhost\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.changeBrowser\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.changeDbRootPwd\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.changePort\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.checkPort\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.checkVersion\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.clearFolders\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.debugApache\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.debugMariadb\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.debugMysql\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.debugPostgresql\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.editAlias\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.editVhost\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.enable\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.exec\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.ext\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.genSslCertificate\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.launchStartup\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.loading\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.manualRestart\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.quickPick\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.quit\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.rebuildIni\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.refreshRepos\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.refreshReposStartup\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.reload\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.restart\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.service\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.startup\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.switchApacheModule\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.switchLang\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.switchLogsVerbose\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.switchOnline\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.switchPhpExtension\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.switchPhpParam\&.php\fP"
.br
.ti -1c
.RI "file \fBclass\&.action\&.switchVersion\&.php\fP"
.br
.in -1c
