.TH "E:/Bearsampp-development/sandbox/core/resources/homepage/ajax Directory Reference" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/resources/homepage/ajax Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBajax\&.apache\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.latestversion\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.mailpit\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.mariadb\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.memcached\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.mysql\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.nodejs\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.php\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.postgresql\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.quickpick\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.summary\&.php\fP"
.br
.ti -1c
.RI "file \fBajax\&.xlight\&.php\fP"
.br
.in -1c
