.TH "E:/Bearsampp-development/sandbox/core/libs/winbinder/fi/freeimage.inc.php" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/libs/winbinder/fi/freeimage.inc.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFreeImage_Allocate\fP ($width, $height, $bpp)"
.br
.ti -1c
.RI "\fBFreeImage_GetBits\fP ($dib)"
.br
.ti -1c
.RI "\fBFreeImage_GetHeight\fP ($bmp)"
.br
.ti -1c
.RI "\fBFreeImage_GetInfoHeader\fP ($dib)"
.br
.ti -1c
.RI "\fBif\fP(!isset( $FI)) \fBFreeImage_GetVersion\fP ()"
.br
.ti -1c
.RI "\fBFreeImage_GetWidth\fP ($bmp)"
.br
.ti -1c
.RI "\fBFreeImage_Load\fP ($type, $filename, $flags=0)"
.br
.ti -1c
.RI "\fBFreeImage_Rescale\fP ($dib, $dst_width, $dst_height, $filter=0)"
.br
.ti -1c
.RI "\fBFreeImage_Save\fP ($type, $dib, $filename, $flags=0)"
.br
.ti -1c
.RI "\fBFreeImage_Unload\fP ($bmp)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBFIF_BMP\fP 0"
.br
.ti -1c
.RI "const \fBFIF_CUT\fP 21"
.br
.ti -1c
.RI "const \fBFIF_DDS\fP 24"
.br
.ti -1c
.RI "const \fBFIF_GIF\fP 25"
.br
.ti -1c
.RI "const \fBFIF_ICO\fP 1"
.br
.ti -1c
.RI "const \fBFIF_IFF\fP \fBFIF_LBM\fP"
.br
.ti -1c
.RI "const \fBFIF_JNG\fP 3"
.br
.ti -1c
.RI "const \fBFIF_JPEG\fP 2"
.br
.ti -1c
.RI "const \fBFIF_KOALA\fP 4"
.br
.ti -1c
.RI "const \fBFIF_LBM\fP 5"
.br
.ti -1c
.RI "const \fBFIF_MNG\fP 6"
.br
.ti -1c
.RI "const \fBFIF_PBM\fP 7"
.br
.ti -1c
.RI "const \fBFIF_PBMRAW\fP 8"
.br
.ti -1c
.RI "const \fBFIF_PCD\fP 9"
.br
.ti -1c
.RI "const \fBFIF_PCX\fP 10"
.br
.ti -1c
.RI "const \fBFIF_PGM\fP 11"
.br
.ti -1c
.RI "const \fBFIF_PGMRAW\fP 12"
.br
.ti -1c
.RI "const \fBFIF_PNG\fP 13"
.br
.ti -1c
.RI "const \fBFIF_PPM\fP 14"
.br
.ti -1c
.RI "const \fBFIF_PPMRAW\fP 15"
.br
.ti -1c
.RI "const \fBFIF_PSD\fP 20"
.br
.ti -1c
.RI "const \fBFIF_RAS\fP 16"
.br
.ti -1c
.RI "const \fBFIF_TARGA\fP 17"
.br
.ti -1c
.RI "const \fBFIF_TIFF\fP 18"
.br
.ti -1c
.RI "const \fBFIF_UNKNOWN\fP \-1"
.br
.ti -1c
.RI "const \fBFIF_WBMP\fP 19"
.br
.ti -1c
.RI "const \fBFIF_XBM\fP 22"
.br
.ti -1c
.RI "const \fBFIF_XPM\fP 23"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FreeImage_Allocate ( $width,  $height,  $bpp)"

.PP
Definition at line \fB110\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.nf
111 {
112     global $FI;
113     static $pfn = null;
114 
115     if($pfn === null)
116         $pfn = wb_get_function_address("FreeImage_Allocate@24", $FI);
117     return wb_call_function($pfn, array($width, $height, $bpp, 0, 0, 0));
118 }
.PP
.fi

.SS "FreeImage_GetBits ( $dib)"

.PP
Definition at line \fB100\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.nf
101 {
102     global $FI;
103     static $pfn = null;
104 
105     if($pfn === null)
106         $pfn = wb_get_function_address("FreeImage_GetBits", $FI);
107     return wb_call_function($pfn, array($dib));
108 }
.PP
.fi

.SS "FreeImage_GetHeight ( $bmp)"

.PP
Definition at line \fB140\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.nf
141 {
142     global $FI;
143     static $pfn = null;
144 
145     if($pfn === null)
146         $pfn = wb_get_function_address("FreeImage_GetHeight", $FI);
147     return wb_call_function($pfn, array($bmp));
148 }
.PP
.fi

.SS "FreeImage_GetInfoHeader ( $dib)"

.PP
Definition at line \fB90\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.nf
91 {
92     global $FI;
93     static $pfn = null;
94 
95     if($pfn === null)
96         $pfn = wb_get_function_address("FreeImage_GetInfoHeader", $FI);
97     return wb_call_function($pfn, array($dib));
98 }
.PP
.fi

.SS "\fBif\fP(!isset($FI)) FreeImage_GetVersion ()"

.PP
Definition at line \fB76\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.nf
77 {
78     global $FI;
79     static $pfn = null;
80 
81     if($pfn === null)
82         $pfn = wb_get_function_address("FreeImage_GetVersion", $FI);
83 
84     // Must use wb_peek because this function returns a string pointer
85 
86     $version = wb_peek(wb_call_function($pfn));
87     return $version;
88 }
.PP
.fi

.SS "FreeImage_GetWidth ( $bmp)"

.PP
Definition at line \fB130\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.nf
131 {
132     global $FI;
133     static $pfn = null;
134 
135     if($pfn === null)
136         $pfn = wb_get_function_address("FreeImage_GetWidth", $FI);
137     return wb_call_function($pfn, array($bmp));
138 }
.PP
.fi

.SS "FreeImage_Load ( $type,  $filename,  $flags = \fR0\fP)"

.PP
Definition at line \fB150\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.nf
151 {
152     global $FI;
153     static $pfn = null;
154 
155     if($pfn === null)
156         $pfn = wb_get_function_address("FreeImage_Load", $FI);
157     return wb_call_function($pfn, array($type, $filename, $flags));
158 }
.PP
.fi

.SS "FreeImage_Rescale ( $dib,  $dst_width,  $dst_height,  $filter = \fR0\fP)"

.PP
Definition at line \fB170\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.nf
171 {
172     global $FI;
173     static $pfn = null;
174 
175     if($pfn === null)
176         $pfn = wb_get_function_address("FreeImage_Rescale", $FI);
177     return wb_call_function($pfn, array($dib, $dst_width, $dst_height, $filter));
178 }
.PP
.fi

.SS "FreeImage_Save ( $type,  $dib,  $filename,  $flags = \fR0\fP)"

.PP
Definition at line \fB160\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.nf
161 {
162     global $FI;
163     static $pfn = null;
164 
165     if($pfn === null)
166         $pfn = wb_get_function_address("FreeImage_Save", $FI);
167     return wb_call_function($pfn, array($type, $dib, $filename, $flags));
168 }
.PP
.fi

.SS "FreeImage_Unload ( $bmp)"

.PP
Definition at line \fB120\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.nf
121 {
122     global $FI;
123     static $pfn = null;
124 
125     if($pfn === null)
126         $pfn = wb_get_function_address("FreeImage_Unload", $FI);
127     return wb_call_function($pfn, array($bmp));
128 }
.PP
.fi

.SH "Variable Documentation"
.PP 
.SS "const FIF_BMP 0"

.PP
Definition at line \fB37\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_CUT 21"

.PP
Definition at line \fB59\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_DDS 24"

.PP
Definition at line \fB62\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_GIF 25"

.PP
Definition at line \fB63\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_ICO 1"

.PP
Definition at line \fB38\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_IFF \fBFIF_LBM\fP"

.PP
Definition at line \fB43\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_JNG 3"

.PP
Definition at line \fB40\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_JPEG 2"

.PP
Definition at line \fB39\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_KOALA 4"

.PP
Definition at line \fB41\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_LBM 5"

.PP
Definition at line \fB42\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_MNG 6"

.PP
Definition at line \fB44\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_PBM 7"

.PP
Definition at line \fB45\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_PBMRAW 8"

.PP
Definition at line \fB46\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_PCD 9"

.PP
Definition at line \fB47\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_PCX 10"

.PP
Definition at line \fB48\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_PGM 11"

.PP
Definition at line \fB49\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_PGMRAW 12"

.PP
Definition at line \fB50\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_PNG 13"

.PP
Definition at line \fB51\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_PPM 14"

.PP
Definition at line \fB52\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_PPMRAW 15"

.PP
Definition at line \fB53\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_PSD 20"

.PP
Definition at line \fB58\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_RAS 16"

.PP
Definition at line \fB54\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_TARGA 17"

.PP
Definition at line \fB55\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_TIFF 18"

.PP
Definition at line \fB56\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_UNKNOWN \-1"

.PP
Definition at line \fB36\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_WBMP 19"

.PP
Definition at line \fB57\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_XBM 22"

.PP
Definition at line \fB60\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SS "const FIF_XPM 23"

.PP
Definition at line \fB61\fP of file \fBfreeimage\&.inc\&.php\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
