.TH "Homepage" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Homepage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBgetHomepagePath\fP ()"
.br
.ti -1c
.RI "\fBgetIconsPath\fP ()"
.br
.ti -1c
.RI "\fBgetImagesPath\fP ()"
.br
.ti -1c
.RI "\fBgetPage\fP ()"
.br
.ti -1c
.RI "\fBgetPageQuery\fP ($query)"
.br
.ti -1c
.RI "\fBgetPageUrl\fP ($query)"
.br
.ti -1c
.RI "\fBgetResourcesPath\fP ()"
.br
.ti -1c
.RI "\fBgetResourcesUrl\fP ()"
.br
.ti -1c
.RI "\fBrefreshAliasContent\fP ()"
.br
.ti -1c
.RI "\fBrefreshCommonsJsContent\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBPAGE_INDEX\fP = 'index'"
.br
.ti -1c
.RI "const \fBPAGE_PHPINFO\fP = 'phpinfo'"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$page\fP"
.br
.ti -1c
.RI "\fB$pageList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBHomepage\fP

.PP
This class handles the homepage functionalities of the \fBBearsampp\fP application\&. It manages the page navigation, resource paths, and content refresh operations\&. 
.PP
Definition at line \fB17\fP of file \fBclass\&.homepage\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"
\fBHomepage\fP constructor\&. Initializes the homepage class and sets the current page based on the query parameter\&. 
.PP
Definition at line \fB36\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
37     {
38         Util::logInitClass($this);
39 
40         $page = Util::cleanGetVar('p');
41         $this\->page = !empty($page) && in_array($page, $this\->pageList) ? $page : self::PAGE_INDEX;
42     }
.PP
.fi

.PP
References \fB$page\fP, \fBUtil\\cleanGetVar()\fP, and \fBUtil\\logInitClass()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getHomepagePath ()"
Gets the path to the homepage directory\&.

.PP
\fBReturns\fP
.RS 4
string The homepage directory path\&. 
.RE
.PP

.PP
Definition at line \fB90\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
91     {
92         global $bearsamppCore;
93         return $bearsamppCore\->getResourcesPath(false) \&. '/homepage';
94     }
.PP
.fi

.PP
References \fB$bearsamppCore\fP\&.
.PP
Referenced by \fBrefreshAliasContent()\fP, and \fBrefreshCommonsJsContent()\fP\&.
.SS "getIconsPath ()"
Gets the path to the icons directory\&.

.PP
\fBReturns\fP
.RS 4
string The icons directory path\&. 
.RE
.PP

.PP
Definition at line \fB111\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
112     {
113         return $this\->getResourcesPath(false) \&. '/img/icons/';
114     }
.PP
.fi

.PP
References \fBgetResourcesPath()\fP\&.
.SS "getImagesPath ()"
Gets the path to the images directory\&.

.PP
\fBReturns\fP
.RS 4
string The images directory path\&. 
.RE
.PP

.PP
Definition at line \fB101\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
102     {
103         return $this\->getResourcesPath(false) \&. '/img/';
104     }
.PP
.fi

.PP
References \fBgetResourcesPath()\fP\&.
.SS "getPage ()"
Gets the current page\&.

.PP
\fBReturns\fP
.RS 4
string The current page\&. 
.RE
.PP

.PP
Definition at line \fB49\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
50     {
51         return $this\->page;
52     }
.PP
.fi

.PP
References \fB$page\fP\&.
.SS "getPageQuery ( $query)"
Constructs the page query string based on the provided query\&.

.PP
\fBParameters\fP
.RS 4
\fI$query\fP The query string to construct\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string The constructed page query string\&. 
.RE
.PP

.PP
Definition at line \fB60\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
61     {
62         if (empty($query)) {
63             return '';
64         }
65 
66         if (in_array($query, $this\->pageList)) {
67             return $query !== self::PAGE_INDEX ? '?p=' \&. $query : 'index\&.php';
68         }
69 
70         return '';
71     }
.PP
.fi

.PP
Referenced by \fBgetPageUrl()\fP\&.
.SS "getPageUrl ( $query)"
Constructs the full URL for the given page query\&.

.PP
\fBParameters\fP
.RS 4
\fI$query\fP The query string to construct the URL for\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string The constructed page URL\&. 
.RE
.PP

.PP
Definition at line \fB79\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
80     {
81         global $bearsamppRoot;
82         return $bearsamppRoot\->getLocalUrl($this\->getPageQuery($query));
83     }
.PP
.fi

.PP
References \fB$bearsamppRoot\fP, and \fBgetPageQuery()\fP\&.
.SS "getResourcesPath ()"
Gets the path to the resources directory\&.

.PP
\fBReturns\fP
.RS 4
string The resources directory path\&. 
.RE
.PP

.PP
Definition at line \fB121\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
122     {
123         global $bearsamppCore;
124         return md5(APP_TITLE);
125     }
.PP
.fi

.PP
References \fB$bearsamppCore\fP, and \fBAPP_TITLE\fP\&.
.PP
Referenced by \fBgetIconsPath()\fP, \fBgetImagesPath()\fP, \fBgetResourcesUrl()\fP, \fBrefreshAliasContent()\fP, and \fBrefreshCommonsJsContent()\fP\&.
.SS "getResourcesUrl ()"
Gets the URL to the resources directory\&.

.PP
\fBReturns\fP
.RS 4
string The resources directory URL\&. 
.RE
.PP

.PP
Definition at line \fB132\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
133     {
134         global $bearsamppRoot;
135         return $bearsamppRoot\->getLocalUrl($this\->getResourcesPath());
136     }
.PP
.fi

.PP
References \fB$bearsamppRoot\fP, and \fBgetResourcesPath()\fP\&.
.SS "refreshAliasContent ()"
Refreshes the alias content by updating the alias configuration file\&.

.PP
\fBReturns\fP
.RS 4
bool True if the alias content was successfully refreshed, false otherwise\&. 
.RE
.PP

.PP
Definition at line \fB143\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
144     {
145         global $bearsamppBins;
146 
147         $result = $bearsamppBins\->getApache()\->getAliasContent(
148             $this\->getResourcesPath(),
149             $this\->getHomepagePath()
150         );
151 
152         return file_put_contents($this\->getHomepagePath() \&. '/alias\&.conf', $result) !== false;
153     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$result\fP, \fBgetHomepagePath()\fP, and \fBgetResourcesPath()\fP\&.
.SS "refreshCommonsJsContent ()"
Refreshes the commons JavaScript content by updating the _commons\&.js file\&. 
.PP
Definition at line \fB158\fP of file \fBclass\&.homepage\&.php\fP\&.
.nf
159     {
160         Util::replaceInFile($this\->getHomepagePath() \&. '/js/_commons\&.js', array(
161             '/^\\s\\surl:\&.*/' => '  url: "' \&. $this\->getResourcesPath() \&. '/ajax\&.php"',
162             '/AJAX_URL\&.*=\&.*/' => 'const AJAX_URL = "' \&. $this\->getResourcesPath() \&. '/ajax\&.php"',
163         ));
164     }
.PP
.fi

.PP
References \fBgetHomepagePath()\fP, \fBgetResourcesPath()\fP, and \fBUtil\\replaceInFile()\fP\&.
.SH "Field Documentation"
.PP 
.SS "$page\fR [private]\fP"

.PP
Definition at line \fB22\fP of file \fBclass\&.homepage\&.php\fP\&.
.PP
Referenced by \fB__construct()\fP, and \fBgetPage()\fP\&.
.SS "$pageList\fR [private]\fP"
\fBInitial value:\fP
.nf
= array(
        self::PAGE_INDEX,
        self::PAGE_PHPINFO,
    )
.PP
.fi

.PP
Definition at line \fB27\fP of file \fBclass\&.homepage\&.php\fP\&.
.SS "const PAGE_INDEX = 'index'"

.PP
Definition at line \fB19\fP of file \fBclass\&.homepage\&.php\fP\&.
.SS "const PAGE_PHPINFO = 'phpinfo'"

.PP
Definition at line \fB20\fP of file \fBclass\&.homepage\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
