Homepage
NAME
Homepage
SYNOPSIS
Public Member Functions
__construct ()
getHomepagePath ()
getIconsPath ()
getImagesPath ()
getPage ()
getPageQuery ($query)
getPageUrl ($query)
getResourcesPath ()
getResourcesUrl ()
refreshAliasContent ()
refreshCommonsJsContent ()
Data Fields
const PAGE_INDEX = 'index'
const PAGE_PHPINFO = 'phpinfo'
Private Attributes
$page
$pageList
Detailed Description
Class Homepage
This class handles the homepage functionalities of the Bearsampp application. It manages the page navigation, resource paths, and content refresh operations.
Definition at line 17 of file class.homepage.php.
Constructor & Destructor Documentation
__construct ()
Homepage constructor. Initializes the homepage class and sets the current page based on the query parameter.
Definition at line 36 of file class.homepage.php.
    {
        Util::logInitClass($this);
        $page = Util::cleanGetVar('p');
        $this->page = !empty($page) && in_array($page, $this->pageList) ? $page : self::PAGE_INDEX;
    }
References $page, Util\cleanGetVar(), and Util\logInitClass().
Member Function Documentation
getHomepagePath ()
Gets the path to the homepage directory.
Returns
string The homepage directory path.
Definition at line 90 of file class.homepage.php.
    {
        global $bearsamppCore;
        return $bearsamppCore->getResourcesPath(false) . '/homepage';
    }
References $bearsamppCore.
Referenced by refreshAliasContent(), and refreshCommonsJsContent().
getIconsPath ()
Gets the path to the icons directory.
Returns
string The icons directory path.
Definition at line 111 of file class.homepage.php.
    {
        return $this->getResourcesPath(false) . '/img/icons/';
    }
References getResourcesPath().
getImagesPath ()
Gets the path to the images directory.
Returns
string The images directory path.
Definition at line 101 of file class.homepage.php.
    {
        return $this->getResourcesPath(false) . '/img/';
    }
References getResourcesPath().
getPage ()
Gets the current page.
Returns
string The current page.
Definition at line 49 of file class.homepage.php.
    {
        return $this->page;
    }
References $page.
getPageQuery ( $query)
Constructs the page query string based on the provided query.
Parameters
$query The query string to construct.
Returns
string The constructed page query string.
Definition at line 60 of file class.homepage.php.
    {
        if (empty($query)) {
            return '';
        }
        if (in_array($query, $this->pageList)) {
            return $query !== self::PAGE_INDEX ? '?p=' . $query : 'index.php';
        }
        return '';
    }
Referenced by getPageUrl().
getPageUrl ( $query)
Constructs the full URL for the given page query.
Parameters
$query The query string to construct the URL for.
Returns
string The constructed page URL.
Definition at line 79 of file class.homepage.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getLocalUrl($this->getPageQuery($query));
    }
References $bearsamppRoot, and getPageQuery().
getResourcesPath ()
Gets the path to the resources directory.
Returns
string The resources directory path.
Definition at line 121 of file class.homepage.php.
    {
        global $bearsamppCore;
        return md5(APP_TITLE);
    }
References $bearsamppCore, and APP_TITLE.
Referenced by getIconsPath(), getImagesPath(), getResourcesUrl(), refreshAliasContent(), and refreshCommonsJsContent().
getResourcesUrl ()
Gets the URL to the resources directory.
Returns
string The resources directory URL.
Definition at line 132 of file class.homepage.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getLocalUrl($this->getResourcesPath());
    }
References $bearsamppRoot, and getResourcesPath().
refreshAliasContent ()
Refreshes the alias content by updating the alias configuration file.
Returns
bool True if the alias content was successfully refreshed, false otherwise.
Definition at line 143 of file class.homepage.php.
    {
        global $bearsamppBins;
        $result = $bearsamppBins->getApache()->getAliasContent(
            $this->getResourcesPath(),
            $this->getHomepagePath()
        );
        return file_put_contents($this->getHomepagePath() . '/alias.conf', $result) !== false;
    }
References $bearsamppBins, $result, getHomepagePath(), and getResourcesPath().
refreshCommonsJsContent ()
Refreshes the commons JavaScript content by updating the _commons.js file.
Definition at line 158 of file class.homepage.php.
    {
        Util::replaceInFile($this->getHomepagePath() . '/js/_commons.js', array(
            '/^\s\surl:.*/' => ' url: "' . $this->getResourcesPath() . '/ajax.php"',
            '/AJAX_URL.*=.*/' => 'const AJAX_URL = "' . $this->getResourcesPath() . '/ajax.php"',
        ));
    }
References getHomepagePath(), getResourcesPath(), and Util\replaceInFile().
Field Documentation
$page [private]
Definition at line 22 of file class.homepage.php.
Referenced by __construct(), and getPage().
$pageList [private]
Initial value:
= array(
        self::PAGE_INDEX,
        self::PAGE_PHPINFO,
    )
Definition at line 27 of file class.homepage.php.
const PAGE_INDEX = 'index'
Definition at line 19 of file class.homepage.php.
const PAGE_PHPINFO = 'phpinfo'
Definition at line 20 of file class.homepage.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.