.TH "Lang" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lang
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetKeys\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBABOUT\fP = 'about'"
.br
.ti -1c
.RI "const \fBABOUT_TEXT\fP = 'aboutText'"
.br
.ti -1c
.RI "const \fBABOUT_TITLE\fP = 'aboutTitle'"
.br
.ti -1c
.RI "const \fBADD_ALIAS_TITLE\fP = 'addAliasTitle'"
.br
.ti -1c
.RI "const \fBADD_VHOST_TITLE\fP = 'addVhostTitle'"
.br
.ti -1c
.RI "const \fBADMINISTRATION\fP = 'administration'"
.br
.ti -1c
.RI "const \fBALIAS_ALREADY_EXISTS\fP = 'aliasAlreadyExists'"
.br
.ti -1c
.RI "const \fBALIAS_CREATED\fP = 'aliasCreated'"
.br
.ti -1c
.RI "const \fBALIAS_CREATED_ERROR\fP = 'aliasCreatedError'"
.br
.ti -1c
.RI "const \fBALIAS_DEST_LABEL\fP = 'aliasDestLabel'"
.br
.ti -1c
.RI "const \fBALIAS_DEST_PATH\fP = 'aliasDestPath'"
.br
.ti -1c
.RI "const \fBALIAS_EXP_LABEL\fP = 'aliasExpLabel'"
.br
.ti -1c
.RI "const \fBALIAS_NAME_LABEL\fP = 'aliasNameLabel'"
.br
.ti -1c
.RI "const \fBALIAS_NOT_VALID_ALPHA\fP = 'aliasNotValidAlpha'"
.br
.ti -1c
.RI "const \fBALIAS_REMOVE_ERROR\fP = 'aliasRemoveError'"
.br
.ti -1c
.RI "const \fBALIAS_REMOVED\fP = 'aliasRemoved'"
.br
.ti -1c
.RI "const \fBALIASES\fP = 'aliases'"
.br
.ti -1c
.RI "const \fBALL_RUNNING_HINT\fP = 'allRunningHint'"
.br
.ti -1c
.RI "const \fBAPACHE\fP = 'apache'"
.br
.ti -1c
.RI "const \fBAPACHE_INCPT\fP = 'apacheIncpt'"
.br
.ti -1c
.RI "const \fBAPPS\fP = 'apps'"
.br
.ti -1c
.RI "const \fBBEARSAMPP_CONF_MALFORMED_ERROR\fP = 'bearsamppConfMalformedError'"
.br
.ti -1c
.RI "const \fBBEARSAMPP_CONF_NOT_FOUND_ERROR\fP = 'bearsamppConfNotFoundError'"
.br
.ti -1c
.RI "const \fBBINS\fP = 'bins'"
.br
.ti -1c
.RI "const \fBBRUNO\fP = 'bruno'"
.br
.ti -1c
.RI "const \fBBUTTON_BACK\fP = 'buttonBack'"
.br
.ti -1c
.RI "const \fBBUTTON_BROWSE\fP = 'buttonBrowse'"
.br
.ti -1c
.RI "const \fBBUTTON_CANCEL\fP = 'buttonCancel'"
.br
.ti -1c
.RI "const \fBBUTTON_DELETE\fP = 'buttonDelete'"
.br
.ti -1c
.RI "const \fBBUTTON_FINISH\fP = 'buttonFinish'"
.br
.ti -1c
.RI "const \fBBUTTON_NEXT\fP = 'buttonNext'"
.br
.ti -1c
.RI "const \fBBUTTON_OK\fP = 'buttonOk'"
.br
.ti -1c
.RI "const \fBBUTTON_SAVE\fP = 'buttonSave'"
.br
.ti -1c
.RI "const \fBCHANGE_BROWSER_EXP_LABEL\fP = 'changeBrowserExpLabel'"
.br
.ti -1c
.RI "const \fBCHANGE_BROWSER_OK\fP = 'changeBrowserOk'"
.br
.ti -1c
.RI "const \fBCHANGE_BROWSER_OTHER_LABEL\fP = 'changeBrowserOtherLabel'"
.br
.ti -1c
.RI "const \fBCHANGE_BROWSER_TITLE\fP = 'changeBrowserTitle'"
.br
.ti -1c
.RI "const \fBCHANGE_DB_ROOT_PWD_CURRENTPWD_LABEL\fP = 'changeDbRootPwdCurrentpwdLabel'"
.br
.ti -1c
.RI "const \fBCHANGE_DB_ROOT_PWD_INCORRECT_ERROR\fP = 'changeDbRootPwdIncorrectError'"
.br
.ti -1c
.RI "const \fBCHANGE_DB_ROOT_PWD_NEWPWD1_LABEL\fP = 'changeDbRootPwdNewpwd1Label'"
.br
.ti -1c
.RI "const \fBCHANGE_DB_ROOT_PWD_NEWPWD2_LABEL\fP = 'changeDbRootPwdNewpwd2Label'"
.br
.ti -1c
.RI "const \fBCHANGE_DB_ROOT_PWD_NOTSAME_ERROR\fP = 'changeDbRootPwdNotsameError'"
.br
.ti -1c
.RI "const \fBCHANGE_DB_ROOT_PWD_TEXT\fP = 'changeDbRootPwdText'"
.br
.ti -1c
.RI "const \fBCHANGE_DB_ROOT_PWD_TITLE\fP = 'changeDbRootPwdTitle'"
.br
.ti -1c
.RI "const \fBCHANGE_PORT_CURRENT_LABEL\fP = 'changePortCurrentLabel'"
.br
.ti -1c
.RI "const \fBCHANGE_PORT_NEW_LABEL\fP = 'changePortNewLabel'"
.br
.ti -1c
.RI "const \fBCHANGE_PORT_SAME_ERROR\fP = 'changePortSameError'"
.br
.ti -1c
.RI "const \fBCHANGE_PORT_TITLE\fP = 'changePortTitle'"
.br
.ti -1c
.RI "const \fBCHANGELOG\fP = 'changelog'"
.br
.ti -1c
.RI "const \fBCHECK_PORT_TITLE\fP = 'checkPortTitle'"
.br
.ti -1c
.RI "const \fBCHECK_VERSION_AVAILABLE_TEXT\fP = 'checkVersionAvailableText'"
.br
.ti -1c
.RI "const \fBCHECK_VERSION_CHANGELOG_TEXT\fP = 'checkVersionChangelogText'"
.br
.ti -1c
.RI "const \fBCHECK_VERSION_LATEST_TEXT\fP = 'checkVersionLatestText'"
.br
.ti -1c
.RI "const \fBCHECK_VERSION_TITLE\fP = 'checkVersionTitle'"
.br
.ti -1c
.RI "const \fBCOMPOSER\fP = 'composer'"
.br
.ti -1c
.RI "const \fBCONSOLE\fP = 'console'"
.br
.ti -1c
.RI "const \fBCONSOLEZ\fP = 'consolez'"
.br
.ti -1c
.RI "const \fBDEBUG\fP = 'debug'"
.br
.ti -1c
.RI "const \fBDEBUG_APACHE_COMPILE_SETTINGS\fP = 'debugApacheCompileSettings'"
.br
.ti -1c
.RI "const \fBDEBUG_APACHE_COMPILED_MODULES\fP = 'debugApacheCompiledModules'"
.br
.ti -1c
.RI "const \fBDEBUG_APACHE_CONFIG_DIRECTIVES\fP = 'debugApacheConfigDirectives'"
.br
.ti -1c
.RI "const \fBDEBUG_APACHE_LOADED_MODULES\fP = 'debugApacheLoadedModules'"
.br
.ti -1c
.RI "const \fBDEBUG_APACHE_SYNTAX_CHECK\fP = 'debugApacheSyntaxCheck'"
.br
.ti -1c
.RI "const \fBDEBUG_APACHE_VERSION_NUMBER\fP = 'debugApacheVersionNumber'"
.br
.ti -1c
.RI "const \fBDEBUG_APACHE_VHOSTS_SETTINGS\fP = 'debugApacheVhostsSettings'"
.br
.ti -1c
.RI "const \fBDEBUG_MARIADB_SYNTAX_CHECK\fP = 'debugMariadbSyntaxCheck'"
.br
.ti -1c
.RI "const \fBDEBUG_MARIADB_VARIABLES\fP = 'debugMariadbVariables'"
.br
.ti -1c
.RI "const \fBDEBUG_MARIADB_VERSION\fP = 'debugMariadbVersion'"
.br
.ti -1c
.RI "const \fBDEBUG_MYSQL_SYNTAX_CHECK\fP = 'debugMysqlSyntaxCheck'"
.br
.ti -1c
.RI "const \fBDEBUG_MYSQL_VARIABLES\fP = 'debugMysqlVariables'"
.br
.ti -1c
.RI "const \fBDEBUG_MYSQL_VERSION\fP = 'debugMysqlVersion'"
.br
.ti -1c
.RI "const \fBDEBUG_POSTGRESQL_VERSION\fP = 'debugPostgresqlVersion'"
.br
.ti -1c
.RI "const \fBDELETE_ALIAS\fP = 'deleteAlias'"
.br
.ti -1c
.RI "const \fBDELETE_ALIAS_TITLE\fP = 'deleteAliasTitle'"
.br
.ti -1c
.RI "const \fBDELETE_VHOST\fP = 'deleteVhost'"
.br
.ti -1c
.RI "const \fBDELETE_VHOST_TITLE\fP = 'deleteVhostTitle'"
.br
.ti -1c
.RI "const \fBDISABLED\fP = 'disabled'"
.br
.ti -1c
.RI "const \fBDISCORD\fP = 'discord'"
.br
.ti -1c
.RI "const \fBDONATE\fP = 'donate'"
.br
.ti -1c
.RI "const \fBDONATE_VIA\fP = 'donateVia'"
.br
.ti -1c
.RI "const \fBDOWNLOAD\fP = 'download'"
.br
.ti -1c
.RI "const \fBDOWNLOAD_MORE\fP = 'downloadMore'"
.br
.ti -1c
.RI "const \fBEDIT_ALIAS_TITLE\fP = 'editAliasTitle'"
.br
.ti -1c
.RI "const \fBEDIT_VHOST_TITLE\fP = 'editVhostTitle'"
.br
.ti -1c
.RI "const \fBENABLE_BUNDLE_NOT_EXIST\fP = 'enableBundleNotExist'"
.br
.ti -1c
.RI "const \fBENABLE_TITLE\fP = 'enableTitle'"
.br
.ti -1c
.RI "const \fBENABLED\fP = 'enabled'"
.br
.ti -1c
.RI "const \fBERROR\fP = 'error'"
.br
.ti -1c
.RI "const \fBERROR_CONF_NOT_FOUND\fP = 'errorConfNotFound'"
.br
.ti -1c
.RI "const \fBERROR_EXE_NOT_FOUND\fP = 'errorExeNotFound'"
.br
.ti -1c
.RI "const \fBERROR_FILE_NOT_FOUND\fP = 'errorFileNotFound'"
.br
.ti -1c
.RI "const \fBERROR_INVALID_PARAMETER\fP = 'errorInvalidParameter'"
.br
.ti -1c
.RI "const \fBEXECUTABLE\fP = 'executable'"
.br
.ti -1c
.RI "const \fBEXIT_LEAVING_TEXT\fP = 'exitLeavingText'"
.br
.ti -1c
.RI "const \fBEXIT_REMOVE_SERVICE_TEXT\fP = 'exitRemoveServiceText'"
.br
.ti -1c
.RI "const \fBEXIT_STOP_OTHER_PROCESS_TEXT\fP = 'exitStopOtherProcessText'"
.br
.ti -1c
.RI "const \fBEXTENSIONS\fP = 'extensions'"
.br
.ti -1c
.RI "const \fBFACEBOOK\fP = 'facebook'"
.br
.ti -1c
.RI "const \fBGENSSL_CREATED\fP = 'genSslCreated'"
.br
.ti -1c
.RI "const \fBGENSSL_CREATED_ERROR\fP = 'genSslCreatedError'"
.br
.ti -1c
.RI "const \fBGENSSL_PATH\fP = 'genSslPath'"
.br
.ti -1c
.RI "const \fBGENSSL_TITLE\fP = 'genSslTitle'"
.br
.ti -1c
.RI "const \fBGHOSTSCRIPT\fP = 'ghostscript'"
.br
.ti -1c
.RI "const \fBGIT\fP = 'git'"
.br
.ti -1c
.RI "const \fBGIT_CONSOLE\fP = 'gitConsole'"
.br
.ti -1c
.RI "const \fBGITGUI\fP = 'gitGui'"
.br
.ti -1c
.RI "const \fBGITHUB\fP = 'github'"
.br
.ti -1c
.RI "const \fBHELP\fP = 'help'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_ABOUT_HTML\fP = 'homepageAboutHtml'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_APC_TEXT\fP = 'homepageApcText'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_BACK_TEXT\fP = 'homepageBackText'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_LICENSE_TEXT\fP = 'homepageLicenseText'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_MAILPIT_TEXT\fP = 'homepageMailpitText'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_OFFICIAL_WEBSITE\fP = 'homepageOfficialWebsite'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_PHPINFO_TEXT\fP = 'homepagePhpinfoText'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_POST_ISSUE\fP = 'homepagePostIssue'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_QUESTIONS_TEXT\fP = 'homepageQuestionsText'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_QUESTIONS_TITLE\fP = 'homepageQuestionsTitle'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_SERVICE_STARTED\fP = 'homepageServiceStarted'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_SERVICE_STOPPED\fP = 'homepageServiceStopped'"
.br
.ti -1c
.RI "const \fBHOMEPAGE_XLIGHT_TEXT\fP = 'homepageXlightText'"
.br
.ti -1c
.RI "const \fBHOSTSEDITOR\fP = 'hostseditor'"
.br
.ti -1c
.RI "const \fBINSTALL_SERVICE_TITLE\fP = 'installServiceTitle'"
.br
.ti -1c
.RI "const \fBLANG\fP = 'lang'"
.br
.ti -1c
.RI "const \fBLICENSE\fP = 'license'"
.br
.ti -1c
.RI "const \fBLOADING\fP = 'loading'"
.br
.ti -1c
.RI "const \fBLOCALE\fP = 'locale'"
.br
.ti -1c
.RI "const \fBLOGS\fP = 'logs'"
.br
.ti -1c
.RI "const \fBLOGS_VERBOSE\fP = 'logsVerbose'"
.br
.ti -1c
.RI "const \fBMAILPIT\fP = 'mailpit'"
.br
.ti -1c
.RI "const \fBMARIADB\fP = 'mariadb'"
.br
.ti -1c
.RI "const \fBMEMCACHED\fP = 'memcached'"
.br
.ti -1c
.RI "const \fBMENU_ABOUT\fP = 'menuAbout'"
.br
.ti -1c
.RI "const \fBMENU_ACCESS_LOGS\fP = 'menuAccessLogs'"
.br
.ti -1c
.RI "const \fBMENU_ADD_ALIAS\fP = 'menuAddAlias'"
.br
.ti -1c
.RI "const \fBMENU_ADD_VHOST\fP = 'menuAddVhost'"
.br
.ti -1c
.RI "const \fBMENU_CHANGE_PORT\fP = 'menuChangePort'"
.br
.ti -1c
.RI "const \fBMENU_CHANGE_ROOT_PWD\fP = 'menuChangeRootPwd'"
.br
.ti -1c
.RI "const \fBMENU_CHECK_PORT\fP = 'menuCheckPort'"
.br
.ti -1c
.RI "const \fBMENU_CHECK_UPDATE\fP = 'menuCheckUpdate'"
.br
.ti -1c
.RI "const \fBMENU_CLEAR_FOLDERS\fP = 'menuClearFolders'"
.br
.ti -1c
.RI "const \fBMENU_EDIT_ALIAS\fP = 'menuEditAlias'"
.br
.ti -1c
.RI "const \fBMENU_EDIT_CONF\fP = 'menuEditConf'"
.br
.ti -1c
.RI "const \fBMENU_EDIT_VHOST\fP = 'menuEditVhost'"
.br
.ti -1c
.RI "const \fBMENU_ENABLE\fP = 'menuEnable'"
.br
.ti -1c
.RI "const \fBMENU_ERROR_LOGS\fP = 'menuErrorLogs'"
.br
.ti -1c
.RI "const \fBMENU_GEN_SSL_CERTIFICATE\fP = 'menuGenSslCertificate'"
.br
.ti -1c
.RI "const \fBMENU_INSTALL_SERVICE\fP = 'menuInstallService'"
.br
.ti -1c
.RI "const \fBMENU_LAUNCH_STARTUP\fP = 'menuLaunchStartup'"
.br
.ti -1c
.RI "const \fBMENU_LOCALHOST\fP = 'menuLocalhost'"
.br
.ti -1c
.RI "const \fBMENU_LOGS\fP = 'menuLogs'"
.br
.ti -1c
.RI "const \fBMENU_PUT_OFFLINE\fP = 'menuPutOffline'"
.br
.ti -1c
.RI "const \fBMENU_PUT_ONLINE\fP = 'menuPutOnline'"
.br
.ti -1c
.RI "const \fBMENU_REBUILD_INI\fP = 'menuRebuildIni'"
.br
.ti -1c
.RI "const \fBMENU_REFRESH_REPOS\fP = 'menuRefreshRepos'"
.br
.ti -1c
.RI "const \fBMENU_REMOVE_SERVICE\fP = 'menuRemoveService'"
.br
.ti -1c
.RI "const \fBMENU_RESTART_SERVICE\fP = 'menuRestartService'"
.br
.ti -1c
.RI "const \fBMENU_RESTART_SERVICES\fP = 'menuRestartServices'"
.br
.ti -1c
.RI "const \fBMENU_REWRITE_LOGS\fP = 'menuRewriteLogs'"
.br
.ti -1c
.RI "const \fBMENU_SCAN_REPOS_STARTUP\fP = 'menuScanReposStartup'"
.br
.ti -1c
.RI "const \fBMENU_SESSION_LOGS\fP = 'menuSessionLogs'"
.br
.ti -1c
.RI "const \fBMENU_START_SERVICE\fP = 'menuStartService'"
.br
.ti -1c
.RI "const \fBMENU_START_SERVICES\fP = 'menuStartServices'"
.br
.ti -1c
.RI "const \fBMENU_STATS_LOGS\fP = 'menuStatsLogs'"
.br
.ti -1c
.RI "const \fBMENU_STOP_SERVICE\fP = 'menuStopService'"
.br
.ti -1c
.RI "const \fBMENU_STOP_SERVICES\fP = 'menuStopServices'"
.br
.ti -1c
.RI "const \fBMENU_TRANSFER_LOGS\fP = 'menuTransferLogs'"
.br
.ti -1c
.RI "const \fBMENU_UPDATE_ENV_PATH\fP = 'menuUpdateEnvPath'"
.br
.ti -1c
.RI "const \fBMENU_WWW_DIRECTORY\fP = 'menuWwwDirectory'"
.br
.ti -1c
.RI "const \fBMODULES\fP = 'modules'"
.br
.ti -1c
.RI "const \fBMYSQL\fP = 'mysql'"
.br
.ti -1c
.RI "const \fBNAME\fP = 'name'"
.br
.ti -1c
.RI "const \fBNGROK\fP = 'ngrok'"
.br
.ti -1c
.RI "const \fBNODEJS\fP = 'nodejs'"
.br
.ti -1c
.RI "const \fBNONE_RUNNING_HINT\fP = 'noneRunningHint'"
.br
.ti -1c
.RI "const \fBPAYPAL\fP = 'paypal'"
.br
.ti -1c
.RI "const \fBPEAR\fP = 'pear'"
.br
.ti -1c
.RI "const \fBPERL\fP = 'perl'"
.br
.ti -1c
.RI "const \fBPHP\fP = 'php'"
.br
.ti -1c
.RI "const \fBPHP_INCPT\fP = 'phpIncpt'"
.br
.ti -1c
.RI "const \fBPHPMYADMIN\fP = 'phpmyadmin'"
.br
.ti -1c
.RI "const \fBPHPPGADMIN\fP = 'phppgadmin'"
.br
.ti -1c
.RI "const \fBPORT_CHANGED\fP = 'portChanged'"
.br
.ti -1c
.RI "const \fBPORT_NOT_USED\fP = 'portNotUsed'"
.br
.ti -1c
.RI "const \fBPORT_NOT_USED_BY\fP = 'portNotUsedBy'"
.br
.ti -1c
.RI "const \fBPORT_USED_BY\fP = 'portUsedBy'"
.br
.ti -1c
.RI "const \fBPORT_USED_BY_ANOTHER_DBMS\fP = 'portUsedByAnotherDbms'"
.br
.ti -1c
.RI "const \fBPOSTGRESQL\fP = 'postgresql'"
.br
.ti -1c
.RI "const \fBPWGEN\fP = 'pwgen'"
.br
.ti -1c
.RI "const \fBPYTHON\fP = 'python'"
.br
.ti -1c
.RI "const \fBPYTHON_CONSOLE\fP = 'pythonConsole'"
.br
.ti -1c
.RI "const \fBQUIT\fP = 'quit'"
.br
.ti -1c
.RI "const \fBREAD_CHANGELOG\fP = 'readChangelog'"
.br
.ti -1c
.RI "const \fBREGISTRY_SET_ERROR_TEXT\fP = 'registrySetErrorText'"
.br
.ti -1c
.RI "const \fBRELOAD\fP = 'reload'"
.br
.ti -1c
.RI "const \fBREMOVE_SERVICE_TITLE\fP = 'removeServiceTitle'"
.br
.ti -1c
.RI "const \fBREPOS\fP = 'repos'"
.br
.ti -1c
.RI "const \fBRESTART\fP = 'restart'"
.br
.ti -1c
.RI "const \fBRESTART_SERVICE_ERROR\fP = 'restartServiceError'"
.br
.ti -1c
.RI "const \fBRESTART_SERVICE_TITLE\fP = 'restartServiceTitle'"
.br
.ti -1c
.RI "const \fBRESTART_TEXT\fP = 'restartText'"
.br
.ti -1c
.RI "const \fBRESTART_TITLE\fP = 'restartTitle'"
.br
.ti -1c
.RI "const \fBRUBY\fP = 'ruby'"
.br
.ti -1c
.RI "const \fBSERVICE\fP = 'service'"
.br
.ti -1c
.RI "const \fBSERVICE_ALREADY_INSTALLED\fP = 'serviceAlreadyInstalled'"
.br
.ti -1c
.RI "const \fBSERVICE_INSTALL_ERROR\fP = 'serviceInstallError'"
.br
.ti -1c
.RI "const \fBSERVICE_INSTALLED\fP = 'serviceInstalled'"
.br
.ti -1c
.RI "const \fBSERVICE_NOT_EXIST\fP = 'serviceNotExist'"
.br
.ti -1c
.RI "const \fBSERVICE_REMOVE_ERROR\fP = 'serviceRemoveError'"
.br
.ti -1c
.RI "const \fBSERVICE_REMOVED\fP = 'serviceRemoved'"
.br
.ti -1c
.RI "const \fBSETTINGS\fP = 'settings'"
.br
.ti -1c
.RI "const \fBSOME_RUNNING_HINT\fP = 'someRunningHint'"
.br
.ti -1c
.RI "const \fBSSL\fP = 'ssl'"
.br
.ti -1c
.RI "const \fBSTART_SERVICE_ERROR\fP = 'startServiceError'"
.br
.ti -1c
.RI "const \fBSTART_SERVICE_TITLE\fP = 'startServiceTitle'"
.br
.ti -1c
.RI "const \fBSTARTUP\fP = 'startup'"
.br
.ti -1c
.RI "const \fBSTARTUP_CHANGE_PATH_TEXT\fP = 'startupChangePathText'"
.br
.ti -1c
.RI "const \fBSTARTUP_CHECK_BROWSER_TEXT\fP = 'startupCheckBrowserText'"
.br
.ti -1c
.RI "const \fBSTARTUP_CHECK_PATH_TEXT\fP = 'startupCheckPathText'"
.br
.ti -1c
.RI "const \fBSTARTUP_CHECK_SERVICE_TEXT\fP = 'startupCheckServiceText'"
.br
.ti -1c
.RI "const \fBSTARTUP_CLEAN_OLD_BEHAVIORS_TEXT\fP = 'startupCleanOldBehaviorsText'"
.br
.ti -1c
.RI "const \fBSTARTUP_CLEAN_TMP_TEXT\fP = 'startupCleanTmpText'"
.br
.ti -1c
.RI "const \fBSTARTUP_ERROR_TITLE\fP = 'startupErrorTitle'"
.br
.ti -1c
.RI "const \fBSTARTUP_GEN_SSL_CRT_TEXT\fP = 'startupGenSslCrtText'"
.br
.ti -1c
.RI "const \fBSTARTUP_INSTALL_SERVICE_TEXT\fP = 'startupInstallServiceText'"
.br
.ti -1c
.RI "const \fBSTARTUP_KILL_OLD_PROCS_TEXT\fP = 'startupKillOldProcsText'"
.br
.ti -1c
.RI "const \fBSTARTUP_PREPARE_RESTART_TEXT\fP = 'startupPrepareRestartText'"
.br
.ti -1c
.RI "const \fBSTARTUP_REFRESH_ALIAS_TEXT\fP = 'startupRefreshAliasText'"
.br
.ti -1c
.RI "const \fBSTARTUP_REFRESH_GIT_REPOS_TEXT\fP = 'startupRefreshGitReposText'"
.br
.ti -1c
.RI "const \fBSTARTUP_REFRESH_HOSTNAME_TEXT\fP = 'startupRefreshHostnameText'"
.br
.ti -1c
.RI "const \fBSTARTUP_REFRESH_VHOSTS_TEXT\fP = 'startupRefreshVhostsText'"
.br
.ti -1c
.RI "const \fBSTARTUP_REGISTRY_ERROR_TEXT\fP = 'startupRegistryErrorText'"
.br
.ti -1c
.RI "const \fBSTARTUP_REGISTRY_TEXT\fP = 'startupRegistryText'"
.br
.ti -1c
.RI "const \fBSTARTUP_ROTATION_LOGS_TEXT\fP = 'startupRotationLogsText'"
.br
.ti -1c
.RI "const \fBSTARTUP_SCAN_FOLDERS_TEXT\fP = 'startupScanFoldersText'"
.br
.ti -1c
.RI "const \fBSTARTUP_SERVICE_CREATE_ERROR\fP = 'startupServiceCreateError'"
.br
.ti -1c
.RI "const \fBSTARTUP_SERVICE_ERROR\fP = 'startupServiceError'"
.br
.ti -1c
.RI "const \fBSTARTUP_SERVICE_PORT_ERROR\fP = 'startupServicePortError'"
.br
.ti -1c
.RI "const \fBSTARTUP_SERVICE_START_ERROR\fP = 'startupServiceStartError'"
.br
.ti -1c
.RI "const \fBSTARTUP_SERVICE_SYNTAX_ERROR\fP = 'startupServiceSyntaxError'"
.br
.ti -1c
.RI "const \fBSTARTUP_START_SERVICE_TEXT\fP = 'startupStartServiceText'"
.br
.ti -1c
.RI "const \fBSTARTUP_STARTING_TEXT\fP = 'startupStartingText'"
.br
.ti -1c
.RI "const \fBSTARTUP_SYS_INFOS\fP = 'startupSysInfos'"
.br
.ti -1c
.RI "const \fBSTARTUP_UPDATE_CONFIG_TEXT\fP = 'startupUpdateConfigText'"
.br
.ti -1c
.RI "const \fBSTATUS\fP = 'status'"
.br
.ti -1c
.RI "const \fBSTATUS_PAGE\fP = 'statusPage'"
.br
.ti -1c
.RI "const \fBSTOP_SERVICE_ERROR\fP = 'stopServiceError'"
.br
.ti -1c
.RI "const \fBSTOP_SERVICE_TITLE\fP = 'stopServiceTitle'"
.br
.ti -1c
.RI "const \fBSWITCH_PHP_SETTING_NOT_FOUND\fP = 'switchPhpSettingNotFound'"
.br
.ti -1c
.RI "const \fBSWITCH_PHP_SETTING_TITLE\fP = 'switchPhpSettingTitle'"
.br
.ti -1c
.RI "const \fBSWITCH_VERSION_OK\fP = 'switchVersionOk'"
.br
.ti -1c
.RI "const \fBSWITCH_VERSION_OK_RESTART\fP = 'switchVersionOkRestart'"
.br
.ti -1c
.RI "const \fBSWITCH_VERSION_REGISTRY\fP = 'switchVersionRegistry'"
.br
.ti -1c
.RI "const \fBSWITCH_VERSION_RELOAD_BINS\fP = 'switchVersionReloadBins'"
.br
.ti -1c
.RI "const \fBSWITCH_VERSION_RELOAD_CONFIG\fP = 'switchVersionReloadConfig'"
.br
.ti -1c
.RI "const \fBSWITCH_VERSION_RESET_SERVICES\fP = 'switchVersionResetServices'"
.br
.ti -1c
.RI "const \fBSWITCH_VERSION_SAME_ERROR\fP = 'switchVersionSameError'"
.br
.ti -1c
.RI "const \fBSWITCH_VERSION_TITLE\fP = 'switchVersionTitle'"
.br
.ti -1c
.RI "const \fBTARGET\fP = 'target'"
.br
.ti -1c
.RI "const \fBTOOLS\fP = 'tools'"
.br
.ti -1c
.RI "const \fBVERBOSE_DEBUG\fP = 'verboseDebug'"
.br
.ti -1c
.RI "const \fBVERBOSE_REPORT\fP = 'verboseReport'"
.br
.ti -1c
.RI "const \fBVERBOSE_SIMPLE\fP = 'verboseSimple'"
.br
.ti -1c
.RI "const \fBVERBOSE_TRACE\fP = 'verboseTrace'"
.br
.ti -1c
.RI "const \fBVERSION\fP = 'version'"
.br
.ti -1c
.RI "const \fBVERSION_URL\fP = 'https://github\&.com/Bearsampp/Bearsampp/releases/tag/'"
.br
.ti -1c
.RI "const \fBVERSIONS\fP = 'versions'"
.br
.ti -1c
.RI "const \fBVHOST_ALREADY_EXISTS\fP = 'vhostAlreadyExists'"
.br
.ti -1c
.RI "const \fBVHOST_CREATED\fP = 'vhostCreated'"
.br
.ti -1c
.RI "const \fBVHOST_CREATED_ERROR\fP = 'vhostCreatedError'"
.br
.ti -1c
.RI "const \fBVHOST_DOC_ROOT_PATH\fP = 'vhostDocRootPath'"
.br
.ti -1c
.RI "const \fBVHOST_DOCUMENT_ROOT_LABEL\fP = 'vhostDocumentRootLabel'"
.br
.ti -1c
.RI "const \fBVHOST_EXP_LABEL\fP = 'vhostExpLabel'"
.br
.ti -1c
.RI "const \fBVHOST_NOT_VALID_DOMAIN\fP = 'vhostNotValidDomain'"
.br
.ti -1c
.RI "const \fBVHOST_REMOVE_ERROR\fP = 'vhostRemoveError'"
.br
.ti -1c
.RI "const \fBVHOST_REMOVED\fP = 'vhostRemoved'"
.br
.ti -1c
.RI "const \fBVHOST_SERVER_NAME_LABEL\fP = 'vhostServerNameLabel'"
.br
.ti -1c
.RI "const \fBVIRTUAL_HOSTS\fP = 'virtualHosts'"
.br
.ti -1c
.RI "const \fBWEBSITE\fP = 'website'"
.br
.ti -1c
.RI "const \fBXLIGHT\fP = 'xlight'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBLang\fP

.PP
This class contains constants used for localization and internationalization within the \fBBearsampp\fP application\&. The constants are categorized into various sections such as General, Single, Menu, \fBBins\fP, \fBApps\fP, \fBTools\fP, Errors, Actions, Windows forms, and \fBHomepage\fP\&. Each constant represents a key that can be used to retrieve localized strings from a language file or database\&. 
.PP
Definition at line \fB20\fP of file \fBclass\&.lang\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getKeys ()\fR [static]\fP"
Get all the keys defined in the \fBLang\fP class\&.

.PP
This method returns an array of all the constants defined in the \fBLang\fP class\&. These constants are used as keys for localization and internationalization purposes within the \fBBearsampp\fP application\&.

.PP
\fBReturns\fP
.RS 4
array An array of all the localization keys\&. 
.RE
.PP

.PP
Definition at line \fB383\fP of file \fBclass\&.lang\&.php\fP\&.
.nf
384     {
385         return array(
386             // General
387             self::ALL_RUNNING_HINT,
388             self::SOME_RUNNING_HINT,
389             self::NONE_RUNNING_HINT,
390 
391             // Single
392             self::ABOUT,
393             self::ADMINISTRATION,
394             self::ALIASES,
395             self::APPS,
396             self::BINS,
397             self::CHANGELOG,
398             self::CONSOLE,
399             self::DEBUG,
400             self::DISABLED,
401             self::DONATE,
402             self::DONATE_VIA,
403             self::DOWNLOAD,
404             self::DOWNLOAD_MORE,
405             self::ENABLED,
406             self::ERROR,
407             self::EXECUTABLE,
408             self::EXTENSIONS,
409             self::GIT_CONSOLE,
410             self::GITHUB,
411             self::HELP,
412             self::HOSTSEDITOR,
413             self::LANG,
414             self::LICENSE,
415             self::LOGS,
416             self::LOGS_VERBOSE,
417             self::MODULES,
418             self::NAME,
419             self::PAYPAL,
420             self::PYTHON_CONSOLE,
421             self::PWGEN,
422             self::QUIT,
423             self::READ_CHANGELOG,
424             self::RELOAD,
425             self::REPOS,
426             self::RESTART,
427             self::SERVICE,
428             self::SETTINGS,
429             self::SSL,
430             self::STARTUP,
431             self::STATUS,
432             self::STATUS_PAGE,
433             self::TARGET,
434             self::TOOLS,
435             self::VERBOSE_DEBUG,
436             self::VERBOSE_REPORT,
437             self::VERBOSE_SIMPLE,
438             self::VERBOSE_TRACE,
439             self::VERSION,
440             self::VERSIONS,
441             self::VIRTUAL_HOSTS,
442             self::WEBSITE,
443 
444             // Menu
445             self::MENU_ABOUT,
446             self::MENU_ACCESS_LOGS,
447             self::MENU_ADD_ALIAS,
448             self::MENU_ADD_VHOST,
449             self::MENU_CHANGE_PORT,
450             self::MENU_CHANGE_ROOT_PWD,
451             self::MENU_CHECK_PORT,
452             self::MENU_CHECK_UPDATE,
453             self::MENU_CLEAR_FOLDERS,
454             self::MENU_EDIT_ALIAS,
455             self::MENU_EDIT_VHOST,
456             self::MENU_ENABLE,
457             self::MENU_ERROR_LOGS,
458             self::MENU_GEN_SSL_CERTIFICATE,
459             self::MENU_INSTALL_SERVICE,
460             self::MENU_LAUNCH_STARTUP,
461             self::MENU_LOCALHOST,
462             self::MENU_LOGS,
463             self::MENU_PUT_OFFLINE,
464             self::MENU_PUT_ONLINE,
465             self::MENU_REBUILD_INI,
466             self::MENU_REFRESH_REPOS,
467             self::MENU_REMOVE_SERVICE,
468             self::MENU_RESTART_SERVICE,
469             self::MENU_RESTART_SERVICES,
470             self::MENU_REWRITE_LOGS,
471             self::MENU_SCAN_REPOS_STARTUP,
472             self::MENU_SESSION_LOGS,
473             self::MENU_START_SERVICE,
474             self::MENU_START_SERVICES,
475             self::MENU_STATS_LOGS,
476             self::MENU_STOP_SERVICE,
477             self::MENU_STOP_SERVICES,
478             self::MENU_TRANSFER_LOGS,
479             self::MENU_UPDATE_ENV_PATH,
480             self::MENU_WWW_DIRECTORY,
481 
482             // Bins
483             self::APACHE,
484             self::PHP,
485             self::PEAR,
486             self::MEMCACHED,
487             self::MAILPIT,
488             self::MARIADB,
489             self::MYSQL,
490             self::NODEJS,
491             self::POSTGRESQL,
492             self::XLIGHT,
493 
494             // Apps
495             self::PHPMYADMIN,
496             self::PHPPGADMIN,
497 
498             // Tools
499             self::BRUNO,
500             self::COMPOSER,
501             self::CONSOLEZ,
502             self::GIT,
503             self::NGROK,
504             self::PERL,
505             self::PYTHON,
506             self::RUBY,
507 
508             // Errors
509             self::ERROR_CONF_NOT_FOUND,
510             self::ERROR_EXE_NOT_FOUND,
511             self::ERROR_FILE_NOT_FOUND,
512             self::ERROR_INVALID_PARAMETER,
513 
514             // Action Switch version
515             self::SWITCH_VERSION_TITLE,
516             self::SWITCH_VERSION_RELOAD_CONFIG,
517             self::SWITCH_VERSION_RELOAD_BINS,
518             self::SWITCH_VERSION_REGISTRY,
519             self::SWITCH_VERSION_RESET_SERVICES,
520             self::SWITCH_VERSION_SAME_ERROR,
521             self::SWITCH_VERSION_OK,
522             self::SWITCH_VERSION_OK_RESTART,
523             self::APACHE_INCPT,
524             self::PHP_INCPT,
525             self::BEARSAMPP_CONF_NOT_FOUND_ERROR,
526             self::BEARSAMPP_CONF_MALFORMED_ERROR,
527 
528             // Action Switch PHP setting
529             self::SWITCH_PHP_SETTING_TITLE,
530             self::SWITCH_PHP_SETTING_NOT_FOUND,
531 
532             // Action Check port
533             self::CHECK_PORT_TITLE,
534             self::PORT_USED_BY,
535             self::PORT_NOT_USED,
536             self::PORT_NOT_USED_BY,
537             self::PORT_USED_BY_ANOTHER_DBMS,
538             self::PORT_CHANGED,
539 
540             // Action Install service
541             self::INSTALL_SERVICE_TITLE,
542             self::SERVICE_ALREADY_INSTALLED,
543             self::SERVICE_INSTALLED,
544             self::SERVICE_INSTALL_ERROR,
545 
546             // Action Remove service
547             self::REMOVE_SERVICE_TITLE,
548             self::SERVICE_NOT_EXIST,
549             self::SERVICE_REMOVED,
550             self::SERVICE_REMOVE_ERROR,
551 
552             // Action Start service
553             self::START_SERVICE_TITLE,
554             self::START_SERVICE_ERROR,
555 
556             // Action Stop service
557             self::STOP_SERVICE_TITLE,
558             self::STOP_SERVICE_ERROR,
559 
560             // Action Restart service
561             self::RESTART_SERVICE_TITLE,
562             self::RESTART_SERVICE_ERROR,
563 
564             // Action Delete alias
565             self::DELETE_ALIAS_TITLE,
566             self::DELETE_ALIAS,
567             self::ALIAS_REMOVED,
568             self::ALIAS_REMOVE_ERROR,
569 
570             // Action Add/Edit alias
571             self::ADD_ALIAS_TITLE,
572             self::ALIAS_NAME_LABEL,
573             self::ALIAS_DEST_LABEL,
574             self::ALIAS_EXP_LABEL,
575             self::ALIAS_DEST_PATH,
576             self::ALIAS_NOT_VALID_ALPHA,
577             self::ALIAS_ALREADY_EXISTS,
578             self::ALIAS_CREATED,
579             self::ALIAS_CREATED_ERROR,
580             self::EDIT_ALIAS_TITLE,
581 
582             // Action Delete vhost
583             self::DELETE_VHOST_TITLE,
584             self::DELETE_VHOST,
585             self::VHOST_REMOVED,
586             self::VHOST_REMOVE_ERROR,
587 
588             // Action Add/Edit vhost
589             self::ADD_VHOST_TITLE,
590             self::VHOST_SERVER_NAME_LABEL,
591             self::VHOST_DOCUMENT_ROOT_LABEL,
592             self::VHOST_EXP_LABEL,
593             self::VHOST_DOC_ROOT_PATH,
594             self::VHOST_NOT_VALID_DOMAIN,
595             self::VHOST_ALREADY_EXISTS,
596             self::VHOST_CREATED,
597             self::VHOST_CREATED_ERROR,
598             self::EDIT_VHOST_TITLE,
599 
600             // Action Change port
601             self::CHANGE_PORT_TITLE,
602             self::CHANGE_PORT_CURRENT_LABEL,
603             self::CHANGE_PORT_NEW_LABEL,
604             self::CHANGE_PORT_SAME_ERROR,
605 
606             // Action Change database root password
607             self::CHANGE_DB_ROOT_PWD_TITLE,
608             self::CHANGE_DB_ROOT_PWD_CURRENTPWD_LABEL,
609             self::CHANGE_DB_ROOT_PWD_NEWPWD1_LABEL,
610             self::CHANGE_DB_ROOT_PWD_NEWPWD2_LABEL,
611             self::CHANGE_DB_ROOT_PWD_NOTSAME_ERROR,
612             self::CHANGE_DB_ROOT_PWD_INCORRECT_ERROR,
613             self::CHANGE_DB_ROOT_PWD_TEXT,
614 
615             // Action Startup
616             self::STARTUP_STARTING_TEXT,
617             self::STARTUP_ROTATION_LOGS_TEXT,
618             self::STARTUP_KILL_OLD_PROCS_TEXT,
619             self::STARTUP_REFRESH_HOSTNAME_TEXT,
620             self::STARTUP_CHECK_BROWSER_TEXT,
621             self::STARTUP_SYS_INFOS,
622             self::STARTUP_CLEAN_TMP_TEXT,
623             self::STARTUP_CLEAN_OLD_BEHAVIORS_TEXT,
624             self::STARTUP_REFRESH_ALIAS_TEXT,
625             self::STARTUP_REFRESH_VHOSTS_TEXT,
626             self::STARTUP_CHECK_PATH_TEXT,
627             self::STARTUP_SCAN_FOLDERS_TEXT,
628             self::STARTUP_CHANGE_PATH_TEXT,
629             self::STARTUP_REGISTRY_TEXT,
630             self::STARTUP_REGISTRY_ERROR_TEXT,
631             self::STARTUP_UPDATE_CONFIG_TEXT,
632             self::STARTUP_CHECK_SERVICE_TEXT,
633             self::STARTUP_INSTALL_SERVICE_TEXT,
634             self::STARTUP_START_SERVICE_TEXT,
635             self::STARTUP_PREPARE_RESTART_TEXT,
636             self::STARTUP_ERROR_TITLE,
637             self::STARTUP_SERVICE_ERROR,
638             self::STARTUP_SERVICE_CREATE_ERROR,
639             self::STARTUP_SERVICE_START_ERROR,
640             self::STARTUP_SERVICE_SYNTAX_ERROR,
641             self::STARTUP_SERVICE_PORT_ERROR,
642             self::STARTUP_REFRESH_GIT_REPOS_TEXT,
643             self::STARTUP_START_SERVICE_TEXT,
644 
645             // Action Quit
646             self::EXIT_LEAVING_TEXT,
647             self::EXIT_REMOVE_SERVICE_TEXT,
648             self::EXIT_STOP_OTHER_PROCESS_TEXT,
649 
650             // Action Change browser
651             self::CHANGE_BROWSER_TITLE,
652             self::CHANGE_BROWSER_EXP_LABEL,
653             self::CHANGE_BROWSER_OTHER_LABEL,
654             self::CHANGE_BROWSER_OK,
655 
656             // Action About
657             self::ABOUT_TITLE,
658             self::ABOUT_TEXT,
659 
660             // Action Debug Apache
661             self::DEBUG_APACHE_VERSION_NUMBER,
662             self::DEBUG_APACHE_COMPILE_SETTINGS,
663             self::DEBUG_APACHE_COMPILED_MODULES,
664             self::DEBUG_APACHE_CONFIG_DIRECTIVES,
665             self::DEBUG_APACHE_VHOSTS_SETTINGS,
666             self::DEBUG_APACHE_LOADED_MODULES,
667             self::DEBUG_APACHE_SYNTAX_CHECK,
668 
669             // Action Debug MySQL
670             self::DEBUG_MYSQL_VERSION,
671             self::DEBUG_MYSQL_VARIABLES,
672             self::DEBUG_MYSQL_SYNTAX_CHECK,
673 
674             // Action Debug MariaDB
675             self::DEBUG_MARIADB_VERSION,
676             self::DEBUG_MARIADB_VARIABLES,
677             self::DEBUG_MARIADB_SYNTAX_CHECK,
678 
679             // Action Debug PostgreSQL
680             self::DEBUG_POSTGRESQL_VERSION,
681 
682             // Action others
683             self::REGISTRY_SET_ERROR_TEXT,
684 
685             // Action check version
686             self::CHECK_VERSION_TITLE,
687             self::CHECK_VERSION_AVAILABLE_TEXT,
688             self::CHECK_VERSION_CHANGELOG_TEXT,
689             self::CHECK_VERSION_LATEST_TEXT,
690 
691             // Action gen SSL certificate
692             self::GENSSL_TITLE,
693             self::GENSSL_PATH,
694             self::GENSSL_CREATED,
695             self::GENSSL_CREATED_ERROR,
696 
697             // Action restart
698             self::RESTART_TITLE,
699             self::RESTART_TEXT,
700 
701             // Action enable
702             self::ENABLE_TITLE,
703             self::ENABLE_BUNDLE_NOT_EXIST,
704 
705             // Windows forms
706             self::BUTTON_OK,
707             self::BUTTON_DELETE,
708             self::BUTTON_SAVE,
709             self::BUTTON_FINISH,
710             self::BUTTON_CANCEL,
711             self::BUTTON_NEXT,
712             self::BUTTON_BACK,
713             self::BUTTON_BROWSE,
714             self::LOADING,
715 
716             // Homepage
717             self::HOMEPAGE_OFFICIAL_WEBSITE,
718             self::HOMEPAGE_SERVICE_STARTED,
719             self::HOMEPAGE_SERVICE_STOPPED,
720             self::HOMEPAGE_ABOUT_HTML,
721             self::HOMEPAGE_LICENSE_TEXT,
722             self::HOMEPAGE_QUESTIONS_TITLE,
723             self::HOMEPAGE_QUESTIONS_TEXT,
724             self::HOMEPAGE_POST_ISSUE,
725             self::HOMEPAGE_PHPINFO_TEXT,
726             self::HOMEPAGE_APC_TEXT,
727             self::HOMEPAGE_MAILPIT_TEXT,
728             self::HOMEPAGE_XLIGHT_TEXT,
729             self::HOMEPAGE_BACK_TEXT,
730         );
731     }
.PP
.fi

.SH "Field Documentation"
.PP 
.SS "const ABOUT = 'about'"

.PP
Definition at line \fB28\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const ABOUT_TEXT = 'aboutText'"

.PP
Definition at line \fB301\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAbout\\__construct()\fP\&.
.SS "const ABOUT_TITLE = 'aboutTitle'"

.PP
Definition at line \fB300\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAbout\\__construct()\fP\&.
.SS "const ADD_ALIAS_TITLE = 'addAliasTitle'"

.PP
Definition at line \fB214\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\__construct()\fP, \fBActionAddAlias\\processWindow()\fP, and \fBActionEditAlias\\processWindow()\fP\&.
.SS "const ADD_VHOST_TITLE = 'addVhostTitle'"

.PP
Definition at line \fB232\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddVhost\\__construct()\fP, \fBActionAddVhost\\processWindow()\fP, and \fBActionEditVhost\\processWindow()\fP\&.
.SS "const ADMINISTRATION = 'administration'"

.PP
Definition at line \fB29\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const ALIAS_ALREADY_EXISTS = 'aliasAlreadyExists'"

.PP
Definition at line \fB220\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\processWindow()\fP, and \fBActionEditAlias\\processWindow()\fP\&.
.SS "const ALIAS_CREATED = 'aliasCreated'"

.PP
Definition at line \fB221\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\processWindow()\fP, and \fBActionEditAlias\\processWindow()\fP\&.
.SS "const ALIAS_CREATED_ERROR = 'aliasCreatedError'"

.PP
Definition at line \fB222\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\processWindow()\fP, and \fBActionEditAlias\\processWindow()\fP\&.
.SS "const ALIAS_DEST_LABEL = 'aliasDestLabel'"

.PP
Definition at line \fB216\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\__construct()\fP, and \fBActionEditAlias\\__construct()\fP\&.
.SS "const ALIAS_DEST_PATH = 'aliasDestPath'"

.PP
Definition at line \fB218\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\processWindow()\fP, \fBActionChangeBrowser\\processWindow()\fP, and \fBActionEditAlias\\processWindow()\fP\&.
.SS "const ALIAS_EXP_LABEL = 'aliasExpLabel'"

.PP
Definition at line \fB217\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\__construct()\fP, \fBActionEditAlias\\__construct()\fP, \fBActionAddAlias\\processWindow()\fP, and \fBActionEditAlias\\processWindow()\fP\&.
.SS "const ALIAS_NAME_LABEL = 'aliasNameLabel'"

.PP
Definition at line \fB215\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\__construct()\fP, and \fBActionEditAlias\\__construct()\fP\&.
.SS "const ALIAS_NOT_VALID_ALPHA = 'aliasNotValidAlpha'"

.PP
Definition at line \fB219\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\processWindow()\fP, and \fBActionEditAlias\\processWindow()\fP\&.
.SS "const ALIAS_REMOVE_ERROR = 'aliasRemoveError'"

.PP
Definition at line \fB211\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditAlias\\processWindow()\fP\&.
.SS "const ALIAS_REMOVED = 'aliasRemoved'"

.PP
Definition at line \fB210\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditAlias\\processWindow()\fP\&.
.SS "const ALIASES = 'aliases'"

.PP
Definition at line \fB30\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApache()\fP\&.
.SS "const ALL_RUNNING_HINT = 'allRunningHint'"

.PP
Definition at line \fB23\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAestan\\getSectionMessages()\fP\&.
.SS "const APACHE = 'apache'"

.PP
Definition at line \fB125\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugApache\\__construct()\fP, \fBTplAppApache\\process()\fP, \fBActionSwitchVersion\\processWindow()\fP, and \fBBinApache\\reload()\fP\&.
.SS "const APACHE_INCPT = 'apacheIncpt'"

.PP
Definition at line \fB166\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\updateConfig()\fP\&.
.SS "const APPS = 'apps'"

.PP
Definition at line \fB31\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApps\\process()\fP\&.
.SS "const BEARSAMPP_CONF_MALFORMED_ERROR = 'bearsamppConfMalformedError'"

.PP
Definition at line \fB169\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\updateConfig()\fP, \fBBinMailpit\\updateConfig()\fP, \fBBinMariadb\\updateConfig()\fP, \fBBinMemcached\\updateConfig()\fP, \fBBinMysql\\updateConfig()\fP, \fBBinNodejs\\updateConfig()\fP, \fBBinPhp\\updateConfig()\fP, \fBBinPostgresql\\updateConfig()\fP, and \fBBinXlight\\updateConfig()\fP\&.
.SS "const BEARSAMPP_CONF_NOT_FOUND_ERROR = 'bearsamppConfNotFoundError'"

.PP
Definition at line \fB168\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\updateConfig()\fP, \fBBinMailpit\\updateConfig()\fP, \fBBinMariadb\\updateConfig()\fP, \fBBinMemcached\\updateConfig()\fP, \fBBinMysql\\updateConfig()\fP, \fBBinNodejs\\updateConfig()\fP, \fBBinPhp\\updateConfig()\fP, \fBBinPostgresql\\updateConfig()\fP, and \fBBinXlight\\updateConfig()\fP\&.
.SS "const BINS = 'bins'"

.PP
Definition at line \fB32\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const BRUNO = 'bruno'"

.PP
Definition at line \fB141\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP, and \fBToolBruno\\reload()\fP\&.
.SS "const BUTTON_BACK = 'buttonBack'"

.PP
Definition at line \fB355\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const BUTTON_BROWSE = 'buttonBrowse'"

.PP
Definition at line \fB356\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\__construct()\fP, \fBActionAddVhost\\__construct()\fP, \fBActionChangeBrowser\\__construct()\fP, \fBActionEditAlias\\__construct()\fP, \fBActionEditVhost\\__construct()\fP, and \fBActionGenSslCertificate\\__construct()\fP\&.
.SS "const BUTTON_CANCEL = 'buttonCancel'"

.PP
Definition at line \fB353\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\__construct()\fP, \fBActionAddVhost\\__construct()\fP, \fBActionChangeBrowser\\__construct()\fP, \fBActionChangeDbRootPwd\\__construct()\fP, \fBActionChangePort\\__construct()\fP, \fBActionEditAlias\\__construct()\fP, \fBActionEditVhost\\__construct()\fP, and \fBActionGenSslCertificate\\__construct()\fP\&.
.SS "const BUTTON_DELETE = 'buttonDelete'"

.PP
Definition at line \fB350\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditAlias\\__construct()\fP, and \fBActionEditVhost\\__construct()\fP\&.
.SS "const BUTTON_FINISH = 'buttonFinish'"

.PP
Definition at line \fB352\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeDbRootPwd\\__construct()\fP, and \fBActionChangePort\\__construct()\fP\&.
.SS "const BUTTON_NEXT = 'buttonNext'"

.PP
Definition at line \fB354\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const BUTTON_OK = 'buttonOk'"

.PP
Definition at line \fB349\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAbout\\__construct()\fP, and \fBActionCheckVersion\\showVersionUpdateWindow()\fP\&.
.SS "const BUTTON_SAVE = 'buttonSave'"

.PP
Definition at line \fB351\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddAlias\\__construct()\fP, \fBActionAddVhost\\__construct()\fP, \fBActionChangeBrowser\\__construct()\fP, \fBActionEditAlias\\__construct()\fP, \fBActionEditVhost\\__construct()\fP, and \fBActionGenSslCertificate\\__construct()\fP\&.
.SS "const CHANGE_BROWSER_EXP_LABEL = 'changeBrowserExpLabel'"

.PP
Definition at line \fB295\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeBrowser\\__construct()\fP\&.
.SS "const CHANGE_BROWSER_OK = 'changeBrowserOk'"

.PP
Definition at line \fB297\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeBrowser\\processWindow()\fP\&.
.SS "const CHANGE_BROWSER_OTHER_LABEL = 'changeBrowserOtherLabel'"

.PP
Definition at line \fB296\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeBrowser\\__construct()\fP\&.
.SS "const CHANGE_BROWSER_TITLE = 'changeBrowserTitle'"

.PP
Definition at line \fB294\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeBrowser\\__construct()\fP, \fBTplAppBrowser\\process()\fP, and \fBActionChangeBrowser\\processWindow()\fP\&.
.SS "const CHANGE_DB_ROOT_PWD_CURRENTPWD_LABEL = 'changeDbRootPwdCurrentpwdLabel'"

.PP
Definition at line \fB251\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeDbRootPwd\\__construct()\fP\&.
.SS "const CHANGE_DB_ROOT_PWD_INCORRECT_ERROR = 'changeDbRootPwdIncorrectError'"

.PP
Definition at line \fB255\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeDbRootPwd\\processWindow()\fP\&.
.SS "const CHANGE_DB_ROOT_PWD_NEWPWD1_LABEL = 'changeDbRootPwdNewpwd1Label'"

.PP
Definition at line \fB252\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeDbRootPwd\\__construct()\fP\&.
.SS "const CHANGE_DB_ROOT_PWD_NEWPWD2_LABEL = 'changeDbRootPwdNewpwd2Label'"

.PP
Definition at line \fB253\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeDbRootPwd\\__construct()\fP\&.
.SS "const CHANGE_DB_ROOT_PWD_NOTSAME_ERROR = 'changeDbRootPwdNotsameError'"

.PP
Definition at line \fB254\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeDbRootPwd\\processWindow()\fP\&.
.SS "const CHANGE_DB_ROOT_PWD_TEXT = 'changeDbRootPwdText'"

.PP
Definition at line \fB256\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeDbRootPwd\\processWindow()\fP\&.
.SS "const CHANGE_DB_ROOT_PWD_TITLE = 'changeDbRootPwdTitle'"

.PP
Definition at line \fB250\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeDbRootPwd\\__construct()\fP, and \fBActionChangeDbRootPwd\\processWindow()\fP\&.
.SS "const CHANGE_PORT_CURRENT_LABEL = 'changePortCurrentLabel'"

.PP
Definition at line \fB245\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangePort\\__construct()\fP\&.
.SS "const CHANGE_PORT_NEW_LABEL = 'changePortNewLabel'"

.PP
Definition at line \fB246\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangePort\\__construct()\fP\&.
.SS "const CHANGE_PORT_SAME_ERROR = 'changePortSameError'"

.PP
Definition at line \fB247\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangePort\\processWindow()\fP\&.
.SS "const CHANGE_PORT_TITLE = 'changePortTitle'"

.PP
Definition at line \fB244\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangePort\\__construct()\fP, and \fBActionChangePort\\processWindow()\fP\&.
.SS "const CHANGELOG = 'changelog'"

.PP
Definition at line \fB33\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const CHECK_PORT_TITLE = 'checkPortTitle'"

.PP
Definition at line \fB176\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\checkPort()\fP, \fBBinMailpit\\checkPort()\fP, \fBBinMariadb\\checkPort()\fP, \fBBinMemcached\\checkPort()\fP, \fBBinMysql\\checkPort()\fP, \fBBinPostgresql\\checkPort()\fP, and \fBBinXlight\\checkPort()\fP\&.
.SS "const CHECK_VERSION_AVAILABLE_TEXT = 'checkVersionAvailableText'"

.PP
Definition at line \fB330\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionCheckVersion\\showVersionUpdateWindow()\fP\&.
.SS "const CHECK_VERSION_CHANGELOG_TEXT = 'checkVersionChangelogText'"

.PP
Definition at line \fB331\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const CHECK_VERSION_LATEST_TEXT = 'checkVersionLatestText'"

.PP
Definition at line \fB332\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionCheckVersion\\showVersionOkMessageBox()\fP\&.
.SS "const CHECK_VERSION_TITLE = 'checkVersionTitle'"

.PP
Definition at line \fB329\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionCheckVersion\\showVersionOkMessageBox()\fP, and \fBActionCheckVersion\\showVersionUpdateWindow()\fP\&.
.SS "const COMPOSER = 'composer'"

.PP
Definition at line \fB142\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP, \fBToolConsoleZ\\getTabTitleComposer()\fP, and \fBToolComposer\\reload()\fP\&.
.SS "const CONSOLE = 'console'"

.PP
Definition at line \fB34\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppMariadb\\getMenuMariadb()\fP, \fBTplAppMysql\\getMenuMysql()\fP, \fBTplAppNodejs\\getMenuNodejs()\fP, \fBTplAppPostgresql\\getMenuPostgresql()\fP, \fBTplAppTools\\getMenuTools()\fP, and \fBToolConsoleZ\\getTabTitleDefault()\fP\&.
.SS "const CONSOLEZ = 'consolez'"

.PP
Definition at line \fB143\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBToolConsoleZ\\reload()\fP\&.
.SS "const DEBUG = 'debug'"

.PP
Definition at line \fB35\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugApache\\__construct()\fP, \fBActionDebugMariadb\\__construct()\fP, \fBActionDebugMysql\\__construct()\fP, \fBActionDebugPostgresql\\__construct()\fP, \fBTplAppApache\\getMenuApache()\fP, \fBTplAppMariadb\\getMenuMariadb()\fP, \fBTplAppMysql\\getMenuMysql()\fP, and \fBTplAppPostgresql\\getMenuPostgresql()\fP\&.
.SS "const DEBUG_APACHE_COMPILE_SETTINGS = 'debugApacheCompileSettings'"

.PP
Definition at line \fB305\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugApache\\__construct()\fP, and \fBTplAppApache\\getMenuApacheDebug()\fP\&.
.SS "const DEBUG_APACHE_COMPILED_MODULES = 'debugApacheCompiledModules'"

.PP
Definition at line \fB306\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugApache\\__construct()\fP, and \fBTplAppApache\\getMenuApacheDebug()\fP\&.
.SS "const DEBUG_APACHE_CONFIG_DIRECTIVES = 'debugApacheConfigDirectives'"

.PP
Definition at line \fB307\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugApache\\__construct()\fP, and \fBTplAppApache\\getMenuApacheDebug()\fP\&.
.SS "const DEBUG_APACHE_LOADED_MODULES = 'debugApacheLoadedModules'"

.PP
Definition at line \fB309\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugApache\\__construct()\fP, and \fBTplAppApache\\getMenuApacheDebug()\fP\&.
.SS "const DEBUG_APACHE_SYNTAX_CHECK = 'debugApacheSyntaxCheck'"

.PP
Definition at line \fB310\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugApache\\__construct()\fP, and \fBTplAppApache\\getMenuApacheDebug()\fP\&.
.SS "const DEBUG_APACHE_VERSION_NUMBER = 'debugApacheVersionNumber'"

.PP
Definition at line \fB304\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugApache\\__construct()\fP, and \fBTplAppApache\\getMenuApacheDebug()\fP\&.
.SS "const DEBUG_APACHE_VHOSTS_SETTINGS = 'debugApacheVhostsSettings'"

.PP
Definition at line \fB308\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugApache\\__construct()\fP, and \fBTplAppApache\\getMenuApacheDebug()\fP\&.
.SS "const DEBUG_MARIADB_SYNTAX_CHECK = 'debugMariadbSyntaxCheck'"

.PP
Definition at line \fB320\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugMariadb\\__construct()\fP, and \fBTplAppMariadb\\getMenuMariadbDebug()\fP\&.
.SS "const DEBUG_MARIADB_VARIABLES = 'debugMariadbVariables'"

.PP
Definition at line \fB319\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugMariadb\\__construct()\fP, and \fBTplAppMariadb\\getMenuMariadbDebug()\fP\&.
.SS "const DEBUG_MARIADB_VERSION = 'debugMariadbVersion'"

.PP
Definition at line \fB318\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugMariadb\\__construct()\fP, and \fBTplAppMariadb\\getMenuMariadbDebug()\fP\&.
.SS "const DEBUG_MYSQL_SYNTAX_CHECK = 'debugMysqlSyntaxCheck'"

.PP
Definition at line \fB315\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugMysql\\__construct()\fP, and \fBTplAppMysql\\getMenuMysqlDebug()\fP\&.
.SS "const DEBUG_MYSQL_VARIABLES = 'debugMysqlVariables'"

.PP
Definition at line \fB314\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugMysql\\__construct()\fP, and \fBTplAppMysql\\getMenuMysqlDebug()\fP\&.
.SS "const DEBUG_MYSQL_VERSION = 'debugMysqlVersion'"

.PP
Definition at line \fB313\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugMysql\\__construct()\fP, and \fBTplAppMysql\\getMenuMysqlDebug()\fP\&.
.SS "const DEBUG_POSTGRESQL_VERSION = 'debugPostgresqlVersion'"

.PP
Definition at line \fB323\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugPostgresql\\__construct()\fP, and \fBTplAppPostgresql\\getMenuPostgresqlDebug()\fP\&.
.SS "const DELETE_ALIAS = 'deleteAlias'"

.PP
Definition at line \fB209\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditAlias\\processWindow()\fP\&.
.SS "const DELETE_ALIAS_TITLE = 'deleteAliasTitle'"

.PP
Definition at line \fB208\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditAlias\\processWindow()\fP\&.
.SS "const DELETE_VHOST = 'deleteVhost'"

.PP
Definition at line \fB227\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditVhost\\processWindow()\fP\&.
.SS "const DELETE_VHOST_TITLE = 'deleteVhostTitle'"

.PP
Definition at line \fB226\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditVhost\\processWindow()\fP\&.
.SS "const DISABLED = 'disabled'"

.PP
Definition at line \fB36\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\processWindow()\fP\&.
.SS "const DISCORD = 'discord'"

.PP
Definition at line \fB37\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const DONATE = 'donate'"

.PP
Definition at line \fB38\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAbout\\__construct()\fP\&.
.SS "const DONATE_VIA = 'donateVia'"

.PP
Definition at line \fB39\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const DOWNLOAD = 'download'"

.PP
Definition at line \fB40\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionCheckVersion\\showVersionUpdateWindow()\fP\&.
.SS "const DOWNLOAD_MORE = 'downloadMore'"

.PP
Definition at line \fB41\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApache()\fP, \fBTplAppMailpit\\getMenuMailpit()\fP, \fBTplAppMariadb\\getMenuMariadb()\fP, \fBTplAppMemcached\\getMenuMemcached()\fP, \fBTplAppMysql\\getMenuMysql()\fP, \fBTplAppNodejs\\getMenuNodejs()\fP, \fBTplAppPhp\\getMenuPhp()\fP, \fBTplAppPostgresql\\getMenuPostgresql()\fP, and \fBTplAppXlight\\getMenuXlight()\fP\&.
.SS "const EDIT_ALIAS_TITLE = 'editAliasTitle'"

.PP
Definition at line \fB223\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditAlias\\__construct()\fP\&.
.SS "const EDIT_VHOST_TITLE = 'editVhostTitle'"

.PP
Definition at line \fB241\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditVhost\\__construct()\fP, and \fBActionEditVhost\\processWindow()\fP\&.
.SS "const ENABLE_BUNDLE_NOT_EXIST = 'enableBundleNotExist'"

.PP
Definition at line \fB346\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\setEnable()\fP, \fBBinMailpit\\setEnable()\fP, \fBBinMariadb\\setEnable()\fP, \fBBinMemcached\\setEnable()\fP, \fBBinMysql\\setEnable()\fP, \fBBinNodejs\\setEnable()\fP, \fBBinPhp\\setEnable()\fP, \fBBinPostgresql\\setEnable()\fP, and \fBBinXlight\\setEnable()\fP\&.
.SS "const ENABLE_TITLE = 'enableTitle'"

.PP
Definition at line \fB345\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\setEnable()\fP, \fBBinMailpit\\setEnable()\fP, \fBBinMariadb\\setEnable()\fP, \fBBinMemcached\\setEnable()\fP, \fBBinMysql\\setEnable()\fP, \fBBinNodejs\\setEnable()\fP, \fBBinPhp\\setEnable()\fP, \fBBinPostgresql\\setEnable()\fP, and \fBBinXlight\\setEnable()\fP\&.
.SS "const ENABLED = 'enabled'"

.PP
Definition at line \fB42\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const ERROR = 'error'"

.PP
Definition at line \fB43\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBNssm\\getError()\fP, \fBWin32Service\\getError()\fP, \fBRegistry\\getValue()\fP, and \fBRegistry\\setValue()\fP\&.
.SS "const ERROR_CONF_NOT_FOUND = 'errorConfNotFound'"

.PP
Definition at line \fB152\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBCore\\getAppVersion()\fP, \fBAppPhpmyadmin\\reload()\fP, \fBAppPhppgadmin\\reload()\fP, \fBBinApache\\reload()\fP, \fBBinMailpit\\reload()\fP, \fBBinMariadb\\reload()\fP, \fBBinMemcached\\reload()\fP, \fBBinMysql\\reload()\fP, \fBBinNodejs\\reload()\fP, \fBBinPhp\\reload()\fP, \fBBinPostgresql\\reload()\fP, \fBBinXlight\\reload()\fP, \fBToolBruno\\reload()\fP, \fBToolComposer\\reload()\fP, \fBToolConsoleZ\\reload()\fP, \fBToolGhostscript\\reload()\fP, \fBToolGit\\reload()\fP, \fBToolNgrok\\reload()\fP, \fBToolPerl\\reload()\fP, \fBToolPython\\reload()\fP, and \fBToolRuby\\reload()\fP\&.
.SS "const ERROR_EXE_NOT_FOUND = 'errorExeNotFound'"

.PP
Definition at line \fB153\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\reload()\fP, \fBBinMailpit\\reload()\fP, \fBBinMariadb\\reload()\fP, \fBBinMemcached\\reload()\fP, \fBBinMysql\\reload()\fP, \fBBinNodejs\\reload()\fP, \fBBinPhp\\reload()\fP, \fBBinPostgresql\\reload()\fP, \fBBinXlight\\reload()\fP, \fBToolBruno\\reload()\fP, \fBToolComposer\\reload()\fP, \fBToolConsoleZ\\reload()\fP, \fBToolGhostscript\\reload()\fP, \fBToolGit\\reload()\fP, \fBToolNgrok\\reload()\fP, \fBToolPerl\\reload()\fP, \fBToolPython\\reload()\fP, and \fBToolRuby\\reload()\fP\&.
.SS "const ERROR_FILE_NOT_FOUND = 'errorFileNotFound'"

.PP
Definition at line \fB154\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBAppPhpmyadmin\\reload()\fP, \fBAppPhppgadmin\\reload()\fP, \fBBinApache\\reload()\fP, \fBBinMailpit\\reload()\fP, \fBBinMariadb\\reload()\fP, \fBBinMemcached\\reload()\fP, \fBBinMysql\\reload()\fP, \fBBinNodejs\\reload()\fP, \fBBinPhp\\reload()\fP, \fBBinPostgresql\\reload()\fP, \fBBinXlight\\reload()\fP, \fBToolBruno\\reload()\fP, \fBToolComposer\\reload()\fP, \fBToolConsoleZ\\reload()\fP, \fBToolGhostscript\\reload()\fP, \fBToolGit\\reload()\fP, \fBToolNgrok\\reload()\fP, \fBToolPerl\\reload()\fP, \fBToolPython\\reload()\fP, and \fBToolRuby\\reload()\fP\&.
.SS "const ERROR_INVALID_PARAMETER = 'errorInvalidParameter'"

.PP
Definition at line \fB155\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\reload()\fP, \fBBinMailpit\\reload()\fP, \fBBinMariadb\\reload()\fP, \fBBinMemcached\\reload()\fP, \fBBinMysql\\reload()\fP, \fBBinPostgresql\\reload()\fP, \fBBinXlight\\reload()\fP, and \fBToolConsoleZ\\reload()\fP\&.
.SS "const EXECUTABLE = 'executable'"

.PP
Definition at line \fB44\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangeBrowser\\processWindow()\fP\&.
.SS "const EXIT_LEAVING_TEXT = 'exitLeavingText'"

.PP
Definition at line \fB289\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionQuit\\__construct()\fP\&.
.SS "const EXIT_REMOVE_SERVICE_TEXT = 'exitRemoveServiceText'"

.PP
Definition at line \fB290\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionQuit\\processWindow()\fP\&.
.SS "const EXIT_STOP_OTHER_PROCESS_TEXT = 'exitStopOtherProcessText'"

.PP
Definition at line \fB291\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionQuit\\processWindow()\fP\&.
.SS "const EXTENSIONS = 'extensions'"

.PP
Definition at line \fB45\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppPhp\\getMenuPhp()\fP\&.
.SS "const FACEBOOK = 'facebook'"

.PP
Definition at line \fB46\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const GENSSL_CREATED = 'genSslCreated'"

.PP
Definition at line \fB337\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionGenSslCertificate\\processWindow()\fP\&.
.SS "const GENSSL_CREATED_ERROR = 'genSslCreatedError'"

.PP
Definition at line \fB338\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionGenSslCertificate\\processWindow()\fP\&.
.SS "const GENSSL_PATH = 'genSslPath'"

.PP
Definition at line \fB336\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionGenSslCertificate\\processWindow()\fP\&.
.SS "const GENSSL_TITLE = 'genSslTitle'"

.PP
Definition at line \fB335\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionGenSslCertificate\\__construct()\fP, and \fBActionGenSslCertificate\\processWindow()\fP\&.
.SS "const GHOSTSCRIPT = 'ghostscript'"

.PP
Definition at line \fB144\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP, \fBToolConsoleZ\\getTabTitleGhostscript()\fP, and \fBToolGhostscript\\reload()\fP\&.
.SS "const GIT = 'git'"

.PP
Definition at line \fB145\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBToolConsoleZ\\getTabTitleGit()\fP, \fBTplAppGit\\process()\fP, and \fBToolGit\\reload()\fP\&.
.SS "const GIT_CONSOLE = 'gitConsole'"

.PP
Definition at line \fB47\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppGit\\getMenuGit()\fP\&.
.SS "const GITGUI = 'gitGui'"

.PP
Definition at line \fB48\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppGit\\getMenuGit()\fP\&.
.SS "const GITHUB = 'github'"

.PP
Definition at line \fB49\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAbout\\__construct()\fP\&.
.SS "const HELP = 'help'"

.PP
Definition at line \fB50\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuRight()\fP\&.
.SS "const HOMEPAGE_ABOUT_HTML = 'homepageAboutHtml'"

.PP
Definition at line \fB363\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_APC_TEXT = 'homepageApcText'"

.PP
Definition at line \fB369\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_BACK_TEXT = 'homepageBackText'"

.PP
Definition at line \fB372\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_LICENSE_TEXT = 'homepageLicenseText'"

.PP
Definition at line \fB364\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_MAILPIT_TEXT = 'homepageMailpitText'"

.PP
Definition at line \fB370\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_OFFICIAL_WEBSITE = 'homepageOfficialWebsite'"

.PP
Definition at line \fB360\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_PHPINFO_TEXT = 'homepagePhpinfoText'"

.PP
Definition at line \fB368\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_POST_ISSUE = 'homepagePostIssue'"

.PP
Definition at line \fB367\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_QUESTIONS_TEXT = 'homepageQuestionsText'"

.PP
Definition at line \fB366\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_QUESTIONS_TITLE = 'homepageQuestionsTitle'"

.PP
Definition at line \fB365\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_SERVICE_STARTED = 'homepageServiceStarted'"

.PP
Definition at line \fB361\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_SERVICE_STOPPED = 'homepageServiceStopped'"

.PP
Definition at line \fB362\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOMEPAGE_XLIGHT_TEXT = 'homepageXlightText'"

.PP
Definition at line \fB371\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const HOSTSEDITOR = 'hostseditor'"

.PP
Definition at line \fB51\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP\&.
.SS "const INSTALL_SERVICE_TITLE = 'installServiceTitle'"

.PP
Definition at line \fB184\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBUtil\\installService()\fP\&.
.SS "const LANG = 'lang'"

.PP
Definition at line \fB52\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppLang\\process()\fP\&.
.SS "const LICENSE = 'license'"

.PP
Definition at line \fB53\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const LOADING = 'loading'"

.PP
Definition at line \fB357\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionLoading\\__construct()\fP, and \fBWinBinder\\createProgressBar()\fP\&.
.SS "const LOCALE = 'locale'"

.PP
Definition at line \fB54\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const LOGS = 'logs'"

.PP
Definition at line \fB55\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppLogs\\process()\fP\&.
.SS "const LOGS_VERBOSE = 'logsVerbose'"

.PP
Definition at line \fB56\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppLogsVerbose\\process()\fP\&.
.SS "const MAILPIT = 'mailpit'"

.PP
Definition at line \fB129\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppMailpit\\getMenuMailpit()\fP, \fBTplAppMailpit\\process()\fP, and \fBBinMailpit\\reload()\fP\&.
.SS "const MARIADB = 'mariadb'"

.PP
Definition at line \fB130\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugMariadb\\__construct()\fP, \fBToolConsoleZ\\getTabTitleMariadb()\fP, \fBTplAppMariadb\\process()\fP, and \fBBinMariadb\\reload()\fP\&.
.SS "const MEMCACHED = 'memcached'"

.PP
Definition at line \fB128\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppMemcached\\process()\fP, and \fBBinMemcached\\reload()\fP\&.
.SS "const MENU_ABOUT = 'menuAbout'"

.PP
Definition at line \fB86\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuRight()\fP\&.
.SS "const MENU_ACCESS_LOGS = 'menuAccessLogs'"

.PP
Definition at line \fB87\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApache()\fP\&.
.SS "const MENU_ADD_ALIAS = 'menuAddAlias'"

.PP
Definition at line \fB88\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApacheAlias()\fP\&.
.SS "const MENU_ADD_VHOST = 'menuAddVhost'"

.PP
Definition at line \fB89\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApacheVhosts()\fP\&.
.SS "const MENU_CHANGE_PORT = 'menuChangePort'"

.PP
Definition at line \fB90\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApacheService()\fP, \fBTplAppMailpit\\getMenuMailpitService()\fP, \fBTplAppMariadb\\getMenuMariadbService()\fP, \fBTplAppMemcached\\getMenuMemcachedService()\fP, \fBTplAppMysql\\getMenuMysqlService()\fP, \fBTplAppPostgresql\\getMenuPostgresqlService()\fP, and \fBTplAppXlight\\getMenuXlightService()\fP\&.
.SS "const MENU_CHANGE_ROOT_PWD = 'menuChangeRootPwd'"

.PP
Definition at line \fB91\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppMariadb\\getMenuMariadbService()\fP, \fBTplAppMysql\\getMenuMysqlService()\fP, and \fBTplAppPostgresql\\getMenuPostgresqlService()\fP\&.
.SS "const MENU_CHECK_PORT = 'menuCheckPort'"

.PP
Definition at line \fB92\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApacheService()\fP, \fBTplAppMailpit\\getMenuMailpitService()\fP, \fBTplAppMariadb\\getMenuMariadbService()\fP, \fBTplAppMemcached\\getMenuMemcachedService()\fP, \fBTplAppMysql\\getMenuMysqlService()\fP, \fBTplAppPostgresql\\getMenuPostgresqlService()\fP, and \fBTplAppXlight\\getMenuXlightService()\fP\&.
.SS "const MENU_CHECK_UPDATE = 'menuCheckUpdate'"

.PP
Definition at line \fB93\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuRight()\fP\&.
.SS "const MENU_CLEAR_FOLDERS = 'menuClearFolders'"

.PP
Definition at line \fB94\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppClearFolders\\process()\fP\&.
.SS "const MENU_EDIT_ALIAS = 'menuEditAlias'"

.PP
Definition at line \fB95\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApacheAlias()\fP\&.
.SS "const MENU_EDIT_CONF = 'menuEditConf'"

.PP
Definition at line \fB96\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppEditConf\\process()\fP\&.
.SS "const MENU_EDIT_VHOST = 'menuEditVhost'"

.PP
Definition at line \fB97\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApacheVhosts()\fP\&.
.SS "const MENU_ENABLE = 'menuEnable'"

.PP
Definition at line \fB98\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApache()\fP, \fBTplAppMailpit\\getMenuMailpit()\fP, \fBTplAppMariadb\\getMenuMariadb()\fP, \fBTplAppMemcached\\getMenuMemcached()\fP, \fBTplAppMysql\\getMenuMysql()\fP, \fBTplAppNodejs\\getMenuNodejs()\fP, \fBTplAppPhp\\getMenuPhp()\fP, \fBTplAppPostgresql\\getMenuPostgresql()\fP, and \fBTplAppXlight\\getMenuXlight()\fP\&.
.SS "const MENU_ERROR_LOGS = 'menuErrorLogs'"

.PP
Definition at line \fB99\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApache()\fP, \fBTplAppMariadb\\getMenuMariadb()\fP, \fBTplAppMysql\\getMenuMysql()\fP, \fBTplAppPhp\\getMenuPhp()\fP, and \fBTplAppPostgresql\\getMenuPostgresql()\fP\&.
.SS "const MENU_GEN_SSL_CERTIFICATE = 'menuGenSslCertificate'"

.PP
Definition at line \fB100\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP\&.
.SS "const MENU_INSTALL_SERVICE = 'menuInstallService'"

.PP
Definition at line \fB101\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplService\\getItemInstall()\fP, \fBTplAppApache\\getMenuApacheService()\fP, \fBTplAppMailpit\\getMenuMailpitService()\fP, \fBTplAppMariadb\\getMenuMariadbService()\fP, \fBTplAppMemcached\\getMenuMemcachedService()\fP, \fBTplAppMysql\\getMenuMysqlService()\fP, \fBTplAppPostgresql\\getMenuPostgresqlService()\fP, and \fBTplAppXlight\\getMenuXlightService()\fP\&.
.SS "const MENU_LAUNCH_STARTUP = 'menuLaunchStartup'"

.PP
Definition at line \fB102\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppLaunchStartup\\process()\fP\&.
.SS "const MENU_LOCALHOST = 'menuLocalhost'"

.PP
Definition at line \fB103\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuLeft()\fP\&.
.SS "const MENU_LOGS = 'menuLogs'"

.PP
Definition at line \fB104\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppMailpit\\getMenuMailpit()\fP, \fBTplAppMemcached\\getMenuMemcached()\fP, and \fBTplAppXlight\\getMenuXlight()\fP\&.
.SS "const MENU_PUT_OFFLINE = 'menuPutOffline'"

.PP
Definition at line \fB105\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppOnline\\process()\fP\&.
.SS "const MENU_PUT_ONLINE = 'menuPutOnline'"

.PP
Definition at line \fB106\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppOnline\\process()\fP\&.
.SS "const MENU_REBUILD_INI = 'menuRebuildIni'"

.PP
Definition at line \fB107\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppRebuildIni\\process()\fP\&.
.SS "const MENU_REFRESH_REPOS = 'menuRefreshRepos'"

.PP
Definition at line \fB108\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppGit\\getMenuGit()\fP\&.
.SS "const MENU_REMOVE_SERVICE = 'menuRemoveService'"

.PP
Definition at line \fB109\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplService\\getItemRemove()\fP, \fBTplAppApache\\getMenuApacheService()\fP, \fBTplAppMailpit\\getMenuMailpitService()\fP, \fBTplAppMariadb\\getMenuMariadbService()\fP, \fBTplAppMemcached\\getMenuMemcachedService()\fP, \fBTplAppMysql\\getMenuMysqlService()\fP, \fBTplAppPostgresql\\getMenuPostgresqlService()\fP, and \fBTplAppXlight\\getMenuXlightService()\fP\&.
.SS "const MENU_RESTART_SERVICE = 'menuRestartService'"

.PP
Definition at line \fB110\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAestan\\getActionService()\fP, and \fBTplService\\getItemRestart()\fP\&.
.SS "const MENU_RESTART_SERVICES = 'menuRestartServices'"

.PP
Definition at line \fB111\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppServices\\process()\fP\&.
.SS "const MENU_REWRITE_LOGS = 'menuRewriteLogs'"

.PP
Definition at line \fB112\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApache()\fP\&.
.SS "const MENU_SCAN_REPOS_STARTUP = 'menuScanReposStartup'"

.PP
Definition at line \fB113\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppGit\\getMenuGit()\fP\&.
.SS "const MENU_SESSION_LOGS = 'menuSessionLogs'"

.PP
Definition at line \fB114\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const MENU_START_SERVICE = 'menuStartService'"

.PP
Definition at line \fB115\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAestan\\getActionService()\fP, and \fBTplService\\getItemStart()\fP\&.
.SS "const MENU_START_SERVICES = 'menuStartServices'"

.PP
Definition at line \fB116\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppServices\\process()\fP\&.
.SS "const MENU_STATS_LOGS = 'menuStatsLogs'"

.PP
Definition at line \fB117\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const MENU_STOP_SERVICE = 'menuStopService'"

.PP
Definition at line \fB118\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAestan\\getActionService()\fP, and \fBTplService\\getItemStop()\fP\&.
.SS "const MENU_STOP_SERVICES = 'menuStopServices'"

.PP
Definition at line \fB119\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppServices\\process()\fP\&.
.SS "const MENU_TRANSFER_LOGS = 'menuTransferLogs'"

.PP
Definition at line \fB120\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const MENU_UPDATE_ENV_PATH = 'menuUpdateEnvPath'"

.PP
Definition at line \fB121\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApacheService()\fP, \fBTplAppMailpit\\getMenuMailpitService()\fP, \fBTplAppMemcached\\getMenuMemcached()\fP, and \fBTplAppXlight\\getMenuXlightService()\fP\&.
.SS "const MENU_WWW_DIRECTORY = 'menuWwwDirectory'"

.PP
Definition at line \fB122\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuLeft()\fP\&.
.SS "const MODULES = 'modules'"

.PP
Definition at line \fB57\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApache()\fP\&.
.SS "const MYSQL = 'mysql'"

.PP
Definition at line \fB131\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugMysql\\__construct()\fP, \fBToolConsoleZ\\getTabTitleMysql()\fP, \fBTplAppMysql\\process()\fP, and \fBBinMysql\\reload()\fP\&.
.SS "const NAME = 'name'"

.PP
Definition at line \fB58\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionGenSslCertificate\\__construct()\fP\&.
.SS "const NGROK = 'ngrok'"

.PP
Definition at line \fB146\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP, \fBToolConsoleZ\\getTabTitleNgrok()\fP, and \fBToolNgrok\\reload()\fP\&.
.SS "const NODEJS = 'nodejs'"

.PP
Definition at line \fB132\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBToolConsoleZ\\getTabTitleNodejs()\fP, \fBTplAppNodejs\\process()\fP, and \fBBinNodejs\\reload()\fP\&.
.SS "const NONE_RUNNING_HINT = 'noneRunningHint'"

.PP
Definition at line \fB25\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAestan\\getSectionMessages()\fP\&.
.SS "const PAYPAL = 'paypal'"

.PP
Definition at line \fB59\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const PEAR = 'pear'"

.PP
Definition at line \fB127\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP, and \fBToolConsoleZ\\getTabTitlePear()\fP\&.
.SS "const PERL = 'perl'"

.PP
Definition at line \fB147\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP, \fBToolConsoleZ\\getTabTitlePerl()\fP, and \fBToolPerl\\reload()\fP\&.
.SS "const PHP = 'php'"

.PP
Definition at line \fB126\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppPhp\\process()\fP, \fBActionSwitchVersion\\processWindow()\fP, and \fBBinPhp\\reload()\fP\&.
.SS "const PHP_INCPT = 'phpIncpt'"

.PP
Definition at line \fB167\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinPhp\\updateConfig()\fP\&.
.SS "const PHPMYADMIN = 'phpmyadmin'"

.PP
Definition at line \fB137\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApps\\getMenuApps()\fP, and \fBAppPhpmyadmin\\reload()\fP\&.
.SS "const PHPPGADMIN = 'phppgadmin'"

.PP
Definition at line \fB138\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApps\\getMenuApps()\fP, and \fBAppPhppgadmin\\reload()\fP\&.
.SS "const PORT_CHANGED = 'portChanged'"

.PP
Definition at line \fB181\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionChangePort\\processWindow()\fP\&.
.SS "const PORT_NOT_USED = 'portNotUsed'"

.PP
Definition at line \fB178\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\checkPort()\fP, \fBBinMailpit\\checkPort()\fP, \fBBinMariadb\\checkPort()\fP, \fBBinMemcached\\checkPort()\fP, \fBBinMysql\\checkPort()\fP, \fBBinXlight\\checkPort()\fP, and \fBBinPostgresql\\handleNonPostgresUsage()\fP\&.
.SS "const PORT_NOT_USED_BY = 'portNotUsedBy'"

.PP
Definition at line \fB179\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\checkPort()\fP, \fBBinMailpit\\checkPort()\fP, \fBBinMariadb\\checkPort()\fP, \fBBinMemcached\\checkPort()\fP, \fBBinMysql\\checkPort()\fP, \fBBinXlight\\checkPort()\fP, \fBUtil\\installService()\fP, and \fBActionChangePort\\processWindow()\fP\&.
.SS "const PORT_USED_BY = 'portUsedBy'"

.PP
Definition at line \fB177\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinApache\\checkPort()\fP, \fBBinMailpit\\checkPort()\fP, \fBBinMariadb\\checkPort()\fP, \fBBinMemcached\\checkPort()\fP, \fBBinMysql\\checkPort()\fP, \fBBinPostgresql\\checkPort()\fP, and \fBBinXlight\\checkPort()\fP\&.
.SS "const PORT_USED_BY_ANOTHER_DBMS = 'portUsedByAnotherDbms'"

.PP
Definition at line \fB180\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBBinMariadb\\checkPort()\fP, \fBBinMysql\\checkPort()\fP, and \fBBinPostgresql\\handleNonPostgresUsage()\fP\&.
.SS "const POSTGRESQL = 'postgresql'"

.PP
Definition at line \fB133\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionDebugPostgresql\\__construct()\fP, \fBToolConsoleZ\\getTabTitlePostgresql()\fP, \fBTplAppPostgresql\\process()\fP, and \fBBinPostgresql\\reload()\fP\&.
.SS "const PWGEN = 'pwgen'"

.PP
Definition at line \fB61\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP\&.
.SS "const PYTHON = 'python'"

.PP
Definition at line \fB148\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppPython\\getMenuPython()\fP, \fBToolConsoleZ\\getTabTitlePython()\fP, \fBTplAppPython\\process()\fP, and \fBToolPython\\reload()\fP\&.
.SS "const PYTHON_CONSOLE = 'pythonConsole'"

.PP
Definition at line \fB60\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppPython\\getMenuPython()\fP\&.
.SS "const QUIT = 'quit'"

.PP
Definition at line \fB62\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionQuit\\__construct()\fP, and \fBTplAppExit\\process()\fP\&.
.SS "const READ_CHANGELOG = 'readChangelog'"

.PP
Definition at line \fB63\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const REGISTRY_SET_ERROR_TEXT = 'registrySetErrorText'"

.PP
Definition at line \fB326\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBRegistry\\setValue()\fP\&.
.SS "const RELOAD = 'reload'"

.PP
Definition at line \fB64\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppReload\\process()\fP\&.
.SS "const REMOVE_SERVICE_TITLE = 'removeServiceTitle'"

.PP
Definition at line \fB190\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const REPOS = 'repos'"

.PP
Definition at line \fB65\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppGit\\getMenuGit()\fP\&.
.SS "const RESTART = 'restart'"

.PP
Definition at line \fB66\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const RESTART_SERVICE_ERROR = 'restartServiceError'"

.PP
Definition at line \fB205\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const RESTART_SERVICE_TITLE = 'restartServiceTitle'"

.PP
Definition at line \fB204\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const RESTART_TEXT = 'restartText'"

.PP
Definition at line \fB342\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionRestart\\__construct()\fP\&.
.SS "const RESTART_TITLE = 'restartTitle'"

.PP
Definition at line \fB341\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionRestart\\__construct()\fP\&.
.SS "const RUBY = 'ruby'"

.PP
Definition at line \fB149\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP, \fBToolConsoleZ\\getTabTitleRuby()\fP, and \fBToolRuby\\reload()\fP\&.
.SS "const SERVICE = 'service'"

.PP
Definition at line \fB67\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApache()\fP, \fBTplAppMailpit\\getMenuMailpit()\fP, \fBTplAppMariadb\\getMenuMariadb()\fP, \fBTplAppMemcached\\getMenuMemcached()\fP, \fBTplAppMysql\\getMenuMysql()\fP, \fBTplAppPostgresql\\getMenuPostgresql()\fP, and \fBTplAppXlight\\getMenuXlight()\fP\&.
.SS "const SERVICE_ALREADY_INSTALLED = 'serviceAlreadyInstalled'"

.PP
Definition at line \fB185\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBUtil\\installService()\fP\&.
.SS "const SERVICE_INSTALL_ERROR = 'serviceInstallError'"

.PP
Definition at line \fB187\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBUtil\\installService()\fP\&.
.SS "const SERVICE_INSTALLED = 'serviceInstalled'"

.PP
Definition at line \fB186\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBUtil\\installService()\fP\&.
.SS "const SERVICE_NOT_EXIST = 'serviceNotExist'"

.PP
Definition at line \fB191\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const SERVICE_REMOVE_ERROR = 'serviceRemoveError'"

.PP
Definition at line \fB193\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const SERVICE_REMOVED = 'serviceRemoved'"

.PP
Definition at line \fB192\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const SETTINGS = 'settings'"

.PP
Definition at line \fB68\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppPhp\\getMenuPhp()\fP\&.
.SS "const SOME_RUNNING_HINT = 'someRunningHint'"

.PP
Definition at line \fB24\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAestan\\getSectionMessages()\fP\&.
.SS "const SSL = 'ssl'"

.PP
Definition at line \fB69\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const START_SERVICE_ERROR = 'startServiceError'"

.PP
Definition at line \fB197\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBUtil\\startService()\fP\&.
.SS "const START_SERVICE_TITLE = 'startServiceTitle'"

.PP
Definition at line \fB196\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchVersion\\processWindow()\fP, and \fBUtil\\startService()\fP\&.
.SS "const STARTUP = 'startup'"

.PP
Definition at line \fB70\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\__construct()\fP\&.
.SS "const STARTUP_CHANGE_PATH_TEXT = 'startupChangePathText'"

.PP
Definition at line \fB271\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\changePath()\fP\&.
.SS "const STARTUP_CHECK_BROWSER_TEXT = 'startupCheckBrowserText'"

.PP
Definition at line \fB263\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\checkBrowser()\fP\&.
.SS "const STARTUP_CHECK_PATH_TEXT = 'startupCheckPathText'"

.PP
Definition at line \fB269\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\checkPath()\fP\&.
.SS "const STARTUP_CHECK_SERVICE_TEXT = 'startupCheckServiceText'"

.PP
Definition at line \fB275\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\installServices()\fP\&.
.SS "const STARTUP_CLEAN_OLD_BEHAVIORS_TEXT = 'startupCleanOldBehaviorsText'"

.PP
Definition at line \fB266\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\cleanOldBehaviors()\fP\&.
.SS "const STARTUP_CLEAN_TMP_TEXT = 'startupCleanTmpText'"

.PP
Definition at line \fB265\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\cleanTmpFolders()\fP\&.
.SS "const STARTUP_ERROR_TITLE = 'startupErrorTitle'"

.PP
Definition at line \fB279\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\processWindow()\fP\&.
.SS "const STARTUP_GEN_SSL_CRT_TEXT = 'startupGenSslCrtText'"

.PP
Definition at line \fB286\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\createSslCrts()\fP\&.
.SS "const STARTUP_INSTALL_SERVICE_TEXT = 'startupInstallServiceText'"

.PP
Definition at line \fB276\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\installServices()\fP\&.
.SS "const STARTUP_KILL_OLD_PROCS_TEXT = 'startupKillOldProcsText'"

.PP
Definition at line \fB261\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\killOldInstances()\fP\&.
.SS "const STARTUP_PREPARE_RESTART_TEXT = 'startupPrepareRestartText'"

.PP
Definition at line \fB278\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\processWindow()\fP\&.
.SS "const STARTUP_REFRESH_ALIAS_TEXT = 'startupRefreshAliasText'"

.PP
Definition at line \fB267\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\refreshAliases()\fP\&.
.SS "const STARTUP_REFRESH_GIT_REPOS_TEXT = 'startupRefreshGitReposText'"

.PP
Definition at line \fB285\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\refreshGitRepos()\fP\&.
.SS "const STARTUP_REFRESH_HOSTNAME_TEXT = 'startupRefreshHostnameText'"

.PP
Definition at line \fB262\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\refreshHostname()\fP\&.
.SS "const STARTUP_REFRESH_VHOSTS_TEXT = 'startupRefreshVhostsText'"

.PP
Definition at line \fB268\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\refreshVhosts()\fP\&.
.SS "const STARTUP_REGISTRY_ERROR_TEXT = 'startupRegistryErrorText'"

.PP
Definition at line \fB273\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\checkBinsRegKey()\fP, \fBActionStartup\\checkPathRegKey()\fP, and \fBActionStartup\\checkSystemPathRegKey()\fP\&.
.SS "const STARTUP_REGISTRY_TEXT = 'startupRegistryText'"

.PP
Definition at line \fB272\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\checkBinsRegKey()\fP, \fBActionStartup\\checkPathRegKey()\fP, and \fBActionStartup\\checkSystemPathRegKey()\fP\&.
.SS "const STARTUP_ROTATION_LOGS_TEXT = 'startupRotationLogsText'"

.PP
Definition at line \fB260\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\rotationLogs()\fP\&.
.SS "const STARTUP_SCAN_FOLDERS_TEXT = 'startupScanFoldersText'"

.PP
Definition at line \fB270\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\scanFolders()\fP\&.
.SS "const STARTUP_SERVICE_CREATE_ERROR = 'startupServiceCreateError'"

.PP
Definition at line \fB281\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\installServices()\fP\&.
.SS "const STARTUP_SERVICE_ERROR = 'startupServiceError'"

.PP
Definition at line \fB280\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\installServices()\fP\&.
.SS "const STARTUP_SERVICE_PORT_ERROR = 'startupServicePortError'"

.PP
Definition at line \fB284\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\installServices()\fP\&.
.SS "const STARTUP_SERVICE_START_ERROR = 'startupServiceStartError'"

.PP
Definition at line \fB282\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\installServices()\fP\&.
.SS "const STARTUP_SERVICE_SYNTAX_ERROR = 'startupServiceSyntaxError'"

.PP
Definition at line \fB283\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBUtil\\installService()\fP, \fBActionStartup\\installServices()\fP, and \fBUtil\\startService()\fP\&.
.SS "const STARTUP_START_SERVICE_TEXT = 'startupStartServiceText'"

.PP
Definition at line \fB277\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\installServices()\fP\&.
.SS "const STARTUP_STARTING_TEXT = 'startupStartingText'"

.PP
Definition at line \fB259\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\__construct()\fP\&.
.SS "const STARTUP_SYS_INFOS = 'startupSysInfos'"

.PP
Definition at line \fB264\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\sysInfos()\fP\&.
.SS "const STARTUP_UPDATE_CONFIG_TEXT = 'startupUpdateConfigText'"

.PP
Definition at line \fB274\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionStartup\\updateConfig()\fP\&.
.SS "const STATUS = 'status'"

.PP
Definition at line \fB71\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBNssm\\getError()\fP, and \fBWin32Service\\getError()\fP\&.
.SS "const STATUS_PAGE = 'statusPage'"

.PP
Definition at line \fB72\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const STOP_SERVICE_ERROR = 'stopServiceError'"

.PP
Definition at line \fB201\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const STOP_SERVICE_TITLE = 'stopServiceTitle'"

.PP
Definition at line \fB200\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchVersion\\processWindow()\fP\&.
.SS "const SWITCH_PHP_SETTING_NOT_FOUND = 'switchPhpSettingNotFound'"

.PP
Definition at line \fB173\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchPhpParam\\__construct()\fP\&.
.SS "const SWITCH_PHP_SETTING_TITLE = 'switchPhpSettingTitle'"

.PP
Definition at line \fB172\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchPhpParam\\__construct()\fP\&.
.SS "const SWITCH_VERSION_OK = 'switchVersionOk'"

.PP
Definition at line \fB164\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchVersion\\processWindow()\fP\&.
.SS "const SWITCH_VERSION_OK_RESTART = 'switchVersionOkRestart'"

.PP
Definition at line \fB165\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchVersion\\processWindow()\fP\&.
.SS "const SWITCH_VERSION_REGISTRY = 'switchVersionRegistry'"

.PP
Definition at line \fB161\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchVersion\\processWindow()\fP\&.
.SS "const SWITCH_VERSION_RELOAD_BINS = 'switchVersionReloadBins'"

.PP
Definition at line \fB160\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchVersion\\processWindow()\fP\&.
.SS "const SWITCH_VERSION_RELOAD_CONFIG = 'switchVersionReloadConfig'"

.PP
Definition at line \fB159\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchVersion\\processWindow()\fP\&.
.SS "const SWITCH_VERSION_RESET_SERVICES = 'switchVersionResetServices'"

.PP
Definition at line \fB162\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchVersion\\processWindow()\fP\&.
.SS "const SWITCH_VERSION_SAME_ERROR = 'switchVersionSameError'"

.PP
Definition at line \fB163\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchVersion\\processWindow()\fP\&.
.SS "const SWITCH_VERSION_TITLE = 'switchVersionTitle'"

.PP
Definition at line \fB158\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionSwitchVersion\\__construct()\fP, \fBBinApache\\updateConfig()\fP, \fBBinMailpit\\updateConfig()\fP, \fBBinMariadb\\updateConfig()\fP, \fBBinMemcached\\updateConfig()\fP, \fBBinMysql\\updateConfig()\fP, \fBBinNodejs\\updateConfig()\fP, \fBBinPhp\\updateConfig()\fP, \fBBinPostgresql\\updateConfig()\fP, and \fBBinXlight\\updateConfig()\fP\&.
.SS "const TARGET = 'target'"

.PP
Definition at line \fB73\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionGenSslCertificate\\__construct()\fP\&.
.SS "const TOOLS = 'tools'"

.PP
Definition at line \fB74\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppTools\\process()\fP\&.
.SS "const VERBOSE_DEBUG = 'verboseDebug'"

.PP
Definition at line \fB75\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppLogsVerbose\\getMenuLogsVerbose()\fP\&.
.SS "const VERBOSE_REPORT = 'verboseReport'"

.PP
Definition at line \fB76\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppLogsVerbose\\getMenuLogsVerbose()\fP\&.
.SS "const VERBOSE_SIMPLE = 'verboseSimple'"

.PP
Definition at line \fB77\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppLogsVerbose\\getMenuLogsVerbose()\fP\&.
.SS "const VERBOSE_TRACE = 'verboseTrace'"

.PP
Definition at line \fB78\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppLogsVerbose\\getMenuLogsVerbose()\fP\&.
.SS "const VERSION = 'version'"

.PP
Definition at line \fB79\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const VERSION_URL = 'https://github\&.com/Bearsampp/Bearsampp/releases/tag/'"

.PP
Definition at line \fB81\fP of file \fBclass\&.lang\&.php\fP\&.
.SS "const VERSIONS = 'versions'"

.PP
Definition at line \fB80\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApache()\fP, \fBTplAppMailpit\\getMenuMailpit()\fP, \fBTplAppMariadb\\getMenuMariadb()\fP, \fBTplAppMemcached\\getMenuMemcached()\fP, \fBTplAppMysql\\getMenuMysql()\fP, \fBTplAppNodejs\\getMenuNodejs()\fP, \fBTplAppPhp\\getMenuPhp()\fP, \fBTplAppPostgresql\\getMenuPostgresql()\fP, and \fBTplAppXlight\\getMenuXlight()\fP\&.
.SS "const VHOST_ALREADY_EXISTS = 'vhostAlreadyExists'"

.PP
Definition at line \fB238\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddVhost\\processWindow()\fP, and \fBActionEditVhost\\processWindow()\fP\&.
.SS "const VHOST_CREATED = 'vhostCreated'"

.PP
Definition at line \fB239\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddVhost\\processWindow()\fP, and \fBActionEditVhost\\processWindow()\fP\&.
.SS "const VHOST_CREATED_ERROR = 'vhostCreatedError'"

.PP
Definition at line \fB240\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddVhost\\processWindow()\fP, and \fBActionEditVhost\\processWindow()\fP\&.
.SS "const VHOST_DOC_ROOT_PATH = 'vhostDocRootPath'"

.PP
Definition at line \fB236\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddVhost\\processWindow()\fP, and \fBActionEditVhost\\processWindow()\fP\&.
.SS "const VHOST_DOCUMENT_ROOT_LABEL = 'vhostDocumentRootLabel'"

.PP
Definition at line \fB234\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddVhost\\__construct()\fP, and \fBActionEditVhost\\__construct()\fP\&.
.SS "const VHOST_EXP_LABEL = 'vhostExpLabel'"

.PP
Definition at line \fB235\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddVhost\\__construct()\fP, \fBActionEditVhost\\__construct()\fP, \fBActionAddVhost\\processWindow()\fP, and \fBActionEditVhost\\processWindow()\fP\&.
.SS "const VHOST_NOT_VALID_DOMAIN = 'vhostNotValidDomain'"

.PP
Definition at line \fB237\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddVhost\\processWindow()\fP, and \fBActionEditVhost\\processWindow()\fP\&.
.SS "const VHOST_REMOVE_ERROR = 'vhostRemoveError'"

.PP
Definition at line \fB229\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditVhost\\processWindow()\fP\&.
.SS "const VHOST_REMOVED = 'vhostRemoved'"

.PP
Definition at line \fB228\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionEditVhost\\processWindow()\fP\&.
.SS "const VHOST_SERVER_NAME_LABEL = 'vhostServerNameLabel'"

.PP
Definition at line \fB233\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAddVhost\\__construct()\fP, and \fBActionEditVhost\\__construct()\fP\&.
.SS "const VIRTUAL_HOSTS = 'virtualHosts'"

.PP
Definition at line \fB82\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppApache\\getMenuApache()\fP\&.
.SS "const WEBSITE = 'website'"

.PP
Definition at line \fB83\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBActionAbout\\__construct()\fP\&.
.SS "const XLIGHT = 'xlight'"

.PP
Definition at line \fB134\fP of file \fBclass\&.lang\&.php\fP\&.
.PP
Referenced by \fBTplAppXlight\\process()\fP, and \fBBinXlight\\reload()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
