.TH "Splash" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Splash
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBgetWbWindow\fP ()"
.br
.ti -1c
.RI "\fBincrProgressBar\fP ($nb=1)"
.br
.ti -1c
.RI "\fBinit\fP ($title, $gauge, $text)"
.br
.ti -1c
.RI "\fBsetTextLoading\fP ($caption)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBWINDOW_HEIGHT\fP = 90"
.br
.ti -1c
.RI "const \fBWINDOW_WIDTH\fP = 460"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$currentImg\fP"
.br
.ti -1c
.RI "\fB$wbImage\fP"
.br
.ti -1c
.RI "\fB$wbProgressBar\fP"
.br
.ti -1c
.RI "\fB$wbTextLoading\fP"
.br
.ti -1c
.RI "\fB$wbWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBSplash\fP

.PP
This class represents a splash screen with a progress bar for the \fBBearsampp\fP application\&. It provides methods to initialize the splash screen, set loading text, and increment the progress bar\&. 
.PP
Definition at line \fB16\fP of file \fBclass\&.splash\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"
\fBSplash\fP constructor\&.

.PP
Initializes the \fBSplash\fP class and sets the current image to null\&. 
.PP
Definition at line \fB34\fP of file \fBclass\&.splash\&.php\fP\&.
.nf
35     {
36         Util::logInitClass($this);
37         $this\->currentImg = null;
38     }
.PP
.fi

.PP
References \fBUtil\\logInitClass()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getWbWindow ()"
Retrieves the window object of the splash screen\&.

.PP
\fBReturns\fP
.RS 4
mixed The window object of the splash screen\&. 
.RE
.PP

.PP
Definition at line \fB103\fP of file \fBclass\&.splash\&.php\fP\&.
.nf
104     {
105         return $this\->wbWindow;
106     }
.PP
.fi

.PP
References \fB$wbWindow\fP\&.
.SS "incrProgressBar ( $nb = \fR1\fP)"
Increments the progress bar by a specified number of steps\&.

.PP
\fBParameters\fP
.RS 4
\fI$nb\fP The number of steps to increment the progress bar by\&. Default is 1\&. 
.RE
.PP

.PP
Definition at line \fB85\fP of file \fBclass\&.splash\&.php\fP\&.
.nf
86     {
87         global $bearsamppCore, $bearsamppWinbinder;
88 
89         for ($i = 0; $i < $nb; $i++) {
90             $bearsamppWinbinder\->drawImage($this\->wbWindow, $bearsamppCore\->getImagesPath() \&. '/bearsampp\&.bmp', 4, 4, 32, 32);
91             $bearsamppWinbinder\->incrProgressBar($this\->wbProgressBar);
92         }
93 
94         $bearsamppWinbinder\->wait();
95         $bearsamppWinbinder\->wait($this\->wbWindow);
96     }
.PP
.fi

.PP
References \fB$bearsamppCore\fP\&.
.PP
Referenced by \fBinit()\fP\&.
.SS "init ( $title,  $gauge,  $text)"
Initializes the splash screen\&.

.PP
\fBParameters\fP
.RS 4
\fI$title\fP The title of the splash screen window\&. 
.br
\fI$gauge\fP The maximum value for the progress bar\&. 
.br
\fI$text\fP The initial loading text to display\&. 
.RE
.PP

.PP
Definition at line \fB47\fP of file \fBclass\&.splash\&.php\fP\&.
.nf
48     {
49         global $bearsamppCore, $bearsamppWinbinder;
50 
51         $bearsamppWinbinder\->reset();
52 
53         $screenArea = explode(' ', $bearsamppWinbinder\->getSystemInfo(WinBinder::SYSINFO_WORKAREA));
54         $screenWidth = intval($screenArea[2]);
55         $screenHeight = intval($screenArea[3]);
56         $xPos = $screenWidth \- self::WINDOW_WIDTH;
57         $yPos = $screenHeight \- self::WINDOW_HEIGHT \- 5;
58 
59         $this\->wbWindow = $bearsamppWinbinder\->createWindow(null, ToolDialog, $title, $xPos, $yPos, self::WINDOW_WIDTH, self::WINDOW_HEIGHT, WBC_TOP | WBC_READONLY, null);
60         $this\->wbImage = $bearsamppWinbinder\->drawImage($this\->wbWindow, $bearsamppCore\->getImagesPath() \&. '/bearsampp\&.bmp');
61         $this\->wbProgressBar = $bearsamppWinbinder\->createProgressBar($this\->wbWindow, $gauge + 1, 42, 24, 390, 15);
62 
63         $this\->setTextLoading($text);
64         $this\->incrProgressBar();
65     }
.PP
.fi

.PP
References \fB$bearsamppCore\fP, \fBincrProgressBar()\fP, \fBsetTextLoading()\fP, and \fBWinBinder\\SYSINFO_WORKAREA\fP\&.
.SS "setTextLoading ( $caption)"
Sets the loading text on the splash screen\&.

.PP
\fBParameters\fP
.RS 4
\fI$caption\fP The loading text to display\&. 
.RE
.PP

.PP
Definition at line \fB72\fP of file \fBclass\&.splash\&.php\fP\&.
.nf
73     {
74         global $bearsamppWinbinder;
75 
76         $bearsamppWinbinder\->drawRect($this\->wbWindow, 42, 0, self::WINDOW_WIDTH \- 42, self::WINDOW_HEIGHT);
77         $this\->wbTextLoading = $bearsamppWinbinder\->drawText($this\->wbWindow, $caption, 42, 0, self::WINDOW_WIDTH \- 44, 25);
78     }
.PP
.fi

.PP
Referenced by \fBinit()\fP\&.
.SH "Field Documentation"
.PP 
.SS "$currentImg\fR [private]\fP"

.PP
Definition at line \fB27\fP of file \fBclass\&.splash\&.php\fP\&.
.SS "$wbImage\fR [private]\fP"

.PP
Definition at line \fB23\fP of file \fBclass\&.splash\&.php\fP\&.
.SS "$wbProgressBar\fR [private]\fP"

.PP
Definition at line \fB25\fP of file \fBclass\&.splash\&.php\fP\&.
.SS "$wbTextLoading\fR [private]\fP"

.PP
Definition at line \fB24\fP of file \fBclass\&.splash\&.php\fP\&.
.SS "$wbWindow\fR [private]\fP"

.PP
Definition at line \fB22\fP of file \fBclass\&.splash\&.php\fP\&.
.PP
Referenced by \fBgetWbWindow()\fP\&.
.SS "const WINDOW_HEIGHT = 90"

.PP
Definition at line \fB20\fP of file \fBclass\&.splash\&.php\fP\&.
.SS "const WINDOW_WIDTH = 460"

.PP
Definition at line \fB19\fP of file \fBclass\&.splash\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
