Symlinks
NAME
Symlinks
SYNOPSIS
Public Member Functions
__construct ($root)
Static Public Member Functions
static deleteCurrentSymlinks ()
Data Fields
const APACHE_SYMLINK = 'apache'
const BRUNO_SYMLINK = 'bruno'
const COMPOSER_SYMLINK = 'composer'
const CONSOLEZ_SYMLINK = 'consolez'
const GHOSTSCRIPT_SYMLINK = 'ghostscript'
const GIT_SYMLINK = 'git'
const MAILPIT_SYMLINK = 'mailpit'
const MARIADB_SYMLINK = 'mariadb'
const MEMCACHED_SYMLINK = 'memcached'
const MYSQL_SYMLINK = 'mysql'
const NGROK_SYMLINK = 'ngrok'
const NODEJS_SYMLINK = 'nodejs'
const PERL_SYMLINK = 'perl'
const PHP_SYMLINK = 'php'
const PHPMYADMIN_SYMLINK = 'phpmyadmin'
const PHPPGADMIN_SYMLINK = 'phppgadmin'
const POSTGRESQL_SYMLINK = 'postgresql'
const PYTHON_SYMLINK = 'python'
const RUBY_SYMLINK = 'ruby'
const XLIGHT_SYMLINK = 'xlight'
Private Attributes
$root
Detailed Description
Manages the creation and deletion of symbolic links for various components within the Bearsampp environment.
Definition at line 14 of file class.symlinks.php.
Constructor & Destructor Documentation
__construct ( $root)
Constructs a Symlinks object and initializes paths to current directories.
Parameters
$root The root object associated with the Bearsampp environment.
Definition at line 47 of file class.symlinks.php.
    {
        $this->root = $root;
        $this->initializePaths();
    }
References $root.
Member Function Documentation
deleteCurrentSymlinks () [static]
Deletes all symbolic links listed in the arrayOfCurrents. Logs each operation's success or failure.
This method iterates over a predefined list of symbolic link paths and attempts to delete each one. If a symbolic link does not exist, an error is logged. If the deletion is successful, a debug message is logged.
@global Root $bearsamppRoot The root object providing access to system paths. @global Core $bearsamppCore The core object providing core functionalities.
Definition at line 63 of file class.symlinks.php.
    {
        global $bearsamppRoot, $bearsamppCore;
        // Check to see if purging is necessary
        $appsPath = $bearsamppRoot->getAppsPath();
        $binPath = $bearsamppRoot->getBinPath();
        $toolsPath = $bearsamppRoot->getToolsPath();
        $array = [
            self::PHPMYADMIN_SYMLINK => $appsPath . '/phpmyadmin/current',
            self::PHPPGADMIN_SYMLINK => $appsPath . '/phppgadmin/current',
            self::APACHE_SYMLINK => $binPath . '/apache/current',
            self::MARIADB_SYMLINK => $binPath . '/mariadb/current',
            self::MEMCACHED_SYMLINK => $binPath . '/memcached/current',
            self::MYSQL_SYMLINK => $binPath . '/mysql/current',
            self::NODEJS_SYMLINK => $binPath . '/nodejs/current',
            self::PHP_SYMLINK => $binPath . '/php/current',
            self::POSTGRESQL_SYMLINK => $binPath . '/postgresql/current',
            self::COMPOSER_SYMLINK => $toolsPath . '/composer/current',
            self::CONSOLEZ_SYMLINK => $toolsPath . '/consolez/current',
            self::GHOSTSCRIPT_SYMLINK => $toolsPath . '/ghostscript/current',
            self::GIT_SYMLINK => $toolsPath . '/git/current',
            self::NGROK_SYMLINK => $toolsPath . '/ngrok/current',
            self::PERL_SYMLINK => $toolsPath . '/perl/current',
            self::PYTHON_SYMLINK => $toolsPath . '/python/current',
            self::RUBY_SYMLINK => $toolsPath . '/ruby/current',
            self::XLIGHT_SYMLINK => $binPath . '/xlight/current',
            self::MAILPIT_SYMLINK => $binPath . '/mailpit/current',
            self::BRUNO_SYMLINK => $toolsPath . '/bruno/current'
        ];
        // Fix for PHP 8.2: Add null checks before accessing array elements
        if (!is_array($array) || empty($array)) {
            Util::logError('Current symlinks array is not initialized or empty.');
            return;
        }
        // Purge "current" symlinks
        foreach ($array as $name => $path) {
            // Skip if path is null
            if (empty($path)) {
                continue;
            }
            
            if (!file_exists($path)) {
                // Skip if the symlink doesn't exist - no need to log an error
                continue;
            }
            
            // Simple approach: use rmdir for directories and unlink for files
            if (is_dir($path)) {
                if (@rmdir($path)) {
                    Util::logDebug('Deleted directory symlink: ' . $path);
                }
            } else {
                if (@unlink($path)) {
                    Util::logDebug('Deleted file symlink: ' . $path);
                }
            }
        }
    }
References $bearsamppCore, $bearsamppRoot, Util\logDebug(), and Util\logError().
Referenced by ActionQuit\processWindow().
Field Documentation
$root [private]
Definition at line 40 of file class.symlinks.php.
Referenced by __construct().
const APACHE_SYMLINK = 'apache'
Definition at line 18 of file class.symlinks.php.
const BRUNO_SYMLINK = 'bruno'
Definition at line 35 of file class.symlinks.php.
const COMPOSER_SYMLINK = 'composer'
Definition at line 25 of file class.symlinks.php.
const CONSOLEZ_SYMLINK = 'consolez'
Definition at line 26 of file class.symlinks.php.
const GHOSTSCRIPT_SYMLINK = 'ghostscript'
Definition at line 27 of file class.symlinks.php.
const GIT_SYMLINK = 'git'
Definition at line 28 of file class.symlinks.php.
const MAILPIT_SYMLINK = 'mailpit'
Definition at line 34 of file class.symlinks.php.
const MARIADB_SYMLINK = 'mariadb'
Definition at line 19 of file class.symlinks.php.
const MEMCACHED_SYMLINK = 'memcached'
Definition at line 20 of file class.symlinks.php.
const MYSQL_SYMLINK = 'mysql'
Definition at line 21 of file class.symlinks.php.
const NGROK_SYMLINK = 'ngrok'
Definition at line 29 of file class.symlinks.php.
const NODEJS_SYMLINK = 'nodejs'
Definition at line 22 of file class.symlinks.php.
const PERL_SYMLINK = 'perl'
Definition at line 30 of file class.symlinks.php.
const PHP_SYMLINK = 'php'
Definition at line 23 of file class.symlinks.php.
const PHPMYADMIN_SYMLINK = 'phpmyadmin'
Definition at line 16 of file class.symlinks.php.
const PHPPGADMIN_SYMLINK = 'phppgadmin'
Definition at line 17 of file class.symlinks.php.
const POSTGRESQL_SYMLINK = 'postgresql'
Definition at line 24 of file class.symlinks.php.
const PYTHON_SYMLINK = 'python'
Definition at line 31 of file class.symlinks.php.
const RUBY_SYMLINK = 'ruby'
Definition at line 32 of file class.symlinks.php.
const XLIGHT_SYMLINK = 'xlight'
Definition at line 33 of file class.symlinks.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.