.TH "ToolBruno" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToolBruno
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($id, $type)"
.br
.ti -1c
.RI "\fBgetExe\fP ()"
.br
.ti -1c
.RI "\fBreload\fP ($id=null, $type=null)"
.br
.ti -1c
.RI "\fBsetVersion\fP ($version)"
.br
.in -1c

Public Member Functions inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBgetCurrentPath\fP ()"
.br
.ti -1c
.RI "\fBgetId\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetRelease\fP ()"
.br
.ti -1c
.RI "\fBgetRootPath\fP ()"
.br
.ti -1c
.RI "\fBgetSymlinkPath\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBgetVersion\fP ()"
.br
.ti -1c
.RI "\fBgetVersionList\fP ()"
.br
.ti -1c
.RI "\fBisEnable\fP ()"
.br
.ti -1c
.RI "\fBupdate\fP ($sub=0, $showWindow=false)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBLOCAL_CFG_EXE\fP = 'brunoExe'"
.br
.ti -1c
.RI "const \fBROOT_CFG_VERSION\fP = 'brunoVersion'"
.br
.in -1c

Data Fields inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "const \fBBUNDLE_RELEASE\fP = 'bundleRelease'"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$exe\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBreplace\fP ($key, $value)"
.br
.ti -1c
.RI "\fBreplaceAll\fP ($params)"
.br
.ti -1c
.RI "\fBupdateConfig\fP ($version=null, $sub=0, $showWindow=false)"
.br
.in -1c

Protected Attributes inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "\fB$bearsamppConf\fP"
.br
.ti -1c
.RI "\fB$bearsamppConfRaw\fP"
.br
.ti -1c
.RI "\fB$currentPath\fP"
.br
.ti -1c
.RI "\fB$enable\fP"
.br
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$release\fP = 'N/A'"
.br
.ti -1c
.RI "\fB$rootPath\fP"
.br
.ti -1c
.RI "\fB$symlinkPath\fP"
.br
.ti -1c
.RI "\fB$version\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBToolBruno\fP

.PP
This class represents the Bruno tool module in the \fBBearsampp\fP application\&. It extends the abstract \fBModule\fP class and provides specific functionalities for managing the Bruno IDE tool, including setting versions, and retrieving the executable path\&. 
.PP
Definition at line \fB19\fP of file \fBclass\&.tool\&.bruno\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $id,  $type)"
Constructor for the \fBToolBruno\fP class\&.

.PP
Initializes the \fBToolBruno\fP instance by logging the initialization and reloading the module configuration with the provided ID and type\&.

.PP
\fBParameters\fP
.RS 4
\fI$id\fP The ID of the module\&. 
.br
\fI$type\fP The type of the module\&. 
.RE
.PP

.PP
Definition at line \fB47\fP of file \fBclass\&.tool\&.bruno\&.php\fP\&.
.nf
47                                             {
48         Util::logInitClass($this);
49         $this\->reload($id, $type);
50     }
.PP
.fi

.PP
References \fBModule\\$id\fP, \fBModule\\$type\fP, \fBUtil\\logInitClass()\fP, and \fBreload()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getExe ()"
Gets the path to the Bruno executable\&.

.PP
\fBReturns\fP
.RS 4
string The path to the Bruno executable\&. 
.RE
.PP

.PP
Definition at line \fB113\fP of file \fBclass\&.tool\&.bruno\&.php\fP\&.
.nf
113                              {
114         return $this\->exe;
115     }
.PP
.fi

.PP
References \fB$exe\fP\&.
.SS "reload ( $id = \fRnull\fP,  $type = \fRnull\fP)"
Reloads the module configuration based on the provided ID and type\&.

.PP
This method overrides the parent reload method to include additional configurations specific to the Bruno tool\&. It sets the name, version, and executable path, and logs errors if the module is not properly configured\&.

.PP
\fBParameters\fP
.RS 4
\fI$id\fP The ID of the module\&. If null, the current ID is used\&. 
.br
\fI$type\fP The type of the module\&. If null, the current type is used\&. 
.RE
.PP

.PP
Reimplemented from \fBModule\fP\&.
.PP
Definition at line \fB62\fP of file \fBclass\&.tool\&.bruno\&.php\fP\&.
.nf
62                                                      {
63         global $bearsamppConfig, $bearsamppLang;
64         Util::logReloadClass($this);
65 
66         $this\->name = $bearsamppLang\->getValue(Lang::BRUNO);
67         $this\->version = $bearsamppConfig\->getRaw(self::ROOT_CFG_VERSION);
68         parent::reload($id, $type);
69 
70         if ($this\->bearsamppConfRaw !== false) {
71             $this\->exe = $this\->symlinkPath \&. '/' \&. $this\->bearsamppConfRaw[self::LOCAL_CFG_EXE];
72         }
73 
74         if (!$this\->enable) {
75             Util::logInfo($this\->name \&. ' is not enabled!');
76             return;
77         }
78         if (!is_dir($this\->currentPath)) {
79             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_FILE_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->currentPath));
80         }
81         if (!is_dir($this\->symlinkPath)) {
82             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_FILE_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->symlinkPath));
83             return;
84         }
85         if (!is_file($this\->bearsamppConf)) {
86             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_CONF_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->bearsamppConf));
87         }
88         if (!is_file($this\->exe)) {
89             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_EXE_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->exe));
90         }
91     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, \fB$bearsamppLang\fP, \fBModule\\$id\fP, \fBModule\\$type\fP, \fBLang\\BRUNO\fP, \fBLang\\ERROR_CONF_NOT_FOUND\fP, \fBLang\\ERROR_EXE_NOT_FOUND\fP, \fBLang\\ERROR_FILE_NOT_FOUND\fP, \fBUtil\\logError()\fP, \fBUtil\\logInfo()\fP, and \fBUtil\\logReloadClass()\fP\&.
.PP
Referenced by \fB__construct()\fP, and \fBsetVersion()\fP\&.
.SS "setVersion ( $version)"
Sets the version of the Bruno IDE tool\&.

.PP
This method updates the version in the configuration and reloads the module to apply the new version\&.

.PP
\fBParameters\fP
.RS 4
\fI$version\fP The version to set\&. 
.RE
.PP

.PP
Reimplemented from \fBModule\fP\&.
.PP
Definition at line \fB101\fP of file \fBclass\&.tool\&.bruno\&.php\fP\&.
.nf
101                                          {
102         global $bearsamppConfig;
103         $this\->version = $version;
104         $bearsamppConfig\->replace(self::ROOT_CFG_VERSION, $version);
105         $this\->reload();
106     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, \fBModule\\$version\fP, and \fBreload()\fP\&.
.SH "Field Documentation"
.PP 
.SS "$exe\fR [private]\fP"

.PP
Definition at line \fB36\fP of file \fBclass\&.tool\&.bruno\&.php\fP\&.
.PP
Referenced by \fBgetExe()\fP\&.
.SS "const LOCAL_CFG_EXE = 'brunoExe'"
Configuration key for the Bruno executable in the local configuration\&. 
.PP
Definition at line \fB29\fP of file \fBclass\&.tool\&.bruno\&.php\fP\&.
.SS "const ROOT_CFG_VERSION = 'brunoVersion'"
Configuration key for the Bruno version in the root configuration\&. 
.PP
Definition at line \fB24\fP of file \fBclass\&.tool\&.bruno\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
