.TH "ToolNgrok" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToolNgrok
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($id, $type)"
.br
.ti -1c
.RI "\fBgetExe\fP ()"
.br
.ti -1c
.RI "\fBreload\fP ($id=null, $type=null)"
.br
.ti -1c
.RI "\fBsetVersion\fP ($version)"
.br
.in -1c

Public Member Functions inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBgetCurrentPath\fP ()"
.br
.ti -1c
.RI "\fBgetId\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetRelease\fP ()"
.br
.ti -1c
.RI "\fBgetRootPath\fP ()"
.br
.ti -1c
.RI "\fBgetSymlinkPath\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBgetVersion\fP ()"
.br
.ti -1c
.RI "\fBgetVersionList\fP ()"
.br
.ti -1c
.RI "\fBisEnable\fP ()"
.br
.ti -1c
.RI "\fBupdate\fP ($sub=0, $showWindow=false)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBLOCAL_CFG_EXE\fP = 'ngrokExe'"
.br
.ti -1c
.RI "const \fBROOT_CFG_VERSION\fP = 'ngrokVersion'"
.br
.in -1c

Data Fields inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "const \fBBUNDLE_RELEASE\fP = 'bundleRelease'"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$exe\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBreplace\fP ($key, $value)"
.br
.ti -1c
.RI "\fBreplaceAll\fP ($params)"
.br
.ti -1c
.RI "\fBupdateConfig\fP ($version=null, $sub=0, $showWindow=false)"
.br
.in -1c

Protected Attributes inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "\fB$bearsamppConf\fP"
.br
.ti -1c
.RI "\fB$bearsamppConfRaw\fP"
.br
.ti -1c
.RI "\fB$currentPath\fP"
.br
.ti -1c
.RI "\fB$enable\fP"
.br
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$release\fP = 'N/A'"
.br
.ti -1c
.RI "\fB$rootPath\fP"
.br
.ti -1c
.RI "\fB$symlinkPath\fP"
.br
.ti -1c
.RI "\fB$version\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBToolNgrok\fP

.PP
This class represents the Ngrok tool module in the \fBBearsampp\fP application\&. It extends the \fBModule\fP class and provides functionalities specific to Ngrok, such as loading configurations, setting versions, and retrieving executable paths\&. 
.PP
Definition at line \fB17\fP of file \fBclass\&.tool\&.ngrok\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $id,  $type)"
Constructor for the \fBToolNgrok\fP class\&.

.PP
\fBParameters\fP
.RS 4
\fI$id\fP The ID of the module\&. 
.br
\fI$type\fP The type of the module\&. 
.RE
.PP

.PP
Definition at line \fB40\fP of file \fBclass\&.tool\&.ngrok\&.php\fP\&.
.nf
40                                             {
41         Util::logInitClass($this);
42         $this\->reload($id, $type);
43     }
.PP
.fi

.PP
References \fBModule\\$id\fP, \fBModule\\$type\fP, \fBUtil\\logInitClass()\fP, and \fBreload()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getExe ()"
Gets the path to the Ngrok executable\&.

.PP
\fBReturns\fP
.RS 4
string The path to the Ngrok executable\&. 
.RE
.PP

.PP
Definition at line \fB99\fP of file \fBclass\&.tool\&.ngrok\&.php\fP\&.
.nf
99                              {
100         return $this\->exe;
101     }
.PP
.fi

.PP
References \fB$exe\fP\&.
.SS "reload ( $id = \fRnull\fP,  $type = \fRnull\fP)"
Reloads the Ngrok module configuration based on the provided ID and type\&.

.PP
\fBParameters\fP
.RS 4
\fI$id\fP The ID of the module\&. If null, the current ID is used\&. 
.br
\fI$type\fP The type of the module\&. If null, the current type is used\&. 
.RE
.PP

.PP
Reimplemented from \fBModule\fP\&.
.PP
Definition at line \fB51\fP of file \fBclass\&.tool\&.ngrok\&.php\fP\&.
.nf
51                                                      {
52         global $bearsamppConfig, $bearsamppLang;
53         Util::logReloadClass($this);
54 
55         $this\->name = $bearsamppLang\->getValue(Lang::NGROK);
56         $this\->version = $bearsamppConfig\->getRaw(self::ROOT_CFG_VERSION);
57         parent::reload($id, $type);
58 
59         if ($this\->bearsamppConfRaw !== false) {
60             $this\->exe = $this\->symlinkPath \&. '/' \&. $this\->bearsamppConfRaw[self::LOCAL_CFG_EXE];
61         }
62 
63         if (!$this\->enable) {
64             Util::logInfo($this\->name \&. ' is not enabled!');
65             return;
66         }
67         if (!is_dir($this\->currentPath)) {
68             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_FILE_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->currentPath));
69         }
70         if (!is_dir($this\->symlinkPath)) {
71             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_FILE_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->symlinkPath));
72             return;
73         }
74         if (!is_file($this\->bearsamppConf)) {
75             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_CONF_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->bearsamppConf));
76         }
77         if (!is_file($this\->exe)) {
78             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_EXE_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->exe));
79         }
80     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, \fB$bearsamppLang\fP, \fBModule\\$id\fP, \fBModule\\$type\fP, \fBLang\\ERROR_CONF_NOT_FOUND\fP, \fBLang\\ERROR_EXE_NOT_FOUND\fP, \fBLang\\ERROR_FILE_NOT_FOUND\fP, \fBUtil\\logError()\fP, \fBUtil\\logInfo()\fP, \fBUtil\\logReloadClass()\fP, and \fBLang\\NGROK\fP\&.
.PP
Referenced by \fB__construct()\fP, and \fBsetVersion()\fP\&.
.SS "setVersion ( $version)"
Sets the version of the Ngrok module and reloads the configuration\&.

.PP
\fBParameters\fP
.RS 4
\fI$version\fP The version to set\&. 
.RE
.PP

.PP
Reimplemented from \fBModule\fP\&.
.PP
Definition at line \fB87\fP of file \fBclass\&.tool\&.ngrok\&.php\fP\&.
.nf
87                                          {
88         global $bearsamppConfig;
89         $this\->version = $version;
90         $bearsamppConfig\->replace(self::ROOT_CFG_VERSION, $version);
91         $this\->reload();
92     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, \fBModule\\$version\fP, and \fBreload()\fP\&.
.SH "Field Documentation"
.PP 
.SS "$exe\fR [private]\fP"

.PP
Definition at line \fB32\fP of file \fBclass\&.tool\&.ngrok\&.php\fP\&.
.PP
Referenced by \fBgetExe()\fP\&.
.SS "const LOCAL_CFG_EXE = 'ngrokExe'"
Configuration key for the Ngrok executable in the local configuration\&. 
.PP
Definition at line \fB27\fP of file \fBclass\&.tool\&.ngrok\&.php\fP\&.
.SS "const ROOT_CFG_VERSION = 'ngrokVersion'"
Configuration key for the Ngrok version in the root configuration\&. 
.PP
Definition at line \fB22\fP of file \fBclass\&.tool\&.ngrok\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
