ToolNgrok
NAME
ToolNgrok
SYNOPSIS
Inherits Module.
Public Member Functions
__construct ($id, $type)
getExe ()
reload ($id=null, $type=null)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_EXE = 'ngrokExe'
const ROOT_CFG_VERSION = 'ngrokVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Private Attributes
$exe
Additional Inherited Members
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class ToolNgrok
This class represents the Ngrok tool module in the Bearsampp application. It extends the Module class and provides functionalities specific to Ngrok, such as loading configurations, setting versions, and retrieving executable paths.
Definition at line 17 of file class.tool.ngrok.php.
Constructor & Destructor Documentation
__construct ( $id, $type)
Constructor for the ToolNgrok class.
Parameters
$id The ID of the module.
$type The type of the module.
Definition at line 40 of file class.tool.ngrok.php.
                                            {
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getExe ()
Gets the path to the Ngrok executable.
Returns
string The path to the Ngrok executable.
Definition at line 99 of file class.tool.ngrok.php.
                             {
        return $this->exe;
    }
References $exe.
reload ( $id = null, $type = null)
Reloads the Ngrok module configuration based on the provided ID and type.
Parameters
$id The ID of the module. If null, the current ID is used.
$type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 51 of file class.tool.ngrok.php.
                                                     {
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::NGROK);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Util\logError(), Util\logInfo(), Util\logReloadClass(), and Lang\NGROK.
Referenced by __construct(), and setVersion().
setVersion ( $version)
Sets the version of the Ngrok module and reloads the configuration.
Parameters
$version The version to set.
Reimplemented from Module.
Definition at line 87 of file class.tool.ngrok.php.
                                         {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Field Documentation
$exe [private]
Definition at line 32 of file class.tool.ngrok.php.
Referenced by getExe().
const LOCAL_CFG_EXE = 'ngrokExe'
Configuration key for the Ngrok executable in the local configuration.
Definition at line 27 of file class.tool.ngrok.php.
const ROOT_CFG_VERSION = 'ngrokVersion'
Configuration key for the Ngrok version in the root configuration.
Definition at line 22 of file class.tool.ngrok.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.