ToolBruno
NAME
ToolBruno
SYNOPSIS
Inherits Module.
Public Member Functions
__construct ($id, $type)
getExe ()
reload ($id=null, $type=null)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_EXE = 'brunoExe'
const ROOT_CFG_VERSION = 'brunoVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Private Attributes
$exe
Additional Inherited Members
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class ToolBruno
This class represents the Bruno tool module in the Bearsampp application. It extends the abstract Module class and provides specific functionalities for managing the Bruno IDE tool, including setting versions, and retrieving the executable path.
Definition at line 19 of file class.tool.bruno.php.
Constructor & Destructor Documentation
__construct ( $id, $type)
Constructor for the ToolBruno class.
Initializes the ToolBruno instance by logging the initialization and reloading the module configuration with the provided ID and type.
Parameters
$id The ID of the module.
$type The type of the module.
Definition at line 47 of file class.tool.bruno.php.
                                            {
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getExe ()
Gets the path to the Bruno executable.
Returns
string The path to the Bruno executable.
Definition at line 113 of file class.tool.bruno.php.
                             {
        return $this->exe;
    }
References $exe.
reload ( $id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
This method overrides the parent reload method to include additional configurations specific to the Bruno tool. It sets the name, version, and executable path, and logs errors if the module is not properly configured.
Parameters
$id The ID of the module. If null, the current ID is used.
$type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 62 of file class.tool.bruno.php.
                                                     {
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::BRUNO);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\BRUNO, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Util\logError(), Util\logInfo(), and Util\logReloadClass().
Referenced by __construct(), and setVersion().
setVersion ( $version)
Sets the version of the Bruno IDE tool.
This method updates the version in the configuration and reloads the module to apply the new version.
Parameters
$version The version to set.
Reimplemented from Module.
Definition at line 101 of file class.tool.bruno.php.
                                         {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Field Documentation
$exe [private]
Definition at line 36 of file class.tool.bruno.php.
Referenced by getExe().
const LOCAL_CFG_EXE = 'brunoExe'
Configuration key for the Bruno executable in the local configuration.
Definition at line 29 of file class.tool.bruno.php.
const ROOT_CFG_VERSION = 'brunoVersion'
Configuration key for the Bruno version in the root configuration.
Definition at line 24 of file class.tool.bruno.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.