ToolGhostscript
NAME
ToolGhostscript
SYNOPSIS
Inherits Module.
Public Member Functions
__construct ($id, $type)
getExe ()
getExeConsole ()
reload ($id=null, $type=null)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_EXE = 'ghostscriptExe'
const LOCAL_CFG_EXE_CONSOLE = 'ghostscriptExeConsole'
const ROOT_CFG_VERSION = 'ghostscriptVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Private Attributes
$exe
$exeConsole
Additional Inherited Members
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class ToolGhostscript
This class represents the Ghostscript tool module in the Bearsampp application. It extends the Module class and provides functionalities specific to Ghostscript, such as loading configurations, setting versions, and retrieving executable paths.
Definition at line 17 of file class.tool.ghostscript.php.
Constructor & Destructor Documentation
__construct ( $id, $type)
Constructor for the ToolGhostscript class.
Parameters
$id The ID of the module.
$type The type of the module.
Definition at line 32 of file class.tool.ghostscript.php.
                                            {
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getExe ()
Gets the path to the Ghostscript executable.
Returns
string The path to the Ghostscript executable.
Definition at line 95 of file class.tool.ghostscript.php.
                             {
        return $this->exe;
    }
References $exe.
getExeConsole ()
Gets the path to the Ghostscript console executable.
Returns
string The path to the Ghostscript console executable.
Definition at line 104 of file class.tool.ghostscript.php.
                                    {
        return $this->exeConsole;
    }
References $exeConsole.
reload ( $id = null, $type = null)
Reloads the Ghostscript module configuration based on the provided ID and type.
Parameters
$id The ID of the module. If null, the current ID is used.
$type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 43 of file class.tool.ghostscript.php.
                                                     {
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::GHOSTSCRIPT);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->exeConsole = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE_CONSOLE];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
        }
        if (!is_file($this->exeConsole)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exeConsole));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\GHOSTSCRIPT, Util\logError(), Util\logInfo(), and Util\logReloadClass().
Referenced by __construct(), and setVersion().
setVersion ( $version)
Sets the version of the Ghostscript module and reloads the configuration.
Parameters
$version The version to set.
Reimplemented from Module.
Definition at line 83 of file class.tool.ghostscript.php.
                                         {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Field Documentation
$exe [private]
Definition at line 23 of file class.tool.ghostscript.php.
Referenced by getExe().
$exeConsole [private]
Definition at line 24 of file class.tool.ghostscript.php.
Referenced by getExeConsole().
const LOCAL_CFG_EXE = 'ghostscriptExe'
Definition at line 20 of file class.tool.ghostscript.php.
const LOCAL_CFG_EXE_CONSOLE = 'ghostscriptExeConsole'
Definition at line 21 of file class.tool.ghostscript.php.
const ROOT_CFG_VERSION = 'ghostscriptVersion'
Definition at line 19 of file class.tool.ghostscript.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.