Tools
NAME
Tools
SYNOPSIS
Public Member Functions
__construct ()
getAll ()
getBruno ()
getComposer ()
getConsoleZ ()
getGhostscript ()
getGit ()
getGitGui ()
getNgrok ()
getPerl ()
getPython ()
getRuby ()
update ()
Data Fields
const TYPE = 'tools'
Private Attributes
$bruno
$composer
$consolez
$ghostscript
$git
$ngrok
$perl
$python
$ruby
Detailed Description
Class Tools
This class manages various tool modules in the Bearsampp application. It provides methods to retrieve and update the configuration of these tools.
Definition at line 17 of file class.tools.php.
Constructor & Destructor Documentation
__construct ()
Constructor for the Tools class.
Definition at line 72 of file class.tools.php.
    {
    }
Member Function Documentation
getAll ()
Retrieves all tool instances.
Returns
array An array of all tool instances.
Definition at line 92 of file class.tools.php.
    {
        return array(
            $this->getBruno(),
            $this->getComposer(),
            $this->getConsoleZ(),
            $this->getGhostscript(),
            $this->getGit(),
            $this->getNgrok(),
            $this->getPerl(),
            $this->getPython(),
            $this->getRuby(),
        );
    }
References getBruno(), getComposer(), getConsoleZ(), getGhostscript(), getGit(), getNgrok(), getPerl(), getPython(), and getRuby().
Referenced by update().
getBruno ()
Retrieves the Bruno tool instance.
Returns
ToolBruno The Bruno tool instance.
Definition at line 112 of file class.tools.php.
    {
        if ($this->bruno == null) {
            $this->bruno = new ToolBruno('bruno', self::TYPE);
        }
        return $this->bruno;
    }
References $bruno.
Referenced by getAll().
getComposer ()
Retrieves the Composer tool instance.
Returns
ToolComposer The Composer tool instance.
Definition at line 125 of file class.tools.php.
    {
        if ($this->composer == null) {
            $this->composer = new ToolComposer('composer', self::TYPE);
        }
        return $this->composer;
    }
References $composer.
Referenced by getAll().
getConsoleZ ()
Retrieves the ConsoleZ tool instance.
Returns
ToolConsoleZ The ConsoleZ tool instance.
Definition at line 138 of file class.tools.php.
    {
        if ($this->consolez == null) {
            $this->consolez = new ToolConsoleZ('consolez', self::TYPE);
        }
        return $this->consolez;
    }
References $consolez.
Referenced by getAll().
getGhostscript ()
Retrieves the Ghostscript tool instance.
Returns
ToolGhostscript The Ghostscript tool instance.
Definition at line 151 of file class.tools.php.
    {
        if ($this->ghostscript == null) {
            $this->ghostscript = new ToolGhostscript('ghostscript', self::TYPE);
        }
        return $this->ghostscript;
    }
References $ghostscript.
Referenced by getAll().
getGit ()
Retrieves the Git tool instance.
Returns
ToolGit The Git tool instance.
Definition at line 164 of file class.tools.php.
    {
        if ($this->git == null) {
            $this->git = new ToolGit('git', self::TYPE);
        }
        return $this->git;
    }
References $git.
Referenced by getAll().
getGitGui ()
Retrieves the Git GUI tool instance.
Returns
ToolGit The Git GUI tool instance.
Definition at line 177 of file class.tools.php.
    {
        if ($this->git == null) {
            $this->git = new ToolGit('git-gui', self::TYPE);
        }
        return $this->git;
    }
References $git.
getNgrok ()
Retrieves the Ngrok tool instance.
Returns
ToolNgrok The Ngrok tool instance.
Definition at line 190 of file class.tools.php.
    {
        if ($this->ngrok == null) {
            $this->ngrok = new ToolNgrok('ngrok', self::TYPE);
        }
        return $this->ngrok;
    }
References $ngrok.
Referenced by getAll().
getPerl ()
Retrieves the Perl tool instance.
Returns
ToolPerl The Perl tool instance.
Definition at line 203 of file class.tools.php.
    {
        if ($this->perl == null) {
            $this->perl = new ToolPerl('perl', self::TYPE);
        }
        return $this->perl;
    }
References $perl.
Referenced by getAll().
getPython ()
Retrieves the Python tool instance.
Returns
ToolPython The Python tool instance.
Definition at line 216 of file class.tools.php.
    {
        if ($this->python == null) {
            $this->python = new ToolPython('python', self::TYPE);
        }
        return $this->python;
    }
References $python.
Referenced by getAll().
getRuby ()
Retrieves the Ruby tool instance.
Returns
ToolRuby The Ruby tool instance.
Definition at line 229 of file class.tools.php.
    {
        if ($this->ruby == null) {
            $this->ruby = new ToolRuby('ruby', self::TYPE);
        }
        return $this->ruby;
    }
References $ruby.
Referenced by getAll().
update ()
Updates the configuration of all tools.
Definition at line 79 of file class.tools.php.
    {
        Util::logInfo('Update tools config');
        foreach ($this->getAll() as $tool) {
            $tool->update();
        }
    }
References getAll(), and Util\logInfo().
Field Documentation
$bruno [private]
Definition at line 32 of file class.tools.php.
Referenced by getBruno().
$composer [private]
Definition at line 27 of file class.tools.php.
Referenced by getComposer().
$consolez [private]
Definition at line 37 of file class.tools.php.
Referenced by getConsoleZ().
$ghostscript [private]
Definition at line 42 of file class.tools.php.
Referenced by getGhostscript().
$git [private]
Definition at line 47 of file class.tools.php.
Referenced by getGit(), and getGitGui().
$ngrok [private]
Definition at line 52 of file class.tools.php.
Referenced by getNgrok().
$perl [private]
Definition at line 57 of file class.tools.php.
Referenced by getPerl().
$python [private]
Definition at line 62 of file class.tools.php.
Referenced by getPython().
$ruby [private]
Definition at line 67 of file class.tools.php.
Referenced by getRuby().
const TYPE = 'tools'
The type of the tools.
Definition at line 22 of file class.tools.php.
Referenced by Module\reload().
Author
Generated automatically by Doxygen for Bearsampp from the source code.