.TH "ToolComposer" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ToolComposer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModule\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($id, $type)"
.br
.ti -1c
.RI "\fBgetExe\fP ()"
.br
.ti -1c
.RI "\fBreload\fP ($id=null, $type=null)"
.br
.ti -1c
.RI "\fBsetVersion\fP ($version)"
.br
.in -1c

Public Member Functions inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBgetCurrentPath\fP ()"
.br
.ti -1c
.RI "\fBgetId\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetRelease\fP ()"
.br
.ti -1c
.RI "\fBgetRootPath\fP ()"
.br
.ti -1c
.RI "\fBgetSymlinkPath\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBgetVersion\fP ()"
.br
.ti -1c
.RI "\fBgetVersionList\fP ()"
.br
.ti -1c
.RI "\fBisEnable\fP ()"
.br
.ti -1c
.RI "\fBupdate\fP ($sub=0, $showWindow=false)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBLOCAL_CFG_EXE\fP = 'composerExe'"
.br
.ti -1c
.RI "const \fBROOT_CFG_VERSION\fP = 'composerVersion'"
.br
.in -1c

Data Fields inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "const \fBBUNDLE_RELEASE\fP = 'bundleRelease'"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fB$exe\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBreplace\fP ($key, $value)"
.br
.ti -1c
.RI "\fBreplaceAll\fP ($params)"
.br
.ti -1c
.RI "\fBupdateConfig\fP ($version=null, $sub=0, $showWindow=false)"
.br
.in -1c

Protected Attributes inherited from \fBModule\fP
.in +1c
.ti -1c
.RI "\fB$bearsamppConf\fP"
.br
.ti -1c
.RI "\fB$bearsamppConfRaw\fP"
.br
.ti -1c
.RI "\fB$currentPath\fP"
.br
.ti -1c
.RI "\fB$enable\fP"
.br
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$release\fP = 'N/A'"
.br
.ti -1c
.RI "\fB$rootPath\fP"
.br
.ti -1c
.RI "\fB$symlinkPath\fP"
.br
.ti -1c
.RI "\fB$version\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBToolComposer\fP

.PP
This class represents the Composer tool module in the \fBBearsampp\fP application\&. It extends the abstract \fBModule\fP class and provides functionalities specific to Composer\&. 
.PP
Definition at line \fB16\fP of file \fBclass\&.tool\&.composer\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $id,  $type)"
Constructor for the \fBToolComposer\fP class\&.

.PP
\fBParameters\fP
.RS 4
\fI$id\fP The ID of the module\&. 
.br
\fI$type\fP The type of the module\&. 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBclass\&.tool\&.composer\&.php\fP\&.
.nf
41                                             {
42         Util::logInitClass($this);
43         $this\->reload($id, $type);
44     }
.PP
.fi

.PP
References \fBModule\\$id\fP, \fBModule\\$type\fP, \fBUtil\\logInitClass()\fP, and \fBreload()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getExe ()"
Gets the path to the Composer executable\&.

.PP
\fBReturns\fP
.RS 4
string The path to the Composer executable\&. 
.RE
.PP

.PP
Definition at line \fB100\fP of file \fBclass\&.tool\&.composer\&.php\fP\&.
.nf
100                              {
101         return $this\->exe;
102     }
.PP
.fi

.PP
References \fB$exe\fP\&.
.SS "reload ( $id = \fRnull\fP,  $type = \fRnull\fP)"
Reloads the Composer module configuration based on the provided ID and type\&.

.PP
\fBParameters\fP
.RS 4
\fI$id\fP The ID of the module\&. If null, the current ID is used\&. 
.br
\fI$type\fP The type of the module\&. If null, the current type is used\&. 
.RE
.PP

.PP
Reimplemented from \fBModule\fP\&.
.PP
Definition at line \fB52\fP of file \fBclass\&.tool\&.composer\&.php\fP\&.
.nf
52                                                      {
53         global $bearsamppConfig, $bearsamppLang;
54         Util::logReloadClass($this);
55 
56         $this\->name = $bearsamppLang\->getValue(Lang::COMPOSER);
57         $this\->version = $bearsamppConfig\->getRaw(self::ROOT_CFG_VERSION);
58         parent::reload($id, $type);
59 
60         if ($this\->bearsamppConfRaw !== false) {
61             $this\->exe = $this\->symlinkPath \&. '/' \&. $this\->bearsamppConfRaw[self::LOCAL_CFG_EXE];
62         }
63 
64         if (!$this\->enable) {
65             Util::logInfo($this\->name \&. ' is not enabled!');
66             return;
67         }
68         if (!is_dir($this\->currentPath)) {
69             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_FILE_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->currentPath));
70         }
71         if (!is_dir($this\->symlinkPath)) {
72             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_FILE_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->symlinkPath));
73             return;
74         }
75         if (!is_file($this\->bearsamppConf)) {
76             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_CONF_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->bearsamppConf));
77         }
78         if (!is_file($this\->exe)) {
79             Util::logError(sprintf($bearsamppLang\->getValue(Lang::ERROR_EXE_NOT_FOUND), $this\->name \&. ' ' \&. $this\->version, $this\->exe));
80         }
81     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, \fB$bearsamppLang\fP, \fBModule\\$id\fP, \fBModule\\$type\fP, \fBLang\\COMPOSER\fP, \fBLang\\ERROR_CONF_NOT_FOUND\fP, \fBLang\\ERROR_EXE_NOT_FOUND\fP, \fBLang\\ERROR_FILE_NOT_FOUND\fP, \fBUtil\\logError()\fP, \fBUtil\\logInfo()\fP, and \fBUtil\\logReloadClass()\fP\&.
.PP
Referenced by \fB__construct()\fP, and \fBsetVersion()\fP\&.
.SS "setVersion ( $version)"
Sets the version of the Composer module and updates the configuration\&.

.PP
\fBParameters\fP
.RS 4
\fI$version\fP The version to set\&. 
.RE
.PP

.PP
Reimplemented from \fBModule\fP\&.
.PP
Definition at line \fB88\fP of file \fBclass\&.tool\&.composer\&.php\fP\&.
.nf
88                                          {
89         global $bearsamppConfig;
90         $this\->version = $version;
91         $bearsamppConfig\->replace(self::ROOT_CFG_VERSION, $version);
92         $this\->reload();
93     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, \fBModule\\$version\fP, and \fBreload()\fP\&.
.SH "Field Documentation"
.PP 
.SS "$exe\fR [private]\fP"

.PP
Definition at line \fB33\fP of file \fBclass\&.tool\&.composer\&.php\fP\&.
.PP
Referenced by \fBgetExe()\fP\&.
.SS "const LOCAL_CFG_EXE = 'composerExe'"
Configuration key for the Composer executable in the local configuration\&. 
.PP
Definition at line \fB26\fP of file \fBclass\&.tool\&.composer\&.php\fP\&.
.SS "const ROOT_CFG_VERSION = 'composerVersion'"
Configuration key for the Composer version in the root configuration\&. 
.PP
Definition at line \fB21\fP of file \fBclass\&.tool\&.composer\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
