.TH "TplAppOnline" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TplAppOnline
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetActionStatus\fP ($status)"
.br
.ti -1c
.RI "static \fBprocess\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBACTION\fP = 'status'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBTplAppOnline\fP

.PP
This class provides methods to handle the online/offline status of the \fBBearsampp\fP application\&. It includes functionalities for generating actions and menu items to switch the application between online and offline states\&. 
.PP
Definition at line \fB17\fP of file \fBclass\&.tpl\&.app\&.online\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getActionStatus ( $status)\fR [static]\fP"
Generates the action string to switch the online/offline status\&.

.PP
This method creates the action string for switching the application's online/offline status\&. It includes commands to restart relevant services and reload the application\&. The action string is used to define what happens when the status switch action is triggered\&.

.PP
\fBParameters\fP
.RS 4
\fI$status\fP The status to switch to (enabled or disabled)\&.
.RE
.PP
\fBReturns\fP
.RS 4
string The generated action string for switching the online/offline status\&. 
.RE
.PP

.PP
Definition at line \fB56\fP of file \fBclass\&.tpl\&.app\&.online\&.php\fP\&.
.nf
57     {
58         return TplApp::getActionRun(Action::SWITCH_ONLINE, array($status)) \&. PHP_EOL \&.
59             TplService::getActionRestart(BinApache::SERVICE_NAME) \&. PHP_EOL \&.
60             TplAppReload::getActionReload() \&. PHP_EOL;
61     }
.PP
.fi

.PP
References \fBTplAppReload\\getActionReload()\fP, \fBTplService\\getActionRestart()\fP, \fBTplApp\\getActionRun()\fP, \fBBinApache\\SERVICE_NAME\fP, and \fBAction\\SWITCH_ONLINE\fP\&.
.SS "process ()\fR [static]\fP"
Generates the menu item and associated actions for switching the online/offline status\&.

.PP
This method creates a menu item for switching the application's online/offline status and defines the actions to be taken when the menu item is selected\&. It uses the global configuration and language objects to retrieve the current status and localized strings\&.

.PP
@global object $bearsamppConfig Provides access to the application's configuration settings\&. @global object $bearsamppLang Provides language support for retrieving language-specific values\&.

.PP
\fBReturns\fP
.RS 4
array The generated menu item and actions for switching the online/offline status\&. 
.RE
.PP

.PP
Definition at line \fB34\fP of file \fBclass\&.tpl\&.app\&.online\&.php\fP\&.
.nf
35     {
36         global $bearsamppConfig, $bearsamppLang;
37 
38         return TplApp::getActionMulti(
39             self::ACTION, array($bearsamppConfig\->isOnline() ? Config::DISABLED : Config::ENABLED),
40             array($bearsamppConfig\->isOnline() ? $bearsamppLang\->getValue(Lang::MENU_PUT_OFFLINE) : $bearsamppLang\->getValue(Lang::MENU_PUT_ONLINE)),
41             false, get_called_class()
42         );
43     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, \fB$bearsamppLang\fP, \fBConfig\\DISABLED\fP, \fBConfig\\ENABLED\fP, \fBTplApp\\getActionMulti()\fP, \fBLang\\MENU_PUT_OFFLINE\fP, and \fBLang\\MENU_PUT_ONLINE\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuLeft()\fP\&.
.SH "Field Documentation"
.PP 
.SS "const ACTION = 'status'"

.PP
Definition at line \fB20\fP of file \fBclass\&.tpl\&.app\&.online\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
