.TH "TplAppEditConf" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TplAppEditConf
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBprocess\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBclass\&.tpl\&.app\&.EditConf\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "process ()\fR [static]\fP"
Processes the request to edit the configuration file\&.

.PP
This method generates a Notepad item string that allows the user to edit the \fRbearsampp\&.conf\fP file\&. It utilizes global variables to access language settings and the root path of the application\&.

.PP
@global \fBLangProc\fP $bearsamppLang The language processor for retrieving localized strings\&. @global \fBRoot\fP $bearsamppRoot The root object for accessing application paths\&. 
.PP
\fBReturns\fP
.RS 4
string The Notepad item string for editing the configuration file\&. 
.RE
.PP

.PP
Definition at line \fB22\fP of file \fBclass\&.tpl\&.app\&.EditConf\&.php\fP\&.
.nf
23     {
24         global $bearsamppLang, $bearsamppRoot;
25 
26         return TplAestan::getItemNotepad(
27             sprintf($bearsamppLang\->getValue(Lang::MENU_EDIT_CONF), "bearsampp\&.conf"),
28             $bearsamppRoot\->getConfigFilePath()
29         ) \&. PHP_EOL;
30     }
.PP
.fi

.PP
References \fB$bearsamppLang\fP, \fB$bearsamppRoot\fP, \fBTplAestan\\getItemNotepad()\fP, and \fBLang\\MENU_EDIT_CONF\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuRight()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
