.TH "TplAppPython" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TplAppPython
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetMenuPython\fP ()"
.br
.ti -1c
.RI "static \fBprocess\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBMENU\fP = 'python'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBTplAppPython\fP

.PP
This class provides methods to generate menu items and actions for managing Python tools within the \fBBearsampp\fP application\&. It includes functionalities for accessing Python console, IDLE, and other Python-related executables\&. 
.PP
Definition at line \fB18\fP of file \fBclass\&.tpl\&.app\&.python\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getMenuPython ()\fR [static]\fP"
Generates the Python menu with options for accessing the Python console, IDLE, and other tools\&.

.PP
@global object $bearsamppLang Provides language support for retrieving language-specific values\&. @global object $bearsamppTools Provides access to various tools and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Python tools\&. 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBclass\&.tpl\&.app\&.python\&.php\fP\&.
.nf
46     {
47         global $bearsamppLang, $bearsamppTools;
48 
49         // Generate menu item for Python console
50         $resultItems = TplAestan::getItemConsoleZ(
51             $bearsamppLang\->getValue(Lang::PYTHON_CONSOLE),
52             TplAestan::GLYPH_PYTHON,
53             $bearsamppTools\->getConsoleZ()\->getTabTitlePython()
54         ) \&. PHP_EOL;
55 
56         // Generate menu item for Python IDLE
57         $resultItems \&.= TplAestan::getItemExe(
58             $bearsamppLang\->getValue(Lang::PYTHON) \&. ' IDLE',
59             $bearsamppTools\->getPython()\->getIdleExe(),
60             TplAestan::GLYPH_PYTHON
61         ) \&. PHP_EOL;
62 
63         return $resultItems;
64     }
.PP
.fi

.PP
References \fB$bearsamppLang\fP, \fBTplAestan\\getItemConsoleZ()\fP, \fBTplAestan\\getItemExe()\fP, \fBTplAestan\\GLYPH_PYTHON\fP, \fBLang\\PYTHON\fP, and \fBLang\\PYTHON_CONSOLE\fP\&.
.SS "process ()\fR [static]\fP"
Generates the main Python menu with options to access Python tools\&.

.PP
@global object $bearsamppLang Provides language support for retrieving language-specific values\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Python\&. 
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBclass\&.tpl\&.app\&.python\&.php\fP\&.
.nf
31     {
32         global $bearsamppLang;
33 
34         return TplApp::getMenu($bearsamppLang\->getValue(Lang::PYTHON), self::MENU, get_called_class());
35     }
.PP
.fi

.PP
References \fB$bearsamppLang\fP, \fBTplApp\\getMenu()\fP, and \fBLang\\PYTHON\fP\&.
.PP
Referenced by \fBTplAppTools\\getMenuTools()\fP\&.
.SH "Field Documentation"
.PP 
.SS "const MENU = 'python'"

.PP
Definition at line \fB21\fP of file \fBclass\&.tpl\&.app\&.python\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
