.TH "TplAppExit" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TplAppExit
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetActionExit\fP ()"
.br
.ti -1c
.RI "static \fBprocess\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBACTION\fP = '\fBexit\fP'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBTplAppExit\fP

.PP
This class provides methods to handle the exit action within the \fBBearsampp\fP application\&. It includes functionalities to process the exit action and generate the necessary action strings\&. 
.PP
Definition at line \fB16\fP of file \fBclass\&.tpl\&.app\&.exit\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getActionExit ()\fR [static]\fP"
Generates the action string to execute the exit action\&.

.PP
This method generates a run action string for the quit action and appends the exit action\&.

.PP
\fBReturns\fP
.RS 4
string The generated action string for the exit action\&. 
.RE
.PP

.PP
Definition at line \fB52\fP of file \fBclass\&.tpl\&.app\&.exit\&.php\fP\&.
.nf
53     {
54         return TplApp::getActionRun(Action::QUIT) \&. PHP_EOL \&. 'Action: exit';
55     }
.PP
.fi

.PP
References \fBTplApp\\getActionRun()\fP, and \fBAction\\QUIT\fP\&.
.SS "process ()\fR [static]\fP"
Processes the exit action and generates the necessary action strings\&.

.PP
This method generates a multi-action string for the exit action, including the caption and glyph\&.

.PP
@global object $bearsamppLang Provides language support for retrieving language-specific values\&.

.PP
\fBReturns\fP
.RS 4
array An array containing the call string and the section content for the exit action\&. 
.RE
.PP

.PP
Definition at line \fB32\fP of file \fBclass\&.tpl\&.app\&.exit\&.php\fP\&.
.nf
33     {
34         global $bearsamppLang;
35 
36         return TplApp::getActionMulti(
37             self::ACTION,
38             null,
39             array($bearsamppLang\->getValue(Lang::QUIT), TplAestan::GLYPH_EXIT),
40             false,
41             get_called_class()
42         );
43     }
.PP
.fi

.PP
References \fB$bearsamppLang\fP, \fBTplApp\\getActionMulti()\fP, \fBTplAestan\\GLYPH_EXIT\fP, and \fBLang\\QUIT\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuRight()\fP\&.
.SH "Field Documentation"
.PP 
.SS "const ACTION = '\fBexit\fP'"
Constant representing the exit action\&. 
.PP
Definition at line \fB21\fP of file \fBclass\&.tpl\&.app\&.exit\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
