TplAppPython
NAME
TplAppPython
SYNOPSIS
Static Public Member Functions
static getMenuPython ()
static process ()
Data Fields
const MENU = 'python'
Detailed Description
Class TplAppPython
This class provides methods to generate menu items and actions for managing Python tools within the Bearsampp application. It includes functionalities for accessing Python console, IDLE, and other Python-related executables.
Definition at line 18 of file class.tpl.app.python.php.
Member Function Documentation
getMenuPython () [static]
Generates the Python menu with options for accessing the Python console, IDLE, and other tools.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppTools Provides access to various tools and their configurations.
Returns
string The generated menu items and actions for Python tools.
Definition at line 45 of file class.tpl.app.python.php.
    {
        global $bearsamppLang, $bearsamppTools;
        // Generate menu item for Python console
        $resultItems = TplAestan::getItemConsoleZ(
            $bearsamppLang->getValue(Lang::PYTHON_CONSOLE),
            TplAestan::GLYPH_PYTHON,
            $bearsamppTools->getConsoleZ()->getTabTitlePython()
        ) . PHP_EOL;
        // Generate menu item for Python IDLE
        $resultItems .= TplAestan::getItemExe(
            $bearsamppLang->getValue(Lang::PYTHON) . ' IDLE',
            $bearsamppTools->getPython()->getIdleExe(),
            TplAestan::GLYPH_PYTHON
        ) . PHP_EOL;
        return $resultItems;
    }
References $bearsamppLang, TplAestan\getItemConsoleZ(), TplAestan\getItemExe(), TplAestan\GLYPH_PYTHON, Lang\PYTHON, and Lang\PYTHON_CONSOLE.
process () [static]
Generates the main Python menu with options to access Python tools.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated menu items and actions for Python.
Definition at line 30 of file class.tpl.app.python.php.
    {
        global $bearsamppLang;
        return TplApp::getMenu($bearsamppLang->getValue(Lang::PYTHON), self::MENU, get_called_class());
    }
References $bearsamppLang, TplApp\getMenu(), and Lang\PYTHON.
Referenced by TplAppTools\getMenuTools().
Field Documentation
const MENU = 'python'
Definition at line 21 of file class.tpl.app.python.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.