TplAppExit
NAME
TplAppExit
SYNOPSIS
Static Public Member Functions
static getActionExit ()
static process ()
Data Fields
const ACTION = 'exit'
Detailed Description
Class TplAppExit
This class provides methods to handle the exit action within the Bearsampp application. It includes functionalities to process the exit action and generate the necessary action strings.
Definition at line 16 of file class.tpl.app.exit.php.
Member Function Documentation
getActionExit () [static]
Generates the action string to execute the exit action.
This method generates a run action string for the quit action and appends the exit action.
Returns
string The generated action string for the exit action.
Definition at line 52 of file class.tpl.app.exit.php.
    {
        return TplApp::getActionRun(Action::QUIT) . PHP_EOL . 'Action: exit';
    }
References TplApp\getActionRun(), and Action\QUIT.
process () [static]
Processes the exit action and generates the necessary action strings.
This method generates a multi-action string for the exit action, including the caption and glyph.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array An array containing the call string and the section content for the exit action.
Definition at line 32 of file class.tpl.app.exit.php.
    {
        global $bearsamppLang;
        return TplApp::getActionMulti(
            self::ACTION,
            null,
            array($bearsamppLang->getValue(Lang::QUIT), TplAestan::GLYPH_EXIT),
            false,
            get_called_class()
        );
    }
References $bearsamppLang, TplApp\getActionMulti(), TplAestan\GLYPH_EXIT, and Lang\QUIT.
Referenced by TplApp\getSectionMenuRight().
Field Documentation
const ACTION = 'exit'
Constant representing the exit action.
Definition at line 21 of file class.tpl.app.exit.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.