TplAppBrowser
NAME
TplAppBrowser
SYNOPSIS
Static Public Member Functions
static getActionChangeBrowser ()
static process ()
Data Fields
const ACTION = 'changeBrowser'
Detailed Description
Class TplAppBrowser
This class provides methods to generate actions and menu items for changing the browser in the Bearsampp application. It includes functionalities for creating change browser actions and processing change browser commands.
Definition at line 16 of file class.tpl.app.browser.php.
Member Function Documentation
getActionChangeBrowser () [static]
Generates the action to change the browser.
This method creates the action string for changing the browser. It includes commands to reload the application after changing the browser. The action string is used to define what happens when the change browser action is triggered.
Returns
string The generated action string for changing the browser.
Definition at line 51 of file class.tpl.app.browser.php.
    {
        return TplApp::getActionRun(Action::CHANGE_BROWSER) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References Action\CHANGE_BROWSER, TplAppReload\getActionReload(), and TplApp\getActionRun().
process () [static]
Generates the change browser menu item and associated actions.
This method creates a menu item for changing the browser and defines the actions to be taken when the change browser menu item is selected. It uses the global language object to retrieve the localized string for the change browser action.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array The generated menu item and actions for changing the browser.
Definition at line 32 of file class.tpl.app.browser.php.
    {
        global $bearsamppLang;
        return TplApp::getActionMulti(
            self::ACTION, null,
            array($bearsamppLang->getValue(Lang::CHANGE_BROWSER_TITLE), TplAestan::GLYPH_BROWSER),
            false, get_called_class()
        );
    }
References $bearsamppLang, Lang\CHANGE_BROWSER_TITLE, TplApp\getActionMulti(), and TplAestan\GLYPH_BROWSER.
Referenced by TplApp\getSectionMenuRight().
Field Documentation
const ACTION = 'changeBrowser'
Definition at line 19 of file class.tpl.app.browser.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.