.TH "TplAppLogsVerbose" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TplAppLogsVerbose
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetActionSwitchLogsVerbose\fP ($verbose)"
.br
.ti -1c
.RI "static \fBgetMenuLogsVerbose\fP ()"
.br
.ti -1c
.RI "static \fBprocess\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBMENU\fP = 'logsVerbose'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBTplAppLogsVerbose\fP

.PP
This class provides methods to generate and manage the logs verbosity menu and actions within the \fBBearsampp\fP application\&. It includes functionalities for creating the logs verbosity menu and processing actions to switch the logs verbosity level\&. 
.PP
Definition at line \fB17\fP of file \fBclass\&.tpl\&.app\&.logsVerbose\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getActionSwitchLogsVerbose ( $verbose)\fR [static]\fP"
Generates the action to switch the logs verbosity level\&.

.PP
This method creates the action string for switching the logs verbosity level\&. It includes commands to reload the application after changing the verbosity level\&.

.PP
\fBParameters\fP
.RS 4
\fI$verbose\fP The verbosity level to switch to\&.
.RE
.PP
\fBReturns\fP
.RS 4
string The generated action string for switching the logs verbosity level\&. 
.RE
.PP

.PP
Definition at line \fB92\fP of file \fBclass\&.tpl\&.app\&.logsVerbose\&.php\fP\&.
.nf
93     {
94         return TplApp::getActionRun(Action::SWITCH_LOGS_VERBOSE, array($verbose)) \&. PHP_EOL \&.
95             TplAppReload::getActionReload();
96     }
.PP
.fi

.PP
References \fBTplAppReload\\getActionReload()\fP, \fBTplApp\\getActionRun()\fP, and \fBAction\\SWITCH_LOGS_VERBOSE\fP\&.
.SS "getMenuLogsVerbose ()\fR [static]\fP"
Generates the menu items and actions for switching logs verbosity levels\&.

.PP
This method creates menu items for each verbosity level and defines the actions to be taken when a verbosity level is selected\&. It uses the global language object to retrieve the localized strings for each verbosity level and the global configuration object to get the current verbosity level\&.

.PP
@global object $bearsamppLang Provides language support for retrieving language-specific values\&. @global object $bearsamppConfig Provides access to the application's configuration settings\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for switching logs verbosity levels\&. 
.RE
.PP

.PP
Definition at line \fB51\fP of file \fBclass\&.tpl\&.app\&.logsVerbose\&.php\fP\&.
.nf
52     {
53         global $bearsamppLang, $bearsamppConfig;
54 
55         $items = '';
56         $actions = '';
57 
58         $verboses = array(
59             Config::VERBOSE_SIMPLE => $bearsamppLang\->getValue(Lang::VERBOSE_SIMPLE),
60             Config::VERBOSE_REPORT => $bearsamppLang\->getValue(Lang::VERBOSE_REPORT),
61             Config::VERBOSE_DEBUG  => $bearsamppLang\->getValue(Lang::VERBOSE_DEBUG),
62             Config::VERBOSE_TRACE  => $bearsamppLang\->getValue(Lang::VERBOSE_TRACE),
63         );
64 
65         foreach ($verboses as $verbose => $caption) {
66             $tplSwitchLogsVerbose = TplApp::getActionMulti(
67                 Action::SWITCH_LOGS_VERBOSE, array($verbose),
68                 array($caption, $verbose == $bearsamppConfig\->getLogsVerbose() ? TplAestan::GLYPH_CHECK : ''),
69                 false, get_called_class()
70             );
71 
72             // Item
73             $items \&.= $tplSwitchLogsVerbose[TplApp::SECTION_CALL] \&. PHP_EOL;
74 
75             // Action
76             $actions \&.= PHP_EOL \&. $tplSwitchLogsVerbose[TplApp::SECTION_CONTENT] \&.  PHP_EOL;
77         }
78 
79         return $items \&. $actions;
80     }
.PP
.fi

.PP
References \fB$bearsamppConfig\fP, \fB$bearsamppLang\fP, \fBTplApp\\getActionMulti()\fP, \fBTplAestan\\GLYPH_CHECK\fP, \fBTplApp\\SECTION_CALL\fP, \fBTplApp\\SECTION_CONTENT\fP, \fBAction\\SWITCH_LOGS_VERBOSE\fP, \fBConfig\\VERBOSE_DEBUG\fP, \fBLang\\VERBOSE_DEBUG\fP, \fBConfig\\VERBOSE_REPORT\fP, \fBLang\\VERBOSE_REPORT\fP, \fBConfig\\VERBOSE_SIMPLE\fP, \fBLang\\VERBOSE_SIMPLE\fP, \fBConfig\\VERBOSE_TRACE\fP, and \fBLang\\VERBOSE_TRACE\fP\&.
.SS "process ()\fR [static]\fP"
Generates the logs verbosity menu\&.

.PP
This method creates a menu for selecting the logs verbosity level\&. It uses the global language object to retrieve the localized string for the logs verbosity menu\&.

.PP
@global object $bearsamppLang Provides language support for retrieving language-specific values\&.

.PP
\fBReturns\fP
.RS 4
array The generated menu for selecting the logs verbosity level\&. 
.RE
.PP

.PP
Definition at line \fB32\fP of file \fBclass\&.tpl\&.app\&.logsVerbose\&.php\fP\&.
.nf
33     {
34         global $bearsamppLang;
35 
36         return TplApp::getMenu($bearsamppLang\->getValue(Lang::LOGS_VERBOSE), self::MENU, get_called_class());
37     }
.PP
.fi

.PP
References \fB$bearsamppLang\fP, \fBTplApp\\getMenu()\fP, and \fBLang\\LOGS_VERBOSE\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuRight()\fP\&.
.SH "Field Documentation"
.PP 
.SS "const MENU = 'logsVerbose'"

.PP
Definition at line \fB20\fP of file \fBclass\&.tpl\&.app\&.logsVerbose\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
