TplAppApps
NAME
TplAppApps
SYNOPSIS
Static Public Member Functions
static getMenuApps ()
static process ()
Data Fields
const MENU = 'apps'
Detailed Description
Class TplAppApps
This class provides methods to generate and manage the "Apps" menu within the Bearsampp application. It includes functionalities for creating the menu and adding specific application links.
Definition at line 16 of file class.tpl.app.apps.php.
Member Function Documentation
getMenuApps () [static]
Generates the content of the "Apps" menu.
This method generates the content of the "Apps" menu by adding links to various applications such as phpMyAdmin and phpPgAdmin.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated menu content as a concatenated string.
Definition at line 49 of file class.tpl.app.apps.php.
    {
        global $bearsamppLang;
        return TplAestan::getItemLink(
                $bearsamppLang->getValue(Lang::PHPMYADMIN),
                'phpmyadmin/',
                true
            ) . PHP_EOL .
            TplAestan::getItemLink(
                $bearsamppLang->getValue(Lang::PHPPGADMIN),
                'phppgadmin/',
                true
            );
    }
References $bearsamppLang, TplAestan\getItemLink(), Lang\PHPMYADMIN, and Lang\PHPPGADMIN.
process () [static]
Processes and generates the "Apps" menu.
This method generates the "Apps" menu by calling the getMenu method from the TplApp class.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array An array containing the call string and the menu content.
Definition at line 32 of file class.tpl.app.apps.php.
    {
        global $bearsamppLang;
        return TplApp::getMenu($bearsamppLang->getValue(Lang::APPS), self::MENU, get_called_class());
    }
References $bearsamppLang, Lang\APPS, and TplApp\getMenu().
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
const MENU = 'apps'
Constant representing the menu identifier for apps.
Definition at line 21 of file class.tpl.app.apps.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.