.TH "TplAppApache" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TplAppApache
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetActionAddAlias\fP ()"
.br
.ti -1c
.RI "static \fBgetActionAddVhost\fP ()"
.br
.ti -1c
.RI "static \fBgetActionChangeApachePort\fP ()"
.br
.ti -1c
.RI "static \fBgetActionEditAlias\fP ($alias)"
.br
.ti -1c
.RI "static \fBgetActionEditVhost\fP ($vhost)"
.br
.ti -1c
.RI "static \fBgetActionEnableApache\fP ($enable)"
.br
.ti -1c
.RI "static \fBgetActionInstallApacheService\fP ()"
.br
.ti -1c
.RI "static \fBgetActionRemoveApacheService\fP ()"
.br
.ti -1c
.RI "static \fBgetActionSwitchApacheModule\fP ($module, $switch)"
.br
.ti -1c
.RI "static \fBgetActionSwitchApacheVersion\fP ($version)"
.br
.ti -1c
.RI "static \fBgetMenuApache\fP ()"
.br
.ti -1c
.RI "static \fBgetMenuApacheAlias\fP ()"
.br
.ti -1c
.RI "static \fBgetMenuApacheDebug\fP ()"
.br
.ti -1c
.RI "static \fBgetMenuApacheModules\fP ()"
.br
.ti -1c
.RI "static \fBgetMenuApacheService\fP ()"
.br
.ti -1c
.RI "static \fBgetMenuApacheVersions\fP ()"
.br
.ti -1c
.RI "static \fBgetMenuApacheVhosts\fP ()"
.br
.ti -1c
.RI "static \fBprocess\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBACTION_ADD_ALIAS\fP = 'addAlias'"
.br
.ti -1c
.RI "const \fBACTION_ADD_VHOST\fP = 'addVhost'"
.br
.ti -1c
.RI "const \fBACTION_CHANGE_PORT\fP = 'changeApachePort'"
.br
.ti -1c
.RI "const \fBACTION_EDIT_ALIAS\fP = 'editAlias'"
.br
.ti -1c
.RI "const \fBACTION_EDIT_VHOST\fP = 'editVhost'"
.br
.ti -1c
.RI "const \fBACTION_ENABLE\fP = 'enableApache'"
.br
.ti -1c
.RI "const \fBACTION_INSTALL_SERVICE\fP = 'installApacheService'"
.br
.ti -1c
.RI "const \fBACTION_REMOVE_SERVICE\fP = 'removeApacheService'"
.br
.ti -1c
.RI "const \fBACTION_SWITCH_MODULE\fP = 'switchApacheModule'"
.br
.ti -1c
.RI "const \fBACTION_SWITCH_VERSION\fP = 'switchApacheVersion'"
.br
.ti -1c
.RI "const \fBMENU\fP = 'apache'"
.br
.ti -1c
.RI "const \fBMENU_ALIAS\fP = 'apacheAlias'"
.br
.ti -1c
.RI "const \fBMENU_DEBUG\fP = 'apacheDebug'"
.br
.ti -1c
.RI "const \fBMENU_MODULES\fP = 'apacheModules'"
.br
.ti -1c
.RI "const \fBMENU_SERVICE\fP = 'apacheService'"
.br
.ti -1c
.RI "const \fBMENU_VERSIONS\fP = 'apacheVersions'"
.br
.ti -1c
.RI "const \fBMENU_VHOSTS\fP = 'apacheVhosts'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBTplAppApache\fP

.PP
This class provides methods to generate menu items and actions for managing Apache services within the \fBBearsampp\fP application\&. It includes functionalities for enabling/disabling Apache, switching versions, changing ports, managing modules, aliases, and virtual hosts\&. 
.PP
Definition at line \fB17\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getActionAddAlias ()\fR [static]\fP"
Generates the action to add an Apache alias\&.

.PP
\fBReturns\fP
.RS 4
string The generated action to add an Apache alias\&. 
.RE
.PP

.PP
Definition at line \fB433\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
434     {
435         return TplApp::getActionRun(Action::ADD_ALIAS) \&. PHP_EOL \&.
436             TplAppReload::getActionReload();
437     }
.PP
.fi

.PP
References \fBAction\\ADD_ALIAS\fP, \fBTplAppReload\\getActionReload()\fP, and \fBTplApp\\getActionRun()\fP\&.
.SS "getActionAddVhost ()\fR [static]\fP"
Generates the action to add an Apache Virtual Host (Vhost)\&.

.PP
\fBReturns\fP
.RS 4
string The generated action to add an Apache Vhost\&. 
.RE
.PP

.PP
Definition at line \fB498\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
499     {
500         return TplApp::getActionRun(Action::ADD_VHOST) \&. PHP_EOL \&.
501             TplAppReload::getActionReload();
502     }
.PP
.fi

.PP
References \fBAction\\ADD_VHOST\fP, \fBTplAppReload\\getActionReload()\fP, and \fBTplApp\\getActionRun()\fP\&.
.SS "getActionChangeApachePort ()\fR [static]\fP"
Generates the action to change the Apache port\&.

.PP
@global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated action to change the Apache port\&. 
.RE
.PP

.PP
Definition at line \fB271\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
272     {
273         global $bearsamppBins;
274 
275         return TplApp::getActionRun(Action::CHANGE_PORT, array($bearsamppBins\->getApache()\->getName())) \&. PHP_EOL \&.
276             TplAppReload::getActionReload();
277     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fBAction\\CHANGE_PORT\fP, \fBTplAppReload\\getActionReload()\fP, and \fBTplApp\\getActionRun()\fP\&.
.SS "getActionEditAlias ( $alias)\fR [static]\fP"
Generates the action to edit an Apache alias\&.

.PP
\fBParameters\fP
.RS 4
\fI$alias\fP The alias to edit\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string The generated action to edit an Apache alias\&. 
.RE
.PP

.PP
Definition at line \fB445\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
446     {
447         return TplApp::getActionRun(Action::EDIT_ALIAS, array($alias)) \&. PHP_EOL \&.
448             TplAppReload::getActionReload();
449     }
.PP
.fi

.PP
References \fBAction\\EDIT_ALIAS\fP, \fBTplAppReload\\getActionReload()\fP, and \fBTplApp\\getActionRun()\fP\&.
.SS "getActionEditVhost ( $vhost)\fR [static]\fP"
Generates the action to edit an Apache Virtual Host (Vhost)\&.

.PP
\fBParameters\fP
.RS 4
\fI$vhost\fP The Vhost to edit\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string The generated action to edit an Apache Vhost\&. 
.RE
.PP

.PP
Definition at line \fB510\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
511     {
512         return TplApp::getActionRun(Action::EDIT_VHOST, array($vhost)) \&. PHP_EOL \&.
513             TplAppReload::getActionReload();
514     }
.PP
.fi

.PP
References \fBAction\\EDIT_VHOST\fP, \fBTplAppReload\\getActionReload()\fP, and \fBTplApp\\getActionRun()\fP\&.
.SS "getActionEnableApache ( $enable)\fR [static]\fP"
Generates the action to enable or disable Apache\&.

.PP
@global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBParameters\fP
.RS 4
\fI$enable\fP The flag to enable (1) or disable (0) Apache\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string The generated action to enable or disable Apache\&. 
.RE
.PP

.PP
Definition at line \fB181\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
182     {
183         global $bearsamppBins;
184 
185         return TplApp::getActionRun(Action::ENABLE, array($bearsamppBins\->getApache()\->getName(), $enable)) \&. PHP_EOL \&.
186             TplAppReload::getActionReload();
187     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fBAction\\ENABLE\fP, \fBTplAppReload\\getActionReload()\fP, and \fBTplApp\\getActionRun()\fP\&.
.SS "getActionInstallApacheService ()\fR [static]\fP"
Generates the action to install the Apache service\&.

.PP
\fBReturns\fP
.RS 4
string The generated action to install the Apache service\&. 
.RE
.PP

.PP
Definition at line \fB284\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
285     {
286         return TplApp::getActionRun(Action::SERVICE, array(BinApache::SERVICE_NAME, ActionService::INSTALL)) \&. PHP_EOL \&.
287             TplAppReload::getActionReload();
288     }
.PP
.fi

.PP
References \fBTplAppReload\\getActionReload()\fP, \fBTplApp\\getActionRun()\fP, \fBActionService\\INSTALL\fP, \fBAction\\SERVICE\fP, and \fBBinApache\\SERVICE_NAME\fP\&.
.SS "getActionRemoveApacheService ()\fR [static]\fP"
Generates the action to remove the Apache service\&.

.PP
\fBReturns\fP
.RS 4
string The generated action to remove the Apache service\&. 
.RE
.PP

.PP
Definition at line \fB295\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
296     {
297         return TplApp::getActionRun(Action::SERVICE, array(BinApache::SERVICE_NAME, ActionService::REMOVE)) \&. PHP_EOL \&.
298             TplAppReload::getActionReload();
299     }
.PP
.fi

.PP
References \fBTplAppReload\\getActionReload()\fP, \fBTplApp\\getActionRun()\fP, \fBActionService\\REMOVE\fP, \fBAction\\SERVICE\fP, and \fBBinApache\\SERVICE_NAME\fP\&.
.SS "getActionSwitchApacheModule ( $module,  $switch)\fR [static]\fP"
Generates the action to switch an Apache module on or off\&.

.PP
\fBParameters\fP
.RS 4
\fI$module\fP The module to switch\&. 
.br
\fI$switch\fP The current switch state of the module\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string The generated action to switch the Apache module\&. 
.RE
.PP

.PP
Definition at line \fB379\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
380     {
381         $switch = $switch == ActionSwitchApacheModule::SWITCH_OFF ? ActionSwitchApacheModule::SWITCH_ON : ActionSwitchApacheModule::SWITCH_OFF;
382         return TplApp::getActionRun(Action::SWITCH_APACHE_MODULE, array($module, $switch)) \&. PHP_EOL \&.
383             TplService::getActionRestart(BinApache::SERVICE_NAME) \&. PHP_EOL \&.
384             TplAppReload::getActionReload() \&. PHP_EOL;
385     }
.PP
.fi

.PP
References \fBTplAppReload\\getActionReload()\fP, \fBTplService\\getActionRestart()\fP, \fBTplApp\\getActionRun()\fP, \fBBinApache\\SERVICE_NAME\fP, \fBAction\\SWITCH_APACHE_MODULE\fP, \fBActionSwitchApacheModule\\SWITCH_OFF\fP, and \fBActionSwitchApacheModule\\SWITCH_ON\fP\&.
.SS "getActionSwitchApacheVersion ( $version)\fR [static]\fP"
Generates the action to switch the Apache version\&.

.PP
@global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBParameters\fP
.RS 4
\fI$version\fP The version to switch to\&. 
.RE
.PP
\fBReturns\fP
.RS 4
string The generated action to switch the Apache version\&. 
.RE
.PP

.PP
Definition at line \fB197\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
198     {
199         global $bearsamppBins;
200         return TplApp::getActionRun(Action::SWITCH_VERSION, array($bearsamppBins\->getApache()\->getName(), $version)) \&. PHP_EOL \&.
201             TplAppReload::getActionReload() \&. PHP_EOL;
202     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fBTplAppReload\\getActionReload()\fP, \fBTplApp\\getActionRun()\fP, and \fBAction\\SWITCH_VERSION\fP\&.
.SS "getMenuApache ()\fR [static]\fP"
Generates the Apache menu with options for versions, service, debug, modules, aliases, and virtual hosts\&.

.PP
@global object $bearsamppBins Provides access to system binaries and their configurations\&. @global object $bearsamppLang Provides language support for retrieving language-specific values\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Apache\&. 
.RE
.PP

.PP
Definition at line \fB62\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
63     {
64         global $bearsamppBins, $bearsamppLang;
65         $resultItems = $resultActions = '';
66 
67         $isEnabled = $bearsamppBins\->getApache()\->isEnable();
68 
69         // Download
70         $resultItems \&.= TplAestan::getItemLink(
71             $bearsamppLang\->getValue(Lang::DOWNLOAD_MORE),
72             Util::getWebsiteUrl('module/apache', '#releases'),
73             false,
74             TplAestan::GLYPH_BROWSER
75         ) \&. PHP_EOL;
76 
77         // Enable
78         $tplEnable = TplApp::getActionMulti(
79             self::ACTION_ENABLE, array($isEnabled ? Config::DISABLED : Config::ENABLED),
80             array($bearsamppLang\->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
81             false, get_called_class()
82         );
83         $resultItems \&.= $tplEnable[TplApp::SECTION_CALL] \&. PHP_EOL;
84         $resultActions \&.= $tplEnable[TplApp::SECTION_CONTENT] \&. PHP_EOL;
85 
86         if ($isEnabled) {
87             $resultItems \&.= TplAestan::getItemSeparator() \&. PHP_EOL;
88 
89             // Versions
90             $tplVersions = TplApp::getMenu($bearsamppLang\->getValue(Lang::VERSIONS), self::MENU_VERSIONS, get_called_class());
91             $resultItems \&.= $tplVersions[TplApp::SECTION_CALL] \&. PHP_EOL;
92             $resultActions \&.= $tplVersions[TplApp::SECTION_CONTENT] \&. PHP_EOL;
93 
94             // Service
95             $tplService = TplApp::getMenu($bearsamppLang\->getValue(Lang::SERVICE), self::MENU_SERVICE, get_called_class());
96             $resultItems \&.= $tplService[TplApp::SECTION_CALL] \&. PHP_EOL;
97             $resultActions \&.= $tplService[TplApp::SECTION_CONTENT] \&. PHP_EOL;
98 
99             // Debug
100             $tplDebug = TplApp::getMenu($bearsamppLang\->getValue(Lang::DEBUG), self::MENU_DEBUG, get_called_class());
101             $resultItems \&.= $tplDebug[TplApp::SECTION_CALL] \&. PHP_EOL;
102             $resultActions \&.= $tplDebug[TplApp::SECTION_CONTENT] \&. PHP_EOL;
103 
104             // Modules
105             $tplModules = TplApp::getMenu($bearsamppLang\->getValue(Lang::MODULES), self::MENU_MODULES, get_called_class());
106             $resultItems \&.= $tplModules[TplApp::SECTION_CALL] \&. PHP_EOL;
107             $resultActions \&.= $tplModules[TplApp::SECTION_CONTENT] \&. PHP_EOL;
108 
109             // Alias
110             $tplAlias = TplApp::getMenu($bearsamppLang\->getValue(Lang::ALIASES), self::MENU_ALIAS, get_called_class());
111             $resultItems \&.= $tplAlias[TplApp::SECTION_CALL] \&. PHP_EOL;
112             $resultActions \&.= $tplAlias[TplApp::SECTION_CONTENT] \&. PHP_EOL;
113 
114             // Vhosts
115             $tplVhosts = TplApp::getMenu($bearsamppLang\->getValue(Lang::VIRTUAL_HOSTS), self::MENU_VHOSTS, get_called_class());
116             $resultItems \&.= $tplVhosts[TplApp::SECTION_CALL] \&. PHP_EOL;
117             $resultActions \&.= $tplVhosts[TplApp::SECTION_CONTENT];
118 
119             // Conf
120             $resultItems \&.= TplAestan::getItemNotepad(basename($bearsamppBins\->getApache()\->getConf()), $bearsamppBins\->getApache()\->getConf()) \&. PHP_EOL;
121 
122             // Access log
123             $resultItems \&.= TplAestan::getItemNotepad($bearsamppLang\->getValue(Lang::MENU_ACCESS_LOGS), $bearsamppBins\->getApache()\->getAccessLog()) \&. PHP_EOL;
124 
125             // Rewrite log
126             $resultItems \&.= TplAestan::getItemNotepad($bearsamppLang\->getValue(Lang::MENU_REWRITE_LOGS), $bearsamppBins\->getApache()\->getRewriteLog()) \&. PHP_EOL;
127 
128             // Error log
129             $resultItems \&.= TplAestan::getItemNotepad($bearsamppLang\->getValue(Lang::MENU_ERROR_LOGS), $bearsamppBins\->getApache()\->getErrorLog()) \&. PHP_EOL;
130         }
131 
132         return $resultItems \&. PHP_EOL \&. $resultActions;
133     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fBLang\\ALIASES\fP, \fBLang\\DEBUG\fP, \fBConfig\\DISABLED\fP, \fBLang\\DOWNLOAD_MORE\fP, \fBConfig\\ENABLED\fP, \fBTplApp\\getActionMulti()\fP, \fBTplAestan\\getItemLink()\fP, \fBTplAestan\\getItemNotepad()\fP, \fBTplAestan\\getItemSeparator()\fP, \fBTplApp\\getMenu()\fP, \fBUtil\\getWebsiteUrl()\fP, \fBTplAestan\\GLYPH_BROWSER\fP, \fBTplAestan\\GLYPH_CHECK\fP, \fBLang\\MENU_ACCESS_LOGS\fP, \fBLang\\MENU_ENABLE\fP, \fBLang\\MENU_ERROR_LOGS\fP, \fBLang\\MENU_REWRITE_LOGS\fP, \fBLang\\MODULES\fP, \fBTplApp\\SECTION_CALL\fP, \fBTplApp\\SECTION_CONTENT\fP, \fBLang\\SERVICE\fP, \fBLang\\VERSIONS\fP, and \fBLang\\VIRTUAL_HOSTS\fP\&.
.SS "getMenuApacheAlias ()\fR [static]\fP"
Generates the Apache Alias menu with options to add and edit aliases\&.

.PP
@global object $bearsamppLang Provides language support for retrieving language-specific values\&. @global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Apache aliases\&. 
.RE
.PP

.PP
Definition at line \fB394\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
395     {
396         global $bearsamppLang, $bearsamppBins;
397 
398         $tplAddAlias = TplApp::getActionMulti(
399             self::ACTION_ADD_ALIAS, null,
400             array($bearsamppLang\->getValue(Lang::MENU_ADD_ALIAS), TplAestan::GLYPH_ADD),
401             false, get_called_class()
402         );
403 
404         // Items
405         $items = $tplAddAlias[TplApp::SECTION_CALL] \&. PHP_EOL \&.
406             TplAestan::getItemSeparator() \&. PHP_EOL;
407 
408         // Actions
409         $actions = PHP_EOL \&. $tplAddAlias[TplApp::SECTION_CONTENT];
410 
411         foreach ($bearsamppBins\->getApache()\->getAlias() as $alias) {
412             $tplEditAlias = TplApp::getActionMulti(
413                 self::ACTION_EDIT_ALIAS, array($alias),
414                 array(sprintf($bearsamppLang\->getValue(Lang::MENU_EDIT_ALIAS), $alias), TplAestan::GLYPH_FILE),
415                 false, get_called_class()
416             );
417 
418             // Items
419             $items \&.= $tplEditAlias[TplApp::SECTION_CALL] \&. PHP_EOL;
420 
421             // Actions
422             $actions \&.= PHP_EOL \&. PHP_EOL \&. $tplEditAlias[TplApp::SECTION_CONTENT];
423         }
424 
425         return $items \&. $actions;
426     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fBTplApp\\getActionMulti()\fP, \fBTplAestan\\getItemSeparator()\fP, \fBTplAestan\\GLYPH_ADD\fP, \fBTplAestan\\GLYPH_FILE\fP, \fBLang\\MENU_ADD_ALIAS\fP, \fBLang\\MENU_EDIT_ALIAS\fP, \fBTplApp\\SECTION_CALL\fP, and \fBTplApp\\SECTION_CONTENT\fP\&.
.SS "getMenuApacheDebug ()\fR [static]\fP"
Generates the Apache debug menu with options to run various debug commands\&.

.PP
@global object $bearsamppLang Provides language support for retrieving language-specific values\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Apache debug\&. 
.RE
.PP

.PP
Definition at line \fB308\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
309     {
310         global $bearsamppLang;
311 
312         return TplApp::getActionRun(
313             Action::DEBUG_APACHE, array(BinApache::CMD_VERSION_NUMBER),
314             array($bearsamppLang\->getValue(Lang::DEBUG_APACHE_VERSION_NUMBER), TplAestan::GLYPH_DEBUG)
315         ) \&. PHP_EOL \&.
316         TplApp::getActionRun(
317             Action::DEBUG_APACHE, array(BinApache::CMD_COMPILE_SETTINGS),
318             array($bearsamppLang\->getValue(Lang::DEBUG_APACHE_COMPILE_SETTINGS), TplAestan::GLYPH_DEBUG)
319         ) \&. PHP_EOL \&.
320         TplApp::getActionRun(
321             Action::DEBUG_APACHE, array(BinApache::CMD_COMPILED_MODULES),
322             array($bearsamppLang\->getValue(Lang::DEBUG_APACHE_COMPILED_MODULES), TplAestan::GLYPH_DEBUG)
323         ) \&. PHP_EOL \&.
324         TplApp::getActionRun(
325             Action::DEBUG_APACHE, array(BinApache::CMD_CONFIG_DIRECTIVES),
326             array($bearsamppLang\->getValue(Lang::DEBUG_APACHE_CONFIG_DIRECTIVES), TplAestan::GLYPH_DEBUG)
327         ) \&. PHP_EOL \&.
328         TplApp::getActionRun(
329             Action::DEBUG_APACHE, array(BinApache::CMD_VHOSTS_SETTINGS),
330             array($bearsamppLang\->getValue(Lang::DEBUG_APACHE_VHOSTS_SETTINGS), TplAestan::GLYPH_DEBUG)
331         ) \&. PHP_EOL \&.
332         TplApp::getActionRun(
333             Action::DEBUG_APACHE, array(BinApache::CMD_LOADED_MODULES),
334             array($bearsamppLang\->getValue(Lang::DEBUG_APACHE_LOADED_MODULES), TplAestan::GLYPH_DEBUG)
335         ) \&. PHP_EOL \&.
336         TplApp::getActionRun(
337             Action::DEBUG_APACHE, array(BinApache::CMD_SYNTAX_CHECK),
338             array($bearsamppLang\->getValue(Lang::DEBUG_APACHE_SYNTAX_CHECK), TplAestan::GLYPH_DEBUG)
339         ) \&. PHP_EOL;
340     }
.PP
.fi

.PP
References \fB$bearsamppLang\fP, \fBBinApache\\CMD_COMPILE_SETTINGS\fP, \fBBinApache\\CMD_COMPILED_MODULES\fP, \fBBinApache\\CMD_CONFIG_DIRECTIVES\fP, \fBBinApache\\CMD_LOADED_MODULES\fP, \fBBinApache\\CMD_SYNTAX_CHECK\fP, \fBBinApache\\CMD_VERSION_NUMBER\fP, \fBBinApache\\CMD_VHOSTS_SETTINGS\fP, \fBAction\\DEBUG_APACHE\fP, \fBLang\\DEBUG_APACHE_COMPILE_SETTINGS\fP, \fBLang\\DEBUG_APACHE_COMPILED_MODULES\fP, \fBLang\\DEBUG_APACHE_CONFIG_DIRECTIVES\fP, \fBLang\\DEBUG_APACHE_LOADED_MODULES\fP, \fBLang\\DEBUG_APACHE_SYNTAX_CHECK\fP, \fBLang\\DEBUG_APACHE_VERSION_NUMBER\fP, \fBLang\\DEBUG_APACHE_VHOSTS_SETTINGS\fP, \fBTplApp\\getActionRun()\fP, and \fBTplAestan\\GLYPH_DEBUG\fP\&.
.SS "getMenuApacheModules ()\fR [static]\fP"
Generates the Apache modules menu with options to switch modules on or off\&.

.PP
@global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Apache modules\&. 
.RE
.PP

.PP
Definition at line \fB349\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
350     {
351         global $bearsamppBins;
352         $items = '';
353         $actions = '';
354 
355         foreach ($bearsamppBins\->getApache()\->getModulesFromConf() as $module => $switch) {
356             $tplSwitchApacheModule = TplApp::getActionMulti(
357                 self::ACTION_SWITCH_MODULE, array($module, $switch),
358                 array($module, ($switch == ActionSwitchApacheModule::SWITCH_ON ? TplAestan::GLYPH_CHECK : '')),
359                 false, get_called_class()
360             );
361 
362             // Item
363             $items \&.= $tplSwitchApacheModule[TplApp::SECTION_CALL] \&. PHP_EOL;
364 
365             // Action
366             $actions \&.= PHP_EOL \&. $tplSwitchApacheModule[TplApp::SECTION_CONTENT];
367         }
368 
369         return $items \&. $actions;
370     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fBTplApp\\getActionMulti()\fP, \fBTplAestan\\GLYPH_CHECK\fP, \fBTplApp\\SECTION_CALL\fP, \fBTplApp\\SECTION_CONTENT\fP, and \fBActionSwitchApacheModule\\SWITCH_ON\fP\&.
.SS "getMenuApacheService ()\fR [static]\fP"
Generates the Apache service menu with options to start, stop, restart, and manage the service\&.

.PP
@global object $bearsamppRoot Provides access to the root path of the application\&. @global object $bearsamppLang Provides language support for retrieving language-specific values\&. @global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Apache service\&. 
.RE
.PP

.PP
Definition at line \fB213\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
214     {
215         global $bearsamppRoot, $bearsamppLang, $bearsamppBins;
216 
217         $tplChangePort = TplApp::getActionMulti(
218             self::ACTION_CHANGE_PORT, null,
219             array($bearsamppLang\->getValue(Lang::MENU_CHANGE_PORT), TplAestan::GLYPH_NETWORK),
220             false, get_called_class()
221         );
222 
223         $result = TplAestan::getItemActionServiceStart($bearsamppBins\->getApache()\->getService()\->getName()) \&. PHP_EOL \&.
224             TplAestan::getItemActionServiceStop($bearsamppBins\->getApache()\->getService()\->getName()) \&. PHP_EOL \&.
225             TplAestan::getItemActionServiceRestart($bearsamppBins\->getApache()\->getService()\->getName()) \&. PHP_EOL \&.
226             TplAestan::getItemSeparator() \&. PHP_EOL \&.
227             TplApp::getActionRun(
228                 Action::CHECK_PORT, array($bearsamppBins\->getApache()\->getName(), $bearsamppBins\->getApache()\->getPort()),
229                 array(sprintf($bearsamppLang\->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins\->getApache()\->getPort()), TplAestan::GLYPH_LIGHT)
230             ) \&. PHP_EOL \&.
231             TplApp::getActionRun(
232                 Action::CHECK_PORT, array($bearsamppBins\->getApache()\->getName(), $bearsamppBins\->getApache()\->getSslPort(), true),
233                 array(sprintf($bearsamppLang\->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins\->getApache()\->getSslPort()) \&. ' (SSL)', TplAestan::GLYPH_RED_LIGHT)
234             ) \&. PHP_EOL \&.
235             $tplChangePort[TplApp::SECTION_CALL] \&. PHP_EOL \&.
236             TplAestan::getItemNotepad($bearsamppLang\->getValue(Lang::MENU_UPDATE_ENV_PATH), $bearsamppRoot\->getRootPath() \&. '/nssmEnvPaths\&.dat') \&. PHP_EOL;
237 
238         $isInstalled = $bearsamppBins\->getApache()\->getService()\->isInstalled();
239         if (!$isInstalled) {
240             $tplInstallService = TplApp::getActionMulti(
241                 self::ACTION_INSTALL_SERVICE, null,
242                 array($bearsamppLang\->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL),
243                 $isInstalled, get_called_class()
244             );
245 
246             $result \&.= $tplInstallService[TplApp::SECTION_CALL] \&. PHP_EOL \&. PHP_EOL \&.
247                 $tplInstallService[TplApp::SECTION_CONTENT] \&. PHP_EOL;
248         } else {
249             $tplRemoveService = TplApp::getActionMulti(
250                 self::ACTION_REMOVE_SERVICE, null,
251                 array($bearsamppLang\->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE),
252                 !$isInstalled, get_called_class()
253             );
254 
255             $result \&.= $tplRemoveService[TplApp::SECTION_CALL] \&. PHP_EOL \&. PHP_EOL \&.
256                 $tplRemoveService[TplApp::SECTION_CONTENT] \&. PHP_EOL;
257         }
258 
259         $result \&.= $tplChangePort[TplApp::SECTION_CONTENT] \&. PHP_EOL;
260 
261         return $result;
262     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fB$bearsamppRoot\fP, \fB$result\fP, \fBAction\\CHECK_PORT\fP, \fBTplApp\\getActionMulti()\fP, \fBTplApp\\getActionRun()\fP, \fBTplAestan\\getItemActionServiceRestart()\fP, \fBTplAestan\\getItemActionServiceStart()\fP, \fBTplAestan\\getItemActionServiceStop()\fP, \fBTplAestan\\getItemNotepad()\fP, \fBTplAestan\\getItemSeparator()\fP, \fBTplAestan\\GLYPH_LIGHT\fP, \fBTplAestan\\GLYPH_NETWORK\fP, \fBTplAestan\\GLYPH_RED_LIGHT\fP, \fBTplAestan\\GLYPH_SERVICE_INSTALL\fP, \fBTplAestan\\GLYPH_SERVICE_REMOVE\fP, \fBLang\\MENU_CHANGE_PORT\fP, \fBLang\\MENU_CHECK_PORT\fP, \fBLang\\MENU_INSTALL_SERVICE\fP, \fBLang\\MENU_REMOVE_SERVICE\fP, \fBLang\\MENU_UPDATE_ENV_PATH\fP, \fBTplApp\\SECTION_CALL\fP, and \fBTplApp\\SECTION_CONTENT\fP\&.
.SS "getMenuApacheVersions ()\fR [static]\fP"
Generates the Apache versions menu with options to switch between different versions\&.

.PP
@global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Apache versions\&. 
.RE
.PP

.PP
Definition at line \fB142\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
143     {
144         global $bearsamppBins;
145         $items = '';
146         $actions = '';
147 
148         foreach ($bearsamppBins\->getApache()\->getVersionList() as $version) {
149             $glyph = '';
150             $apachePhpModule = $bearsamppBins\->getPhp()\->getApacheModule($version);
151             if ($apachePhpModule === false) {
152                 $glyph = TplAestan::GLYPH_WARNING;
153             } elseif ($version == $bearsamppBins\->getApache()\->getVersion()) {
154                 $glyph = TplAestan::GLYPH_CHECK;
155             }
156 
157             $tplSwitchApacheVersion = TplApp::getActionMulti(
158                 self::ACTION_SWITCH_VERSION, array($version),
159                 array($version, $glyph),
160                 false, get_called_class()
161             );
162 
163             // Item
164             $items \&.= $tplSwitchApacheVersion[TplApp::SECTION_CALL] \&. PHP_EOL;
165 
166             // Action
167             $actions \&.= PHP_EOL \&. $tplSwitchApacheVersion[TplApp::SECTION_CONTENT];
168         }
169 
170         return $items \&. $actions;
171     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fBTplApp\\getActionMulti()\fP, \fBTplAestan\\GLYPH_CHECK\fP, \fBTplAestan\\GLYPH_WARNING\fP, \fBTplApp\\SECTION_CALL\fP, and \fBTplApp\\SECTION_CONTENT\fP\&.
.SS "getMenuApacheVhosts ()\fR [static]\fP"
Generates the Apache Virtual Hosts (Vhosts) menu with options to add and edit Vhosts\&.

.PP
@global object $bearsamppLang Provides language support for retrieving language-specific values\&. @global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Apache Vhosts\&. 
.RE
.PP

.PP
Definition at line \fB459\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
460     {
461         global $bearsamppLang, $bearsamppBins;
462 
463         $tplAddVhost = TplApp::getActionMulti(
464             self::ACTION_ADD_VHOST, null,
465             array($bearsamppLang\->getValue(Lang::MENU_ADD_VHOST), TplAestan::GLYPH_ADD),
466             false, get_called_class()
467         );
468 
469         // Items
470         $items = $tplAddVhost[TplApp::SECTION_CALL] \&. PHP_EOL \&.
471             TplAestan::getItemSeparator() \&. PHP_EOL;
472 
473         // Actions
474         $actions = PHP_EOL \&. $tplAddVhost[TplApp::SECTION_CONTENT];
475 
476         foreach ($bearsamppBins\->getApache()\->getVhosts() as $vhost) {
477             $tplEditVhost = TplApp::getActionMulti(
478                 self::ACTION_EDIT_VHOST, array($vhost),
479                 array(sprintf($bearsamppLang\->getValue(Lang::MENU_EDIT_VHOST), $vhost), TplAestan::GLYPH_FILE),
480                 false, get_called_class()
481             );
482 
483             // Items
484             $items \&.= $tplEditVhost[TplApp::SECTION_CALL] \&. PHP_EOL;
485 
486             // Actions
487             $actions \&.= PHP_EOL \&. PHP_EOL \&. $tplEditVhost[TplApp::SECTION_CONTENT];
488         }
489 
490         return $items \&. $actions;
491     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fBTplApp\\getActionMulti()\fP, \fBTplAestan\\getItemSeparator()\fP, \fBTplAestan\\GLYPH_ADD\fP, \fBTplAestan\\GLYPH_FILE\fP, \fBLang\\MENU_ADD_VHOST\fP, \fBLang\\MENU_EDIT_VHOST\fP, \fBTplApp\\SECTION_CALL\fP, and \fBTplApp\\SECTION_CONTENT\fP\&.
.SS "process ()\fR [static]\fP"
Generates the main Apache menu with options to enable/disable Apache and access submenus\&.

.PP
@global object $bearsamppLang Provides language support for retrieving language-specific values\&. @global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Apache\&. 
.RE
.PP

.PP
Definition at line \fB47\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.nf
48     {
49         global $bearsamppLang, $bearsamppBins;
50 
51         return TplApp::getMenuEnable($bearsamppLang\->getValue(Lang::APACHE), self::MENU, get_called_class(), $bearsamppBins\->getApache()\->isEnable());
52     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fBLang\\APACHE\fP, and \fBTplApp\\getMenuEnable()\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuLeft()\fP\&.
.SH "Field Documentation"
.PP 
.SS "const ACTION_ADD_ALIAS = 'addAlias'"

.PP
Definition at line \fB34\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const ACTION_ADD_VHOST = 'addVhost'"

.PP
Definition at line \fB36\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const ACTION_CHANGE_PORT = 'changeApachePort'"

.PP
Definition at line \fB30\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const ACTION_EDIT_ALIAS = 'editAlias'"

.PP
Definition at line \fB35\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const ACTION_EDIT_VHOST = 'editVhost'"

.PP
Definition at line \fB37\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const ACTION_ENABLE = 'enableApache'"

.PP
Definition at line \fB28\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const ACTION_INSTALL_SERVICE = 'installApacheService'"

.PP
Definition at line \fB31\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const ACTION_REMOVE_SERVICE = 'removeApacheService'"

.PP
Definition at line \fB32\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const ACTION_SWITCH_MODULE = 'switchApacheModule'"

.PP
Definition at line \fB33\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const ACTION_SWITCH_VERSION = 'switchApacheVersion'"

.PP
Definition at line \fB29\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const MENU = 'apache'"

.PP
Definition at line \fB20\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const MENU_ALIAS = 'apacheAlias'"

.PP
Definition at line \fB25\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const MENU_DEBUG = 'apacheDebug'"

.PP
Definition at line \fB23\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const MENU_MODULES = 'apacheModules'"

.PP
Definition at line \fB24\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const MENU_SERVICE = 'apacheService'"

.PP
Definition at line \fB22\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const MENU_VERSIONS = 'apacheVersions'"

.PP
Definition at line \fB21\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.
.SS "const MENU_VHOSTS = 'apacheVhosts'"

.PP
Definition at line \fB26\fP of file \fBclass\&.tpl\&.app\&.apache\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
