TplAestan
NAME
TplAestan
SYNOPSIS
Static Public Member Functions
static getActionServiceRestart ($service)
static getActionServicesClose ()
static getActionServiceStart ($service)
static getActionServiceStop ($service)
static getGlyphFlah ($lang)
static getItemActionServiceRestart ($service)
static getItemActionServicesClose ()
static getItemActionServiceStart ($service)
static getItemActionServiceStop ($service)
static getItemConsoleZ ($caption, $glyph, $id=null, $title=null, $initDir=null, $command=null)
static getItemExe ($caption, $exe, $glyph, $params=null)
static getItemExplore ($caption, $path)
static getItemLink ($caption, $link, $local=false, $glyph=self::GLYPH_WEB_PAGE)
static getItemNotepad ($caption, $path)
static getItemSeparator ()
static getSectionConfig ()
static getSectionMenuLeftSettings ($caption)
static getSectionMenuRightSettings ()
static getSectionMessages ()
Data Fields
const GLYPH_ABOUT = 21
const GLYPH_ADD = 1
const GLYPH_BROWSER = 5
const GLYPH_BRUNO = 61
const GLYPH_CHECK = 13
const GLYPH_COMPOSER = 37
const GLYPH_CONSOLEZ = 0
const GLYPH_DEBUG = 31
const GLYPH_EXIT = 20
const GLYPH_FILE = 6
const GLYPH_FOLDER_CLOSE = 3
const GLYPH_FOLDER_DISABLED = 48
const GLYPH_FOLDER_ENABLED = 49
const GLYPH_FOLDER_OPEN = 2
const GLYPH_GHOSTSCRIPT = 56
const GLYPH_GIT = 26
const GLYPH_HOSTSEDITOR = 39
const GLYPH_IMAGEMAGICK = 41
const GLYPH_LIGHT = 25
const GLYPH_NETWORK = 29
const GLYPH_NGROK = 57
const GLYPH_NODEJS = 28
const GLYPH_NOTEPAD2 = 42
const GLYPH_PASSWORD = 45
const GLYPH_PAUSE = 10
const GLYPH_PEAR = 38
const GLYPH_PERL = 55
const GLYPH_PWGEN = 58
const GLYPH_PYTHON = 50
const GLYPH_REBUILD_INI = 60
const GLYPH_RED_LIGHT = 36
const GLYPH_RELOAD = 12
const GLYPH_RESTART = 34
const GLYPH_RUBY = 52
const GLYPH_SERVICE_ALL_RUNNING = 16
const GLYPH_SERVICE_INSTALL = 8
const GLYPH_SERVICE_NONE_RUNNING = 18
const GLYPH_SERVICE_REMOVE = 7
const GLYPH_SERVICE_SOME_RUNNING = 17
const GLYPH_SERVICES_RESTART = 22
const GLYPH_SERVICES_START = 24
const GLYPH_SERVICES_STOP = 23
const GLYPH_SSL_CERTIFICATE = 35
const GLYPH_START = 9
const GLYPH_STOP = 11
const GLYPH_TRASHCAN = 32
const GLYPH_UPDATE = 33
const GLYPH_WARNING = 19
const GLYPH_WEB_PAGE = 30
const GLYPH_XLIGHT = 59
const IMG_BAR_PICTURE = 'bar.dat'
const IMG_GLYPH_SPRITES = 'sprites.dat'
const SERVICE_RESTART = 'restart'
const SERVICE_START = 'startresume'
const SERVICE_STOP = 'stop'
const SERVICES_CLOSE = 'closeservices'
Static Private Member Functions
static getActionService ($service, $action, $item=false)
Detailed Description
Class TplAestan
This class provides various methods to generate configuration strings for the Bearsampp application. It includes methods to create items for ConsoleZ, links, Notepad, executables, and explorer actions. Additionally, it handles service actions such as start, stop, and restart, and generates configuration sections for messages, config, and menu settings.
Constants:
Glyph constants for various icons used in the application.
Service actions for starting, stopping, and restarting services.
Image files used in the application.
Methods:
getGlyphFlah($lang): Retrieves the glyph flag for a given language.
getItemSeparator(): Returns a string representing a separator item.
getItemConsoleZ($caption, $glyph, $id, $title, $initDir, $command): Returns a string representing a ConsoleZ item.
getItemLink($caption, $link, $local, $glyph): Returns a string representing a link item.
getItemNotepad($caption, $path): Returns a string representing a Notepad item.
getItemExe($caption, $exe, $glyph, $params): Returns a string representing an executable item.
getItemExplore($caption, $path): Returns a string representing an explorer item.
getActionService($service, $action, $item): Returns a string representing a service action.
getActionServiceStart($service): Returns a string representing a service start action.
getItemActionServiceStart($service): Returns a string representing a service start item.
getActionServiceStop($service): Returns a string representing a service stop action.
getItemActionServiceStop($service): Returns a string representing a service stop item.
getActionServiceRestart($service): Returns a string representing a service restart action.
getItemActionServiceRestart($service): Returns a string representing a service restart item.
getActionServicesClose(): Returns a string representing a close services action.
getItemActionServicesClose(): Returns a string representing a close services item.
getSectionMessages(): Returns a string representing the messages section.
getSectionConfig(): Returns a string representing the config section.
getSectionMenuRightSettings(): Returns a string representing the right menu settings section.
getSectionMenuLeftSettings($caption): Returns a string representing the left menu settings section.
Definition at line 46 of file class.tpl.aestan.php.
Member Function Documentation
getActionService ( $service, $action, $item = false) [static], [private]
Returns a string representing a service action.
Parameters
$service The service name.
$action The action to perform.
$item Whether to return as an item.
Returns
string The service action string.
Definition at line 254 of file class.tpl.aestan.php.
    {
        global $bearsamppLang;
        $result = 'Action: ' . $action;
        if ($service != null) {
            $result = 'Action: service; ' .
                'Service: ' . $service . '; ' .
                'ServiceAction: ' . $action;
        }
        if ($item) {
            $result = 'Type: item; ' . $result;
            if ($action == self::SERVICE_START) {
                $result .= '; Caption: "' . $bearsamppLang->getValue(Lang::MENU_START_SERVICE) . '"' .
                    '; Glyph: ' . self::GLYPH_START;
            } elseif ($action == self::SERVICE_STOP) {
                $result .= '; Caption: "' . $bearsamppLang->getValue(Lang::MENU_STOP_SERVICE) . '"' .
                    '; Glyph: ' . self::GLYPH_STOP;
            } elseif ($action == self::SERVICE_RESTART) {
                $result .= '; Caption: "' . $bearsamppLang->getValue(Lang::MENU_RESTART_SERVICE) . '"' .
                    '; Glyph: ' . self::GLYPH_RELOAD;
            }
        } elseif ($action != self::SERVICES_CLOSE) {
            $result .= '; Flags: ignoreerrors waituntilterminated';
        }
        return $result;
    }
References $bearsamppLang, $result, Lang\MENU_RESTART_SERVICE, Lang\MENU_START_SERVICE, and Lang\MENU_STOP_SERVICE.
Referenced by getActionServiceRestart(), getActionServicesClose(), getActionServiceStart(), getActionServiceStop(), getItemActionServiceRestart(), getItemActionServicesClose(), getItemActionServiceStart(), and getItemActionServiceStop().
getActionServiceRestart ( $service) [static]
Returns a string representing a service restart action.
Parameters
$service The service name.
Returns
string The service restart action string.
Definition at line 334 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_RESTART, false);
    }
References getActionService().
getActionServicesClose () [static]
Returns a string representing a close services action.
Returns
string The close services action string.
Definition at line 355 of file class.tpl.aestan.php.
    {
        return self::getActionService(null, self::SERVICES_CLOSE, false);
    }
References getActionService().
getActionServiceStart ( $service) [static]
Returns a string representing a service start action.
Parameters
$service The service name.
Returns
string The service start action string.
Definition at line 290 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_START, false);
    }
References getActionService().
getActionServiceStop ( $service) [static]
Returns a string representing a service stop action.
Parameters
$service The service name.
Returns
string The service stop action string.
Definition at line 312 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_STOP, false);
    }
References getActionService().
getGlyphFlah ( $lang) [static]
Retrieves the glyph flag for a given language.
Parameters
$lang The language code.
Returns
void
Definition at line 116 of file class.tpl.aestan.php.
    {
    }
getItemActionServiceRestart ( $service) [static]
Returns a string representing a service restart item.
Parameters
$service The service name.
Returns
string The service restart item string.
Definition at line 345 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_RESTART, true);
    }
References getActionService().
Referenced by TplAppApache\getMenuApacheService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
getItemActionServicesClose () [static]
Returns a string representing a close services item.
Returns
string The close services item string.
Definition at line 365 of file class.tpl.aestan.php.
    {
        return self::getActionService(null, self::SERVICES_CLOSE, true);
    }
References getActionService().
getItemActionServiceStart ( $service) [static]
Returns a string representing a service start item.
Parameters
$service The service name.
Returns
string The service start item string.
Definition at line 301 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_STOP, true);
    }
References getActionService().
Referenced by TplAppApache\getMenuApacheService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
getItemActionServiceStop ( $service) [static]
Returns a string representing a service stop item.
Parameters
$service The service name.
Returns
string The service stop item string.
Definition at line 323 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_START, true);
    }
References getActionService().
Referenced by TplAppApache\getMenuApacheService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
getItemConsoleZ ( $caption, $glyph, $id = null, $title = null, $initDir = null, $command = null) [static]
Returns a string representing a ConsoleZ item.
Parameters
$caption The caption for the item.
$glyph The glyph index.
$id The ID for the item.
$title The title for the item.
$initDir The initial directory for the item.
$command The command to execute.
Returns
string The ConsoleZ item string.
Definition at line 141 of file class.tpl.aestan.php.
    {
        global $bearsamppTools;
        $args = '';
        if ($id != null) {
            $args .= ' -t ""' . $id . '""';
        }
        if ($title != null) {
            $args .= ' -w ""' . $title . '""';
        }
        if ($initDir != null) {
            $args .= ' -d ""' . $initDir . '""';
        }
        if ($command != null) {
            $args .= ' -r ""' . $command . '""';
        }
        return self::getItemExe(
            $caption,
            $bearsamppTools->getConsoleZ()->getExe(),
            $glyph,
            $args
        );
    }
References getItemExe().
Referenced by TplAppGit\getMenuGit(), TplAppGit\getMenuGitRepos(), TplAppMariadb\getMenuMariadb(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPostgresql\getMenuPostgresql(), TplAppPython\getMenuPython(), and TplAppTools\getMenuTools().
getItemExe ( $caption, $exe, $glyph, $params = null) [static]
Returns a string representing an executable item.
Parameters
$caption The caption for the item.
$exe The path to the executable.
$glyph The glyph index.
$params The parameters for the executable.
Returns
string The executable item string.
Definition at line 220 of file class.tpl.aestan.php.
    {
        return 'Type: item; ' .
            'Caption: "' . $caption . '"; ' .
            'Action: run; ' .
            'FileName: "' . $exe . '"; ' .
            (!empty($params) ? 'Parameters: "' . $params . '"; ' : '') .
            'Glyph: ' . $glyph;
    }
Referenced by getItemConsoleZ(), getItemLink(), getItemNotepad(), TplAppGit\getMenuGit(), TplAppMailpit\getMenuMailpit(), TplAppPython\getMenuPython(), and TplAppTools\getMenuTools().
getItemExplore ( $caption, $path) [static]
Returns a string representing an explorer item.
Parameters
$caption The caption for the item.
$path The path to explore.
Returns
string The explorer item string.
Definition at line 237 of file class.tpl.aestan.php.
    {
        return 'Type: item; ' .
            'Caption: "' . $caption . '"; ' .
            'Action: shellexecute; ' .
            'FileName: "' . $path . '"; ' .
            'Glyph: ' . self::GLYPH_FOLDER_OPEN;
    }
Referenced by TplApp\getSectionMenuLeft().
getItemLink ( $caption, $link, $local = false, $glyph = self::GLYPH_WEB_PAGE) [static]
Returns a string representing a link item.
Parameters
$caption The caption for the item.
$link The URL for the link.
$local Whether the link is local.
$glyph The glyph index.
Returns
string The link item string.
Definition at line 176 of file class.tpl.aestan.php.
    {
        global $bearsamppRoot, $bearsamppConfig;
        if ($local) {
            $link = $bearsamppRoot->getLocalUrl($link);
        }
        return self::getItemExe(
            $caption,
            $bearsamppConfig->getBrowser(),
            $glyph,
            $link
        );
    }
References $bearsamppConfig, $bearsamppRoot, and getItemExe().
Referenced by TplAppApache\getMenuApache(), TplAppApps\getMenuApps(), TplAppMailpit\getMenuMailpit(), TplAppMariadb\getMenuMariadb(), TplAppMemcached\getMenuMemcached(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPhp\getMenuPhp(), TplAppPostgresql\getMenuPostgresql(), TplAppXlight\getMenuXlight(), TplApp\getSectionMenuLeft(), and TplApp\getSectionMenuRight().
getItemNotepad ( $caption, $path) [static]
Returns a string representing a Notepad item.
Parameters
$caption The caption for the item.
$path The path to the file.
Returns
string The Notepad item string.
Definition at line 199 of file class.tpl.aestan.php.
    {
        global $bearsamppConfig;
        return self::getItemExe(
            $caption,
            $bearsamppConfig->getNotepad(),
            self::GLYPH_FILE,
            $path
        );
    }
References $bearsamppConfig, and getItemExe().
Referenced by TplAppApache\getMenuApache(), TplAppApache\getMenuApacheService(), TplAppLogs\getMenuLogs(), TplAppMailpit\getMenuMailpit(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadb(), TplAppMemcached\getMenuMemcached(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPhp\getMenuPhp(), TplAppPostgresql\getMenuPostgresql(), TplAppXlight\getMenuXlight(), TplAppXlight\getMenuXlightService(), and TplAppEditConf\process().
getItemSeparator () [static]
Returns a string representing a separator item.
Returns
string The separator item string.
Definition at line 125 of file class.tpl.aestan.php.
    {
        return 'Type: separator';
    }
Referenced by TplAppApache\getMenuApache(), TplAppApache\getMenuApacheAlias(), TplAppApache\getMenuApacheService(), TplAppApache\getMenuApacheVhosts(), TplAppGit\getMenuGit(), TplAppMailpit\getMenuMailpit(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadb(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcached(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysql(), TplAppMysql\getMenuMysqlService(), TplAppNodejs\getMenuNodejs(), TplAppPhp\getMenuPhp(), TplAppPostgresql\getMenuPostgresql(), TplAppPostgresql\getMenuPostgresqlService(), TplAppTools\getMenuTools(), TplAppXlight\getMenuXlight(), TplAppXlight\getMenuXlightService(), TplApp\getSectionMenuLeft(), and TplApp\getSectionMenuRight().
getSectionConfig () [static]
Returns a string representing the config section.
Returns
string The config section string.
Definition at line 390 of file class.tpl.aestan.php.
    {
        global $bearsamppCore;
        return '[Config]' . PHP_EOL .
            'ImageList=' . self::IMG_GLYPH_SPRITES . PHP_EOL .
            'ServiceCheckInterval=1' . PHP_EOL .
            'TrayIconAllRunning=' . self::GLYPH_SERVICE_ALL_RUNNING . PHP_EOL .
            'TrayIconSomeRunning=' . self::GLYPH_SERVICE_SOME_RUNNING . PHP_EOL .
            'TrayIconNoneRunning=' . self::GLYPH_SERVICE_NONE_RUNNING . PHP_EOL .
            'ID={' . strtolower(APP_TITLE) . '}' . PHP_EOL .
            'AboutHeader=' . APP_TITLE . PHP_EOL .
            'AboutVersion=Version ' . $bearsamppCore->getAppVersion() . PHP_EOL;
    }
References $bearsamppCore, and APP_TITLE.
Referenced by TplApp\process(), and TplApp\processLight().
getSectionMenuLeftSettings ( $caption) [static]
Returns a string representing the left menu settings section.
Parameters
$caption The caption for the left menu.
Returns
string The left menu settings section string.
Definition at line 429 of file class.tpl.aestan.php.
    {
        return '[Menu.Left.Settings]' . PHP_EOL .
            'AutoLineReduction=no' . PHP_EOL .
            'BarVisible=yes' . PHP_EOL .
            'BarCaptionAlignment=bottom' . PHP_EOL .
            'BarCaptionCaption=' . $caption . PHP_EOL .
            'BarCaptionDepth=1' . PHP_EOL .
            'BarCaptionDirection=downtoup' . PHP_EOL .
            'BarCaptionFont=Tahoma,14,clWhite' . PHP_EOL .
            'BarCaptionHighlightColor=clNone' . PHP_EOL .
            'BarCaptionOffsetY=0' . PHP_EOL .
            'BarCaptionShadowColor=clNone' . PHP_EOL .
            'BarPictureHorzAlignment=center' . PHP_EOL .
            'BarPictureOffsetX=0' . PHP_EOL .
            'BarPictureOffsetY=0' . PHP_EOL .
            'BarPicturePicture=' . self::IMG_BAR_PICTURE . PHP_EOL .
            'BarPictureTransparent=yes' . PHP_EOL .
            'BarPictureVertAlignment=bottom' . PHP_EOL .
            'BarBorder=clNone' . PHP_EOL .
            'BarGradientEnd=$00c07840' . PHP_EOL .
            'BarGradientStart=$00c07840' . PHP_EOL .
            'BarGradientStyle=horizontal' . PHP_EOL .
            'BarSide=left' . PHP_EOL .
            'BarSpace=0' . PHP_EOL .
            'BarWidth=32' . PHP_EOL .
            'SeparatorsAlignment=center' . PHP_EOL .
            'SeparatorsFade=yes' . PHP_EOL .
            'SeparatorsFadeColor=clBtnShadow' . PHP_EOL .
            'SeparatorsFlatLines=yes' . PHP_EOL .
            'SeparatorsFont=Arial,8,clWhite,bold' . PHP_EOL .
            'SeparatorsGradientEnd=$00FFAA55' . PHP_EOL .
            'SeparatorsGradientStart=$00550000' . PHP_EOL .
            'SeparatorsGradientStyle=horizontal' . PHP_EOL .
            'SeparatorsSeparatorStyle=caption' . PHP_EOL;
    }
Referenced by TplApp\process().
getSectionMenuRightSettings () [static]
Returns a string representing the right menu settings section.
Returns
string The right menu settings section string.
Definition at line 409 of file class.tpl.aestan.php.
    {
        return '[Menu.Right.Settings]' . PHP_EOL .
            'BarVisible=no' . PHP_EOL .
            'SeparatorsAlignment=center' . PHP_EOL .
            'SeparatorsFade=yes' . PHP_EOL .
            'SeparatorsFadeColor=clBtnShadow' . PHP_EOL .
            'SeparatorsFlatLines=yes' . PHP_EOL .
            'SeparatorsGradientEnd=clSilver' . PHP_EOL .
            'SeparatorsGradientStart=clGray' . PHP_EOL .
            'SeparatorsGradientStyle=horizontal' . PHP_EOL .
            'SeparatorsSeparatorStyle=shortline' . PHP_EOL;
    }
Referenced by TplApp\process().
getSectionMessages () [static]
Returns a string representing the messages section.
Returns
string The messages section string.
Definition at line 375 of file class.tpl.aestan.php.
    {
        global $bearsamppLang;
        return '[Messages]' . PHP_EOL .
            'AllRunningHint=' . $bearsamppLang->getValue(Lang::ALL_RUNNING_HINT) . PHP_EOL .
            'SomeRunningHint=' . $bearsamppLang->getValue(Lang::SOME_RUNNING_HINT) . PHP_EOL .
            'NoneRunningHint=' . $bearsamppLang->getValue(Lang::NONE_RUNNING_HINT) . PHP_EOL;
    }
References $bearsamppLang, Lang\ALL_RUNNING_HINT, Lang\NONE_RUNNING_HINT, and Lang\SOME_RUNNING_HINT.
Referenced by TplApp\process(), and TplApp\processLight().
Field Documentation
const GLYPH_ABOUT = 21
Definition at line 67 of file class.tpl.aestan.php.
Referenced by TplApp\getSectionMenuRight().
const GLYPH_ADD = 1
Definition at line 50 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheAlias(), and TplAppApache\getMenuApacheVhosts().
const GLYPH_BROWSER = 5
Definition at line 53 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApache(), TplAppMailpit\getMenuMailpit(), TplAppMariadb\getMenuMariadb(), TplAppMemcached\getMenuMemcached(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPhp\getMenuPhp(), TplAppPostgresql\getMenuPostgresql(), TplAppXlight\getMenuXlight(), and TplAppBrowser\process().
const GLYPH_BRUNO = 61
Definition at line 98 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
const GLYPH_CHECK = 13
Definition at line 61 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApache(), TplAppApache\getMenuApacheModules(), TplAppApache\getMenuApacheVersions(), TplAppGit\getMenuGit(), TplAppLang\getMenuLang(), TplAppLogsVerbose\getMenuLogsVerbose(), TplAppMailpit\getMenuMailpit(), TplAppMailpit\getMenuMailpitVersions(), TplAppMariadb\getMenuMariadb(), TplAppMariadb\getMenuMariadbVersions(), TplAppMemcached\getMenuMemcached(), TplAppMemcached\getMenuMemcachedVersions(), TplAppMysql\getMenuMysql(), TplAppMysql\getMenuMysqlVersions(), TplAppNodejs\getMenuNodejs(), TplAppNodejs\getMenuNodejsVersions(), TplAppPhp\getMenuPhp(), TplAppPhp\getMenuPhpExtensions(), TplAppPhp\getMenuPhpSettings(), TplAppPhp\getMenuPhpVersions(), TplAppPostgresql\getMenuPostgresql(), TplAppPostgresql\getMenuPostgresqlVersions(), TplAppXlight\getMenuXlight(), TplAppXlight\getMenuXlightVersions(), TplAppPhp\getSubmenuPhpSettings(), and TplAppLaunchStartup\process().
const GLYPH_COMPOSER = 37
Definition at line 82 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
const GLYPH_CONSOLEZ = 0
Definition at line 49 of file class.tpl.aestan.php.
Referenced by TplAppMariadb\getMenuMariadb(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPostgresql\getMenuPostgresql(), and TplAppTools\getMenuTools().
const GLYPH_DEBUG = 31
Definition at line 76 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheDebug(), TplAppMariadb\getMenuMariadbDebug(), TplAppMysql\getMenuMysqlDebug(), and TplAppPostgresql\getMenuPostgresqlDebug().
const GLYPH_EXIT = 20
Definition at line 66 of file class.tpl.aestan.php.
Referenced by TplAppExit\process().
const GLYPH_FILE = 6
Definition at line 54 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheAlias(), and TplAppApache\getMenuApacheVhosts().
const GLYPH_FOLDER_CLOSE = 3
Definition at line 52 of file class.tpl.aestan.php.
Referenced by TplApp\getMenu(), TplApp\getMenuEnable(), TplAppPhp\getMenuPhpSettings(), and TplAppPhp\getSubmenuPhpSettings().
const GLYPH_FOLDER_DISABLED = 48
Definition at line 88 of file class.tpl.aestan.php.
Referenced by TplApp\getMenuEnable().
const GLYPH_FOLDER_ENABLED = 49
Definition at line 89 of file class.tpl.aestan.php.
const GLYPH_FOLDER_OPEN = 2
Definition at line 51 of file class.tpl.aestan.php.
const GLYPH_GHOSTSCRIPT = 56
Definition at line 93 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
const GLYPH_GIT = 26
Definition at line 72 of file class.tpl.aestan.php.
Referenced by TplAppGit\getMenuGit(), and TplAppGit\getMenuGitRepos().
const GLYPH_HOSTSEDITOR = 39
Definition at line 84 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
const GLYPH_IMAGEMAGICK = 41
Definition at line 85 of file class.tpl.aestan.php.
const GLYPH_LIGHT = 25
Definition at line 71 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
const GLYPH_NETWORK = 29
Definition at line 74 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
const GLYPH_NGROK = 57
Definition at line 94 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
const GLYPH_NODEJS = 28
Definition at line 73 of file class.tpl.aestan.php.
const GLYPH_NOTEPAD2 = 42
Definition at line 86 of file class.tpl.aestan.php.
const GLYPH_PASSWORD = 45
Definition at line 87 of file class.tpl.aestan.php.
Referenced by TplAppMariadb\getMenuMariadbService(), TplAppMysql\getMenuMysqlService(), and TplAppPostgresql\getMenuPostgresqlService().
const GLYPH_PAUSE = 10
Definition at line 58 of file class.tpl.aestan.php.
const GLYPH_PEAR = 38
Definition at line 83 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
const GLYPH_PERL = 55
Definition at line 92 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
const GLYPH_PWGEN = 58
Definition at line 95 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
const GLYPH_PYTHON = 50
Definition at line 90 of file class.tpl.aestan.php.
Referenced by TplAppPython\getMenuPython().
const GLYPH_REBUILD_INI = 60
Definition at line 97 of file class.tpl.aestan.php.
Referenced by TplAppRebuildIni\process().
const GLYPH_RED_LIGHT = 36
Definition at line 81 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheService().
const GLYPH_RELOAD = 12
Definition at line 60 of file class.tpl.aestan.php.
Referenced by TplService\getItemRestart(), TplAppGit\getMenuGit(), and TplAppReload\process().
const GLYPH_RESTART = 34
Definition at line 79 of file class.tpl.aestan.php.
const GLYPH_RUBY = 52
Definition at line 91 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
const GLYPH_SERVICE_ALL_RUNNING = 16
Definition at line 62 of file class.tpl.aestan.php.
const GLYPH_SERVICE_INSTALL = 8
Definition at line 56 of file class.tpl.aestan.php.
Referenced by TplService\getItemInstall(), TplAppApache\getMenuApacheService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
const GLYPH_SERVICE_NONE_RUNNING = 18
Definition at line 64 of file class.tpl.aestan.php.
const GLYPH_SERVICE_REMOVE = 7
Definition at line 55 of file class.tpl.aestan.php.
Referenced by TplService\getItemRemove(), TplAppApache\getMenuApacheService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
const GLYPH_SERVICE_SOME_RUNNING = 17
Definition at line 63 of file class.tpl.aestan.php.
const GLYPH_SERVICES_RESTART = 22
Definition at line 68 of file class.tpl.aestan.php.
Referenced by TplAppServices\process().
const GLYPH_SERVICES_START = 24
Definition at line 70 of file class.tpl.aestan.php.
Referenced by TplAppServices\process().
const GLYPH_SERVICES_STOP = 23
Definition at line 69 of file class.tpl.aestan.php.
Referenced by TplAppServices\process().
const GLYPH_SSL_CERTIFICATE = 35
Definition at line 80 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
const GLYPH_START = 9
Definition at line 57 of file class.tpl.aestan.php.
Referenced by TplService\getItemStart().
const GLYPH_STOP = 11
Definition at line 59 of file class.tpl.aestan.php.
Referenced by TplService\getItemStop().
const GLYPH_TRASHCAN = 32
Definition at line 77 of file class.tpl.aestan.php.
Referenced by TplAppClearFolders\process().
const GLYPH_UPDATE = 33
Definition at line 78 of file class.tpl.aestan.php.
Referenced by TplApp\getSectionMenuRight().
const GLYPH_WARNING = 19
Definition at line 65 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheVersions(), TplAppPhp\getMenuPhpSettings(), TplAppPhp\getMenuPhpVersions(), and TplAppPhp\getSubmenuPhpSettings().
const GLYPH_WEB_PAGE = 30
Definition at line 75 of file class.tpl.aestan.php.
Referenced by TplAppMailpit\getMenuMailpit().
const GLYPH_XLIGHT = 59
Definition at line 96 of file class.tpl.aestan.php.
const IMG_BAR_PICTURE = 'bar.dat'
Definition at line 107 of file class.tpl.aestan.php.
const IMG_GLYPH_SPRITES = 'sprites.dat'
Definition at line 108 of file class.tpl.aestan.php.
const SERVICE_RESTART = 'restart'
Definition at line 103 of file class.tpl.aestan.php.
const SERVICE_START = 'startresume'
Definition at line 101 of file class.tpl.aestan.php.
const SERVICE_STOP = 'stop'
Definition at line 102 of file class.tpl.aestan.php.
const SERVICES_CLOSE = 'closeservices'
Definition at line 104 of file class.tpl.aestan.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.