.TH "TplAppNodejs" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TplAppNodejs
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetActionEnableNodejs\fP ($enable)"
.br
.ti -1c
.RI "static \fBgetActionSwitchNodejsVersion\fP ($version)"
.br
.ti -1c
.RI "static \fBgetMenuNodejs\fP ()"
.br
.ti -1c
.RI "static \fBgetMenuNodejsVersions\fP ()"
.br
.ti -1c
.RI "static \fBprocess\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBACTION_ENABLE\fP = 'enableNodejs'"
.br
.ti -1c
.RI "const \fBACTION_SWITCH_VERSION\fP = 'switchNodejsVersion'"
.br
.ti -1c
.RI "const \fBMENU\fP = 'nodejs'"
.br
.ti -1c
.RI "const \fBMENU_VERSIONS\fP = 'nodejsVersions'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBTplAppNodejs\fP

.PP
This class provides methods to generate and manage menu items and actions related to Node\&.js within the \fBBearsampp\fP application\&. It includes functionalities for enabling/disabling Node\&.js, switching Node\&.js versions, and generating menus for Node\&.js actions\&. 
.PP
Definition at line \fB16\fP of file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "getActionEnableNodejs ( $enable)\fR [static]\fP"
Generates the action to enable or disable Node\&.js\&.

.PP
This method creates the action string for enabling or disabling Node\&.js\&. It includes commands to reload the application\&.

.PP
\fBParameters\fP
.RS 4
\fI$enable\fP The flag indicating whether to enable (1) or disable (0) Node\&.js\&.
.RE
.PP
@global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated action string for enabling or disabling Node\&.js\&. 
.RE
.PP

.PP
Definition at line \fB159\fP of file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP\&.
.nf
160     {
161         global $bearsamppBins;
162 
163         return TplApp::getActionRun(
164             Action::ENABLE,
165             array($bearsamppBins\->getNodejs()\->getName(), $enable)
166         ) \&. PHP_EOL \&. TplAppReload::getActionReload();
167     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fBAction\\ENABLE\fP, \fBTplAppReload\\getActionReload()\fP, and \fBTplApp\\getActionRun()\fP\&.
.SS "getActionSwitchNodejsVersion ( $version)\fR [static]\fP"
Generates the action to switch Node\&.js versions\&.

.PP
This method creates the action string for switching Node\&.js versions\&. It includes commands to reload the application\&.

.PP
\fBParameters\fP
.RS 4
\fI$version\fP The version of Node\&.js to switch to\&.
.RE
.PP
@global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated action string for switching Node\&.js versions\&. 
.RE
.PP

.PP
Definition at line \fB180\fP of file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP\&.
.nf
181     {
182         global $bearsamppBins;
183 
184         return TplApp::getActionRun(
185             Action::SWITCH_VERSION,
186             array($bearsamppBins\->getNodejs()\->getName(), $version)
187         ) \&. PHP_EOL \&. TplAppReload::getActionReload() \&. PHP_EOL;
188     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fBTplAppReload\\getActionReload()\fP, \fBTplApp\\getActionRun()\fP, and \fBAction\\SWITCH_VERSION\fP\&.
.SS "getMenuNodejs ()\fR [static]\fP"
Generates the Node\&.js menu items and associated actions\&.

.PP
This method creates menu items for Node\&.js, including options to download more versions, enable/disable Node\&.js, switch versions, open a console, and edit the configuration file\&.

.PP
@global object $bearsamppBins Provides access to system binaries and their configurations\&. @global object $bearsamppLang Provides language support for retrieving language-specific values\&. @global object $bearsamppTools Provides access to various tools used in the application\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Node\&.js\&. 
.RE
.PP

.PP
Definition at line \fB59\fP of file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP\&.
.nf
60     {
61         global $bearsamppBins, $bearsamppLang, $bearsamppTools;
62         $resultItems = $resultActions = '';
63 
64         $isEnabled = $bearsamppBins\->getNodejs()\->isEnable();
65 
66         // Download
67         $resultItems \&.= TplAestan::getItemLink(
68             $bearsamppLang\->getValue(Lang::DOWNLOAD_MORE),
69             Util::getWebsiteUrl('module/nodejs', '#releases'),
70             false,
71             TplAestan::GLYPH_BROWSER
72         ) \&. PHP_EOL;
73 
74         // Enable
75         $tplEnable = TplApp::getActionMulti(
76             self::ACTION_ENABLE,
77             array($isEnabled ? Config::DISABLED : Config::ENABLED),
78             array($bearsamppLang\->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
79             false,
80             get_called_class()
81         );
82         $resultItems \&.= $tplEnable[TplApp::SECTION_CALL] \&. PHP_EOL;
83         $resultActions \&.= $tplEnable[TplApp::SECTION_CONTENT] \&. PHP_EOL;
84 
85         if ($isEnabled) {
86             $resultItems \&.= TplAestan::getItemSeparator() \&. PHP_EOL;
87 
88             // Versions
89             $tplVersions = TplApp::getMenu(
90                 $bearsamppLang\->getValue(Lang::VERSIONS),
91                 self::MENU_VERSIONS,
92                 get_called_class()
93             );
94             $resultItems \&.= $tplVersions[TplApp::SECTION_CALL] \&. PHP_EOL;
95             $resultActions \&.= $tplVersions[TplApp::SECTION_CONTENT];
96 
97             // Console
98             $resultItems \&.= TplAestan::getItemConsoleZ(
99                 $bearsamppLang\->getValue(Lang::CONSOLE),
100                 TplAestan::GLYPH_CONSOLEZ,
101                 $bearsamppTools\->getConsoleZ()\->getTabTitleNodejs()
102             ) \&. PHP_EOL;
103 
104             // Conf
105             $resultItems \&.= TplAestan::getItemNotepad(
106                 basename($bearsamppBins\->getNodejs()\->getConf()),
107                 $bearsamppBins\->getNodejs()\->getConf()
108             ) \&. PHP_EOL;
109         }
110 
111         return $resultItems \&. PHP_EOL \&. $resultActions;
112     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fBLang\\CONSOLE\fP, \fBConfig\\DISABLED\fP, \fBLang\\DOWNLOAD_MORE\fP, \fBConfig\\ENABLED\fP, \fBTplApp\\getActionMulti()\fP, \fBTplAestan\\getItemConsoleZ()\fP, \fBTplAestan\\getItemLink()\fP, \fBTplAestan\\getItemNotepad()\fP, \fBTplAestan\\getItemSeparator()\fP, \fBTplApp\\getMenu()\fP, \fBUtil\\getWebsiteUrl()\fP, \fBTplAestan\\GLYPH_BROWSER\fP, \fBTplAestan\\GLYPH_CHECK\fP, \fBTplAestan\\GLYPH_CONSOLEZ\fP, \fBLang\\MENU_ENABLE\fP, \fBTplApp\\SECTION_CALL\fP, \fBTplApp\\SECTION_CONTENT\fP, and \fBLang\\VERSIONS\fP\&.
.SS "getMenuNodejsVersions ()\fR [static]\fP"
Generates the Node\&.js versions menu items and associated actions\&.

.PP
This method creates menu items for switching between different Node\&.js versions\&.

.PP
@global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
string The generated menu items and actions for Node\&.js versions\&. 
.RE
.PP

.PP
Definition at line \fB123\fP of file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP\&.
.nf
124     {
125         global $bearsamppBins;
126         $items = '';
127         $actions = '';
128 
129         foreach ($bearsamppBins\->getNodejs()\->getVersionList() as $version) {
130             $tplSwitchNodejsVersion = TplApp::getActionMulti(
131                 self::ACTION_SWITCH_VERSION,
132                 array($version),
133                 array($version, $version == $bearsamppBins\->getNodejs()\->getVersion() ? TplAestan::GLYPH_CHECK : ''),
134                 false,
135                 get_called_class()
136             );
137 
138             // Item
139             $items \&.= $tplSwitchNodejsVersion[TplApp::SECTION_CALL] \&. PHP_EOL;
140 
141             // Action
142             $actions \&.= PHP_EOL \&. $tplSwitchNodejsVersion[TplApp::SECTION_CONTENT];
143         }
144 
145         return $items \&. $actions;
146     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fBTplApp\\getActionMulti()\fP, \fBTplAestan\\GLYPH_CHECK\fP, \fBTplApp\\SECTION_CALL\fP, and \fBTplApp\\SECTION_CONTENT\fP\&.
.SS "process ()\fR [static]\fP"
Processes and generates the Node\&.js menu\&.

.PP
This method generates the menu for Node\&.js, including options to enable/disable Node\&.js and switch versions\&.

.PP
@global object $bearsamppLang Provides language support for retrieving language-specific values\&. @global object $bearsamppBins Provides access to system binaries and their configurations\&.

.PP
\fBReturns\fP
.RS 4
array The generated menu for Node\&.js\&. 
.RE
.PP

.PP
Definition at line \fB35\fP of file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP\&.
.nf
36     {
37         global $bearsamppLang, $bearsamppBins;
38 
39         return TplApp::getMenuEnable(
40             $bearsamppLang\->getValue(Lang::NODEJS),
41             self::MENU,
42             get_called_class(),
43             $bearsamppBins\->getNodejs()\->isEnable()
44         );
45     }
.PP
.fi

.PP
References \fB$bearsamppBins\fP, \fB$bearsamppLang\fP, \fBTplApp\\getMenuEnable()\fP, and \fBLang\\NODEJS\fP\&.
.PP
Referenced by \fBTplApp\\getSectionMenuLeft()\fP\&.
.SH "Field Documentation"
.PP 
.SS "const ACTION_ENABLE = 'enableNodejs'"

.PP
Definition at line \fB22\fP of file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP\&.
.SS "const ACTION_SWITCH_VERSION = 'switchNodejsVersion'"

.PP
Definition at line \fB23\fP of file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP\&.
.SS "const MENU = 'nodejs'"

.PP
Definition at line \fB19\fP of file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP\&.
.SS "const MENU_VERSIONS = 'nodejsVersions'"

.PP
Definition at line \fB20\fP of file \fBclass\&.tpl\&.app\&.nodejs\&.php\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
