TplAppReload
NAME
TplAppReload
SYNOPSIS
Static Public Member Functions
static getActionReload ()
static process ()
static triggerReload ($args=null)
Data Fields
const ACTION = 'reload'
Detailed Description
Manages reload action templates and execution for Bearsampp menu system
Definition at line 6 of file class.tpl.app.reload.php.
Member Function Documentation
getActionReload () [static]
Builds sequence of actions for configuration reload
Returns
string Concatenated action sequence containing:
1.
PHP process execution command
2.
Service reset command
3.
Configuration reload command
Definition at line 44 of file class.tpl.app.reload.php.
                                            : string
    {
        return implode("\n", [
            TplApp::getActionRun(Action::RELOAD),
            'Action: resetservices',
            'Action: readconfig'
        ]);
    }
References TplApp\getActionRun(), and Action\RELOAD.
Referenced by TplAppApache\getActionAddAlias(), TplAppApache\getActionAddVhost(), TplAppApache\getActionChangeApachePort(), TplAppBrowser\getActionChangeBrowser(), TplAppMailpit\getActionChangeMailpitPort(), TplAppMariadb\getActionChangeMariadbPort(), TplAppMariadb\getActionChangeMariadbRootPwd(), TplAppMemcached\getActionChangeMemcachedPort(), TplAppMysql\getActionChangeMysqlPort(), TplAppMysql\getActionChangeMysqlRootPwd(), TplAppPostgresql\getActionChangePostgresqlPort(), TplAppPostgresql\getActionChangePostgresqlRootPwd(), TplAppXlight\getActionChangeXlightPort(), TplAppApache\getActionEditAlias(), TplAppApache\getActionEditVhost(), TplAppApache\getActionEnableApache(), TplAppMailpit\getActionEnableMailpit(), TplAppMariadb\getActionEnableMariadb(), TplAppMemcached\getActionEnableMemcached(), TplAppMysql\getActionEnableMysql(), TplAppNodejs\getActionEnableNodejs(), TplAppPhp\getActionEnablePhp(), TplAppPostgresql\getActionEnablePostgresql(), TplAppXlight\getActionEnableXlight(), TplAppApache\getActionInstallApacheService(), TplAppMailpit\getActionInstallMailpitService(), TplAppMariadb\getActionInstallMariadbService(), TplAppMemcached\getActionInstallMemcachedService(), TplAppMysql\getActionInstallMysqlService(), TplAppPostgresql\getActionInstallPostgresqlService(), TplAppXlight\getActionInstallXlightService(), TplAppLaunchStartup\getActionLaunchStartup(), TplAppGit\getActionRefreshGitRepos(), TplAppGit\getActionRefreshGitReposStartup(), TplAppApache\getActionRemoveApacheService(), TplAppMailpit\getActionRemoveMailpitService(), TplAppMariadb\getActionRemoveMariadbService(), TplAppMemcached\getActionRemoveMemcachedService(), TplAppMysql\getActionRemoveMysqlService(), TplAppPostgresql\getActionRemovePostgresqlService(), TplAppXlight\getActionRemoveXlightService(), TplAppOnline\getActionStatus(), TplAppApache\getActionSwitchApacheModule(), TplAppApache\getActionSwitchApacheVersion(), TplAppLang\getActionSwitchLang(), TplAppLogsVerbose\getActionSwitchLogsVerbose(), TplAppMailpit\getActionSwitchMailpitVersion(), TplAppMariadb\getActionSwitchMariadbVersion(), TplAppMemcached\getActionSwitchMemcachedVersion(), TplAppMysql\getActionSwitchMysqlVersion(), TplAppNodejs\getActionSwitchNodejsVersion(), TplAppPhp\getActionSwitchPhpExtension(), TplAppPhp\getActionSwitchPhpSetting(), TplAppPhp\getActionSwitchPhpVersion(), TplAppPostgresql\getActionSwitchPostgresqlVersion(), TplAppXlight\getActionSwitchXlightVersion(), TplApp\getSectionStartupAction(), and triggerReload().
process () [static]
Generates multi-action menu item for reload functionality
@global Lang $bearsamppLang Bearsampp language configuration instance
Returns
array Array structure for TplApp\getActionMulti containing:
Action identifier
Action parameters
Menu item configuration (label + glyph)
Disabled state
Calling class name
Definition at line 24 of file class.tpl.app.reload.php.
                                    : array
    {
        global $bearsamppLang;
        return TplApp::getActionMulti(
            self::ACTION,
            null,
            [$bearsamppLang->getValue(Lang::RELOAD), TplAestan::GLYPH_RELOAD],
            false,
            get_called_class()
        );
    }
References $bearsamppLang, TplApp\getActionMulti(), TplAestan\GLYPH_RELOAD, and Lang\RELOAD.
Referenced by TplApp\getSectionMenuRight().
triggerReload ( $args = null) [static]
Executes reload sequence and returns action string
Parameters
$args Arguments to pass to reload action
Returns
string Generated INI action sequence
Exceptions
Exception If reload operation fails
@log TRACE: Logs method entry and generated action content @log ERROR: Captures and logs any exceptions during reload
Definition at line 63 of file class.tpl.app.reload.php.
                                                      : string
    {
        Util::logTrace('ENTERING triggerReload..');
        try {
            new ActionReload($args);
            $actionContent = self::getActionReload();
            Util::logTrace('Generated reload actions: ' . $actionContent);
            return $actionContent;
        } catch (Exception $e) {
            Util::logError('Reload failed: ' . $e->getMessage());
            return '';
        }
    }
References getActionReload(), Util\logError(), and Util\logTrace().
Referenced by ActionRebuildini\__construct().
Field Documentation
const ACTION = 'reload'
Definition at line 11 of file class.tpl.app.reload.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.