TplService
NAME
TplService
SYNOPSIS
Static Public Member Functions
static getActionCreate ($sName)
static getActionInstall ($sName)
static getActionRemove ($sName)
static getActionRestart ($sName)
static getActionStart ($sName)
static getActionStop ($sName)
static getItemInstall ($sName)
static getItemRemove ($sName)
static getItemRestart ($sName)
static getItemStart ($sName)
static getItemStop ($sName)
Detailed Description
Definition at line 10 of file class.tpl.service.php.
Member Function Documentation
getActionCreate ( $sName) [static]
Generates an action string to create a service.
Parameters
$sName The name of the service to create.
Returns
string The generated action string for creating the service.
Definition at line 18 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::CREATE));
    }
References ActionService\CREATE, TplApp\getActionRun(), and Action\SERVICE.
getActionInstall ( $sName) [static]
Generates an action string to install a service.
Parameters
$sName The name of the service to install.
Returns
string The generated action string for installing the service.
Definition at line 62 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::INSTALL));
    }
References TplApp\getActionRun(), ActionService\INSTALL, and Action\SERVICE.
getActionRemove ( $sName) [static]
Generates an action string to remove a service.
Parameters
$sName The name of the service to remove.
Returns
string The generated action string for removing the service.
Definition at line 73 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::REMOVE));
    }
References TplApp\getActionRun(), ActionService\REMOVE, and Action\SERVICE.
getActionRestart ( $sName) [static]
Generates an action string to restart a service.
Parameters
$sName The name of the service to restart.
Returns
string The generated action string for restarting the service.
Definition at line 51 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::RESTART));
    }
References TplApp\getActionRun(), ActionService\RESTART, and Action\SERVICE.
Referenced by TplAppOnline\getActionStatus(), TplAppApache\getActionSwitchApacheModule(), TplAppPhp\getActionSwitchPhpExtension(), TplAppPhp\getActionSwitchPhpSetting(), and ActionEditVhost\processWindow().
getActionStart ( $sName) [static]
Generates an action string to start a service.
Parameters
$sName The name of the service to start.
Returns
string The generated action string for starting the service.
Definition at line 29 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::START));
    }
References TplApp\getActionRun(), Action\SERVICE, and ActionService\START.
Referenced by TplAppServices\getActionStartServices().
getActionStop ( $sName) [static]
Generates an action string to stop a service.
Parameters
$sName The name of the service to stop.
Returns
string The generated action string for stopping the service.
Definition at line 40 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::STOP));
    }
References TplApp\getActionRun(), Action\SERVICE, and ActionService\STOP.
Referenced by TplAppServices\getActionStopServices().
getItemInstall ( $sName) [static]
Generates a menu item to install a service.
Parameters
$sName The name of the service to install.
Returns
string The generated menu item string for installing the service.
Definition at line 132 of file class.tpl.service.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::SERVICE, array($sName, ActionService::INSTALL),
            array($bearsamppLang->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL)
        );
    }
References $bearsamppLang, TplApp\getActionRun(), TplAestan\GLYPH_SERVICE_INSTALL, ActionService\INSTALL, Lang\MENU_INSTALL_SERVICE, and Action\SERVICE.
getItemRemove ( $sName) [static]
Generates a menu item to remove a service.
Parameters
$sName The name of the service to remove.
Returns
string The generated menu item string for removing the service.
Definition at line 148 of file class.tpl.service.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::SERVICE, array($sName, ActionService::REMOVE),
            array($bearsamppLang->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE)
        );
    }
References $bearsamppLang, TplApp\getActionRun(), TplAestan\GLYPH_SERVICE_REMOVE, Lang\MENU_REMOVE_SERVICE, ActionService\REMOVE, and Action\SERVICE.
getItemRestart ( $sName) [static]
Generates a menu item to restart a service.
Parameters
$sName The name of the service to restart.
Returns
string The generated menu item string for restarting the service.
Definition at line 116 of file class.tpl.service.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::SERVICE, array($sName, ActionService::RESTART),
            array($bearsamppLang->getValue(Lang::MENU_RESTART_SERVICE), TplAestan::GLYPH_RELOAD)
        );
    }
References $bearsamppLang, TplApp\getActionRun(), TplAestan\GLYPH_RELOAD, Lang\MENU_RESTART_SERVICE, ActionService\RESTART, and Action\SERVICE.
getItemStart ( $sName) [static]
Generates a menu item to start a service.
Parameters
$sName The name of the service to start.
Returns
string The generated menu item string for starting the service.
Definition at line 84 of file class.tpl.service.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::SERVICE, array($sName, ActionService::START),
            array($bearsamppLang->getValue(Lang::MENU_START_SERVICE), TplAestan::GLYPH_START)
        );
    }
References $bearsamppLang, TplApp\getActionRun(), TplAestan\GLYPH_START, Lang\MENU_START_SERVICE, Action\SERVICE, and ActionService\START.
getItemStop ( $sName) [static]
Generates a menu item to stop a service.
Parameters
$sName The name of the service to stop.
Returns
string The generated menu item string for stopping the service.
Definition at line 100 of file class.tpl.service.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::SERVICE, array($sName, ActionService::STOP),
            array($bearsamppLang->getValue(Lang::MENU_STOP_SERVICE), TplAestan::GLYPH_STOP)
        );
    }
References $bearsamppLang, TplApp\getActionRun(), TplAestan\GLYPH_STOP, Lang\MENU_STOP_SERVICE, Action\SERVICE, and ActionService\STOP.
Author
Generated automatically by Doxygen for Bearsampp from the source code.