Vbs
NAME
Vbs
SYNOPSIS
Public Member Functions
__construct ()
Static Public Member Functions
static countFilesFolders ($path)
static createShortcut ($savePath)
static exec ($basename, $resultFile, $content, $timeout=true)
static getDefaultBrowser ()
static getInstalledBrowsers ()
static getListProcs ($vbsKeys)
static getResultFile ($basename)
static getServiceInfos ($serviceName)
static getStartupPath ($file=null)
static getTmpFile ($ext, $customName=null)
static killProc ($pid)
Data Fields
const ALL_DESKTOP_PATH = 'objShell.SpecialFolders('AllUsersDesktop')'
const ALL_STARTUP_PATH = 'objShell.SpecialFolders('AllUsersStartup')'
const DESKTOP_PATH = 'objShell.SpecialFolders('Desktop')'
const END_PROCESS_STR = 'FINISHED!'
const STARTUP_PATH = 'objShell.SpecialFolders('Startup')'
const STR_SEPARATOR = ' || '
Static Private Member Functions
static getSpecialPath ($path)
static writeLog ($log)
Detailed Description
Class Vbs
This class provides various utility functions for interacting with the Windows operating system using VBScript. It includes methods for counting files and folders, retrieving default and installed browsers, managing processes, and creating shortcuts.
Definition at line 18 of file class.vbs.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 28 of file class.vbs.php.
    {
    }
Member Function Documentation
countFilesFolders ( $path) [static]
Counts the number of files and folders in the specified path.
Parameters
$path The path to count files and folders in.
Returns
int|false The count of files and folders, or false on failure.
Definition at line 50 of file class.vbs.php.
    {
        $basename = 'countFilesFolders';
        $resultFile = self::getResultFile( $basename );
        $content = 'Dim objFso, objResultFile, objCheckFile' . PHP_EOL . PHP_EOL;
        $content .= 'Set objFso = CreateObject("scripting.filesystemobject")' . PHP_EOL;
        $content .= 'Set objResultFile = objFso.CreateTextFile("' . $resultFile . '", True)' . PHP_EOL;
        $content .= 'count = 0' . PHP_EOL;
        $content .= 'CountFiles("' . $path . '")' . PHP_EOL . PHP_EOL;
        $content .= 'Function CountFiles(ByVal path)' . PHP_EOL;
        $content .= ' Dim parentFld, subFld' . PHP_EOL;
        $content .= ' Set parentFld = objFso.GetFolder(path)' . PHP_EOL . PHP_EOL;
        $content .= ' count = count + parentFld.Files.Count + parentFld.SubFolders.Count' . PHP_EOL;
        $content .= ' For Each subFld In parentFld.SubFolders' . PHP_EOL;
        $content .= ' count = count + CountFiles(subFld.Path)' . PHP_EOL;
        $content .= ' Next' . PHP_EOL . PHP_EOL;
        $content .= 'End Function' . PHP_EOL . PHP_EOL;
        $content .= 'objResultFile.Write count' . PHP_EOL;
        $content .= 'objResultFile.Close' . PHP_EOL;
        $result = self::exec( $basename, $resultFile, $content );
        return isset( $result[0] ) && is_numeric( $result[0] ) ? intval( $result[0] ) : false;
    }
References $result, exec(), and getResultFile().
createShortcut ( $savePath) [static]
Creates a shortcut to the Bearsampp executable.
Parameters
$savePath The path to save the shortcut.
Returns
bool True on success, false on failure.
Definition at line 314 of file class.vbs.php.
    {
        global $bearsamppRoot, $bearsamppCore;
        $basename = 'createShortcut';
        $resultFile = self::getResultFile( $basename );
        $content = 'Dim objShell, objFso, objResultFile' . PHP_EOL . PHP_EOL;
        $content .= 'Set objShell = Wscript.CreateObject("Wscript.Shell")' . PHP_EOL;
        $content .= 'Set objFso = CreateObject("scripting.filesystemobject")' . PHP_EOL;
        $content .= 'Set objResultFile = objFso.CreateTextFile("' . $resultFile . '", True)' . PHP_EOL . PHP_EOL;
        $content .= 'Set objShortcut = objShell.CreateShortcut("' . $savePath . '")' . PHP_EOL;
        $content .= 'objShortCut.TargetPath = "' . $bearsamppRoot->getExeFilePath() . '"' . PHP_EOL;
        $content .= 'objShortCut.WorkingDirectory = "' . $bearsamppRoot->getRootPath() . '"' . PHP_EOL;
        $content .= 'objShortCut.Description = "' . APP_TITLE . ' ' . $bearsamppCore->getAppVersion() . '"' . PHP_EOL;
        $content .= 'objShortCut.IconLocation = "' . $bearsamppCore->getIconsPath() . '/app.ico' . '"' . PHP_EOL;
        $content .= 'objShortCut.Save' . PHP_EOL;
        $content .= 'If Err.Number <> 0 Then' . PHP_EOL;
        $content .= ' objResultFile.Write Err.Number & ": " & Err.Description' . PHP_EOL;
        $content .= 'End If' . PHP_EOL;
        $content .= 'objResultFile.Close' . PHP_EOL;
        $result = self::exec( $basename, $resultFile, $content );
        if ( empty( $result ) ) {
            return true;
        }
        elseif ( isset( $result[0] ) ) {
            Util::logError( 'createShortcut: ' . $result[0] );
            return false;
        }
        return false;
    }
References $bearsamppCore, $bearsamppRoot, $result, APP_TITLE, exec(), getResultFile(), and Util\logError().
Referenced by Util\enableLaunchStartup().
exec ( $basename, $resultFile, $content, $timeout = true) [static]
Executes a VBScript file and retrieves the result.
Parameters
$basename The base name for the script and result files.
$resultFile The path to the result file.
$content The VBScript content to execute.
$timeout The timeout duration in seconds, or true for default timeout, or false for no timeout.
Returns
array|false The result of the script execution as an array of lines, or false on failure.
Definition at line 439 of file class.vbs.php.
    {
        global $bearsamppConfig, $bearsamppWinbinder;
        $result = false;
        $scriptPath = self::getTmpFile( '.vbs', $basename );
        $checkFile = self::getTmpFile( '.tmp', $basename );
        $errFile = self::getTmpFile( '.tmp', $basename );
        $randomVarName = Util::random( 15, false );
        $randomObjErrFile = Util::random( 15, false );
        $randomObjFile = Util::random( 15, false );
        $randomObjFso = Util::random( 15, false );
        // Add a timeout to the VBScript itself
        $timeoutSeconds = 10; // 10 seconds timeout for the VBScript
        // Header with timeout
        $header = 'On Error Resume Next' . PHP_EOL .
            'Dim ' . $randomVarName . ', ' . $randomObjFso . ', ' . $randomObjErrFile . ', ' . $randomObjFile . PHP_EOL .
            'Set ' . $randomObjFso . ' = CreateObject("scripting.filesystemobject")' . PHP_EOL .
            'Set ' . $randomObjErrFile . ' = ' . $randomObjFso . '.CreateTextFile("' . $errFile . '", True)' . PHP_EOL .
            'Set ' . $randomObjFile . ' = ' . $randomObjFso . '.CreateTextFile("' . $checkFile . '", True)' . PHP_EOL .
            // Add timeout mechanism to VBScript
            'startTime = Timer' . PHP_EOL .
            'timeoutSeconds = ' . $timeoutSeconds . PHP_EOL . PHP_EOL;
        // Footer with timeout check
        $footer = PHP_EOL . PHP_EOL .
            // Add timeout check before ending
            'If Timer - startTime > timeoutSeconds Then' . PHP_EOL .
            $randomObjErrFile . '.Write "VBScript execution timed out after " & timeoutSeconds & " seconds"' . PHP_EOL .
            'End If' . PHP_EOL .
            'If Err.Number <> 0 Then' . PHP_EOL .
            $randomObjErrFile . '.Write Err.Description' . PHP_EOL .
            'End If' . PHP_EOL .
            $randomObjFile . '.Write "' . self::END_PROCESS_STR . '"' . PHP_EOL .
            $randomObjFile . '.Close' . PHP_EOL .
            $randomObjErrFile . '.Close' . PHP_EOL;
        // Process
        file_put_contents( $scriptPath, $header . $content . $footer );
        // Use set_time_limit to prevent PHP script timeout
        $originalTimeout = ini_get('max_execution_time');
        set_time_limit(30); // 30 seconds timeout for PHP
        Util::logTrace("Starting VBS execution for: " . $basename);
        $startTime = microtime(true);
        try {
            $bearsamppWinbinder->exec( 'wscript.exe', '"' . $scriptPath . '"' );
            $timeout = is_numeric( $timeout ) ? $timeout : ($timeout === true ? $bearsamppConfig->getScriptsTimeout() : false);
            // Use a shorter timeout for VBS execution
            $timeout = min($timeout, 15); // Maximum 15 seconds
            $maxtime = time() + $timeout;
            $noTimeout = $timeout === false;
            // Add a microtime-based timeout as well
            $microTimeStart = microtime(true);
            $microTimeMax = 15; // 15 seconds maximum
            $loopCount = 0;
            $maxLoops = 30; // Maximum number of attempts
            while ( ($result === false || empty( $result )) && $loopCount < $maxLoops ) {
                $loopCount++;
                if ( file_exists( $checkFile ) ) {
                    $check = file( $checkFile );
                    if ( !empty( $check ) && trim( $check[0] ) == self::END_PROCESS_STR ) {
                        $result = file( $resultFile );
                        Util::logTrace("VBS execution completed successfully after " . $loopCount . " attempts");
                        break;
                    }
                }
                // Check both timeouts
                if (($maxtime < time() && !$noTimeout) || (microtime(true) - $microTimeStart > $microTimeMax)) {
                    Util::logTrace("VBS execution timed out after " . round(microtime(true) - $startTime, 2) . " seconds");
                    break;
                }
                // Sleep a short time to prevent CPU hogging
                usleep(100000); // 100ms
            }
            if ($loopCount >= $maxLoops) {
                Util::logTrace("VBS execution reached maximum loop count (" . $maxLoops . ")");
            }
        } catch (\Exception $e) {
            Util::logTrace("Exception during VBS execution: " . $e->getMessage());
        } catch (\Throwable $e) {
            Util::logTrace("Throwable during VBS execution: " . $e->getMessage());
        } finally {
            // Reset the timeout
            set_time_limit($originalTimeout);
        }
        $executionTime = round(microtime(true) - $startTime, 2);
        Util::logTrace("VBS execution for " . $basename . " took " . $executionTime . " seconds");
        $err = file_get_contents( $errFile );
        if ( !empty( $err ) ) {
            Util::logError( 'VBS error on ' . $basename . ': ' . $err );
        }
        self::writeLog( 'Exec ' . $basename . ':' );
        self::writeLog( '-> content: ' . str_replace( PHP_EOL, ' \\\\ ', $content ) );
        self::writeLog( '-> errFile: ' . $errFile );
        self::writeLog( '-> checkFile: ' . $checkFile );
        self::writeLog( '-> resultFile: ' . $resultFile );
        self::writeLog( '-> scriptPath: ' . $scriptPath );
        if ( $result !== false && !empty( $result ) ) {
            $rebuildResult = array();
            foreach ( $result as $row ) {
                $row = trim( $row );
                if ( !empty( $row ) ) {
                    $rebuildResult[] = $row;
                }
            }
            $result = $rebuildResult;
            self::writeLog( '-> result: ' . substr( implode( ' \\\\ ', $result ), 0, 2048 ) );
        }
        else {
            self::writeLog( '-> result: N/A' );
        }
        return $result;
    }
Referenced by countFilesFolders(), createShortcut(), Registry\exists(), getDefaultBrowser(), getInstalledBrowsers(), getListProcs(), getSpecialPath(), Registry\getValue(), killProc(), and Registry\setValue().
getDefaultBrowser () [static]
Retrieves the default browser's executable path.
Returns
string|false The path to the default browser executable, or false on failure.
Definition at line 81 of file class.vbs.php.
    {
        $basename = 'getDefaultBrowser';
        $resultFile = self::getResultFile( $basename );
        $content = 'On Error Resume Next' . PHP_EOL;
        $content .= 'Err.Clear' . PHP_EOL . PHP_EOL;
        $content .= 'Dim objShell, objFso, objFile' . PHP_EOL . PHP_EOL;
        $content .= 'Set objShell = WScript.CreateObject("WScript.Shell")' . PHP_EOL;
        $content .= 'Set objFso = CreateObject("scripting.filesystemobject")' . PHP_EOL;
        $content .= 'Set objFile = objFso.CreateTextFile("' . $resultFile . '", True)' . PHP_EOL . PHP_EOL;
        $content .= 'objFile.Write objShell.RegRead("HKLM\SOFTWARE\Classes\http\shell\open\command\")' . PHP_EOL;
        $content .= 'objFile.Close' . PHP_EOL;
        $result = self::exec( $basename, $resultFile, $content );
        if ( $result !== false && !empty( $result ) ) {
            if ( preg_match( '/"([^"]+)"/', $result[0], $matches ) ) {
                return $matches[1];
            }
            else {
                return str_replace( '"', '', $result[0] );
            }
        }
        else {
            return false;
        }
    }
References $result, exec(), and getResultFile().
Referenced by ActionReload\__construct(), and ActionStartup\checkBrowser().
getInstalledBrowsers () [static]
Retrieves a list of installed browsers' executable paths.
Returns
array|false An array of paths to installed browser executables, or false on failure.
Definition at line 114 of file class.vbs.php.
    {
        $basename = 'getInstalledBrowsers';
        $resultFile = self::getResultFile( $basename );
        $content = 'On Error Resume Next' . PHP_EOL;
        $content .= 'Err.Clear' . PHP_EOL . PHP_EOL;
        $content .= 'Dim objShell, objRegistry, objFso, objFile' . PHP_EOL . PHP_EOL;
        $content .= 'Set objShell = WScript.CreateObject("WScript.Shell")' . PHP_EOL;
        $content .= 'Set objRegistry = GetObject("winmgmts://./root/default:StdRegProv")' . PHP_EOL;
        $content .= 'Set objFso = CreateObject("scripting.filesystemobject")' . PHP_EOL;
        $content .= 'Set objFile = objFso.CreateTextFile("' . $resultFile . '", True)' . PHP_EOL . PHP_EOL;
        $content .= 'mainKey = "SOFTWARE\WOW6432Node\Clients\StartMenuInternet"' . PHP_EOL;
        $content .= 'checkKey = objShell.RegRead("HKLM\" & mainKey & "\")' . PHP_EOL;
        $content .= 'If Err.Number <> 0 Then' . PHP_EOL;
        $content .= ' Err.Clear' . PHP_EOL;
        $content .= ' mainKey = "SOFTWARE\Clients\StartMenuInternet"' . PHP_EOL;
        $content .= ' checkKey = objShell.RegRead("HKLM\" & mainKey & "\")' . PHP_EOL;
        $content .= ' If Err.Number <> 0 Then' . PHP_EOL;
        $content .= ' mainKey = ""' . PHP_EOL;
        $content .= ' End If' . PHP_EOL;
        $content .= 'End If' . PHP_EOL . PHP_EOL;
        $content .= 'Err.Clear' . PHP_EOL;
        $content .= 'If mainKey <> "" Then' . PHP_EOL;
        $content .= ' objRegistry.EnumKey &H80000002, mainKey, arrSubKeys' . PHP_EOL;
        $content .= ' For Each subKey In arrSubKeys' . PHP_EOL;
        $content .= ' objFile.Write objShell.RegRead("HKLM\SOFTWARE\Clients\StartMenuInternet\" & subKey & "\shell\open\command\") & vbCrLf' . PHP_EOL;
        $content .= ' Next' . PHP_EOL;
        $content .= 'End If' . PHP_EOL;
        $content .= 'objFile.Close' . PHP_EOL;
        $result = self::exec( $basename, $resultFile, $content );
        if ( $result !== false && !empty( $result ) ) {
            $rebuildResult = array();
            foreach ( $result as $browser ) {
                $rebuildResult[] = str_replace( '"', '', $browser );
            }
            $result = $rebuildResult;
        }
        return $result;
    }
References $result, exec(), and getResultFile().
Referenced by ActionChangeBrowser\__construct().
getListProcs ( $vbsKeys) [static]
Retrieves a list of running processes with specified keys.
Parameters
$vbsKeys The keys to retrieve for each process.
Returns
array|false An array of process information, or false on failure.
Definition at line 164 of file class.vbs.php.
    {
        $basename = 'getListProcs';
        $resultFile = self::getResultFile( $basename );
        $sep = ' & "' . self::STR_SEPARATOR . '" & _';
        $content = 'Dim objFso, objResultFile, objWMIService' . PHP_EOL . PHP_EOL;
        $content .= 'Set objFso = CreateObject("scripting.filesystemobject")' . PHP_EOL;
        $content .= 'Set objResultFile = objFso.CreateTextFile("' . $resultFile . '", True)' . PHP_EOL;
        $content .= 'strComputer = "."' . PHP_EOL;
        $content .= 'Set objWMIService = GetObject("winmgmts:" & "{impersonationLevel=impersonate}!\\\\" & strComputer & "\root\cimv2")' . PHP_EOL;
        $content .= 'Set listProcess = objWMIService.ExecQuery ("SELECT * FROM Win32_Process")' . PHP_EOL;
        $content .= 'For Each process in listProcess' . PHP_EOL;
        $content .= ' objResultFile.WriteLine(_' . PHP_EOL;
        foreach ( $vbsKeys as $vbsKey ) {
            $content .= ' process.' . $vbsKey . $sep . PHP_EOL;
        }
        $content = substr( $content, 0, strlen( $content ) - strlen( $sep ) - 1 ) . ')' . PHP_EOL;
        $content .= 'Next' . PHP_EOL;
        $content .= 'objResultFile.WriteLine("' . self::END_PROCESS_STR . '")' . PHP_EOL;
        $content .= 'objResultFile.Close' . PHP_EOL;
        $content .= 'Err.Clear' . PHP_EOL;
        $result = self::exec( $basename, $resultFile, $content );
        if ( empty( $result ) ) {
            return false;
        }
        unset( $result[array_search( self::END_PROCESS_STR, $result )] );
        if ( is_array( $result ) && count( $result ) > 0 ) {
            $rebuildResult = array();
            foreach ( $result as $row ) {
                $row = explode( trim( self::STR_SEPARATOR ), $row );
                if ( count( $row ) != count( $vbsKeys ) ) {
                    continue;
                }
                $processInfo = array();
                foreach ( $vbsKeys as $key => $vbsKey ) {
                    $processInfo[$vbsKey] = trim( $row[$key] );
                }
                if ( !empty( $processInfo[Win32Ps::EXECUTABLE_PATH] ) ) {
                    $rebuildResult[] = $processInfo;
                }
            }
            return $rebuildResult;
        }
        return false;
    }
References $result, exec(), Win32Ps\EXECUTABLE_PATH, and getResultFile().
Referenced by Win32Ps\getListProcs().
getResultFile ( $basename) [static]
Retrieves the path for a result file based on a given basename.
Parameters
$basename The base name to use for the result file.
Returns
string The path to the result file.
Definition at line 424 of file class.vbs.php.
    {
        return self::getTmpFile( '.vbs', $basename );
    }
Referenced by countFilesFolders(), createShortcut(), Registry\exists(), getDefaultBrowser(), getInstalledBrowsers(), getListProcs(), getServiceInfos(), getSpecialPath(), Registry\getValue(), killProc(), and Registry\setValue().
getServiceInfos ( $serviceName) [static]
Retrieves information about a Windows service.
Parameters
$serviceName The name of the service to retrieve information about.
Returns
array|false An array of service information, or false on failure.
Definition at line 355 of file class.vbs.php.
    {
        $basename = 'getServiceInfos';
        $resultFile = self::getResultFile( $basename );
        $sep = ' & "' . self::STR_SEPARATOR . '" & _';
        $vbsKeys = Win32Service::getVbsKeys();
        $content = 'Dim objFso, objResultFile, objWMIService' . PHP_EOL . PHP_EOL;
        $content .= 'Set objFso = CreateObject("scripting.filesystemobject")' . PHP_EOL;
        $content .= 'Set objResultFile = objFso.CreateTextFile("' . $resultFile . '", True)' . PHP_EOL;
        $content .= 'strComputer = "."' . PHP_EOL;
        $content .= 'Set objWMIService = GetObject("winmgmts:" & "{impersonationLevel=impersonate}!\\\\" & strComputer & "\root\cimv2")' . PHP_EOL;
        $content .= 'Set listServices = objWMIService.ExecQuery ("SELECT * FROM Win32_Service WHERE Name=\'' . $serviceName . '\'")' . PHP_EOL;
        $content .= 'For Each service in listServices' . PHP_EOL;
        $content .= ' objResultFile.WriteLine(_' . PHP_EOL;
        foreach ( $vbsKeys as $vbsKey ) {
            $content .= ' service.' . $vbsKey . $sep . PHP_EOL;
        }
        $content = substr( $content, 0, strlen( $content ) - strlen( $sep ) - 1 ) . ')' . PHP_EOL;
        $content .= 'Next' . PHP_EOL;
        $content .= 'objResultFile.WriteLine("' . self::END_PROCESS_STR . '")' . PHP_EOL;
        $content .= 'objResultFile.Close' . PHP_EOL;
        $result = self::exec( $basename, $resultFile, $content );
        if ( empty( $result ) ) {
            return false;
        }
        unset( $result[array_search( self::END_PROCESS_STR, $result )] );
        if ( is_array( $result ) && count( $result ) == 1 ) {
            $rebuildResult = array();
            $row = explode( trim( self::STR_SEPARATOR ), $result[0] );
            if ( count( $row ) != count( $vbsKeys ) ) {
                return false;
            }
            foreach ( $vbsKeys as $key => $vbsKey ) {
                $rebuildResult[$vbsKey] = trim( $row[$key] );
            }
            return $rebuildResult;
        }
        return false;
    }
References getResultFile(), and Win32Service\getVbsKeys().
Referenced by Nssm\infos(), and Win32Service\infos().
getSpecialPath ( $path) [static], [private]
Retrieves a special folder path.
Parameters
$path The VBScript path constant for the special folder.
Returns
string|null The path to the special folder, or null on failure.
Definition at line 275 of file class.vbs.php.
    {
        $basename = 'getSpecialPath';
        $resultFile = self::getResultFile( $basename );
        $content = 'Dim objShell, objFso, objResultFile' . PHP_EOL . PHP_EOL;
        $content .= 'Set objShell = Wscript.CreateObject("Wscript.Shell")' . PHP_EOL;
        $content .= 'Set objFso = CreateObject("scripting.filesystemobject")' . PHP_EOL;
        $content .= 'Set objResultFile = objFso.CreateTextFile("' . $resultFile . '", True)' . PHP_EOL . PHP_EOL;
        $content .= 'objResultFile.WriteLine(' . $path . ')' . PHP_EOL;
        $content .= 'objResultFile.Close' . PHP_EOL;
        $result = self::exec( $basename, $resultFile, $content );
        if ( !empty( $result ) && is_array( $result ) && count( $result ) == 1 ) {
            return Util::formatUnixPath( $result[0] );
        }
        return null;
    }
References $result, exec(), Util\formatUnixPath(), and getResultFile().
Referenced by getStartupPath().
getStartupPath ( $file = null) [static]
Retrieves the startup path, optionally appending a file name.
Parameters
$file The file name to append to the startup path.
Returns
string The startup path.
Definition at line 302 of file class.vbs.php.
    {
        return self::getSpecialPath( self::STARTUP_PATH ) . ($file != null ? '/' . $file : '');
    }
References getSpecialPath().
Referenced by Util\getStartupLnkPath().
getTmpFile ( $ext, $customName = null) [static]
Generates a temporary file path with a given extension and optional custom name.
Parameters
$ext The file extension for the temporary file.
$customName An optional custom name to include in the file name.
Returns
string The formatted path to the temporary file.
Definition at line 410 of file class.vbs.php.
    {
        global $bearsamppCore;
        return Util::formatWindowsPath( $bearsamppCore->getTmpPath() . '/' . (!empty( $customName ) ? $customName . '-' : '') . Util::random() . $ext );
    }
killProc ( $pid) [static]
Terminates a process by its PID.
Parameters
$pid The process ID to terminate.
Returns
bool True on success, false on failure.
Definition at line 224 of file class.vbs.php.
    {
        $basename = 'killProc';
        $resultFile = self::getResultFile( $basename );
        $content = 'Dim objFso, objResultFile, objWMIService, processFound' . PHP_EOL . PHP_EOL;
        $content .= 'Set objFso = CreateObject("scripting.filesystemobject")' . PHP_EOL;
        $content .= 'Set objResultFile = objFso.CreateTextFile("' . $resultFile . '", True)' . PHP_EOL;
        $content .= 'strComputer = "."' . PHP_EOL;
        $content .= 'strProcessKill = "' . $pid . '"' . PHP_EOL;
        $content .= 'processFound = False' . PHP_EOL;
        $content .= 'Set objWMIService = GetObject("winmgmts:" & "{impersonationLevel=impersonate}!\\\\" & strComputer & "\root\cimv2")' . PHP_EOL;
        $content .= 'Set listProcess = objWMIService.ExecQuery ("Select * from Win32_Process Where ProcessID = " & strProcessKill)' . PHP_EOL;
        $content .= 'For Each objProcess in listProcess' . PHP_EOL;
        $content .= ' processFound = True' . PHP_EOL;
        $content .= ' objResultFile.WriteLine(objProcess.Name & "' . self::STR_SEPARATOR . '" & objProcess.ProcessID & "' . self::STR_SEPARATOR . '" & objProcess.ExecutablePath)' . PHP_EOL;
        $content .= ' objProcess.Terminate()' . PHP_EOL;
        $content .= 'Next' . PHP_EOL;
        $content .= 'If Not processFound Then' . PHP_EOL;
        $content .= ' objResultFile.WriteLine("PROCESS_NOT_FOUND' . self::STR_SEPARATOR . '" & strProcessKill & "' . self::STR_SEPARATOR . '")' . PHP_EOL;
        $content .= 'End If' . PHP_EOL;
        $content .= 'objResultFile.Close' . PHP_EOL;
        $result = self::exec( $basename, $resultFile, $content );
        if ( empty( $result ) ) {
            return true;
        }
        if ( is_array( $result ) && count( $result ) > 0 ) {
            foreach ( $result as $row ) {
                $row = explode( self::STR_SEPARATOR, $row );
                if ( count( $row ) == 3 ) {
                    if ( $row[0] === 'PROCESS_NOT_FOUND' ) {
                        Util::logDebug( 'Process with PID ' . $row[1] . ' not found' );
                    } elseif ( !empty( $row[2] ) ) {
                        Util::logDebug( 'Kill process ' . $row[2] . ' (PID ' . $row[1] . ')' );
                    }
                }
            }
        }
        return true;
    }
References $result, exec(), getResultFile(), and Util\logDebug().
Referenced by Win32Ps\kill(), and ActionQuit\terminatePhpProcesses().
writeLog ( $log) [static], [private]
Writes a log entry to the VBS log file.
Parameters
$log The log message to write.
Definition at line 37 of file class.vbs.php.
    {
        global $bearsamppRoot;
        Util::logDebug( $log, $bearsamppRoot->getVbsLogFilePath() );
    }
References $bearsamppRoot, and Util\logDebug().
Field Documentation
const ALL_DESKTOP_PATH = 'objShell.SpecialFolders('AllUsersDesktop')'
Definition at line 24 of file class.vbs.php.
const ALL_STARTUP_PATH = 'objShell.SpecialFolders('AllUsersStartup')'
Definition at line 26 of file class.vbs.php.
const DESKTOP_PATH = 'objShell.SpecialFolders('Desktop')'
Definition at line 23 of file class.vbs.php.
const END_PROCESS_STR = 'FINISHED!'
Definition at line 20 of file class.vbs.php.
const STARTUP_PATH = 'objShell.SpecialFolders('Startup')'
Definition at line 25 of file class.vbs.php.
const STR_SEPARATOR = ' || '
Definition at line 21 of file class.vbs.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.