Win32Service
NAME
Win32Service
SYNOPSIS
Public Member Functions
__construct ($name)
create ()
delete ()
getBinPath ()
getDisplayName ()
getError ()
getErrorControl ()
getLatestError ()
getLatestStatus ()
getName ()
getNssm ()
getParams ()
getStartType ()
infos ()
isInstalled ()
isPaused ()
isPending ($status)
isRunning ()
isStopped ()
reset ()
restart ()
setBinPath ($binPath)
setDisplayName ($displayName)
setErrorControl ($errorControl)
setName ($name)
setNssm ($nssm)
setParams ($params)
setStartType ($startType)
start ()
status ($timeout=true)
stop ()
Static Public Member Functions
static getVbsKeys ()
Data Fields
const PENDING_TIMEOUT = 20
const SERVER_ERROR_IGNORE = '0'
const SERVER_ERROR_NORMAL = '1'
const SERVICE_AUTO_START = '2'
const SERVICE_DEMAND_START = '3'
const SERVICE_DISABLED = '4'
const SLEEP_TIME = 500000
const VBS_DESCRIPTION = 'Description'
const VBS_DISPLAY_NAME = 'DisplayName'
const VBS_NAME = 'Name'
const VBS_PATH_NAME = 'PathName'
const VBS_STATE = 'State'
const WIN32_ERROR_ACCESS_DENIED = '5'
const WIN32_ERROR_CIRCULAR_DEPENDENCY = '423'
const WIN32_ERROR_DATABASE_DOES_NOT_EXIST = '429'
const WIN32_ERROR_DEPENDENT_SERVICES_RUNNING = '41B'
const WIN32_ERROR_DUPLICATE_SERVICE_NAME = '436'
const WIN32_ERROR_FAILED_SERVICE_CONTROLLER_CONNECT = '427'
const WIN32_ERROR_INSUFFICIENT_BUFFER = '7A'
const WIN32_ERROR_INVALID_DATA = 'D'
const WIN32_ERROR_INVALID_HANDLE = '6'
const WIN32_ERROR_INVALID_LEVEL = '7C'
const WIN32_ERROR_INVALID_NAME = '7B'
const WIN32_ERROR_INVALID_PARAMETER = '57'
const WIN32_ERROR_INVALID_SERVICE_ACCOUNT = '421'
const WIN32_ERROR_INVALID_SERVICE_CONTROL = '41C'
const WIN32_ERROR_PATH_NOT_FOUND = '3'
const WIN32_ERROR_SERVICE_ALREADY_RUNNING = '420'
const WIN32_ERROR_SERVICE_CANNOT_ACCEPT_CTRL = '425'
const WIN32_ERROR_SERVICE_DATABASE_LOCKED = '41F'
const WIN32_ERROR_SERVICE_DEPENDENCY_DELETED = '433'
const WIN32_ERROR_SERVICE_DEPENDENCY_FAIL = '42C'
const WIN32_ERROR_SERVICE_DISABLED = '422'
const WIN32_ERROR_SERVICE_DOES_NOT_EXIST = '424'
const WIN32_ERROR_SERVICE_EXISTS = '431'
const WIN32_ERROR_SERVICE_LOGON_FAILED = '42D'
const WIN32_ERROR_SERVICE_MARKED_FOR_DELETE = '430'
const WIN32_ERROR_SERVICE_NO_THREAD = '41E'
const WIN32_ERROR_SERVICE_NOT_ACTIVE = '426'
const WIN32_ERROR_SERVICE_REQUEST_TIMEOUT = '41D'
const WIN32_ERROR_SHUTDOWN_IN_PROGRESS = '45B'
const WIN32_NO_ERROR = '0'
const WIN32_SERVICE_CONTINUE_PENDING = '5'
const WIN32_SERVICE_NA = '0'
const WIN32_SERVICE_PAUSE_PENDING = '6'
const WIN32_SERVICE_PAUSED = '7'
const WIN32_SERVICE_RUNNING = '4'
const WIN32_SERVICE_START_PENDING = '2'
const WIN32_SERVICE_STOP_PENDING = '3'
const WIN32_SERVICE_STOPPED = '1'
Private Member Functions
callWin32Service ($function, $param, $checkError=false)
getWin32ErrorCodeDesc ($code)
getWin32ServiceStatusDesc ($status)
writeLog ($log)
Private Attributes
$binPath
$displayName
$errorControl
$latestError
$latestStatus
$name
$nssm
$params
$startType
Static Private Attributes
static $loggedFunctions = array()
Detailed Description
Class Win32Service
This class provides an interface to manage Windows services. It includes methods to create, delete, start, stop, and query the status of services. It also handles logging and error reporting for service operations.
Definition at line 17 of file class.win32service.php.
Constructor & Destructor Documentation
__construct ( $name)
Constructor for the Win32Service class.
Parameters
$name The name of the service.
Definition at line 96 of file class.win32service.php.
    {
        Util::logInitClass( $this );
        $this->name = $name;
    }
References $name, and Util\logInitClass().
Member Function Documentation
callWin32Service ( $function, $param, $checkError = false) [private]
Calls a Win32 service function.
Parameters
$function The function name.
$param The parameter to pass to the function.
$checkError Whether to check for errors.
Returns
mixed The result of the function call.
Definition at line 138 of file class.win32service.php.
                                                                             : mixed
    {
        $result = false;
        if ( function_exists( $function ) ) {
            if (!isset(self::$loggedFunctions[$function])) {
                Util::logTrace('Win32 function: ' . $function . ' exists');
                self::$loggedFunctions[$function] = true;
            }
            // Special handling for win32_query_service_status to prevent hanging
            if ($function === 'win32_query_service_status') {
                Util::logTrace("Using enhanced handling for win32_query_service_status");
                // Set a shorter timeout for this specific function
                $originalTimeout = ini_get('max_execution_time');
                set_time_limit(5); // 5 seconds timeout
                try {
                    // Ensure proper parameter handling for PHP 8.2.3 compatibility
                    $result = call_user_func($function, $param);
                    // Reset the timeout
                    set_time_limit($originalTimeout);
                    if ($checkError && $result !== null) {
                        // Convert to int before using dechex for PHP 8.2.3 compatibility
                        $resultInt = is_numeric($result) ? (int)$result : 0;
                        if (dechex($resultInt) != self::WIN32_NO_ERROR) {
                            $this->latestError = dechex($resultInt);
                        }
                    }
                } catch (\Win32ServiceException $e) {
                    // Reset the timeout
                    set_time_limit($originalTimeout);
                    Util::logTrace("Win32ServiceException caught: " . $e->getMessage());
                    // Handle "service does not exist" exception
                    if (strpos($e->getMessage(), 'service does not exist') !== false) {
                        Util::logTrace("Service does not exist exception handled for: " . $param);
                        // Return the appropriate error code for "service does not exist"
                        $result = hexdec(self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST);
                    } else {
                        // For other exceptions, log and return false
                        Util::logTrace("Unhandled Win32ServiceException: " . $e->getMessage());
                        $result = false;
                    }
                } catch (\Exception $e) {
                    // Reset the timeout
                    set_time_limit($originalTimeout);
                    // Catch any other exceptions to prevent application freeze
                    Util::logTrace("Exception caught in callWin32Service: " . $e->getMessage());
                    $result = false;
                } catch (\Throwable $e) {
                    // Reset the timeout
                    set_time_limit($originalTimeout);
                    // Catch any other throwable (PHP 7+) to prevent application freeze
                    Util::logTrace("Throwable caught in callWin32Service: " . $e->getMessage());
                    $result = false;
                }
            } else {
                // Standard handling for other functions
                try {
                    // Ensure proper parameter handling for PHP 8.2.3 compatibility
                    $result = call_user_func($function, $param);
                    if ($checkError && $result !== null) {
                        // Convert to int before using dechex for PHP 8.2.3 compatibility
                        $resultInt = is_numeric($result) ? (int)$result : 0;
                        if (dechex($resultInt) != self::WIN32_NO_ERROR) {
                            $this->latestError = dechex($resultInt);
                        }
                    }
                } catch (\Win32ServiceException $e) {
                    Util::logTrace("Win32ServiceException caught: " . $e->getMessage());
                    // Handle "service does not exist" exception
                    if (strpos($e->getMessage(), 'service does not exist') !== false) {
                        Util::logTrace("Service does not exist exception handled for: " . $param);
                        // Return the appropriate error code for "service does not exist"
                        $result = hexdec(self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST);
                    } else {
                        // For other exceptions, log and return false
                        Util::logTrace("Unhandled Win32ServiceException: " . $e->getMessage());
                        $result = false;
                    }
                } catch (\Exception $e) {
                    // Catch any other exceptions to prevent application freeze
                    Util::logTrace("Exception caught in callWin32Service: " . $e->getMessage());
                    $result = false;
                } catch (\Throwable $e) {
                    // Catch any other throwable (PHP 7+) to prevent application freeze
                    Util::logTrace("Throwable caught in callWin32Service: " . $e->getMessage());
                    $result = false;
                }
            }
        } else {
            if (!isset(self::$loggedFunctions[$function])) {
                Util::logTrace('Win32 function: ' . $function . ' missing');
                self::$loggedFunctions[$function] = true;
            }
        }
        return $result;
    }
References $result, and Util\logTrace().
Referenced by create(), delete(), start(), status(), and stop().
create ()
Creates the service.
Returns
bool True if the service was created successfully, false otherwise.
Definition at line 351 of file class.win32service.php.
                            : bool
    {
        global $bearsamppBins;
        Util::logTrace("Starting Win32Service::create for service: " . $this->getName());
        if ( $this->getName() == BinPostgresql::SERVICE_NAME ) {
            Util::logTrace("PostgreSQL service detected - using specialized installation");
            $bearsamppBins->getPostgresql()->rebuildConf();
            Util::logTrace("PostgreSQL configuration rebuilt");
            $bearsamppBins->getPostgresql()->initData();
            Util::logTrace("PostgreSQL data initialized");
            $result = Batch::installPostgresqlService();
            Util::logTrace("PostgreSQL service installation " . ($result ? "succeeded" : "failed"));
            return $result;
        }
        if ( $this->getNssm() instanceof Nssm ) {
            Util::logTrace("Using NSSM for service installation");
            $nssmEnvPath = Util::getAppBinsRegKey( false );
            Util::logTrace("NSSM environment path (bins): " . $nssmEnvPath);
            $nssmEnvPath .= Util::getNssmEnvPaths();
            Util::logTrace("NSSM environment path (with additional paths): " . $nssmEnvPath);
            $nssmEnvPath .= '%SystemRoot%/system32;';
            $nssmEnvPath .= '%SystemRoot%;';
            $nssmEnvPath .= '%SystemRoot%/system32/Wbem;';
            $nssmEnvPath .= '%SystemRoot%/system32/WindowsPowerShell/v1.0';
            Util::logTrace("NSSM final environment PATH: " . $nssmEnvPath);
            $this->getNssm()->setEnvironmentExtra( 'PATH=' . $nssmEnvPath );
            Util::logTrace("NSSM service parameters:");
            Util::logTrace("-> Name: " . $this->getNssm()->getName());
            Util::logTrace("-> DisplayName: " . $this->getNssm()->getDisplayName());
            Util::logTrace("-> BinPath: " . $this->getNssm()->getBinPath());
            Util::logTrace("-> Params: " . $this->getNssm()->getParams());
            Util::logTrace("-> Start: " . $this->getNssm()->getStart());
            Util::logTrace("-> Stdout: " . $this->getNssm()->getStdout());
            Util::logTrace("-> Stderr: " . $this->getNssm()->getStderr());
            $result = $this->getNssm()->create();
            Util::logTrace("NSSM service creation " . ($result ? "succeeded" : "failed"));
            if (!$result) {
                Util::logTrace("NSSM error: " . $this->getNssm()->getLatestError());
            }
            return $result;
        }
        Util::logTrace("Using win32_create_service for service installation");
        $serviceParams = array(
            'service' => $this->getName(),
            'display' => $this->getDisplayName(),
            'description' => $this->getDisplayName(),
            'path' => $this->getBinPath(),
            'params' => $this->getParams(),
            'start_type' => $this->getStartType() != null ? $this->getStartType() : self::SERVICE_DEMAND_START,
            'error_control' => $this->getErrorControl() != null ? $this->getErrorControl() : self::SERVER_ERROR_NORMAL,
        );
        Util::logTrace("win32_create_service parameters:");
        foreach ($serviceParams as $key => $value) {
            Util::logTrace("-> $key: $value");
        }
        $result = $this->callWin32Service( 'win32_create_service', $serviceParams, true );
        // Ensure proper type conversion for PHP 8.2.3 compatibility
        $resultInt = is_numeric($result) ? (int)$result : 0;
        $create = $result !== null ? dechex( $resultInt ) : '0';
        Util::logTrace("win32_create_service result code: " . $create);
        $this->writeLog( 'Create service: ' . $create . ' (status: ' . $this->status() . ')' );
        $this->writeLog( '-> service: ' . $this->getName() );
        $this->writeLog( '-> display: ' . $this->getDisplayName() );
        $this->writeLog( '-> description: ' . $this->getDisplayName() );
        $this->writeLog( '-> path: ' . $this->getBinPath() );
        $this->writeLog( '-> params: ' . $this->getParams() );
        $this->writeLog( '-> start_type: ' . ($this->getStartType() != null ? $this->getStartType() : self::SERVICE_DEMAND_START) );
        $this->writeLog( '-> service: ' . ($this->getErrorControl() != null ? $this->getErrorControl() : self::SERVER_ERROR_NORMAL) );
        if ( $create != self::WIN32_NO_ERROR ) {
            Util::logTrace("Service creation failed with error code: " . $create);
            return false;
        }
        elseif ( !$this->isInstalled() ) {
            Util::logTrace("Service created but not found as installed");
            $this->latestError = self::WIN32_NO_ERROR;
            return false;
        }
        Util::logTrace("Service created successfully: " . $this->getName());
        return true;
    }
References $bearsamppBins, $result, callWin32Service(), Util\getAppBinsRegKey(), getBinPath(), getDisplayName(), getErrorControl(), getLatestError(), getName(), getNssm(), Util\getNssmEnvPaths(), getParams(), getStartType(), Batch\installPostgresqlService(), isInstalled(), Util\logTrace(), BinPostgresql\SERVICE_NAME, status(), and writeLog().
Referenced by reset().
delete ()
Deletes the service.
Returns
bool True if the service was deleted successfully, false otherwise.
Definition at line 453 of file class.win32service.php.
                            : bool
    {
        Util::logTrace("Starting Win32Service::delete for service: " . $this->getName());
        Util::logTrace("Checking if service is installed: " . $this->getName());
        if ( !$this->isInstalled() ) {
            Util::logTrace("Service is not installed, skipping deletion: " . $this->getName());
            return true;
        }
        Util::logTrace("Stopping service before deletion: " . $this->getName());
        $this->stop();
        if ( $this->getName() == BinPostgresql::SERVICE_NAME ) {
            Util::logTrace("PostgreSQL service detected - using specialized uninstallation");
            $result = Batch::uninstallPostgresqlService();
            Util::logTrace("PostgreSQL service uninstallation " . ($result ? "succeeded" : "failed"));
            return $result;
        }
        Util::logTrace("Calling win32_delete_service for service: " . $this->getName());
        $result = $this->callWin32Service( 'win32_delete_service', $this->getName(), true );
        // Ensure proper type conversion for PHP 8.2.3 compatibility
        $resultInt = is_numeric($result) ? (int)$result : 0;
        $delete = $result !== null ? dechex( $resultInt ) : '0';
        Util::logTrace("Delete service result code: " . $delete);
        $this->writeLog( 'Delete service ' . $this->getName() . ': ' . $delete . ' (status: ' . $this->status() . ')' );
        if ( $delete != self::WIN32_NO_ERROR && $delete != self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST ) {
            return false;
        }
        elseif ( $this->isInstalled() ) {
            $this->latestError = self::WIN32_NO_ERROR;
            return false;
        }
        return true;
    }
References $result, callWin32Service(), getName(), isInstalled(), Util\logTrace(), BinPostgresql\SERVICE_NAME, status(), stop(), Batch\uninstallPostgresqlService(), and writeLog().
getBinPath ()
Gets the binary path of the service.
Returns
string The binary path of the service.
Definition at line 918 of file class.win32service.php.
                                : string
    {
        return $this->binPath;
    }
References $binPath.
Referenced by create().
getDisplayName ()
Gets the display name of the service.
Returns
string The display name of the service.
Definition at line 898 of file class.win32service.php.
                                    : string
    {
        return $this->displayName;
    }
References $displayName.
Referenced by create().
getError ()
Gets a detailed error message for the latest error encountered by the service.
Returns
string|null The detailed error message, or null if no error.
Definition at line 1044 of file class.win32service.php.
    {
        global $bearsamppLang;
        if ( $this->latestError != self::WIN32_NO_ERROR ) {
            // Ensure proper type conversion for PHP 8.2.3 compatibility
            $errorInt = is_numeric($this->latestError) ? hexdec( $this->latestError ) : 0;
            return $bearsamppLang->getValue( Lang::ERROR ) . ' ' .
                $this->latestError . ' (' . $errorInt . ' : ' . $this->getWin32ErrorCodeDesc( $this->latestError ) . ')';
        }
        elseif ( $this->latestStatus != self::WIN32_SERVICE_NA ) {
            // Ensure proper type conversion for PHP 8.2.3 compatibility
            $statusInt = is_numeric($this->latestStatus) ? hexdec( $this->latestStatus ) : 0;
            return $bearsamppLang->getValue( Lang::STATUS ) . ' ' .
                $this->latestStatus . ' (' . $statusInt . ' : ' . $this->getWin32ServiceStatusDesc( $this->latestStatus ) . ')';
        }
        return null;
    }
References $bearsamppLang, Lang\ERROR, getWin32ErrorCodeDesc(), getWin32ServiceStatusDesc(), and Lang\STATUS.
getErrorControl ()
Gets the error control setting of the service.
Returns
string The error control setting of the service.
Definition at line 978 of file class.win32service.php.
                                     : string
    {
        return $this->errorControl;
    }
References $errorControl.
Referenced by create().
getLatestError ()
Gets the latest error encountered by the service.
Returns
string The latest error encountered by the service.
Definition at line 1034 of file class.win32service.php.
    {
        return $this->latestError;
    }
References $latestError.
Referenced by create().
getLatestStatus ()
Gets the latest status of the service.
Returns
string The latest status of the service.
Definition at line 1024 of file class.win32service.php.
    {
        return $this->latestStatus;
    }
References $latestStatus.
getName ()
Gets the name of the service.
Returns
string The name of the service.
Definition at line 878 of file class.win32service.php.
                             : string
    {
        return $this->name;
    }
References $name.
Referenced by create(), delete(), infos(), isInstalled(), isPaused(), isRunning(), isStopped(), start(), status(), and stop().
getNssm ()
Gets the NSSM instance associated with the service.
Returns
Nssm The NSSM instance.
Definition at line 998 of file class.win32service.php.
    {
        return $this->nssm;
    }
References $nssm.
Referenced by create(), and infos().
getParams ()
Gets the parameters for the service.
Returns
string The parameters for the service.
Definition at line 938 of file class.win32service.php.
                               : string
    {
        return $this->params;
    }
References $params.
Referenced by create().
getStartType ()
Gets the start type of the service.
Returns
string The start type of the service.
Definition at line 958 of file class.win32service.php.
                                  : string
    {
        return $this->startType;
    }
References $startType.
Referenced by create().
getVbsKeys () [static]
Returns an array of VBS keys used for service information.
Returns
array The array of VBS keys.
Definition at line 118 of file class.win32service.php.
                                       : array
    {
        return array(
            self::VBS_NAME,
            self::VBS_DISPLAY_NAME,
            self::VBS_DESCRIPTION,
            self::VBS_PATH_NAME,
            self::VBS_STATE
        );
    }
Referenced by Vbs\getServiceInfos().
getWin32ErrorCodeDesc ( $code) [private]
Returns a description of the Win32 error code.
Parameters
$code The error code.
Returns
string|null The description of the error code, or null if the code is not recognized.
Definition at line 862 of file class.win32service.php.
                                                 : ?string
    {
        switch ( $code ) {
            case self::WIN32_ERROR_ACCESS_DENIED:
                return 'The handle to the SCM database does not have the appropriate access rights.';
            // ... other cases ...
            default:
                return null;
        }
    }
Referenced by getError().
getWin32ServiceStatusDesc ( $status) [private]
Returns a description of the Win32 service status.
Parameters
$status The status code.
Returns
string|null The status description.
Definition at line 823 of file class.win32service.php.
                                                       : ?string
    {
        switch ( $status ) {
            case self::WIN32_SERVICE_CONTINUE_PENDING:
                return 'The service continue is pending.';
            case self::WIN32_SERVICE_PAUSE_PENDING:
                return 'The service pause is pending.';
            case self::WIN32_SERVICE_PAUSED:
                return 'The service is paused.';
            case self::WIN32_SERVICE_RUNNING:
                return 'The service is running.';
            case self::WIN32_SERVICE_START_PENDING:
                return 'The service is starting.';
            case self::WIN32_SERVICE_STOP_PENDING:
                return 'The service is stopping.';
            case self::WIN32_SERVICE_STOPPED:
                return 'The service is not running.';
            case self::WIN32_SERVICE_NA:
                return 'Cannot retrieve service status.';
            default:
                return null;
        }
    }
Referenced by getError().
infos ()
Retrieves information about the service.
Returns
array|false The service information, or false on failure.
Definition at line 647 of file class.win32service.php.
    {
        Util::logTrace("Starting Win32Service::infos for service: " . $this->getName());
        try {
            // Set a timeout for the entire operation
            $startTime = microtime(true);
            $timeout = 10; // 10 seconds timeout for the entire operation
            if ($this->getNssm() instanceof Nssm) {
                Util::logTrace("Using NSSM to get service info");
                $result = $this->getNssm()->infos();
                Util::logTrace("NSSM info retrieval completed in " . round(microtime(true) - $startTime, 2) . " seconds");
                return $result;
            }
            Util::logTrace("Using VBS to get service info");
            // Use set_time_limit to prevent PHP script timeout
            $originalTimeout = ini_get('max_execution_time');
            set_time_limit(15); // 15 seconds timeout
            // Create a separate process to get service info with a timeout
            $result = Vbs::getServiceInfos($this->getName());
            // Reset the timeout
            set_time_limit($originalTimeout);
            // Check if we've exceeded our timeout
            if (microtime(true) - $startTime > $timeout) {
                Util::logTrace("Timeout exceeded in infos() method, returning false");
                return false;
            }
            Util::logTrace("VBS info retrieval completed in " . round(microtime(true) - $startTime, 2) . " seconds");
            return $result;
        } catch (\Exception $e) {
            Util::logTrace("Exception in infos() method: " . $e->getMessage() . ", returning false");
            return false;
        } catch (\Throwable $e) {
            Util::logTrace("Throwable in infos() method: " . $e->getMessage() . ", returning false");
            return false;
        }
    }
References $result, getName(), getNssm(), Vbs\getServiceInfos(), and Util\logTrace().
isInstalled ()
Checks if the service is installed.
Returns
bool True if the service is installed, false otherwise.
Definition at line 697 of file class.win32service.php.
                                 : bool
    {
        Util::logTrace("Checking if service is installed: " . $this->getName());
        try {
            // Set a timeout for the entire operation
            $startTime = microtime(true);
            $timeout = 15; // 15 seconds timeout for the entire operation
            // Call status() with a try-catch to ensure we don't get stuck
            $status = $this->status();
            // Check if we've exceeded our timeout
            if (microtime(true) - $startTime > $timeout) {
                Util::logTrace("Timeout exceeded in isInstalled() method, assuming service is not installed");
                $this->writeLog('isInstalled ' . $this->getName() . ': NO (timeout exceeded)');
                return false;
            }
            $isInstalled = $status != self::WIN32_SERVICE_NA;
            Util::logTrace("Service " . $this->getName() . " installation status: " . ($isInstalled ? "YES" : "NO") . " (status code: " . $status . ")");
            $this->writeLog('isInstalled ' . $this->getName() . ': ' . ($isInstalled ? 'YES' : 'NO') . ' (status: ' . $status . ')');
            return $isInstalled;
        } catch (\Exception $e) {
            Util::logTrace("Exception in isInstalled() method: " . $e->getMessage() . ", assuming service is not installed");
            $this->writeLog('isInstalled ' . $this->getName() . ': NO (exception: ' . $e->getMessage() . ')');
            return false;
        } catch (\Throwable $e) {
            Util::logTrace("Throwable in isInstalled() method: " . $e->getMessage() . ", assuming service is not installed");
            $this->writeLog('isInstalled ' . $this->getName() . ': NO (throwable: ' . $e->getMessage() . ')');
            return false;
        }
    }
References getName(), Util\logTrace(), status(), and writeLog().
Referenced by create(), and delete().
isPaused ()
Checks if the service is paused.
Returns
bool True if the service is paused, false otherwise.
Definition at line 774 of file class.win32service.php.
                              : bool
    {
        Util::logTrace("Checking if service is paused: " . $this->getName());
        $status = $this->status();
        $isPaused = $status == self::WIN32_SERVICE_PAUSED;
        Util::logTrace("Service " . $this->getName() . " paused status: " . ($isPaused ? "YES" : "NO") . " (status code: " . $status . ")");
        $this->writeLog( 'isPaused ' . $this->getName() . ': ' . ($isPaused ? 'YES' : 'NO') . ' (status: ' . $status . ')' );
        return $isPaused;
    }
References getName(), Util\logTrace(), status(), and writeLog().
isPending ( $status)
Checks if the service is in a pending state.
Parameters
$status The status to check.
Returns
bool True if the service is in a pending state, false otherwise.
Definition at line 794 of file class.win32service.php.
                                      : bool
    {
        $isPending = $status == self::WIN32_SERVICE_START_PENDING || $status == self::WIN32_SERVICE_STOP_PENDING
            || $status == self::WIN32_SERVICE_CONTINUE_PENDING || $status == self::WIN32_SERVICE_PAUSE_PENDING;
        Util::logTrace("Checking if status is pending: " . $status . " - Result: " . ($isPending ? "YES" : "NO"));
        if ($isPending) {
            if ($status == self::WIN32_SERVICE_START_PENDING) {
                Util::logTrace("Service is in START_PENDING state");
            } else if ($status == self::WIN32_SERVICE_STOP_PENDING) {
                Util::logTrace("Service is in STOP_PENDING state");
            } else if ($status == self::WIN32_SERVICE_CONTINUE_PENDING) {
                Util::logTrace("Service is in CONTINUE_PENDING state");
            } else if ($status == self::WIN32_SERVICE_PAUSE_PENDING) {
                Util::logTrace("Service is in PAUSE_PENDING state");
            }
        }
        return $isPending;
    }
References Util\logTrace().
Referenced by status().
isRunning ()
Checks if the service is running.
Returns
bool True if the service is running, false otherwise.
Definition at line 738 of file class.win32service.php.
                               : bool
    {
        Util::logTrace("Checking if service is running: " . $this->getName());
        $status = $this->status();
        $isRunning = $status == self::WIN32_SERVICE_RUNNING;
        Util::logTrace("Service " . $this->getName() . " running status: " . ($isRunning ? "YES" : "NO") . " (status code: " . $status . ")");
        $this->writeLog( 'isRunning ' . $this->getName() . ': ' . ($isRunning ? 'YES' : 'NO') . ' (status: ' . $status . ')' );
        return $isRunning;
    }
References getName(), Util\logTrace(), status(), and writeLog().
Referenced by start().
isStopped ()
Checks if the service is stopped.
Returns
bool True if the service is stopped, false otherwise.
Definition at line 756 of file class.win32service.php.
                               : bool
    {
        Util::logTrace("Checking if service is stopped: " . $this->getName());
        $status = $this->status();
        $isStopped = $status == self::WIN32_SERVICE_STOPPED;
        Util::logTrace("Service " . $this->getName() . " stopped status: " . ($isStopped ? "YES" : "NO") . " (status code: " . $status . ")");
        $this->writeLog( 'isStopped ' . $this->getName() . ': ' . ($isStopped ? 'YES' : 'NO') . ' (status: ' . $status . ')' );
        return $isStopped;
    }
References getName(), Util\logTrace(), status(), and writeLog().
Referenced by stop().
reset ()
Resets the service by deleting and recreating it.
Returns
bool True if the service was reset successfully, false otherwise.
Definition at line 498 of file class.win32service.php.
                           : bool
    {
        if ( $this->delete() ) {
            usleep( self::SLEEP_TIME );
            return $this->create();
        }
        return false;
    }
References create().
restart ()
Restarts the service by stopping and then starting it.
Returns
bool True if the service was restarted successfully, false otherwise.
Definition at line 633 of file class.win32service.php.
                             : bool
    {
        if ( $this->stop() ) {
            return $this->start();
        }
        return false;
    }
References start(), and stop().
setBinPath ( $binPath)
Sets the binary path of the service.
Parameters
$binPath The binary path to set.
Definition at line 928 of file class.win32service.php.
                                        : void
    {
        $this->binPath = str_replace( '"', '', Util::formatWindowsPath( $binPath ) );
    }
References $binPath, and Util\formatWindowsPath().
Referenced by setNssm().
setDisplayName ( $displayName)
Sets the display name of the service.
Parameters
$displayName The display name to set.
Definition at line 908 of file class.win32service.php.
                                                : void
    {
        $this->displayName = $displayName;
    }
References $displayName.
Referenced by setNssm().
setErrorControl ( $errorControl)
Sets the error control setting of the service.
Parameters
$errorControl The error control setting to set.
Definition at line 988 of file class.win32service.php.
                                                  : void
    {
        $this->errorControl = $errorControl;
    }
References $errorControl.
setName ( $name)
Sets the name of the service.
Parameters
$name The name to set.
Definition at line 888 of file class.win32service.php.
                                  : void
    {
        $this->name = $name;
    }
References $name.
setNssm ( $nssm)
Sets the NSSM instance associated with the service.
Parameters
$nssm The NSSM instance to set.
Definition at line 1008 of file class.win32service.php.
    {
        if ( $nssm instanceof Nssm ) {
            $this->setDisplayName( $nssm->getDisplayName() );
            $this->setBinPath( $nssm->getBinPath() );
            $this->setParams( $nssm->getParams() );
            $this->setStartType( $nssm->getStart() );
            $this->nssm = $nssm;
        }
    }
References $nssm, setBinPath(), setDisplayName(), setParams(), and setStartType().
setParams ( $params)
Sets the parameters for the service.
Parameters
$params The parameters to set.
Definition at line 948 of file class.win32service.php.
                                      : void
    {
        $this->params = $params;
    }
References $params.
Referenced by setNssm().
setStartType ( $startType)
Sets the start type of the service.
Parameters
$startType The start type to set.
Definition at line 968 of file class.win32service.php.
                                            : void
    {
        $this->startType = $startType;
    }
References $startType.
Referenced by setNssm().
start ()
Starts the service.
Returns
bool True if the service was started successfully, false otherwise.
Definition at line 514 of file class.win32service.php.
                           : bool
    {
        global $bearsamppBins;
        Util::logInfo('Attempting to start service: ' . $this->getName());
        if ( $this->getName() == BinMysql::SERVICE_NAME ) {
            $bearsamppBins->getMysql()->initData();
        }
        elseif ( $this->getName() == BinMailpit::SERVICE_NAME ) {
            $bearsamppBins->getMailpit()->rebuildConf();
        }
        elseif ( $this->getName() == BinMemcached::SERVICE_NAME ) {
            $bearsamppBins->getMemcached()->rebuildConf();
        }
        elseif ( $this->getName() == BinPostgresql::SERVICE_NAME ) {
            $bearsamppBins->getPostgresql()->rebuildConf();
            $bearsamppBins->getPostgresql()->initData();
        }
        elseif ( $this->getName() == BinXlight::SERVICE_NAME ) {
            $bearsamppBins->getXlight()->rebuildConf();
        }
        $result = $this->callWin32Service( 'win32_start_service', $this->getName(), true );
        // Ensure proper type conversion for PHP 8.2.3 compatibility
        $resultInt = is_numeric($result) ? (int)$result : 0;
        $start = $result !== null ? dechex( $resultInt ) : '0';
        Util::logDebug( 'Start service ' . $this->getName() . ': ' . $start . ' (status: ' . $this->status() . ')' );
        if ( $start != self::WIN32_NO_ERROR && $start != self::WIN32_ERROR_SERVICE_ALREADY_RUNNING ) {
            // Write error to log
            Util::logError('Failed to start service: ' . $this->getName() . ' with error code: ' . $start);
            if ( $this->getName() == BinApache::SERVICE_NAME ) {
                $cmdOutput = $bearsamppBins->getApache()->getCmdLineOutput( BinApache::CMD_SYNTAX_CHECK );
                if ( !$cmdOutput['syntaxOk'] ) {
                    file_put_contents(
                        $bearsamppBins->getApache()->getErrorLog(),
                        '[' . date( 'Y-m-d H:i:s', time() ) . '] [error] ' . $cmdOutput['content'] . PHP_EOL,
                        FILE_APPEND
                    );
                }
            }
            elseif ( $this->getName() == BinMysql::SERVICE_NAME ) {
                $cmdOutput = $bearsamppBins->getMysql()->getCmdLineOutput( BinMysql::CMD_SYNTAX_CHECK );
                if ( !$cmdOutput['syntaxOk'] ) {
                    file_put_contents(
                        $bearsamppBins->getMysql()->getErrorLog(),
                        '[' . date( 'Y-m-d H:i:s', time() ) . '] [error] ' . $cmdOutput['content'] . PHP_EOL,
                        FILE_APPEND
                    );
                }
            }
            elseif ( $this->getName() == BinMariadb::SERVICE_NAME ) {
                $cmdOutput = $bearsamppBins->getMariadb()->getCmdLineOutput( BinMariadb::CMD_SYNTAX_CHECK );
                if ( !$cmdOutput['syntaxOk'] ) {
                    file_put_contents(
                        $bearsamppBins->getMariadb()->getErrorLog(),
                        '[' . date( 'Y-m-d H:i:s', time() ) . '] [error] ' . $cmdOutput['content'] . PHP_EOL,
                        FILE_APPEND
                    );
                }
            }
            return false;
        }
        elseif ( !$this->isRunning() ) {
            $this->latestError = self::WIN32_NO_ERROR;
            Util::logError('Service ' . $this->getName() . ' is not running after start attempt.');
            $this->latestError = null;
            return false;
        }
        Util::logInfo('Service ' . $this->getName() . ' started successfully.');
        return true;
    }
References $bearsamppBins, $result, callWin32Service(), BinApache\CMD_SYNTAX_CHECK, BinMariadb\CMD_SYNTAX_CHECK, BinMysql\CMD_SYNTAX_CHECK, getName(), isRunning(), Util\logDebug(), Util\logError(), Util\logInfo(), BinApache\SERVICE_NAME, BinMailpit\SERVICE_NAME, BinMariadb\SERVICE_NAME, BinMemcached\SERVICE_NAME, BinMysql\SERVICE_NAME, BinPostgresql\SERVICE_NAME, BinXlight\SERVICE_NAME, and status().
Referenced by restart().
status ( $timeout = true)
Queries the status of the service.
Parameters
$timeout Whether to use a timeout.
Returns
string The status of the service.
Definition at line 251 of file class.win32service.php.
                                           : string
    {
        usleep( self::SLEEP_TIME );
        $this->latestStatus = self::WIN32_SERVICE_NA;
        $maxtime = time() + self::PENDING_TIMEOUT;
        Util::logTrace("Querying status for service: " . $this->getName() . " (timeout: " . ($timeout ? "enabled" : "disabled") . ")");
        if ($timeout) {
            Util::logTrace("Max timeout time set to: " . date('Y-m-d H:i:s', $maxtime));
        }
        // Add a safety counter to prevent infinite loops
        $loopCount = 0;
        $maxLoops = 5; // Maximum number of attempts
        $startTime = microtime(true);
        try {
            while ( ($this->latestStatus == self::WIN32_SERVICE_NA || $this->isPending( $this->latestStatus )) && $loopCount < $maxLoops ) {
                $loopCount++;
                Util::logTrace("Calling win32_query_service_status for service: " . $this->getName() . " (attempt " . $loopCount . " of " . $maxLoops . ")");
                // Add a timeout check before making the call
                if (microtime(true) - $startTime > 10) { // 10 seconds overall timeout
                    Util::logTrace("Overall timeout reached before making service status call");
                    break;
                }
                $this->latestStatus = $this->callWin32Service( 'win32_query_service_status', $this->getName() );
                if ( is_array( $this->latestStatus ) && isset( $this->latestStatus['CurrentState'] ) ) {
                    // Ensure proper type conversion for PHP 8.2.3 compatibility
                    $stateInt = is_numeric($this->latestStatus['CurrentState']) ? (int)$this->latestStatus['CurrentState'] : 0;
                    $this->latestStatus = dechex( $stateInt );
                    Util::logTrace("Service status returned as array, CurrentState: " . $this->latestStatus);
                }
                elseif ( $this->latestStatus !== null ) {
                    // Ensure proper type conversion for PHP 8.2.3 compatibility
                    $statusInt = is_numeric($this->latestStatus) ? (int)$this->latestStatus : 0;
                    $statusHex = dechex( $statusInt );
                    Util::logTrace("Service status returned as value: " . $statusHex);
                    if ( $statusHex == self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST ) {
                        $this->latestStatus = $statusHex;
                        Util::logTrace("Service does not exist, breaking loop");
                        break; // Exit the loop immediately if service doesn't exist
                    }
                } else {
                    Util::logTrace("Service status query returned null");
                    // If we get a null result, assume service does not exist to avoid hanging
                    if ($loopCount >= 2) { // Only do this after at least one retry
                        Util::logTrace("Multiple null results, assuming service does not exist");
                        $this->latestStatus = self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST;
                        break;
                    }
                }
                if ( $timeout && $maxtime < time() ) {
                    Util::logTrace("Timeout reached while querying service status");
                    break;
                }
                // Only sleep if we're going to loop again
                if ($loopCount < $maxLoops && ($this->latestStatus == self::WIN32_SERVICE_NA || $this->isPending($this->latestStatus))) {
                    Util::logTrace("Sleeping before next status check attempt");
                    usleep(self::SLEEP_TIME);
                }
            }
        } catch (\Exception $e) {
            Util::logTrace("Exception in status method: " . $e->getMessage());
            // If an exception occurs, assume service does not exist
            $this->latestStatus = self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST;
        } catch (\Throwable $e) {
            Util::logTrace("Throwable in status method: " . $e->getMessage());
            // If a throwable occurs, assume service does not exist
            $this->latestStatus = self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST;
        }
        if ($loopCount >= $maxLoops) {
            Util::logTrace("Maximum query attempts reached for service: " . $this->getName());
        }
        $elapsedTime = microtime(true) - $startTime;
        Util::logTrace("Status check completed in " . round($elapsedTime, 2) . " seconds after " . $loopCount . " attempts");
        if ( $this->latestStatus == self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST ) {
            $this->latestError = $this->latestStatus;
            $this->latestStatus = self::WIN32_SERVICE_NA;
            Util::logTrace("Service does not exist, setting status to NA");
        }
        Util::logTrace("Final status for service " . $this->getName() . ": " . $this->latestStatus);
        return $this->latestStatus;
    }
References $latestStatus, callWin32Service(), getName(), isPending(), and Util\logTrace().
Referenced by create(), delete(), isInstalled(), isPaused(), isRunning(), isStopped(), start(), and stop().
stop ()
Stops the service.
Returns
bool True if the service was stopped successfully, false otherwise.
Definition at line 598 of file class.win32service.php.
                          : bool
    {
        Util::logTrace("Starting Win32Service::stop for service: " . $this->getName());
        Util::logTrace("Calling win32_stop_service for service: " . $this->getName());
        $result = $this->callWin32Service( 'win32_stop_service', $this->getName(), true );
        // Ensure proper type conversion for PHP 8.2.3 compatibility
        $resultInt = is_numeric($result) ? (int)$result : 0;
        $stop = $result !== null ? dechex( $resultInt ) : '0';
        Util::logTrace("Stop service result code: " . $stop);
        Util::logTrace("Checking current status after stop attempt");
        $currentStatus = $this->status();
        Util::logTrace("Current status: " . $currentStatus);
        $this->writeLog( 'Stop service ' . $this->getName() . ': ' . $stop . ' (status: ' . $currentStatus . ')' );
        if ( $stop != self::WIN32_NO_ERROR ) {
            return false;
        }
        elseif ( !$this->isStopped() ) {
            $this->latestError = self::WIN32_NO_ERROR;
            return false;
        }
        return true;
    }
References $result, callWin32Service(), getName(), isStopped(), Util\logTrace(), status(), and writeLog().
Referenced by delete(), and restart().
writeLog ( $log) [private]
Writes a log entry.
Parameters
$log The log message.
Definition at line 107 of file class.win32service.php.
                                   : void
    {
        global $bearsamppRoot;
        Util::logDebug( $log, $bearsamppRoot->getServicesLogFilePath() );
    }
References $bearsamppRoot, and Util\logDebug().
Referenced by create(), delete(), isInstalled(), isPaused(), isRunning(), isStopped(), and stop().
Field Documentation
$binPath [private]
Definition at line 79 of file class.win32service.php.
Referenced by getBinPath(), and setBinPath().
$displayName [private]
Definition at line 78 of file class.win32service.php.
Referenced by getDisplayName(), and setDisplayName().
$errorControl [private]
Definition at line 82 of file class.win32service.php.
Referenced by getErrorControl(), and setErrorControl().
$latestError [private]
Definition at line 86 of file class.win32service.php.
Referenced by getLatestError().
$latestStatus [private]
Definition at line 85 of file class.win32service.php.
Referenced by getLatestStatus(), and status().
$loggedFunctions = array() [static], [private]
Definition at line 89 of file class.win32service.php.
$name [private]
Definition at line 77 of file class.win32service.php.
Referenced by __construct(), getName(), and setName().
$nssm [private]
Definition at line 83 of file class.win32service.php.
Referenced by getNssm(), and setNssm().
$params [private]
Definition at line 80 of file class.win32service.php.
Referenced by getParams(), and setParams().
$startType [private]
Definition at line 81 of file class.win32service.php.
Referenced by getStartType(), and setStartType().
const PENDING_TIMEOUT = 20
Definition at line 68 of file class.win32service.php.
const SERVER_ERROR_IGNORE = '0'
Definition at line 61 of file class.win32service.php.
const SERVER_ERROR_NORMAL = '1'
Definition at line 62 of file class.win32service.php.
Referenced by BinMariadb\reload(), BinMysql\reload(), and BinPostgresql\reload().
const SERVICE_AUTO_START = '2'
Definition at line 64 of file class.win32service.php.
const SERVICE_DEMAND_START = '3'
Definition at line 65 of file class.win32service.php.
Referenced by BinMariadb\reload(), BinMysql\reload(), and BinPostgresql\reload().
const SERVICE_DISABLED = '4'
Definition at line 66 of file class.win32service.php.
const SLEEP_TIME = 500000
Definition at line 69 of file class.win32service.php.
const VBS_DESCRIPTION = 'Description'
Definition at line 73 of file class.win32service.php.
const VBS_DISPLAY_NAME = 'DisplayName'
Definition at line 72 of file class.win32service.php.
const VBS_NAME = 'Name'
Definition at line 71 of file class.win32service.php.
const VBS_PATH_NAME = 'PathName'
Definition at line 74 of file class.win32service.php.
Referenced by Nssm\infos(), and ActionStartup\installServices().
const VBS_STATE = 'State'
Definition at line 75 of file class.win32service.php.
const WIN32_ERROR_ACCESS_DENIED = '5'
Definition at line 30 of file class.win32service.php.
const WIN32_ERROR_CIRCULAR_DEPENDENCY = '423'
Definition at line 31 of file class.win32service.php.
const WIN32_ERROR_DATABASE_DOES_NOT_EXIST = '429'
Definition at line 32 of file class.win32service.php.
const WIN32_ERROR_DEPENDENT_SERVICES_RUNNING = '41B'
Definition at line 33 of file class.win32service.php.
const WIN32_ERROR_DUPLICATE_SERVICE_NAME = '436'
Definition at line 34 of file class.win32service.php.
const WIN32_ERROR_FAILED_SERVICE_CONTROLLER_CONNECT = '427'
Definition at line 35 of file class.win32service.php.
const WIN32_ERROR_INSUFFICIENT_BUFFER = '7A'
Definition at line 36 of file class.win32service.php.
const WIN32_ERROR_INVALID_DATA = 'D'
Definition at line 37 of file class.win32service.php.
const WIN32_ERROR_INVALID_HANDLE = '6'
Definition at line 38 of file class.win32service.php.
const WIN32_ERROR_INVALID_LEVEL = '7C'
Definition at line 39 of file class.win32service.php.
const WIN32_ERROR_INVALID_NAME = '7B'
Definition at line 40 of file class.win32service.php.
const WIN32_ERROR_INVALID_PARAMETER = '57'
Definition at line 41 of file class.win32service.php.
const WIN32_ERROR_INVALID_SERVICE_ACCOUNT = '421'
Definition at line 42 of file class.win32service.php.
const WIN32_ERROR_INVALID_SERVICE_CONTROL = '41C'
Definition at line 43 of file class.win32service.php.
const WIN32_ERROR_PATH_NOT_FOUND = '3'
Definition at line 44 of file class.win32service.php.
const WIN32_ERROR_SERVICE_ALREADY_RUNNING = '420'
Definition at line 45 of file class.win32service.php.
const WIN32_ERROR_SERVICE_CANNOT_ACCEPT_CTRL = '425'
Definition at line 46 of file class.win32service.php.
const WIN32_ERROR_SERVICE_DATABASE_LOCKED = '41F'
Definition at line 47 of file class.win32service.php.
const WIN32_ERROR_SERVICE_DEPENDENCY_DELETED = '433'
Definition at line 48 of file class.win32service.php.
const WIN32_ERROR_SERVICE_DEPENDENCY_FAIL = '42C'
Definition at line 49 of file class.win32service.php.
const WIN32_ERROR_SERVICE_DISABLED = '422'
Definition at line 50 of file class.win32service.php.
const WIN32_ERROR_SERVICE_DOES_NOT_EXIST = '424'
Definition at line 51 of file class.win32service.php.
const WIN32_ERROR_SERVICE_EXISTS = '431'
Definition at line 52 of file class.win32service.php.
const WIN32_ERROR_SERVICE_LOGON_FAILED = '42D'
Definition at line 53 of file class.win32service.php.
const WIN32_ERROR_SERVICE_MARKED_FOR_DELETE = '430'
Definition at line 54 of file class.win32service.php.
const WIN32_ERROR_SERVICE_NO_THREAD = '41E'
Definition at line 55 of file class.win32service.php.
const WIN32_ERROR_SERVICE_NOT_ACTIVE = '426'
Definition at line 56 of file class.win32service.php.
const WIN32_ERROR_SERVICE_REQUEST_TIMEOUT = '41D'
Definition at line 57 of file class.win32service.php.
const WIN32_ERROR_SHUTDOWN_IN_PROGRESS = '45B'
Definition at line 58 of file class.win32service.php.
const WIN32_NO_ERROR = '0'
Definition at line 59 of file class.win32service.php.
const WIN32_SERVICE_CONTINUE_PENDING = '5'
Definition at line 20 of file class.win32service.php.
const WIN32_SERVICE_NA = '0'
Definition at line 27 of file class.win32service.php.
const WIN32_SERVICE_PAUSE_PENDING = '6'
Definition at line 21 of file class.win32service.php.
const WIN32_SERVICE_PAUSED = '7'
Definition at line 22 of file class.win32service.php.
const WIN32_SERVICE_RUNNING = '4'
Definition at line 23 of file class.win32service.php.
const WIN32_SERVICE_START_PENDING = '2'
Definition at line 24 of file class.win32service.php.
const WIN32_SERVICE_STOP_PENDING = '3'
Definition at line 25 of file class.win32service.php.
const WIN32_SERVICE_STOPPED = '1'
Definition at line 26 of file class.win32service.php.
Author
Generated automatically by Doxygen for Bearsampp from the source code.