.TH "Win32ServiceException" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Win32ServiceException
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message='', $code=0, \\Throwable $previous=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBWin32ServiceException\fP

.PP
This class represents exceptions thrown by Win32 service operations\&. It extends the base Exception class to provide specific error handling for Win32 service functions\&. 
.PP
Definition at line \fB17\fP of file \fBclass\&.win32serviceexception\&.php\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message = \fR''\fP,  $code = \fR0\fP, \\Throwable $previous = \fRnull\fP)"
Constructor for the \fBWin32ServiceException\fP class\&.

.PP
\fBParameters\fP
.RS 4
\fI$message\fP The exception message\&. 
.br
\fI$code\fP The exception code\&. 
.br
\fI$previous\fP The previous throwable used for exception chaining\&. 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBclass\&.win32serviceexception\&.php\fP\&.
.nf
27     {
28         parent::__construct($message, $code, $previous);
29     }
.PP
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
