Win32Ps
NAME
Win32Ps
SYNOPSIS
Public Member Functions
__construct ()
Static Public Member Functions
static exists ($pid)
static findByPath ($path)
static findByPid ($pid)
static getCurrentPid ()
static getKeys ()
static getListProcs ()
static getStatProc ()
static kill ($pid)
static killBins ($refreshProcs=false)
Data Fields
const CAPTION = 'Caption'
const COMMAND_LINE = 'CommandLine'
const EXECUTABLE_PATH = 'ExecutablePath'
const NAME = 'Name'
const PROCESS_ID = 'ProcessID'
Static Private Member Functions
static callWin32Ps ($function)
Detailed Description
Class Win32Ps
This class provides various utility functions for interacting with Windows processes. It includes methods for retrieving process information, checking process existence, finding processes by PID or path, and terminating processes.
Definition at line 18 of file class.win32ps.php.
Constructor & Destructor Documentation
__construct ()
Definition at line 26 of file class.win32ps.php.
    {
    }
Member Function Documentation
callWin32Ps ( $function) [static], [private]
Calls a specified function if it exists.
Parameters
$function The name of the function to call.
Returns
mixed The result of the function call, or false if the function does not exist.
Definition at line 36 of file class.win32ps.php.
    {
        $result = false;
        if (function_exists($function)) {
            $result = @call_user_func($function);
        }
        return $result;
    }
References $result.
Referenced by getStatProc().
exists ( $pid) [static]
Checks if a process with the specified PID exists.
Parameters
$pid The process ID to check.
Returns
bool True if the process exists, false otherwise.
Definition at line 109 of file class.win32ps.php.
    {
        return self::findByPid($pid) !== false;
    }
References findByPid().
findByPath ( $path) [static]
Finds a process by its executable path.
Parameters
$path The path to the executable.
Returns
array|false An array of process information, or false if not found.
Definition at line 142 of file class.win32ps.php.
    {
        $path = Util::formatUnixPath($path);
        if (!empty($path) && is_file($path)) {
            $procs = self::getListProcs();
            if ($procs !== false) {
                foreach ($procs as $proc) {
                    $unixExePath = Util::formatUnixPath($proc[self::EXECUTABLE_PATH]);
                    if ($unixExePath == $path) {
                        return $proc;
                    }
                }
            }
        }
        return false;
    }
References $proc, Util\formatUnixPath(), and getListProcs().
findByPid ( $pid) [static]
Finds a process by its PID.
Parameters
$pid The process ID to find.
Returns
array|false An array of process information, or false if not found.
Definition at line 120 of file class.win32ps.php.
    {
        if (!empty($pid)) {
            $procs = self::getListProcs();
            if ($procs !== false) {
                foreach ($procs as $proc) {
                    if ($proc[self::PROCESS_ID] == $pid) {
                        return $proc;
                    }
                }
            }
        }
        return false;
    }
References $proc, and getListProcs().
Referenced by exists().
getCurrentPid () [static]
Retrieves the current process ID.
Returns
int The current process ID, or 0 if not found.
Definition at line 68 of file class.win32ps.php.
    {
        $procInfo = self::getStatProc();
        return isset($procInfo[self::PROCESS_ID]) ? intval($procInfo[self::PROCESS_ID]) : 0;
    }
References getStatProc().
Referenced by ActionLoading\__construct(), WinBinder\destroyWindow(), ActionLoading\processLoading(), ActionQuit\processWindow(), ActionStartup\processWindow(), and ActionQuit\terminatePhpProcesses().
getKeys () [static]
Retrieves the keys used for process information.
Returns
array An array of keys used for process information.
Definition at line 52 of file class.win32ps.php.
    {
        return array(
            self::NAME,
            self::PROCESS_ID,
            self::EXECUTABLE_PATH,
            self::CAPTION,
            self::COMMAND_LINE
        );
    }
getListProcs () [static]
Retrieves a list of running processes.
Returns
array|false An array of process information, or false on failure.
Definition at line 79 of file class.win32ps.php.
    {
        return Vbs::getListProcs(self::getKeys());
    }
References Vbs\getListProcs().
Referenced by findByPath(), findByPid(), killBins(), Root\register(), and ActionQuit\terminatePhpProcesses().
getStatProc () [static]
Retrieves the status of the current process.
Returns
array|null An array containing the process ID and executable path, or null on failure.
Definition at line 89 of file class.win32ps.php.
    {
        $statProc = self::callWin32Ps('win32_ps_stat_proc');
        if ($statProc !== false) {
            return array(
                self::PROCESS_ID => $statProc['pid'],
                self::EXECUTABLE_PATH => $statProc['exe']
            );
        }
        return null;
    }
References callWin32Ps().
Referenced by getCurrentPid().
kill ( $pid) [static]
Terminates a process by its PID.
Parameters
$pid The process ID to terminate.
Definition at line 165 of file class.win32ps.php.
    {
        $pid = intval($pid);
        if (!empty($pid)) {
            Vbs::killProc($pid);
        }
    }
References Vbs\killProc().
Referenced by killBins(), ActionLoading\processLoading(), Util\stopLoading(), and ActionQuit\terminatePhpProcesses().
killBins ( $refreshProcs = false) [static]
Terminates all Bearsampp-related processes except the current one.
Parameters
$refreshProcs Whether to refresh the list of processes before terminating.
Returns
array An array of terminated processes.
Definition at line 179 of file class.win32ps.php.
    {
        global $bearsamppRoot;
        $killed = array();
        $procs = $bearsamppRoot->getProcs();
        if ($refreshProcs || $procs === null) {
            $procs = self::getListProcs();
        }
        if ($procs !== false && $procs !== null) {
            foreach ($procs as $proc) {
                $unixExePath = Util::formatUnixPath($proc[self::EXECUTABLE_PATH]);
                $unixCommandPath = Util::formatUnixPath($proc[self::COMMAND_LINE]);
                // Not kill current PID (PHP)
                if ($proc[self::PROCESS_ID] == self::getCurrentPid()) {
                    continue;
                }
                // Not kill bearsampp
                if ($unixExePath == $bearsamppRoot->getExeFilePath()) {
                    continue;
                }
                // Not kill inside www
                if (Util::startWith($unixExePath, $bearsamppRoot->getWwwPath() . '/') || Util::contains($unixCommandPath, $bearsamppRoot->getWwwPath() . '/')) {
                    continue;
                }
                // Not kill external process
                if (!Util::startWith($unixExePath, $bearsamppRoot->getRootPath() . '/') && !Util::contains($unixCommandPath, $bearsamppRoot->getRootPath() . '/')) {
                    continue;
                }
                self::kill($proc[self::PROCESS_ID]);
                $killed[] = $proc;
            }
        }
        return $killed;
    }
References $bearsamppRoot, $proc, Util\contains(), Util\formatUnixPath(), getListProcs(), kill(), and Util\startWith().
Referenced by ActionManualRestart\__construct(), Batch\exitApp(), ActionStartup\installServices(), ActionStartup\killOldInstances(), ActionQuit\processWindow(), and ActionExt\procReload().
Field Documentation
const CAPTION = 'Caption'
Definition at line 23 of file class.win32ps.php.
const COMMAND_LINE = 'CommandLine'
Definition at line 24 of file class.win32ps.php.
const EXECUTABLE_PATH = 'ExecutablePath'
Definition at line 22 of file class.win32ps.php.
Referenced by Vbs\getListProcs(), ActionStartup\killOldInstances(), ActionStartup\processWindow(), and ActionQuit\terminatePhpProcesses().
const NAME = 'Name'
Definition at line 20 of file class.win32ps.php.
const PROCESS_ID = 'ProcessID'
Definition at line 21 of file class.win32ps.php.
Referenced by ActionStartup\killOldInstances(), ActionStartup\processWindow(), and ActionQuit\terminatePhpProcesses().
Author
Generated automatically by Doxygen for Bearsampp from the source code.