WinBinder
NAME
WinBinder
SYNOPSIS
Public Member Functions
__construct ()
createAppWindow ($caption, $width, $height, $style=null, $params=null)
createButton ($parent, $caption, $xPos, $yPos, $width=null, $height=null, $style=null, $params=null)
createControl ($parent, $ctlClass, $caption, $xPos, $yPos, $width, $height, $style=null, $params=null)
createEditBox ($parent, $value, $xPos, $yPos, $width=null, $height=null, $style=null, $params=null)
createFont ($fontName, $size=null, $color=null, $style=null)
createHyperLink ($parent, $caption, $xPos, $yPos, $width=null, $height=null, $style=null, $params=null)
createInputText ($parent, $value, $xPos, $yPos, $width=null, $height=null, $maxLength=null, $style=null, $params=null)
createLabel ($parent, $caption, $xPos, $yPos, $width=null, $height=null, $style=null, $params=null)
createNakedWindow ($caption, $width, $height, $style=null, $params=null)
createProgressBar ($parent, $max, $xPos, $yPos, $width=null, $height=null, $style=null, $params=null)
createRadioButton ($parent, $caption, $checked, $xPos, $yPos, $width=null, $height=null, $startGroup=false)
createTimer ($wbobject, $wait=1000)
createWindow ($parent, $wclass, $caption, $xPos, $yPos, $width, $height, $style=null, $params=null)
destroyTimer ($wbobject, $timerobject)
destroyWindow ($window)
drawImage ($wbobject, $path, $xPos=0, $yPos=0, $width=0, $height=0)
drawLine ($wbobject, $xStartPos, $yStartPos, $xEndPos, $yEndPos, $color, $height=1)
drawRect ($parent, $xPos, $yPos, $width, $height, $color=15790320, $filled=true)
drawText ($parent, $caption, $xPos, $yPos, $width=null, $height=null, $font=null)
exec ($cmd, $params=null, $silent=false)
findFile ($filename)
getFocus ()
getSystemInfo ($info)
getText ($wbobject)
getValue ($wbobject)
incrProgressBar ($progressBar)
isEnabled ($wbobject)
mainLoop ()
messageBox ($message, $type, $title=null)
messageBoxError ($message, $title=null)
messageBoxInfo ($message, $title=null)
messageBoxOk ($message, $title=null)
messageBoxOkCancel ($message, $title=null)
messageBoxQuestion ($message, $title=null)
messageBoxWarning ($message, $title=null)
messageBoxYesNo ($message, $title=null)
messageBoxYesNoCancel ($message, $title=null)
refresh ($wbobject)
reset ()
resetProgressBar ($progressBar)
setArea ($wbobject, $width, $height)
setCursor ($wbobject, $type=self::CURSOR_ARROW)
setDisabled ($wbobject)
setEnabled ($wbobject, $enabled=true)
setFocus ($wbobject)
setHandler ($wbobject, $classCallback, $methodCallback, $launchTimer=null)
setImage ($wbobject, $path)
setMaxLength ($wbobject, $length)
setProgressBarMax ($progressBar, $max)
setProgressBarValue ($progressBar, $value)
setRange ($wbobject, $min, $max)
setStyle ($wbobject, $style)
setText ($wbobject, $content)
setValue ($wbobject, $content)
sysDlgOpen ($parent, $title, $filter=null, $path=null)
sysDlgPath ($parent, $title, $path=null)
wait ($wbobject=null)
Data Fields
$callback
$gauge
const BOX_ERROR = WBC_STOP
const BOX_INFO = WBC_INFO
const BOX_OK = WBC_OK
const BOX_OKCANCEL = WBC_OKCANCEL
const BOX_QUESTION = WBC_QUESTION
const BOX_WARNING = WBC_WARNING
const BOX_YESNO = WBC_YESNO
const BOX_YESNOCANCEL = WBC_YESNOCANCEL
const CTRL_ID = 0
const CTRL_OBJ = 1
const CURSOR_ARROW = 'arrow'
const CURSOR_CROSS = 'cross'
const CURSOR_FINGER = 'finger'
const CURSOR_FORBIDDEN = 'forbidden'
const CURSOR_HELP = 'help'
const CURSOR_IBEAM = 'ibeam'
const CURSOR_NONE = null
const CURSOR_SIZEALL = 'sizeall'
const CURSOR_SIZENESW = 'sizenesw'
const CURSOR_SIZENS = 'sizens'
const CURSOR_SIZENWSE = 'sizenwse'
const CURSOR_SIZEWE = 'sizewe'
const CURSOR_UPARROW = 'uparrow'
const CURSOR_WAIT = 'wait'
const CURSOR_WAITARROW = 'waitarrow'
const INCR_PROGRESS_BAR = '++'
const NEW_LINE = '@nl@'
const SYSINFO_SCREENAREA = 'screenarea'
const SYSINFO_WORKAREA = 'workarea'
Private Member Functions
callWinBinder ($function, $params=array(), $removeErrorHandler=false)
processMessages ()
windowIsValid ($window)
Static Private Member Functions
static writeLog ($log)
Private Attributes
$countCtrls
$defaultTitle
Detailed Description
Class WinBinder
This class provides an interface to the WinBinder library, allowing for the creation and management of Windows GUI elements in PHP. It includes methods for creating windows, controls, handling events, and executing system commands.
Definition at line 18 of file class.winbinder.php.
Constructor & Destructor Documentation
__construct ()
WinBinder constructor.
Initializes the WinBinder class, sets the default window title, and resets control counters.
Definition at line 68 of file class.winbinder.php.
    {
        global $bearsamppCore;
        Util::logInitClass($this);
        $this->defaultTitle = APP_TITLE . ' ' . $bearsamppCore->getAppVersion();
        $this->reset();
    }
References $bearsamppCore, APP_TITLE, Util\logInitClass(), and reset().
Member Function Documentation
callWinBinder ( $function, $params = array(), $removeErrorHandler = false) [private]
Calls a WinBinder function with error handling.
Parameters
$function The name of the WinBinder function to call.
$params The parameters to pass to the function.
$removeErrorHandler Whether to suppress errors during the call.
Returns
mixed The result of the function call.
Definition at line 142 of file class.winbinder.php.
                                                                                             : mixed
    {
        $result = false;
        if (function_exists($function)) {
            if ($removeErrorHandler) {
                // Suppress all errors for this call
                $oldErrorLevel = error_reporting(0);
                $result = @call_user_func_array($function, $params);
                error_reporting($oldErrorLevel);
            } else {
                $result = call_user_func_array($function, $params);
            }
        }
        return $result;
    }
References $result.
Referenced by createControl(), createFont(), createTimer(), createWindow(), destroyTimer(), destroyWindow(), drawImage(), drawLine(), drawRect(), drawText(), exec(), findFile(), getFocus(), getSystemInfo(), getText(), getValue(), isEnabled(), mainLoop(), messageBox(), processMessages(), refresh(), setArea(), setCursor(), setEnabled(), setFocus(), setHandler(), setImage(), setMaxLength(), setProgressBarValue(), setRange(), setStyle(), setText(), setValue(), sysDlgOpen(), sysDlgPath(), wait(), and windowIsValid().
createAppWindow ( $caption, $width, $height, $style = null, $params = null)
Creates a new application window.
Parameters
$caption The window caption.
$width The width of the window.
$height The height of the window.
$style The window style.
$params Additional parameters for the window.
Returns
mixed The created window object.
Definition at line 97 of file class.winbinder.php.
                                                                                             : mixed
    {
        return $this->createWindow(null, AppWindow, $caption, WBC_CENTER, WBC_CENTER, $width, $height, $style, $params);
    }
References createWindow().
createButton ( $parent, $caption, $xPos, $yPos, $width = null, $height = null, $style = null, $params = null)
Creates a button control.
Parameters
$parent The parent window or control.
$caption The caption for the button.
$xPos The x-coordinate of the button.
$yPos The y-coordinate of the button.
$width The width of the button.
$height The height of the button.
$style The style for the button.
$params Additional parameters for the button.
Returns
array An array containing the control ID and object.
Definition at line 868 of file class.winbinder.php.
    {
        $width = $width == null ? 80 : $width;
        $height = $height == null ? 25 : $height;
        return $this->createControl($parent, PushButton, $caption, $xPos, $yPos, $width, $height, $style, $params);
    }
References createControl().
createControl ( $parent, $ctlClass, $caption, $xPos, $yPos, $width, $height, $style = null, $params = null)
Creates a new control.
Parameters
$parent The parent window or control.
$ctlClass The control class.
$caption The control caption.
$xPos The x-coordinate of the control.
$yPos The y-coordinate of the control.
$width The width of the control.
$height The height of the control.
$style The control style.
$params Additional parameters for the control.
Returns
array An array containing the control ID and object.
Definition at line 707 of file class.winbinder.php.
    {
        $this->countCtrls++;
        return array(
            self::CTRL_ID => $this->countCtrls,
            self::CTRL_OBJ => $this->callWinBinder('wb_create_control', array(
                $parent,
                $ctlClass,
                $caption,
                $xPos,
                $yPos,
                $width,
                $height,
                $this->countCtrls,
                $style,
                $params
            )),
        );
    }
References callWinBinder().
Referenced by createButton(), createEditBox(), createHyperLink(), createInputText(), createLabel(), createProgressBar(), and createRadioButton().
createEditBox ( $parent, $value, $xPos, $yPos, $width = null, $height = null, $style = null, $params = null)
Creates an edit box control.
Parameters
$parent The parent window or control.
$value The initial value for the edit box.
$xPos The x-coordinate of the edit box.
$yPos The y-coordinate of the edit box.
$width The width of the edit box.
$height The height of the edit box.
$style The style for the edit box.
$params Additional parameters for the edit box.
Returns
array An array containing the control ID and object.
Definition at line 783 of file class.winbinder.php.
    {
        $value = str_replace(self::NEW_LINE, PHP_EOL, $value);
        $width = $width == null ? 540 : $width;
        $height = $height == null ? 340 : $height;
        $editBox = $this->createControl($parent, RTFEditBox, (string)$value, $xPos, $yPos, $width, $height, $style, $params);
        return $editBox;
    }
References createControl().
createFont ( $fontName, $size = null, $color = null, $style = null)
Creates a font for use in WinBinder controls.
Parameters
$fontName The name of the font.
$size The size of the font.
$color The color of the font.
$style The style of the font.
Returns
mixed The created font object.
Definition at line 469 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_create_font', array($fontName, $size, $color, $style));
    }
References callWinBinder().
createHyperLink ( $parent, $caption, $xPos, $yPos, $width = null, $height = null, $style = null, $params = null)
Creates a hyperlink control.
Parameters
$parent The parent window or control.
$caption The caption for the hyperlink.
$xPos The x-coordinate of the hyperlink.
$yPos The y-coordinate of the hyperlink.
$width The width of the hyperlink.
$height The height of the hyperlink.
$style The style for the hyperlink.
$params Additional parameters for the hyperlink.
Returns
array An array containing the control ID and object.
Definition at line 807 of file class.winbinder.php.
    {
        $caption = str_replace(self::NEW_LINE, PHP_EOL, $caption);
        $width = $width == null ? 120 : $width;
        $height = $height == null ? 15 : $height;
        $hyperLink = $this->createControl($parent, HyperLink, (string)$caption, $xPos, $yPos, $width, $height, $style, $params);
        $this->setCursor($hyperLink[self::CTRL_OBJ], self::CURSOR_FINGER);
        return $hyperLink;
    }
References createControl(), and setCursor().
createInputText ( $parent, $value, $xPos, $yPos, $width = null, $height = null, $maxLength = null, $style = null, $params = null)
Creates an input text control.
Parameters
$parent The parent window or control.
$value The initial value for the input text.
$xPos The x-coordinate of the input text.
$yPos The y-coordinate of the input text.
$width The width of the input text.
$height The height of the input text.
$maxLength The maximum length of the input text.
$style The style for the input text.
$params Additional parameters for the input text.
Returns
array An array containing the control ID and object.
Definition at line 743 of file class.winbinder.php.
    {
        $value = str_replace(self::NEW_LINE, PHP_EOL, $value);
        $width = $width == null ? 120 : $width;
        $height = $height == null ? 25 : $height;
        $inputText = $this->createControl($parent, EditBox, (string)$value, $xPos, $yPos, $width, $height, $style, $params);
        if (is_numeric($maxLength) && $maxLength > 0) {
            $this->setMaxLength($inputText[self::CTRL_OBJ], $maxLength);
        }
        return $inputText;
    }
References createControl(), and setMaxLength().
createLabel ( $parent, $caption, $xPos, $yPos, $width = null, $height = null, $style = null, $params = null)
Creates a label control.
Parameters
$parent The parent window or control.
$caption The caption for the label.
$xPos The x-coordinate of the label.
$yPos The y-coordinate of the label.
$width The width of the label.
$height The height of the label.
$style The style for the label.
$params Additional parameters for the label.
Returns
array An array containing the control ID and object.
Definition at line 683 of file class.winbinder.php.
    {
        $caption = str_replace(self::NEW_LINE, PHP_EOL, $caption);
        $width = $width == null ? 120 : $width;
        $height = $height == null ? 25 : $height;
        return $this->createControl($parent, Label, $caption, $xPos, $yPos, $width, $height, $style, $params);
    }
References createControl().
createNakedWindow ( $caption, $width, $height, $style = null, $params = null)
Creates a new naked window.
Parameters
$caption The window caption.
$width The width of the window.
$height The height of the window.
$style The window style.
$params Additional parameters for the window.
Returns
mixed The created window object.
Definition at line 195 of file class.winbinder.php.
                                                                                               : mixed
    {
        $window = $this->createWindow(null, NakedWindow, $caption, WBC_CENTER, WBC_CENTER, $width, $height, $style, $params);
        $this->setArea($window, $width, $height);
        return $window;
    }
References createWindow(), and setArea().
createProgressBar ( $parent, $max, $xPos, $yPos, $width = null, $height = null, $style = null, $params = null)
Creates a progress bar control.
Parameters
$parent The parent window or control.
$max The maximum value for the progress bar.
$xPos The x-coordinate of the progress bar.
$yPos The y-coordinate of the progress bar.
$width The width of the progress bar.
$height The height of the progress bar.
$style The style for the progress bar.
$params Additional parameters for the progress bar.
Returns
array An array containing the control ID and object.
Definition at line 890 of file class.winbinder.php.
    {
        global $bearsamppLang;
        $width = $width == null ? 200 : $width;
        $height = $height == null ? 15 : $height;
        $progressBar = $this->createControl($parent, Gauge, $bearsamppLang->getValue(Lang::LOADING), $xPos, $yPos, $width, $height, $style, $params);
        $this->setRange($progressBar[self::CTRL_OBJ], 0, $max);
        $this->gauge[$progressBar[self::CTRL_OBJ]] = 0;
        return $progressBar;
    }
References $bearsamppLang, createControl(), Lang\LOADING, and setRange().
createRadioButton ( $parent, $caption, $checked, $xPos, $yPos, $width = null, $height = null, $startGroup = false)
Creates a radio button control.
Parameters
$parent The parent window or control.
$caption The caption for the radio button.
$checked Whether the radio button is checked.
$xPos The x-coordinate of the radio button.
$yPos The y-coordinate of the radio button.
$width The width of the radio button.
$height The height of the radio button.
$startGroup Whether this radio button starts a new group.
Returns
array An array containing the control ID and object.
Definition at line 845 of file class.winbinder.php.
    {
        $caption = str_replace(self::NEW_LINE, PHP_EOL, $caption);
        $width = $width == null ? 120 : $width;
        $height = $height == null ? 25 : $height;
        return $this->createControl($parent, RadioButton, (string)$caption, $xPos, $yPos, $width, $height, $startGroup ? WBC_GROUP : null, $checked ? 1 : 0);
    }
References createControl().
createTimer ( $wbobject, $wait = 1000)
Creates a timer for a WinBinder object.
Parameters
$wbobject The WinBinder object to create the timer for.
$wait The wait time in milliseconds.
Returns
array An array containing the timer ID and object.
Definition at line 543 of file class.winbinder.php.
    {
        $this->countCtrls++;
        return array(
            self::CTRL_ID => $this->countCtrls,
            self::CTRL_OBJ => $this->callWinBinder('wb_create_timer', array($wbobject, $this->countCtrls, $wait))
        );
    }
References callWinBinder().
Referenced by setHandler().
createWindow ( $parent, $wclass, $caption, $xPos, $yPos, $width, $height, $style = null, $params = null)
Creates a new window.
Parameters
$parent The parent window or null for a top-level window.
$wclass The window class.
$caption The window caption.
$xPos The x-coordinate of the window.
$yPos The y-coordinate of the window.
$width The width of the window.
$height The height of the window.
$style The window style.
$params Additional parameters for the window.
Returns
mixed The created window object.
Definition at line 117 of file class.winbinder.php.
                                                                                                                          : mixed
    {
        global $bearsamppCore;
        // Fix for PHP 8.2: Convert null to 0 for parent parameter
        $parent = $parent === null ? 0 : $parent;
        $caption = empty($caption) ? $this->defaultTitle : $this->defaultTitle . ' - ' . $caption;
        $window = $this->callWinBinder('wb_create_window', array($parent, $wclass, $caption, $xPos, $yPos, $width, $height, $style, $params));
        // Set tiny window icon
        $this->setImage($window, $bearsamppCore->getIconsPath() . '/app.ico');
        return $window;
    }
References $bearsamppCore, callWinBinder(), and setImage().
Referenced by createAppWindow(), and createNakedWindow().
destroyTimer ( $wbobject, $timerobject)
Destroys a timer for a WinBinder object.
Parameters
$wbobject The WinBinder object to destroy the timer for.
$timerobject The timer object to destroy.
Returns
mixed The result of the destroy operation.
Definition at line 494 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_destroy_timer', array($wbobject, $timerobject));
    }
References callWinBinder().
destroyWindow ( $window)
Destroys a window with proper cleanup and handling.
Parameters
$window The window object to destroy.
Returns
boolean True if window was successfully destroyed
Definition at line 223 of file class.winbinder.php.
                                          : bool
    {
        // Check if window exists and is valid
        if (!$window || !$this->windowIsValid($window)) {
            return true; // Already closed or invalid window
        }
        // Get window title before destruction for fallback
        $windowTitle = $this->getText($window);
        $currentPid = Win32Ps::getCurrentPid();
        // Attempt standard destruction
        $this->callWinBinder('wb_destroy_window', array($window));
        // Verify closure with retries
        $maxAttempts = 3;
        $attempt = 0;
        $destroyed = false;
        while ($attempt < $maxAttempts && !$destroyed) {
            $this->processMessages();
            usleep(100000); // 100ms delay
            $destroyed = !$this->windowIsValid($window);
            $attempt++;
        }
        // Fallback to process termination if window still exists
        if (!$destroyed) {
            // 1. Try to close using window title
            $this->exec('taskkill', '/FI "WINDOWTITLE eq ' . $windowTitle . '" /F', true);
            // 2. Try to kill process directly using Winbinder's PID method
            $currentPid = Win32Ps::getCurrentPid();
            if (!empty($currentPid)) {
                $this->exec('taskkill', '/PID ' . $currentPid . ' /T /F', true);
                $this->writeLog('Force-killed PID: ' . $currentPid . ' for window: ' . $window);
            }
            // 3. Final sanity check
            if ($this->windowIsValid($window)) {
                $this->callWinBinder('wb_destroy_window', array($window), true); // Force native call
            }
            // 4. Reset internal state to prevent memory leaks
            $this->reset();
        }
        // Final verification
        return !$this->windowIsValid($window);
    }
References callWinBinder(), exec(), Win32Ps\getCurrentPid(), getText(), processMessages(), reset(), windowIsValid(), and writeLog().
drawImage ( $wbobject, $path, $xPos = 0, $yPos = 0, $width = 0, $height = 0)
Draws an image on a WinBinder object.
Parameters
$wbobject The WinBinder object to draw on.
$path The path to the image file.
$xPos The x-coordinate of the image.
$yPos The y-coordinate of the image.
$width The width of the image.
$height The height of the image.
Returns
mixed The result of the draw operation.
Definition at line 394 of file class.winbinder.php.
                                                                                              : mixed
    {
        $image = $this->callWinBinder('wb_load_image', array($path));
        return $this->callWinBinder('wb_draw_image', array($wbobject, $image, $xPos, $yPos, $width, $height));
    }
References callWinBinder().
drawLine ( $wbobject, $xStartPos, $yStartPos, $xEndPos, $yEndPos, $color, $height = 1)
Draws a line on a WinBinder object.
Parameters
$wbobject The WinBinder object to draw on.
$xStartPos The starting x-coordinate of the line.
$yStartPos The starting y-coordinate of the line.
$xEndPos The ending x-coordinate of the line.
$yEndPos The ending y-coordinate of the line.
$color The color of the line.
$height The height of the line.
Returns
mixed The result of the draw operation.
Definition at line 454 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_draw_line', array($wbobject, $xStartPos, $yStartPos, $xEndPos, $yEndPos, $color, $height));
    }
References callWinBinder().
drawRect ( $parent, $xPos, $yPos, $width, $height, $color = 15790320, $filled = true)
Draws a rectangle on a WinBinder object.
Parameters
$parent The parent WinBinder object.
$xPos The x-coordinate of the rectangle.
$yPos The y-coordinate of the rectangle.
$width The width of the rectangle.
$height The height of the rectangle.
$color The color of the rectangle.
$filled Whether the rectangle should be filled.
Returns
mixed The result of the draw operation.
Definition at line 436 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_draw_rect', array($parent, $xPos, $yPos, $width, $height, $color, $filled));
    }
References callWinBinder().
drawText ( $parent, $caption, $xPos, $yPos, $width = null, $height = null, $font = null)
Draws text on a WinBinder object.
Parameters
$parent The parent WinBinder object.
$caption The text to draw.
$xPos The x-coordinate of the text.
$yPos The y-coordinate of the text.
$width The width of the text area.
$height The height of the text area.
$font The font to use for the text.
Returns
mixed The result of the draw operation.
Definition at line 414 of file class.winbinder.php.
    {
        $caption = str_replace(self::NEW_LINE, PHP_EOL, $caption);
        $width = $width == null ? 120 : $width;
        $height = $height == null ? 25 : $height;
        return $this->callWinBinder('wb_draw_text', array($parent, $caption, $xPos, $yPos, $width, $height, $font));
    }
References callWinBinder().
exec ( $cmd, $params = null, $silent = false)
Executes a system command.
Parameters
$cmd The command to execute.
$params The parameters to pass to the command.
$silent Whether to execute the command silently.
Returns
mixed The result of the command execution.
Definition at line 322 of file class.winbinder.php.
                                                               : mixed
    {
        global $bearsamppCore;
        if ($silent) {
            $silent = '"' . $bearsamppCore->getScript(Core::SCRIPT_EXEC_SILENT) . '" "' . $cmd . '"';
            $cmd = 'wscript.exe';
            $params = !empty($params) ? $silent . ' "' . $params . '"' : $silent;
        }
        $this->writeLog('exec: ' . $cmd . ' ' . $params);
        return $this->callWinBinder('wb_exec', array($cmd, $params));
    }
References $bearsamppCore, callWinBinder(), Core\SCRIPT_EXEC_SILENT, and writeLog().
Referenced by destroyWindow().
findFile ( $filename)
Finds a file using WinBinder.
Parameters
$filename The name of the file to find.
Returns
mixed The result of the find operation.
Definition at line 506 of file class.winbinder.php.
    {
        $result = $this->callWinBinder('wb_find_file', array($filename));
        $this->writeLog('findFile ' . $filename . ': ' . $result);
        return $result != $filename ? $result : false;
    }
References $result, callWinBinder(), and writeLog().
getFocus ()
Retrieves the focus from a WinBinder object.
Returns
mixed The WinBinder object that has the focus.
Definition at line 573 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_get_focus');
    }
References callWinBinder().
getSystemInfo ( $info)
Retrieves system information.
Parameters
$info The type of system information to retrieve.
Returns
mixed The retrieved system information.
Definition at line 377 of file class.winbinder.php.
                                        : mixed
    {
        return $this->callWinBinder('wb_get_system_info', array($info));
    }
References callWinBinder().
getText ( $wbobject)
Retrieves the text from a WinBinder object.
Parameters
$wbobject The WinBinder object to get the text from.
Returns
mixed The retrieved text.
Definition at line 281 of file class.winbinder.php.
                                      : mixed
    {
        return $this->callWinBinder('wb_get_text', array($wbobject));
    }
References callWinBinder().
Referenced by destroyWindow().
getValue ( $wbobject)
Retrieves the value from a WinBinder object.
Parameters
$wbobject The WinBinder object to get the value from.
Returns
mixed The retrieved value.
Definition at line 911 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_get_value', array($wbobject));
    }
References callWinBinder().
incrProgressBar ( $progressBar)
Increments the value of a progress bar.
Parameters
$progressBar The progress bar control.
Definition at line 935 of file class.winbinder.php.
    {
        $this->setProgressBarValue($progressBar, self::INCR_PROGRESS_BAR);
    }
References setProgressBarValue().
isEnabled ( $wbobject)
Checks if a WinBinder object is enabled.
Parameters
$wbobject The WinBinder object to check.
Returns
mixed True if the object is enabled, false otherwise.
Definition at line 597 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_get_enabled', array($wbobject));
    }
References callWinBinder().
mainLoop ()
Starts the main event loop.
Returns
mixed The result of the main loop.
Definition at line 353 of file class.winbinder.php.
                              : mixed
    {
        return $this->callWinBinder('wb_main_loop');
    }
References callWinBinder().
messageBox ( $message, $type, $title = null)
Displays a message box.
Parameters
$message The message to display.
$type The type of message box.
$title The title of the message box.
Returns
mixed The result of the message box operation.
Definition at line 1018 of file class.winbinder.php.
    {
        global $bearsamppCore;
        $message = str_replace(self::NEW_LINE, PHP_EOL, $message);
        $messageBox = $this->callWinBinder('wb_message_box', array(
            0, // Use 0 instead of null for the window handle parameter
            strlen($message) < 64 ? str_pad($message, 64) : $message, // Pad message to display entire title
            $title == null ? $this->defaultTitle : $this->defaultTitle . ' - ' . $title,
            $type
        ));
        return $messageBox;
    }
References $bearsamppCore, and callWinBinder().
Referenced by messageBoxError(), messageBoxInfo(), messageBoxOk(), messageBoxOkCancel(), messageBoxQuestion(), messageBoxWarning(), messageBoxYesNo(), and messageBoxYesNoCancel().
messageBoxError ( $message, $title = null)
Displays an error message box.
Parameters
$message The message to display.
$title The title of the message box. If null, the default title will be used.
Returns
mixed The result of the message box operation.
Definition at line 1080 of file class.winbinder.php.
    {
        return $this->messageBox($message, self::BOX_ERROR, $title);
    }
References messageBox().
messageBoxInfo ( $message, $title = null)
Displays an informational message box.
Parameters
$message The message to display.
$title The title of the message box.
Returns
mixed The result of the message box operation.
Definition at line 1004 of file class.winbinder.php.
    {
        return $this->messageBox($message, self::BOX_INFO, $title);
    }
References messageBox().
messageBoxOk ( $message, $title = null)
Displays an OK message box.
Parameters
$message The message to display.
$title The title of the message box.
Returns
mixed The result of the message box operation.
Definition at line 1041 of file class.winbinder.php.
    {
        return $this->messageBox($message, self::BOX_OK, $title);
    }
References messageBox().
messageBoxOkCancel ( $message, $title = null)
Displays an OK/Cancel message box.
Parameters
$message The message to display.
$title The title of the message box.
Returns
mixed The result of the message box operation.
Definition at line 1054 of file class.winbinder.php.
    {
        return $this->messageBox($message, self::BOX_OKCANCEL, $title);
    }
References messageBox().
messageBoxQuestion ( $message, $title = null)
Displays a question message box.
Parameters
$message The message to display.
$title The title of the message box. If null, the default title will be used.
Returns
mixed The result of the message box operation.
Definition at line 1067 of file class.winbinder.php.
    {
        return $this->messageBox($message, self::BOX_QUESTION, $title);
    }
References messageBox().
messageBoxWarning ( $message, $title = null)
Displays a warning message box.
Parameters
$message The message to display.
$title The title of the message box. If null, the default title will be used.
Returns
mixed The result of the message box operation.
Definition at line 1093 of file class.winbinder.php.
    {
        return $this->messageBox($message, self::BOX_WARNING, $title);
    }
References messageBox().
messageBoxYesNo ( $message, $title = null)
Displays a Yes/No message box.
Parameters
$message The message to display.
$title The title of the message box. If null, the default title will be used.
Returns
mixed The result of the message box operation.
Definition at line 1106 of file class.winbinder.php.
    {
        return $this->messageBox($message, self::BOX_YESNO, $title);
    }
References messageBox().
messageBoxYesNoCancel ( $message, $title = null)
Displays a Yes/No/Cancel message box.
Parameters
$message The message to display.
$title The title of the message box. If null, the default title will be used.
Returns
mixed The result of the message box operation.
Definition at line 1119 of file class.winbinder.php.
    {
        return $this->messageBox($message, self::BOX_YESNOCANCEL, $title);
    }
References messageBox().
processMessages () [private]
Process any pending window messages.
Returns
void
Definition at line 308 of file class.winbinder.php.
                                      : void
    {
        $this->callWinBinder('wb_wait', array(null, 1), true);
    }
References callWinBinder().
Referenced by destroyWindow().
refresh ( $wbobject)
Refreshes a WinBinder object.
Parameters
$wbobject The WinBinder object to refresh.
Returns
mixed The result of the refresh operation.
Definition at line 365 of file class.winbinder.php.
                                      : mixed
    {
        return $this->callWinBinder('wb_refresh', array($wbobject, true));
    }
References callWinBinder().
reset ()
Resets the control counter and callback array.
Definition at line 80 of file class.winbinder.php.
                           : void
    {
        $this->countCtrls = 1000;
        $this->callback = array();
    }
Referenced by __construct(), and destroyWindow().
resetProgressBar ( $progressBar)
Resets the value of a progress bar to zero.
Parameters
$progressBar The progress bar control.
Definition at line 980 of file class.winbinder.php.
    {
        $this->setProgressBarValue($progressBar, 0);
    }
References setProgressBarValue().
setArea ( $wbobject, $width, $height)
Sets the area of a WinBinder object.
Parameters
$wbobject The WinBinder object to set the area for.
$width The width of the area.
$height The height of the area.
Returns
mixed The result of the set area operation.
Definition at line 212 of file class.winbinder.php.
                                                       : mixed
    {
        return $this->callWinBinder('wb_set_area', array($wbobject, WBC_TITLE, 0, 0, $width, $height));
    }
References callWinBinder().
Referenced by createNakedWindow().
setCursor ( $wbobject, $type = self::CURSOR_ARROW)
Sets the cursor type for a WinBinder object.
Parameters
$wbobject The WinBinder object to set the cursor for.
$type The cursor type to set.
Returns
mixed The result of the set cursor operation.
Definition at line 826 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_set_cursor', array($wbobject, $type));
    }
References callWinBinder().
Referenced by createHyperLink().
setDisabled ( $wbobject)
Disables a WinBinder object.
Parameters
$wbobject The WinBinder object to disable.
Returns
mixed The result of the disable operation.
Definition at line 609 of file class.winbinder.php.
    {
        return $this->setEnabled($wbobject, false);
    }
References setEnabled().
setEnabled ( $wbobject, $enabled = true)
Sets the enabled state for a WinBinder object.
Parameters
$wbobject The WinBinder object to set the enabled state for.
$enabled True to enable the object, false to disable it.
Returns
mixed The result of the set enabled state operation.
Definition at line 622 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_set_enabled', array($wbobject, $enabled));
    }
References callWinBinder().
Referenced by setDisabled().
setFocus ( $wbobject)
Sets the focus to a WinBinder object.
Parameters
$wbobject The WinBinder object to set the focus to.
Returns
mixed The result of the set focus operation.
Definition at line 585 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_set_focus', array($wbobject));
    }
References callWinBinder().
setHandler ( $wbobject, $classCallback, $methodCallback, $launchTimer = null)
Sets an event handler for a WinBinder object.
Parameters
$wbobject The WinBinder object to set the handler for.
$classCallback The class callback for the handler.
$methodCallback The method callback for the handler.
$launchTimer The timer to launch for the handler.
Returns
mixed The result of the set handler operation.
Definition at line 524 of file class.winbinder.php.
    {
        if ($launchTimer != null) {
            $launchTimer = $this->createTimer($wbobject, $launchTimer);
        }
        $this->callback[$wbobject] = array($classCallback, $methodCallback, $launchTimer);
        return $this->callWinBinder('wb_set_handler', array($wbobject, '__winbinderEventHandler'));
    }
References callWinBinder(), and createTimer().
setImage ( $wbobject, $path)
Sets an image for a WinBinder object.
Parameters
$wbobject The WinBinder object to set the image for.
$path The path to the image file.
Returns
mixed The result of the set image operation.
Definition at line 167 of file class.winbinder.php.
                                              : mixed
    {
        if ($wbobject === null) {
            error_log('Error: $wbobject is null.');
            return false;
        }
        if (!file_exists($path)) {
            error_log('Error: Image file does not exist at path: ' . $path);
            return false;
        }
        return $this->callWinBinder('wb_set_image', array($wbobject, $path));
    }
References callWinBinder().
Referenced by createWindow().
setMaxLength ( $wbobject, $length)
Sets the maximum length for a WinBinder object.
Parameters
$wbobject The WinBinder object to set the maximum length for.
$length The maximum length to set.
Returns
mixed The result of the set maximum length operation.
Definition at line 764 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_send_message', array($wbobject, 0x00c5, $length, 0));
    }
References callWinBinder().
Referenced by createInputText().
setProgressBarMax ( $progressBar, $max)
Sets the maximum value of a progress bar.
Parameters
$progressBar The progress bar control.
$max The maximum value to set.
Definition at line 991 of file class.winbinder.php.
    {
        $this->setRange($progressBar[self::CTRL_OBJ], 0, $max);
    }
References setRange().
setProgressBarValue ( $progressBar, $value)
Sets the value of a progress bar.
Parameters
$progressBar The progress bar control.
$value The value to set.
Definition at line 946 of file class.winbinder.php.
    {
        if ($progressBar != null && isset($progressBar[self::CTRL_OBJ]) && isset($this->gauge[$progressBar[self::CTRL_OBJ]])) {
            if (strval($value) == self::INCR_PROGRESS_BAR) {
                $value = $this->gauge[$progressBar[self::CTRL_OBJ]] + 1;
            }
            if (is_numeric($value)) {
                $this->gauge[$progressBar[self::CTRL_OBJ]] = $value;
                
                // Check if the control is still valid before setting the value
                // This prevents errors when the parent window has been destroyed
                $this->callWinBinder('wb_set_value', array($progressBar[self::CTRL_OBJ], $value), true);
            }
        }
    }
References callWinBinder().
Referenced by incrProgressBar(), and resetProgressBar().
setRange ( $wbobject, $min, $max)
Sets the range for a WinBinder object.
Parameters
$wbobject The WinBinder object to set the range for.
$min The minimum value of the range.
$max The maximum value of the range.
Returns
mixed The result of the set range operation.
Definition at line 925 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_set_range', array($wbobject, $min, $max));
    }
References callWinBinder().
Referenced by createProgressBar(), and setProgressBarMax().
setStyle ( $wbobject, $style)
Sets the style for a WinBinder object.
Parameters
$wbobject The WinBinder object to set the style for.
$style The style to set.
Returns
mixed The result of the set style operation.
Definition at line 635 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_set_style', array($wbobject, $style));
    }
References callWinBinder().
setText ( $wbobject, $content)
Sets the text for a WinBinder object.
Parameters
$wbobject The WinBinder object to set the text for.
$content The text content to set.
Returns
mixed The result of the set text operation.
Definition at line 561 of file class.winbinder.php.
    {
        $content = str_replace(self::NEW_LINE, PHP_EOL, $content);
        return $this->callWinBinder('wb_set_text', array($wbobject, $content));
    }
References callWinBinder().
setValue ( $wbobject, $content)
Sets the value for a WinBinder object.
Parameters
$wbobject The WinBinder object to set the value for.
$content The value to set.
Returns
mixed The result of the set value operation.
Definition at line 970 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_set_value', array($wbobject, $content));
    }
References callWinBinder().
sysDlgOpen ( $parent, $title, $filter = null, $path = null)
Opens a system dialog to open a file.
Parameters
$parent The parent window for the dialog.
$title The title of the dialog.
$filter The file filter for the dialog.
$path The initial path for the dialog.
Returns
mixed The selected file path.
Definition at line 664 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_sys_dlg_open', array($parent, $title, $filter, $path));
    }
References callWinBinder().
sysDlgPath ( $parent, $title, $path = null)
Opens a system dialog to select a path.
Parameters
$parent The parent window for the dialog.
$title The title of the dialog.
$path The initial path for the dialog.
Returns
mixed The selected path.
Definition at line 649 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_sys_dlg_path', array($parent, $title, $path));
    }
References callWinBinder().
wait ( $wbobject = null)
Waits for an event on a WinBinder object.
Parameters
$wbobject The WinBinder object to wait on.
Returns
mixed The result of the wait operation.
Definition at line 481 of file class.winbinder.php.
    {
        return $this->callWinBinder('wb_wait', array($wbobject), true);
    }
References callWinBinder().
windowIsValid ( $window) [private]
Checks if a window handle is still valid.
Parameters
$window The window object to check.
Returns
boolean True if window is valid
Definition at line 292 of file class.winbinder.php.
                                           : bool
    {
        if (!$window) {
            return false;
        }
        // Try to get window text - if window is invalid, this will fail
        $text = $this->callWinBinder('wb_get_text', array($window), true);
        return ($text !== false);
    }
References callWinBinder().
Referenced by destroyWindow().
writeLog ( $log) [static], [private]
Writes a log message to the WinBinder log file.
Parameters
$log The log message to write.
Definition at line 342 of file class.winbinder.php.
                                          : void
    {
        global $bearsamppRoot;
        Util::logDebug($log, $bearsamppRoot->getWinbinderLogFilePath());
    }
References $bearsamppRoot, and Util\logDebug().
Referenced by destroyWindow(), exec(), and findFile().
Field Documentation
$callback
Definition at line 58 of file class.winbinder.php.
$countCtrls [private]
Definition at line 61 of file class.winbinder.php.
$defaultTitle [private]
Definition at line 60 of file class.winbinder.php.
$gauge
Definition at line 59 of file class.winbinder.php.
const BOX_ERROR = WBC_STOP
Definition at line 33 of file class.winbinder.php.
const BOX_INFO = WBC_INFO
Definition at line 29 of file class.winbinder.php.
const BOX_OK = WBC_OK
Definition at line 30 of file class.winbinder.php.
const BOX_OKCANCEL = WBC_OKCANCEL
Definition at line 31 of file class.winbinder.php.
const BOX_QUESTION = WBC_QUESTION
Definition at line 32 of file class.winbinder.php.
const BOX_WARNING = WBC_WARNING
Definition at line 34 of file class.winbinder.php.
const BOX_YESNO = WBC_YESNO
Definition at line 35 of file class.winbinder.php.
const BOX_YESNOCANCEL = WBC_YESNOCANCEL
Definition at line 36 of file class.winbinder.php.
const CTRL_ID = 0
Definition at line 21 of file class.winbinder.php.
Referenced by ActionAbout\processWindow(), ActionAddAlias\processWindow(), ActionAddVhost\processWindow(), ActionChangeBrowser\processWindow(), ActionChangeDbRootPwd\processWindow(), ActionChangePort\processWindow(), ActionCheckVersion\processWindow(), ActionEditAlias\processWindow(), ActionEditVhost\processWindow(), and ActionGenSslCertificate\processWindow().
const CTRL_OBJ = 1
Definition at line 22 of file class.winbinder.php.
Referenced by ActionChangeBrowser\__construct(), ActionChangeDbRootPwd\__construct(), ActionChangePort\__construct(), ActionAddAlias\processWindow(), ActionAddVhost\processWindow(), ActionChangeBrowser\processWindow(), ActionChangeDbRootPwd\processWindow(), ActionChangePort\processWindow(), ActionEditAlias\processWindow(), ActionEditVhost\processWindow(), and ActionGenSslCertificate\processWindow().
const CURSOR_ARROW = 'arrow'
Definition at line 39 of file class.winbinder.php.
const CURSOR_CROSS = 'cross'
Definition at line 40 of file class.winbinder.php.
const CURSOR_FINGER = 'finger'
Definition at line 41 of file class.winbinder.php.
const CURSOR_FORBIDDEN = 'forbidden'
Definition at line 42 of file class.winbinder.php.
const CURSOR_HELP = 'help'
Definition at line 43 of file class.winbinder.php.
const CURSOR_IBEAM = 'ibeam'
Definition at line 44 of file class.winbinder.php.
const CURSOR_NONE = null
Definition at line 45 of file class.winbinder.php.
const CURSOR_SIZEALL = 'sizeall'
Definition at line 46 of file class.winbinder.php.
const CURSOR_SIZENESW = 'sizenesw'
Definition at line 47 of file class.winbinder.php.
const CURSOR_SIZENS = 'sizens'
Definition at line 48 of file class.winbinder.php.
const CURSOR_SIZENWSE = 'sizenwse'
Definition at line 49 of file class.winbinder.php.
const CURSOR_SIZEWE = 'sizewe'
Definition at line 50 of file class.winbinder.php.
const CURSOR_UPARROW = 'uparrow'
Definition at line 51 of file class.winbinder.php.
const CURSOR_WAIT = 'wait'
Definition at line 52 of file class.winbinder.php.
const CURSOR_WAITARROW = 'waitarrow'
Definition at line 53 of file class.winbinder.php.
const INCR_PROGRESS_BAR = '++'
Definition at line 25 of file class.winbinder.php.
const NEW_LINE = '@nl@'
Definition at line 26 of file class.winbinder.php.
const SYSINFO_SCREENAREA = 'screenarea'
Definition at line 56 of file class.winbinder.php.
const SYSINFO_WORKAREA = 'workarea'
Definition at line 57 of file class.winbinder.php.
Referenced by ActionLoading\__construct(), and Splash\init().
Author
Generated automatically by Doxygen for Bearsampp from the source code.