.TH "E:/Bearsampp-development/sandbox/core/libs/winbinder/winbinder.php" 3 "Version 2025.8.29" "Bearsampp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
E:/Bearsampp-development/sandbox/core/libs/winbinder/winbinder.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$_mainpath\fP = pathinfo(__FILE__)"
.br
.ti -1c
.RI "\fBif\fP(!extension_loaded('winbinder')) \fBif\fP(!dl('php_winbinder\&.dll')) trigger_error('WinBinder extension could not be loaded\&.\\n' \fBE_USER_ERROR\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$_mainpath = pathinfo(__FILE__)"

.PP
Definition at line \fB18\fP of file \fBwinbinder\&.php\fP\&.
.SS "\fBif\fP (!extension_loaded( 'winbinder')) \fBif\fP(!dl( 'php_winbinder\&.dll')) trigger_error('WinBinder extension could not be loaded\&.\\n' E_USER_ERROR"

.PP
Definition at line \fB16\fP of file \fBwinbinder\&.php\fP\&.
.PP
Referenced by \fBRoot\\errorHandler()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bearsampp from the source code\&.
