var searchData=
[
  ['label_0',['label',['../commands.html#cmdcond',1,'\\cond [(section-label)]'],['../commands.html#cmdelseif',1,'\\elseif (section-label)'],['../commands.html#cmdif',1,'\\if (section-label)'],['../commands.html#cmdifnot',1,'\\ifnot (section-label)']]],
  ['language_1',['Step 2: Register New Language',['../i18n_guide.html#i18n_step2',1,'']]],
  ['language_2',['Step 0: Check if Doxygen supports your programming/hardware description language',['../starting.html#step0',1,'']]],
  ['language_20code_20standards_3',['Language Code Standards',['../i18n_guide.html#i18n_codes',1,'']]],
  ['language_20is_20x_20can_20i_20still_20use_20doxygen_4',['My favorite programming language is X. Can I still use Doxygen?',['../faq.html#faq_pgm_X',1,'']]],
  ['language_20support_5',['Adding New Language Support',['../i18n_guide.html#i18n_adding',1,'']]],
  ['languageid_6',['\\~[LanguageId]',['../commands.html#cmdtilde',1,'']]],
  ['languages_20c_20c_20c_20objective_20c_20php_20java_7',['Comment blocks for C-like languages (C/C++/C#/Objective-C/PHP/Java)',['../docblocks.html#cppblock',1,'']]],
  ['latex_20directory_20i_20get_20tex_20capacity_20exceeded_20now_20what_8',['When running make in the latex directory I get &quot;TeX capacity exceeded&quot;. Now what?',['../faq.html#faq_latex',1,'']]],
  ['latex_20generator_9',['Using the LaTeX generator.',['../perlmod.html#perlmod_latex',1,'']]],
  ['latex_20output_10',['LaTeX output',['../config.html#config_latex',1,'Configuration options related to the LaTeX output'],['../starting.html#latex_out',1,'LaTeX output']]],
  ['layout_20of_20pages_11',['Changing the layout of pages',['../customize.html#layout',1,'']]],
  ['like_20languages_20c_20c_20c_20objective_20c_20php_20java_12',['Comment blocks for C-like languages (C/C++/C#/Objective-C/PHP/Java)',['../docblocks.html#cppblock',1,'']]],
  ['like_20the_20quick_20index_20that_20is_20put_20above_20each_20html_20page_20what_20do_20i_20do_13',['I don&apos;t like the quick index that is put above each HTML page, what do I do?',['../faq.html#faq_html',1,'']]],
  ['limits_14',['Code Spans Limits',['../markdown.html#mddox_code_spans',1,'']]],
  ['limits_15',['Emphasis and strikethrough limits',['../markdown.html#mddox_emph_spans',1,'']]],
  ['limits_20on_20markup_20scope_16',['Limits on markup scope',['../markdown.html#mddox_limits',1,'']]],
  ['line_17',['Can I configure Doxygen from the command line?',['../faq.html#faq_cmdline',1,'']]],
  ['lineno_18',['lineno',['../commands.html#cmddontinclude',1,'\\dontinclude[&apos;{lineno}&apos;] &amp;lt;file-name&amp;gt;'],['../commands.html#cmdexample',1,'\\example[&apos;{lineno}&apos;] &amp;lt;file-name&amp;gt;']]],
  ['link_20generation_19',['Automatic link generation',['../autolink.html',1,'']]],
  ['link_20to_20the_20class_20myclass_20somewhere_20in_20the_20running_20text_20how_20do_20i_20prevent_20that_20at_20a_20certain_20place_20',['Doxygen automatically generates a link to the class MyClass somewhere in the running text. How do I prevent that at a certain place?',['../faq.html#faq_class',1,'']]],
  ['linking_21',['Automatic Linking',['../markdown.html#md_autolink',1,'']]],
  ['linking_20to_20external_20documentation_22',['Linking to external documentation',['../external.html',1,'']]],
  ['links_23',['Links',['../markdown.html#md_inlinelinks',1,'Inline Links'],['../markdown.html#md_links',1,'Links'],['../markdown.html#md_reflinks',1,'Reference Links']]],
  ['links_20to_20classes_24',['Links to classes',['../autolink.html#linkclass',1,'']]],
  ['links_20to_20files_25',['Links to files',['../autolink.html#linkfile',1,'']]],
  ['links_20to_20functions_26',['Links to functions',['../autolink.html#linkfunc',1,'']]],
  ['links_20to_20other_20members_27',['Links to other members',['../autolink.html#linkother',1,'']]],
  ['links_20to_20web_20pages_20and_20mail_20addresses_28',['Links to web pages and mail addresses',['../autolink.html#linkurl',1,'']]],
  ['list_20of_20authors_29',['list of authors',['../commands.html#cmdauthor',1,'\\author { list of authors }'],['../commands.html#cmdauthors',1,'\\authors { list of authors }']]],
  ['list_20title_20text_30',['\\xrefitem &amp;lt;key&amp;gt; &quot;heading&quot; &quot;list title&quot; { text }',['../commands.html#cmdxrefitem',1,'']]],
  ['lists_31',['Lists',['../lists.html',1,'Lists'],['../markdown.html#md_lists',1,'Lists']]],
  ['lists_20extensions_32',['Lists Extensions',['../markdown.html#mddox_lists',1,'']]],
  ['localized_20config_20file_33',['Step 3: Create Localized Config File',['../i18n_guide.html#i18n_step4',1,'']]],
  ['localized_20config_20files_34',['Syncing Localized Config Files',['../i18n_guide.html#i18n_config_sync',1,'']]],
  ['looks_20different_20while_20i_20only_20wanted_20to_20use_20my_20own_20html_20header_20file_35',['The overall HTML output looks different, while I only wanted to use my own html header file',['../faq.html#faq_html_header',1,'']]]
];
